### ISSUE TITLE
Exception on member access when using raw generics

### ISSUE THREAD

**Issue by twistedsquare** [typetools/checker-framework#1003]
This one is fairly obscure and raw generics are a bad idea anyway, but I thought I'd at least report it.  The following program causes an exception in the checker framework when compiled with the nullness checker and checker framework 2.1.7 (it didn't cause an exception with 2.1.6):

```
import java.util.*;
import org.checkerframework.checker.nullness.qual.Nullable;
// The fact that M extends MethodMember is unimportant,
// I'm just doing this to wrap it up into a single class example:
class MethodMember<M extends MethodMember>
{
	public int field = 0;
	
	public @Nullable M getFoo()
	{
		return null;
	}
	
	public static void methodMemberAccess()
	{
		// Use of raw generics:
		MethodMember m = new MethodMember();
		// This version causes error but not exception:
		// MethodMember<MethodMember> m = new MethodMember<>();
		// Exception caused by this line:
		int x = m.getFoo().field;
	}
}
```

Workaround is to specify the type on the generic rather than using it raw.

(Quick side note: was happy to update to 2.1.7 as it fixed the other issues I'd reported, thanks very much for fixing them!)

**Comment by smillst** [comment]
Thanks for reporting this issue!  While fixing this crash, I found two more crashes on other sorts of field accesses.  I've submitted the fix in pull request #1004.
