### ISSUE TITLE
SOE in 2.1.8

### ISSUE THREAD

**Issue by justmin** [typetools/checker-framework#1027]
```
import java.util.Map;
import java.util.stream.Collectors;

public class TestCheckerFramework {
    public static String foo(Map<String, String> arg){
        return arg.keySet().stream()
                .map(key -> key)
                .collect(Collectors.joining());
    }
}

```
Error:java: SourceChecker.typeProcess: unexpected Throwable (StackOverflowError) while processing TestCheckerFramework.java; invoke the compiler with -AprintErrorStack to see the stack trace.

**Comment by wmdietlGC** [comment]
Thanks for the bug report and sorry for the problem! I've reproduced the issue and have a fix. I'll open a PR soon.

**Comment by wmdietlGC** [comment]
https://github.com/typetools/checker-framework/pull/1038

**Comment by wmdietlGC** [comment]
Fixed in https://github.com/typetools/checker-framework/commit/aff092273a0d97c236e87d518a31dbe891fe77dc
