### ISSUE TITLE
URLStreamHandlerFactory.createURLStreamHandler's return value should have @Nullable annotation

### ISSUE THREAD

**Issue by felixfontein** [typetools/checker-framework#1035]
While not being mentioned in the documentation (https://docs.oracle.com/javase/7/docs/api/java/net/URLStreamHandlerFactory.html), the function is supposed to return `null` when the protocol is not known.

(See `URL.getURLStreamHandler`'s source code: it calls `createURLStreamHandler` and checks whether the return value is `null` to determine whether to use the `URLStreamHandler` it creates or whether to try to create a default URL handler for this protocol.)

**Comment by mernst** [comment]
Thanks for pointing this out.  I'm not going to put it in the annotated JDK for now.

If a fact is not mentioned in the documentation, then it is an implementation detail.  Clients should not depend on such implementation details, which are prone to change without notice.

Could you submit a bug report to Oracle asking them to update the documentation to reflect this fact?  If they do, then we can we can put it in the specification too as a `@Nullable` annotation.

In the meanwhile, you can create a local stub file if you wish to depend on your assumption that this behavior will never change.

Thanks again for the issue report.

**Comment by felixfontein** [comment]
Thanks for your prompt reply! I've now reported this to Oracle; if this results in something, I'll update this issue.

**Comment by mernst** [comment]
Great! I hope they update the documentation to indicate the design intent,
which will also enable the annotated JDK to be more useful. Feel free to
linn to the Oracle issue from here even before the resolve it.

**Comment by felixfontein** [comment]
Here's the Oracle issue: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8174803

**Comment by felixfontein** [comment]
It looks like this was already fixed for Java 9, and won't be backported to earlier versions.

**Comment by felixfontein** [comment]
(See here: http://download.java.net/java/jdk9/docs/api/java/net/URLStreamHandlerFactory.html#createURLStreamHandler-java.lang.String-)

**Comment by felixfontein** [comment]
Since Java 9 is out, I guess this can be added now. (See updated documentation: https://docs.oracle.com/javase/9/docs/api/java/net/URLStreamHandlerFactory.html)

**Comment by mernst** [comment]
Thanks for following up on this old issue!  I have committed the annotation.
