### ISSUE TITLE
castNonNull in dist/checker-qual.jar not working as expected?

### ISSUE THREAD

**Issue by felixfontein** [typetools/checker-framework#1037]
I'm trying to compile the following test:
``` .java
import org.checkerframework.checker.nullness.qual.*;
import org.checkerframework.checker.nullness.NullnessUtil;

public class test {
    public abstract @Nullable String g(int x) {
        return x < 0 ? null : Integer.toString(x);
    }

    // Copied from checker-qual-source.jar
    @SuppressWarnings({"nullness"})
    public static @EnsuresNonNull("#1") <T extends @Nullable Object> @NonNull T myCastNonNull(T ref) {
        assert ref != null : "Misuse of castNonNull: called with a null argument";
        return (@NonNull T) ref;
    }

    public static void main(String[] args) {
        @NonNull String x = NullnessUtil.castNonNull(g(1));
        @NonNull String y = myCastNonNull(g(1));
    }
}
```
as follows:
```
$ bin/javac -processor Nullness -classpath .:dist/checker-qual.jar test.java
```
I'm expecting no error, but I get:
```
test.java:14: error: [assignment.type.incompatible] incompatible types in assignment.
        @NonNull String x = NullnessUtil.castNonNull(g(1)); // results in error
                                                    ^
  found   : @Initialized @Nullable String
  required: @UnknownInitialization @NonNull String
1 error
```
Am I doing something wrong? Or is this a problem with `dist/checker-qual.jar`?

I'm using Java 8 (OpenJDK), and this happens both with the current release (https://checkerframework.org/checker-framework-2.1.8.zip) as well as with the git master.

**Comment by wmdietl** [comment]
Thanks for filing this issue! I recently ran into this, too.
We should remove two lines:
https://github.com/typetools/checker-framework/blob/master/checker/build.xml#L447
https://github.com/typetools/checker-framework/blob/master/checker/build.xml#L512

Removing the first use of `-XDTA:noannotationsincomments` should fix the checker-qual.jar file; the second use also seems strange.
@smillst do you remember why we used `-XDTA:noannotationsincomments` here?

**Comment by wmdietlGC** [comment]
Fixed in https://github.com/typetools/checker-framework/commit/25ee5a51d093303b9d3ea38868687d66eeb5ac63

**Comment by felixfontein** [comment]
Thanks!
