### ISSUE TITLE
Uninitialized field check for type parameters with @Nullable bound

### ISSUE THREAD

**Issue by wmdietlGC** [typetools/checker-framework#1044]
The following program:

```
public class TypeVarInit<V> {
  V f;

  public static void main(String[] args) {
    new TypeVarInit<String>().f.toString();
  }
}
```

compiles without error with the Nullness Checker.
When executing it, it results in a NullPointerException:

```
Exception in thread "main" java.lang.NullPointerException
	at TypeVarInit.main(TypeVarInit.java:5)
```

I would have expected:

```
TypeVarInit.java:1: error: [initialization.fields.uninitialized] the constructor does not initialize fields: f
public class TypeVarInit<V> {
       ^
1 error
```

Note that if the upper bound of `V` is changed from the implicit `@Nullable Object` to `@NonNull Object` we get the expected error:

```
TypeVarInit.java:1: error: [initialization.fields.uninitialized] the constructor does not initialize fields: f
public class TypeVarInit<V extends Object> {
       ^
1 error
```

**Comment by vatsalsura** [comment]
I think I understood the problem here.  We have to give the user a warning when it is checked with the Nullness Checker about the variable which is not initialized by the constructor. If I am correct can you guide me on how to progress on this?

**Comment by smillst** [comment]
@vatsalsura Thanks for your interest in this issue.  I've already got a patch that fix it, though. (See PR #1107).
