### ISSUE TITLE
Spurious `api` directories

### ISSUE THREAD

**Issue by wmdietlGC** [typetools/checker-framework#1054]
After a build, there are `api` directories in all sub-projects. Those directories contain a single css file:

```
./dataflow/api/resources/fonts/dejavu.css
./checker/api/resources/fonts/dejavu.css
./stubparser/api/resources/fonts/dejavu.css
./framework/api/resources/fonts/dejavu.css
./javacutil/api/resources/fonts/dejavu.css
```

There are no other files in these `api` directories.

I'm wondering if this css file can be moved to a single location within the `docs` directory.

**Comment by wmdietlGC** [comment]
Note that there is a `docs/api` symbolic link that points to `checker/api`, but that directory doesn't exist before a build. This should be cleaned up.

**Comment by smillst** [comment]
This css file is empty.  It is create in the "prep-all" target in [build-common.xml](https://github.com/typetools/checker-framework/blob/master/build-common.xml#L99).  It is created to work around a Javadoc bug.  I could still create a symbolic link to a single empty file, but it doesn't seem worth the trouble to me.

**Comment by smillst** [comment]
The `docs/api` symbolic link  should be created when `checker/api` is created.

**Comment by smillst** [comment]
Fixed via https://github.com/typetools/checker-framework/commit/9378b4d5cf97cca21fed33717ee95a1e6cb97455.
