### ISSUE TITLE
Incorrect wildcard bound determination with stub files

### ISSUE THREAD

**Issue by wmdietlGC** [typetools/checker-framework#1055]
Take the following simple class:

```
class NonN<T> {}
```

Compile with normal javac.
Then add a file `NonN.astub` that specifies the upper bound is non-null:

```
import org.checkerframework.checker.nullness.qual.NonNull;

class NonN<T extends @NonNull Object> {}
```

Then add this main class:

```
class Wildcards {
  NonN<?> f = new NonN<Object>();

  class LocalNonN<T extends Object> {}
  LocalNonN<?> g = new LocalNonN<Object>();
}
```

Compile with `.../javac -processor nullness -Astubs=NonN.astub Wildcards.java` and you get:

```
Wildcards.java:2: error: [type.argument.type.incompatible] incompatible types in type argument.
  NonN<?> f = new NonN<Object>();
       ^
  found   : ? extends @Initialized @Nullable Object
  required: @Initialized @NonNull Object
1 error
```

The behavior for the wildcard is different for `NonN` and `LocalNonN`, which is wrong.
I was able to reproduce it with this stub-file setup, but maybe there is a simpler way to reproduce this.

**Comment by wmdietlGC** [comment]
This issue might be related to https://github.com/typetools/checker-framework/issues/824 which was supposed to be fixed by https://github.com/typetools/checker-framework/pull/865 .
@smillst do you know why the fix from https://github.com/typetools/checker-framework/pull/865 didn't solve this issue?

**Comment by smillst** [comment]
I haven't looked at #865 closely, but it fixed a similar problem with method type parameters.  This issue is about class type parameters.

**Comment by wmdietlGC** [comment]
#865 seems to touch both method and class type parameters.

**Comment by smillst** [comment]
This code seem to be the problem:
https://github.com/typetools/checker-framework/blob/master/framework/src/org/checkerframework/framework/type/typeannotator/PropagationTypeAnnotator.java#L105-L106

Annotations on class type parameters in stub files are not stored directly in typesFromStubFiles.  So getting the type via a type parameter  element won't include them.

**Comment by wmdietlGC** [comment]
Thanks for pointing at that code!
If the annotations for class type parameters from stub files are not stored in `typesFromStubFiles` where are they stored?

**Comment by smillst** [comment]
They are stored in `typesFromStubfiles`.  But to access them, you need to use the class element that declares them to get its AnnotatedDeclaredType, then call getTypeArguments().  Or the stub parsers need to be changed to store them by themselves.

**Comment by wmdietlGC** [comment]
Ok, so the type parameters are not stored, but the enclosing class is.
Putting the type parameter elements into `typesFromStubfiles` seems the better way; otherwise, every user has to remember to go back to the class and access the type parameters from there.
Do you know the location where to do this or should I look?

**Comment by smillst** [comment]
It should be done somewhere in org.checkerframework.framework.stub.StubParser#parseType.

**Comment by wmdietlGC** [comment]
Not in org.checkerframework.framework.stub.StubParser#annotateTypeParameters ?

**Comment by smillst** [comment]
That is called for both method and class type parameters.  I don't know if method type parameters need to be stored, too.

Also, you'll need to get the type parameter element from somewhere.  You can get it from the type element in parseType.  But I guess that could be passed to annotateTypeParameters.

**Comment by wmdietlGC** [comment]
https://github.com/typetools/checker-framework/pull/1206
