### ISSUE TITLE
Unable to build under Android starting with 2.1.5

### ISSUE THREAD

**Issue by scottkennedy** [typetools/checker-framework#1066]
I'm building for Android, and I can't use 2.1.5 or later when I depend on `org.checkerframework:checker-qual`

It gives me an error "bad class file magic (cafebabe) or version (0034.0000)".

I use `@EnsuresNonNullIf`, which is not included in `org.checkerframework:checker-compat-qual`.  I'm not sure if there should be a version in there, or if there's some other way to get this to build for me, but it worked in 2.1.4 and not in 2.1.5 (or later).

**Comment by shubhadeepc** [comment]
I wonder how you're able to get past the [error](https://github.com/typetools/checker-framework/issues/1062) that I'm getting. Any ideas?

**Comment by scottkennedy** [comment]
That error comes later in the process (so this error blocks me from seeing that one), and I saw it earlier today when I commented out all the `@EnsuresNonNullIf` and that dependency.

**Comment by mernst** [comment]
Thanks for the bug report, and I'm sorry you are having trouble.  Can you please provide a complete, reproducible bug report?  That will save us time of guessing what you did, and it will enable us to ensure that our fix works for your specific use case.  Thanks in advance.

**Comment by mernst** [comment]
The Checker Framework Manual now has new instructions for type-checking Android code:
https://checkerframework.org/manual/#android-gradle
These instructions ought to resolve this issue.
