### ISSUE TITLE
Remove out-of-date guava sources

### ISSUE THREAD

**Issue by wmdietlGC** [typetools/checker-framework#1077]
There are out-of-date guave sources here: https://github.com/typetools/checker-framework/tree/master/checker/jdk/nullness/src/com/google/common

All of these have been replaced by https://github.com/typetools/guava according to https://github.com/typetools/checker-framework/blob/master/checker/lib/README

**Comment by smillst** [comment]
#334 is related to this maybe even a duplicate.

**Comment by wmdietlGC** [comment]
I think #334 is out of date. The Guava sources were moved to the typetools/guava repository. There no longer is a need to move them to stub files.
I think #334 should be closed.
