### ISSUE TITLE
make caches in AnnotationUtils thread safe

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#1108]
It'd be great if the [static caches in `AnnotationUtils`](https://github.com/typetools/checker-framework/blob/b7f67fc1c973439e8c2644490ca1d94eafc19a06/javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java#L60) could be made into instance fields instead (there are already `TODO` comments in the code to this effect).  Beyond the issue of memory leaks (motivating the `AnnotationUtils.clear()` method), these caches are not thread safe.  I am using the Checker dataflow framework from within [Buck](https://buckbuild.com/), and Buck runs multiple javac instances concurrently within the same JVM.  I got lucky and observed a crash due to a data race on these fields, but the issue could have lurked for a long time.

I have a patch to at least make the caches thread safe, while leaving them as static fields (via locking).  Changing them to be instance fields required more pervasive code changes than I felt capable of.  If doing the proper instance field fix isn't something doable in the short term, I am willing to contribute a fix to at least make them thread safe.

Also, FWIW, I observed that the attempt to bound [the `annotationMirrorNames` cache](https://github.com/typetools/checker-framework/blob/b7f67fc1c973439e8c2644490ca1d94eafc19a06/javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java#L69) using an LRU cache wasn't working.  The cache was still growing without bound, so I had to insert `clear()` calls anyway.  Not sure what exactly was going on; maybe things break when the cache persists across multiple javac instances?

**Comment by wmdietlGC** [comment]
I completely agree that we should get rid of any static state and make sure the code is thread safe.

At some point we started an effort of passing around a context object for the current compilation:
framework/src/org/checkerframework/framework/util/BaseContext.java and framework/src/org/checkerframework/framework/util/CFContext.java .
However, we never fully converted all utility classes.

Do you have a feeling for how much your thread-safe patch would impact single-threaded performance? If the impact is small, it would be great to integrate this fix.

**Comment by msridhar** [comment]
I don't know single-threaded performance impact. If someone has benchmarks
I could put up a pull request so we could try it out.

**Comment by wmdietlGC** [comment]
As a first step let's just see whether `ant tests-nobuildjdk` has about the same running time.
A PR would be great!
