### ISSUE TITLE
Spaces in path to javac compiler leads to error: Error: Unable to access jarfile C:\Users\Vatsal

### ISSUE THREAD

**Issue by vatsalsura** [typetools/checker-framework#1110]
- Checker-Framework Version: 2.1.9
- OS Version: Windows 10 Pro (version 1607, build 14393.693)

**# Steps to Reproduce:**

1. Copy and unzip the checker-framework at any path containing at least a single white-space (in my case:
`C:\Users\Vatsal Sura\Downloads\`

2. Run the javac command in the directory:
`C:\Users\Vatsal Sura\Downloads\checker-framework-2.1.9\checker\bin`

**# Expected behavior:**
Give the following output:
`javac: no source files or class names`
`Usage: javac <options> <source files>`
`use -help for a list of possible options`

**# Actual behavior:**
`Error: Unable to access jarfile C:\Users\Vatsal`

**Comment by vatsalsura** [comment]
@wmdietlGC I would like to work on this issue but as I am beginner I don't know where to start from. Can I get some pointers on where to start from?

**Comment by wmdietl** [comment]
Sure, PRs are always welcome!

**Comment by vatsalsura** [comment]
#1113
