### ISSUE TITLE
Keep the latest version on maven central

### ISSUE THREAD

**Issue by levonk** [typetools/checker-framework#1132]
Thank great tool!

We currently have to import the dependencies directly from https://types.cs.washington.edu/m2-repo/  .  The latest release version should always be on maven central.  Otherwise, this causes a few problems 

- New users get outdated version when using search.maven.org
- Tools like maven stop looking for the latest version in the maven central and assume its a missing artifact which causes needless developer lost time
- plugins like maven-project-info-reports-plugin have problems generating dependency-management reports.

**Comment by levonk** [comment]
Using maven, deploying to maven central is easy: https://github.com/DGHLJ/pub-maven-archetypes/blob/master/pom.xml#L146-L165

**Comment by mernst** [comment]
The latest version of the artifacts is on Maven Central already:  https://search.maven.org/#search%7Cga%7C1%7Ccheckerframework

This is explained in the Checker Framework manual:
https://checkerframework.org/manual/#maven

Can you explain why you believed incorrectly that "We currently have to import the dependencies directly from https://types.cs.washington.edu/m2-repo/ ."?

**Comment by levonk** [comment]
Thanks for the quick response.   Old doc I must have referenced, I'll try updating to the latest doc.   I was getting failures on org.checkerframework:checker-framework:2.1.6 when I didn't have it pointing to the cs.washington.edu site.   I'll give it a try with the newer doc.

**Comment by mernst** [comment]
Can you be specific?  I can't tell from your inexact descriptions how to improve the situation.
What exact "old doc" -- what is the URL or other source?
What "failures on org.checkerframework:checker-framework:2.1.6 when I didn't have it pointing to the cs.washington.edu site."?  What is the exact failure that occurred, and what is a sequence of steps that reproduces it?
We want to help you, but we cannot do so if we have only incomplete information.
