### ISSUE TITLE
 Nullness checker handling of ConcurrentHashMap

### ISSUE THREAD

**Issue by kanha95** [typetools/checker-framework#1142]
This is a bug.The root cause is that ConcurrentHashMap does not appear in the annotated JDK for the Nullness Checker.

The solution is to annotate file ConcurrentHashMap.java from the Java 8 JDK, and add it to checker/jdk/nullness/src/java/util/concurrent/ in the Checker Framework repository.

**Comment by mernst** [comment]
This bug report is fragmentary and incomplete.  Please add a test case and any other information that is relevant.  Thanks!

**Comment by kanha95** [comment]
Example 1: 

void foo() {

Map<Integer,@Nullable Integer> myMap =new ConcurrentHashMap<>();

myMap.put(1, 1);

myMap.put(2, 2);

myMap.put(3, 3);

Iterator<Integer> it1 = myMap.keySet().iterator();

while(it1.hasNext()) {

Integer key = it1.next();

System.out.println(key+" Map Value:"+myMap.get(key));

if(key.equals(1)) {

myMap.put(3, null);

}

}

}

Output: Nullness Checker passed!

N.B:

As per java docs ,

https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentHashMap.html

The concurrent-hashmap raises NullpointerException if any of the key or value is null. So here the Nullness Checker fails in catching the NullPointerException generated at the runtime. If bymistake any programmer annotes the value parameter to be @Nullable then the program will crash at the runtime.

Example 2:

void foo() {

Map<@Nullable Integer,Integer> myMap =new ConcurrentHashMap<>();

myMap.put(1, 1);

myMap.put(2, 2);

myMap.put(3, 3);

for(Map.Entry<@Nullable Integer,Integer> i:myMap.entrySet()){

System.out.println(i.getKey()+" "+i.getValue());

if(i.getValue()==2){

myMap.put(null, 4);

}

}

}

Output: Nullness Checker Passed!

N.B.

Here also the same problem arises. It is not able to catch the NullPointerException generated during runtime because of the above mentioned reasons.

**Comment by rajatjain1997** [comment]
Can I work on this bug if @kanha95 is not assigned to it? I'd love to try annotating the ConcurrentQueue class for a start.

**Comment by mernst** [comment]
Sure.  This is a nice, easy task to start with.  Please check whether there are other classes that also prohibit null and should be annotated at the same time.

**Comment by wmdietl** [comment]
@kanha95 @rajatjain1997 You two should synchronize on who wants to work on this. There are plenty of other tasks to be done, so there is no need to do the same thing twice.
https://github.com/typetools/checker-framework/pull/1145

**Comment by rajatjain1997** [comment]
Okay @wmdietl I'm off the issue for now, since @kanha95 is the one who reported it :-). If he wants I can help him with it. I would be active on the PR if I've any new annotated classes.
