### ISSUE TITLE
Class StringJoiner of java 8 needs to be annotated for add method

### ISSUE THREAD

**Issue by kanha95** [typetools/checker-framework#1147]
import org.checkerframework.checker.nullness.qual.*;
import java.util.StringJoiner;
class Test2{

public static void main(String[] args){

StringJoiner sj=new StringJoiner(",");

    sj.add("a");
    sj.add(null);

    System.out.println(sj);
}
}

It's a correct program but Nullness Checker gives false warnings at compile time. The documentation states that null is a valid argument, so the parameter should be annotated as @Nullable.

**Comment by mernst** [comment]
I agree.  Thanks for pointing out this problem.

**Comment by smillst** [comment]
Close via dcf80de
