### ISSUE TITLE
Conjunction to specify range of array lengths, in Index Checker

### ISSUE THREAD

**Issue by Bohdankm22** [typetools/checker-framework#1159]
Consider following code:

```
private static void readInfo(String k, int m) {
        String[] parts = k.split(" ");
        if (parts.length <= 5) {
            // Do nothing
        } else if (parts.length > 5 && parts.length <= 10) {
            // Do nothing
        } else {
            // The array length have to be > 10
            Integer.parseInt(parts[0]);
            Integer.parseInt(parts[6]);  // Potentially unsafe array access: the index could be larger than the arrays bound
            Integer.parseInt(parts[9]);  // Potentially unsafe array access: the index could be larger than the arrays bound
            Integer.parseInt(parts[10]);  // Potentially unsafe array access: the index could be larger than the arrays bound
        }
    }
```

As seen from code example above there is the if-else used for checking the array length. 
Firstly it checks that  "parts.length <= 5", then there is "else if" with the condition "parts.length > 5 && parts.length <= 10". Basically after this step only scenarios with the array length > 10 left. However, accessing array items with indexes from 6 to 10 lead to the following error:

```
Error:(125, 36) java: [array.access.unsafe.high] Potentially unsafe array access: the index could be larger than the array's bound
  found   : @UpperBoundUnknown int
  required: an integer less than parts's length (@LTLengthOf("parts"))
```

Expected: in the last else block array items with indexes from 6 to 10 are safe to access.

My assumption is that condition "parts.length > 5 && parts.length <= 10" was not considered enough to assume that the "else" clause will be only executed if the array length > 10.

**Comment by mernst** [comment]
I agree that the code is safe and therefore the checker warning is a false positive
Thanks for the test case!

Here is a shorter version of your test case:

```java
import org.checkerframework.checker.index.qual.MinLen;

public class RangeConjunction {

  private static void readInfo(String[] parts) {
    if (parts.length <= 5) {
      // Do nothing
    } else if (parts.length > 5 && parts.length <= 10) {
      // Do nothing
    } else {
      String  @MinLen(10) [] temp = parts;
    }
  }

}
```

and here is the Index Checker output:

```java
$ch/bin/javac -g RangeConjunction.java -processor index
RangeConjunction.java:11: error: [assignment.type.incompatible] incompatible types in assignment.
      String  @MinLen(10) [] temp = parts;
                                    ^
  found   : @MinLen(0) String @MinLen(6) []
  required: @MinLen(0) String @MinLen(10) []
1 error
```

I can make the code shorter and simpler by dropping the redundant clause in the conjunction:

```java
import org.checkerframework.checker.index.qual.MinLen;

public class RangeConjunction {

  private static void readInfo(String[] parts) {
    if (parts.length <= 5) {
      // Do nothing
    } else if (parts.length <= 10) {
      // Do nothing
    } else {
      String  @MinLen(10) [] temp = parts;
    }
  }

}
```

This is arguably better code, and the Index Checker issues no warnings in this case:  the Index Checker can verify the correctness of this code.

The Index Checker does not perform every possible type of arithmetic.  It performs a subset that are important in practice.  This is an example of something that is outside its capabilities.

I'm going to close this issue for now, but if there are real-world examples where this is important and the code cannot be easily rewritten to avoid the problem, let's re-open it.

Thanks again for the report.
