### ISSUE TITLE
not taking correct files for compiling

### ISSUE THREAD

**Issue by shivanshsoni** [typetools/checker-framework#1187]
I have a folder named winter on my desktop where I keep my codes and when I process command 
**javac -processor NullnessChecker bladder.java**
then instead of processing bladder.java, it started showing results for christmas.class.
When I put it in another folder it shows correct output.
when I compile it with
**javac bladder.java** 
it compiled it properly. 

**My output:**
![screenshot 20](https://cloud.githubusercontent.com/assets/24546371/24328128/e91e85d8-11fe-11e7-8853-2a19ca92d909.png)

I think it is a big issue. Please review this.

**Comment by mernst** [comment]
Can you please provide a complete, reproducible test case so that other people can see the same results you are seeing?  You have not attached `christmas.java`, for example; I would assume that (and anything else in your `winter` folder) is needed in order to reproduce the problem.  Also, have you attached the correct version of `bladder.java`, or might there be two different versions in the two directories?

**Comment by shivanshsoni** [comment]
Actually I have created a file named string.java in which I have christmas1 mehod.

Something like this:

![screenshot 23](https://cloud.githubusercontent.com/assets/24546371/24328499/165afa72-1209-11e7-8e4d-a1ec756d315e.png)

and instead ofusing java library, string mehod in bladder.java is using this string.java to produce results.

Bladder.java:

import java.util.Scanner;
class bladder
{
	public static void main(String[]args)
	{
		Scanner scan=new Scanner(System.in);
		int t,i,j,k,l;
		t=scan.nextInt();
		for(i=0;i<t;i++)
		{
			j=scan.nextInt();
			k=scan.nextInt();
			if(j%2!=0&&k%2!=0||j%2==0&&k%2==0)
			{
				if(j-k==2||k-j==2)
				{
					System.out.println("YES");
				}
				else
				{
					System.out.println("NO");
				}
			}
			else if(j%2==0&&k%2!=0)
			{
				if(j-k==1)
				{
					System.out.println("YES");
				}
				else
				{
					System.out.println("NO");
				}
			}
			else if(j%2!=0&&k%2==0)
			{
				if(k-j==1)
				{
					System.out.println("YES");
				}
				else
				{
					System.out.println("NO");
				}
			}
			else
			{
				System.out.println("NO");
			}
		}
	}
}

**Comment by shivanshsoni** [comment]
Is it due to usage of String[]args inside main mehod.
as it i have String[]args so instead of using library of java it is taking String.java

**Comment by mernst** [comment]
Great, it sounds like you have solved the problem, and it wasn't related to running an annotation processor.  Maybe your operating system doesn't distinguish lower-case from upper-case letters, so javac is using `string.java` when you use `String` in your program.

**Comment by shivanshsoni** [comment]
But it is working fine with javac 8 compiler

**Comment by shivanshsoni** [comment]
@mernst I think it is a problem as I dont think my opearing system is working fine with uppercase and lowercase letters.

**Comment by mernst** [comment]
It seems that your `string.java` file contains potential null pointer exceptions.  Compiling that file with javac won't issue any errors, but type-checking it with the Nullness Checker will.
