### ISSUE TITLE
IntRange on new array lengths causes Value Checker to crash

### ISSUE THREAD

**Issue by kelloggm** [typetools/checker-framework#1198]
Consider the following code:

```java
import org.checkerframework.common.value.qual.*;

class IntRangeArrayInteraction {
    void test(@IntRange( to = 1, from = Integer.MAX_VALUE ) int length) {
	int[] a = new int[length];
    }
}
```

When the Value Checker is run on this code, it attempts to assign an `@ArrayLen` annotation to `a` in `ValueAnnotatedTypeFactory#ValueTreeAnnotator#handleDimensions`. When it does this, it tries to call `getIntValues` on the annotation on `length`, which fails because `length`'s annotation is a range.

**Comment by kelloggm** [comment]
@JasonMrX

**Comment by JasonMrX** [comment]
I am looking into this.

**Comment by JasonMrX** [comment]
@kelloggm sorry for causing this issue. The checker would crash if `length` is annotated with anything other than `@IntVal`, e.g. `@IntRange`, `@BottomVal`. 

A quick fix would be doing an `areSameByClass` check in the `ValueAnnotatedTypeFactory#handleDimensions()` and if the annotation is `@IntRange`, we call `ValueAnnotatedTypeFactory#convertIntRangeToIntVal()` before calling `getIntValues()`.

In the long term, would it be beneficial to add an `@ArrayLenRange` to handle a wider range?

What is the process of fixing an issue in the repo? Do I create a new PR or reopen the last one? I wasn't aware of the fact that `@ArrayLen` depends on `@IntVal`. Really sorry for causing the trouble.

**Comment by kelloggm** [comment]
No worries at all; we're glad to have your help. The right thing to do is
open another pull request with the fix, which can be reviewed independently.

**Comment by wmdietl** [comment]
That should probably be in `handleDimensions` https://github.com/typetools/checker-framework/blob/master/framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java#L565 change `getIntValues` to a method that handles either IntVal or IntRange...
