### ISSUE TITLE
Polymorphic qualifier on only a return type

### ISSUE THREAD

**Issue by mernst** [typetools/checker-framework#1209]
The [manual says](https://checkerframework.org/manual/#qualifier-polymorphism-multiple-qualifiers):

> It is not permitted to write just one polymorphic qualifier, on a return type.  You may write a polymorphic qualifier on a return type only if that polymorphic qualifier also appears elsewhere in the signature, on some formal parameter.

This restriction is not currently enforced.  A test case appears in file `checker/tests/signedness/PolymorphicReturnType.java`.

**Comment by wmdietl** [comment]
Java allows method type parameters that only appear in return types. Polymorphic qualifiers that only appear in returns would have the same use cases and soundness concerns if misused.
Maybe the manual should be updated to highlight that trade-off.

**Comment by mernst** [comment]
Good point.  Can you point at a discussion of the use cases and soundness concerns in Java?

**Comment by mernst** [comment]
A standard example is `Collections.emptyList()`.
