### ISSUE TITLE
Value Checker Array element type inference

### ISSUE THREAD

**Issue by mernst** [typetools/checker-framework#1229]
Array element type inference seems to work differently, and not as well, for the Value Checker as for other checkers.

Consider the following example.  The Regex Checker is able to type-check all three declarations, but the Value Checker fails to type-check the declaration of `a3`.

```java
import org.checkerframework.checker.regex.qual.Regex;
import org.checkerframework.common.value.qual.IntVal;

public class ArrayElementInference {

  @IntVal({0,1,2,3}) int[] a1 = new @IntVal({0,1,2,3}) int[] {0, 1, 2, 3};
  int[] a2 = new @IntVal({0,1,2,3}) int[] {0, 1, 2, 3};
  @IntVal({0,1,2,3}) int[] a3 = new int[] {0, 1, 2, 3};

  @Regex(1) String[] a4 = new @Regex(1) String[] {"(hello)", "(two) (groups)"};
  String[] a5 = new @Regex(1) String[] {"(hello)", "(two) (groups)"};
  @Regex(1) String[] a6 = new String[] {"(hello)", "(two) (groups)"};

}
```

The compiler output is:

```
$ch/bin/javac -g ArrayElementInference.java -processor index,regex
ArrayElementInference.java:8: error: [assignment.type.incompatible] incompatible types in assignment.
  @IntVal({0,1,2,3}) int[] a3 = new int[] {0, 1, 2, 3};
                                ^
  found   : @UnknownVal int @ArrayLen(4) []
  required: @IntVal({0L, 1L, 2L, 3L}) int @UnknownVal []
1 error
```

I would expect that there is some common mechanism that all type-checkers use automatically, without the need for special handling within the implementation of any type-checker.

**Comment by smillst** [comment]
The code that implements this functionally is in `PropagationTreeAnnotator#visitNewArray`.  The Value Checker does not use this TreeAnnotator because it uses different typing rules.  Except that it should use the same rules for NewArrayTrees.
