### ISSUE TITLE
Irregular compilation error

### ISSUE THREAD

**Issue by justmin** [typetools/checker-framework#1239]
This problem appeared many times on different computers. It is like 'works on my machine'
Our project is compileable with CheckerFramework enabled, but sometimes, one or another developer report compilation error in code, which is compileable on other machines. Sometimes build failed on builder machine. After some period of time error usually disappeared: we try to remove .m2 downloaded dependencies, restart ide/computer etc. 

The only information I can provide is stack trace. There are no information about even class where error appears...

Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:718)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:45)
  org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:146)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:325)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:32)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:302)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:41)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:80)
  org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:66)
  org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:126)
  org.checkerframework.framework.type.DefaultTypeHierarchy.castedAsSuper(DefaultTypeHierarchy.java:896)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:415)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:52)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:302)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:221)
  org.checkerframework.checker.nullness.KeyForAnnotatedTypeFactory$KeyForTypeHierarchy.isSubtype(KeyForAnnotatedTypeFactory.java:390)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:171)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:152)
  org.checkerframework.framework.util.typeinference.DefaultTypeArgumentInference.combineSupertypeAndAssignmentResults(DefaultTypeArgumentInference.java:516)
  org.checkerframework.framework.util.typeinference.DefaultTypeArgumentInference.infer(DefaultTypeArgumentInference.java:254)
  org.checkerframework.framework.util.typeinference.DefaultTypeArgumentInference.inferTypeArgs(DefaultTypeArgumentInference.java:104)
  org.checkerframework.framework.util.AnnotatedTypes.findTypeArguments(AnnotatedTypes.java:565)
  org.checkerframework.framework.type.AnnotatedTypeFactory.methodFromUse(AnnotatedTypeFactory.java:1818)
  org.checkerframework.framework.type.AnnotatedTypeFactory.methodFromUse(AnnotatedTypeFactory.java:1804)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.methodFromUse(GenericAnnotatedTypeFactory.java:1131)
  org.checkerframework.checker.nullness.KeyForAnnotatedTypeFactory.methodFromUse(KeyForAnnotatedTypeFactory.java:205)
  org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:209)
  org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:53)
  com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
  com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
  org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:36)
  org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:1172)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:953)
  org.checkerframework.framework.flow.CFAbstractTransfer.getValueFromFactory(CFAbstractTransfer.java:210)
  org.checkerframework.framework.flow.CFAbstractTransfer.visitMethodInvocation(CFAbstractTransfer.java:887)
  org.checkerframework.checker.nullness.KeyForTransfer.visitMethodInvocation(KeyForTransfer.java:62)
  org.checkerframework.checker.nullness.KeyForTransfer.visitMethodInvocation(KeyForTransfer.java:34)
  org.checkerframework.dataflow.cfg.node.MethodInvocationNode.accept(MethodInvocationNode.java:81)
  org.checkerframework.dataflow.analysis.Analysis.callTransferFunction(Analysis.java:362)
  org.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:220)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:893)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:861)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:805)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1090)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.addComputedTypeAnnotations(GenericAnnotatedTypeFactory.java:1057)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.addComputedTypeAnnotations(GenericAnnotatedTypeFactory.java:1037)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:960)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:2156)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:296)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:172)
 com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:70)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:942)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:449)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:443)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:209)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.main.Main.compile(Main.java:381)
  com.sun.tools.javac.main.Main.compile(Main.java:370)
  com.sun.tools.javac.main.Main.compile(Main.java:361)
  com.sun.tools.javac.Main.compile(Main.java:56)
  com.sun.tools.javac.Main.main(Main.java:42)

**Comment by justmin** [comment]
CF 2.1.0

**Comment by mernst** [comment]
Thanks for the bug report!  I am sorry that you are having trouble.
Two quick comments:

1. Upgrading to CF 2.1.10 may correct some or all of your problems.  We have fixed a lot of bugs in the past 9 months.
2. We have a reproducible test case that has a stack trace somewhat similar to yours.  However, that test case is an entire, huge, proprietary project, and although we are actively working on it, we haven't been able to reproduce it as a small test case.  When we figure out that test, maybe it will help you.

**Comment by justmin** [comment]
We tried to upgrade to later versions, but there is showstopper for this: https://github.com/typetools/checker-framework/issues/989 
Are you planning to fix it?

**Comment by wmdietl** [comment]
Hi @justmin ; sorry about the delay on #989 I hadn't run into that issue myself and forgot that it is blocking you; I'll work on it for the May 1st release.
Issue #1239 is something I'm also running into, but have a hard time to reproduce externally. Please let us know if you find a test case.

**Comment by justmin** [comment]
Hello,

Thank you for your efforts!
I could add some details about 1239: In most cases it appears when project is cloned at first time on machine, but there was many development work on the same machine before: many different maven dependencies was download. May be it is due to conflicts in dependencies versions?

**Comment by wmdietl** [comment]
@justmin #989 is fixed and will be included in the next release.
Can you try and see if this issue goes away? If not, we need to work on producing a test case.
Thanks,
cu, WMD.

**Comment by justmin** [comment]
Hello,
This issue is resolved. Thank you.

**Comment by smillst** [comment]
Great! Thanks for letting us know!
