### ISSUE TITLE
"this" (the keyword) should *always* be @NonNull

### ISSUE THREAD

**Issue by JacksonBailey** [typetools/checker-framework#1268]
I was playing around with this today, so naturally to even get it to come *close* to working with my project I had to tell it everything is `@Nullable` and `@NotOnlyInitalized` *(the latter because a lot of our classes have private no-arg constuctors for frameworks like Spring and Jackson to use but public ones with args for humans to use.)*

So I placed this `package-info.java` in the base of our project.

```java
@org.checkerframework.framework.qual.DefaultQualifiers({
    @org.checkerframework.framework.qual.DefaultQualifier(org.checkerframework.checker.nullness.qual.Nullable.class),
    @org.checkerframework.framework.qual.DefaultQualifier(org.checkerframework.checker.initialization.qual.NotOnlyInitialized.class)
  })
package com.foo;
```

Then, when I ran it (through Maven) I see a lot of errors like this:

```log
[ERROR] /C:/code/projects/foo/src/main/java/com/foo/response/FooAddress.java:[75,47] [argument.type.incompatible] incompatible types in argument.
[ERROR]   found   : @Initialized @Nullable FooAddress
[ERROR]   required: @Initialized @NonNull Object
```

Here is the code the error is referring to:

```java  
@Override
public String toString() {
  return ToStringBuilder.reflectionToString(this);
}
```

So the framework believes that `this` is `@Nullable`. `this` can *never* be `null` because if `this` were `null` then the method `this` is in couldn't even be called. (I found this [StackOverflow post][1] which confirms my belief. I checked in case there was some weird corner case.)

I suspect this is technically an enhancement and not a defect because I actually *am* telling the checker to assume *everything* is `@Nullable`. It would make more sense if `this` was always `@NonNull` to the framework, similarly to how it "casts" to `@NonNull` in side of null-check conditionals.

[1]: http://stackoverflow.com/a/3789534/1858327

**Comment by smillst** [comment]
Thanks for reporting this.  `this` is indeed always non-null, so it would be better if changing the defaults did not change the type of `this`.  

You can work around this by changing the default for 'this' by adding the following annotation to your list of default qualifiers:
`@DefaultQualifier(value = NonNull.class, locations = TypeUseLocation.RECEIVER)`

**Comment by mernst** [comment]
There are three ways a Java type can be given a type qualifier:  implicits, defaults, and explicitly written type annotations.

The Nullness Checker should use implicits to give the `this` identifier its type via implicits, just as `null` is.
It is a bug that `this` is given its type via defaults.
To fix this bug, it is possible to hard-code behavior into the Nullness Checker, as the behavior is for `null`.  That is perhaps the most pragmatic way forward.

This issue is related to #1139; fixing that issue is also desirable but would take more time.

**Comment by wmdietl** [comment]
Should this issue have been closed with #1414?

Suitable for the subject of this issue, if I write:

```java
import org.checkerframework.checker.nullness.qual.Nullable;
class C {
  void foo(@Nullable C this) {
    this.toString();
  }
}
```

I get:

```
Error: [method.invocation.invalid] call to toString() not allowed on the given receiver.
   found   : @Initialized @Nullable Object
   required: @Initialized @NonNull Object
```

So we should also stop people from explicitly making `this` `@Nullable`.

**Comment by JacksonBailey** [comment]
@wmdietl It looks like #1414 was closed as it was a duplicate of this (pun unintended haha). I have not used this tool in ages so I am unsure if the problem is still around.

**Comment by mernst** [comment]
@JacksonBailey I believe it is a duplicate, so I'm closing it now.  Thank you for noticing!
