### ISSUE TITLE
Build fails when user name contains a space

### ISSUE THREAD

**Issue by panacekcz** [typetools/checker-framework#1270]
On Windows, if the user name contains a space (for example Vlastimil Dort), the build fails with an error:
```
build:
     [java] javac: file not found: C:\Users\VLASTI~1\AppData\Local\Temp\Vlastimil (System cannot find the file specified)
```
This is caused by using the property `${tmpdir}` in arguments without quotes in several `java` tasks in [checker/build.xml](https://github.com/typetools/checker-framework/blob/master/checker/build.xml). The property `${tmpdir}` is defined in [build-common.xml](https://github.com/typetools/checker-framework/blob/master/build-common.xml) as a path where one of the parts is `${user.name}`. If the user name contains a space, then the path contains a space and it is treated as multiple separate arguments by javac.

**Comment by mernst** [comment]
I believe this was fixed by commit 301a13f8558ac8a5d16e38864cc82d97c346a9c1.
