### ISSUE TITLE
Build fails on Windows when Git symlinks are disabled

### ISSUE THREAD

**Issue by panacekcz** [typetools/checker-framework#1271]
Because creating symbolic links on Windows requires permissions, Git for Windows may set the git option [`core.symlinks`](https://git-scm.com/docs/git-config#git-config-coresymlinks) to `false`. (This can be configured during installation, see https://github.com/git-for-windows/git/issues/921.)

When `core.symlinks` is `false`, symbolic liks are checked out as text files and the build fails with an error:
```
     [exec] make[1]: Entering directory `/…/checker-framework/checker/jdk/nullness'
     [exec] make[1]: Leaving directory `/…/checker-framework/checker/jdk/nullness'
     [exec] make: Leaving directory `/…/checker-framework/checker/jdk'
     [exec] Makefile:1: *** missing separator.  Stop.
     [exec] make: *** [nullness.clean] Error 2
```

A possible solution could be to use [`include`](https://www.gnu.org/software/make/manual/html_node/Include.html) directives instead of symbolic links. Like this: https://github.com/panacekcz/checker-framework/commit/0c89f8becdc52734e45ecc84c6cc48a370a1237a.

**Comment by smillst** [comment]
Fixed via fe6e81bd146a557f5d118604299d44fe05164455.
