### ISSUE TITLE
Support @Repeatable on appropriate annotations

### ISSUE THREAD

**Issue by aabdagic** [typetools/checker-framework#1307]
Suppose I want to annotate an interface like this:

```java
interface FooOrBar {
  @Nullable getFoo();
  @Nullable getBar();
  
  @EnsuresNonNullIf(expression = "getFoo()", result = true)
  @EnsuresNonNullIf(expression = "getBar()", result = false)
  boolean hasFoo();

  @EnsuresNonNullIf(expression = "getBar()", result = true)
  @EnsuresNonNullIf(expression = "getFoo()", result = false)
  boolean hasBar();
}
```

This isn't possible today because `@EnsuresNonNullIf` doesn't support `@Repeatable`. There are a few more use-cases that unlock if `@Repeatable` is supported. The same applies to several other annotations, e.g. `@EnsuresNonNull`, `@EnsuresQualifierIf`, etc.

**Comment by wmdietl** [comment]
Hi Alvin,
thanks for the suggestion!

I agree that for the declaration annotations that take a set of expressions and a truth value it might be useful to make them `@Repeatable`, to allow specifying expressions for both true and false.

I don't see a benefit for an annotation like `@EnsuresNonNull` that only takes a set of expressions - you can simply concatenate the two sets.

One thing to consider is the implementation of these `hasXXX` methods. They would usually be something like:

```
@EnsuresNonNullIf(expression = "getFoo()", result = true)
@EnsuresNonNullIf(expression = "getBar()", result = false)
boolean hasFoo() {
  return getFoo() != null;
}
```

When we type check that method we can make sure that the first contract is established - we see that `getFoo` is not null.
However, we don't see that `getBar` will return null. So one would have to suppress a warning on this method declaration.

Another thing to consider is future extensions. Let's say a new `getBaz` method is added that is non-null if the other two are null. Now one has to add that specification to all the existing methods and make sure that all existing conditions are adapted.
Sticking with just a single post-condition would force one to write:

```
if (hasFoo()) {
  getFoo() is non-null;
} else if (hasBar()) {
  getBar() is non-null;
} else {
  raise an error!
}
```

This way every has/get pair only needs to specify their own properties and adding a new case for hasBaz/getBaz is easy to track down.

**Comment by mernst** [comment]
@aabdagic In his comment above, Werner hypothesizes that this feature would be hard to implement and would be of little use in practice.  Can you give a realistic use case to support your feature request?

**Comment by aidanPB** [comment]
It seems to me that (in the generic case, at least) the hard work of implementing this feature has already been done. One can already write the following:
```java
@EnsuresQualifiersIf({
    @EnsuresQualifierIf(result=true, qualifier=NonNull.class, expression="getFoo()"),
    @EnsuresQualifierIf(result=false, qualifier=NonNull.class, expression="getBar()")
})
boolean hasFoo();
```
All that's missing is the `@Repeatable(EnsuresQualifiersIf.class)` annotation on `@EnsuresQualifierIf` to allow omitting the containing annotation type. (Of course, the fact that the Checker Framework operates on source files may complicate matters somewhat, but it would be nice if the JavaDocs explained _why_ `@EnsuresQualifierIf` can't be made repeatable if such is the case.)

**Comment by wmdietl** [comment]
Let me look into making `EnsuresQualifierIf` repeatable and adding a containing annotation for `EnsuresNonNullIf`.

**Comment by gokaco** [comment]
Mike, I am not understading the real motive of this issue. @DefaultQualifier is repeatable using @DefaultQualifiers and @EnsureQualifierIf is also repeatable using @EnsuresQualifiersIf. Do you want that without using @DefaultQualifiers and @EnsuresQualifiersIf annotations they should be repeatable?

**Comment by mernst** [comment]
Yes, you are right that wrappers are defined that can contain multiple annotations.
But, it is not possible for a programmer to write multiple annotations and have the wrapper automatically inferred.
There is documentation here:  https://docs.oracle.com/javase/tutorial/java/annotations/repeating.html

**Comment by mernst** [comment]
Here is a list of annotations that should be `@Repeatable`:
```
  @DefaultQualifier
  @EnsuresKeyFor
  @EnsuresKeyForIf
  @EnsuresLockHeldIf
  @EnsuresLTLengthOf
  @EnsuresLTLengthOfIf
  @EnsuresMinLenIf
  @EnsuresNonNullIf
  @EnsuresQualifier
  @EnsuresQualifierIf
  @FieldInvariant
  @GuardSatisfied
  @HasSubsequence
  @MethodVal
  @MinLenFieldInvariant
  @RequiresQualifier
  @SubstringIndexFor
```
