### ISSUE TITLE
Confusing FAQ entry in the manual about nullness of Collection type parameter

### ISSUE THREAD

**Issue by panacekcz** [typetools/checker-framework#1324]
The section 31.7.1 states:

> The annotation on java.util.Collection only allows non-null elements:
> `public interface Collection<E extends @NonNull Object> {`

However, the annotation in [Colleciton.java](https://github.com/typetools/checker-framework/blob/master/checker/jdk/nullness/src/java/util/Collection.java#L9) is `@Nullable`. 

The whole entry seems to be outdated / confusing.

**Comment by smillst** [comment]
Thanks for pointing this out! That FAQ was added in 2009 (ae115ed2b7b35ef933a68eb03675d550b1482069) and is out of date.  Interestingly, the manual has another entry about Collections, Section 2.4.3 (https://checkerframework.org/manual/#annotations-are-a-contract) -- this one is up-to-date.

**Comment by mernst** [comment]
I have a commit that removes the section, but I haven't pushed the commit yet.
