### ISSUE TITLE
Issue one warning if any type argument inference fails

### ISSUE THREAD

**Issue by smillst** [typetools/checker-framework#1355]
Pull request #1343 issues a warning on at every location that type argument inference fails is `-AconservativeUninferredTypeArguments` is passed.  If `AconservativeUninferredTypeArguments` is not passed, then a warning should be issued once if any type argument inference fails. 

Some implementation comments from Werner:
>Regarding issuing a warning only once: I'm not sure whether we have done that anywhere yet.
I would look at DeferredDiagnosticHandler in jsr308-langtools/src/share/classes/com/sun/tools/javac/util/Log.java and how it is used in jsr308-langtools/src/share/classes/com/sun/tools/javac/comp/Check.java.

**Comment by mernst** [comment]
This will be fixed when issue #979 is fixed.
