### ISSUE TITLE
Type annotation in stub file stored as declaration annotation 

### ISSUE THREAD

**Issue by smillst** [typetools/checker-framework#1356]
The stubparser stores some type annotations as declaration annotations.   The annotation is put in `AnnotatedTypeFactory#declAnnosFromStubFiles` which is then written out to bytecode.  This cause errors `type.invalid` when the byte code is later used. (Example below or `checker/jtreg/stubs/issue1356`.)  This only seems to happen if the type annotation has some argument.

~~This issue is blocking #1352, so we may want to add some work around such as removing type annotations from  `AnnotatedTypeFactory#declAnnosFromStubFiles`.~~  The ValueAnnotatedTypeFactory has been changed to work around this problem.  When this issue is fixed, please remove the work around.

File named MyClass.astub
```
import org.checkerframework.checker.regex.qual.*;
import org.checkerframework.common.value.qual.*;

package mypackage;

class MyClass {
   static @ArrayLen(1) @Regex(1) String toString(char c);
}
```
```java
package mypackage;

public class MyClass {
    static String toString(char c) {
        return c + "";
    }
}
```
```java
package mypackage;

public class UseMyClass {
    void test() {
        String s = MyClass.toString('a');
    }
}
```

Compile MyClass:
```
javacheck -processor org.checkerframework.checker.regex.RegexChecker -Astubs=stub.astub mypackage/MyClass.java
```
Compile UseMyClass
```
javacheck -processor org.checkerframework.checker.regex.RegexChecker mypackage/UseMyClass.java
```
Output:

```
mypackage/UseMyClass.java:5: error: [type.invalid] [@Regex(1), @UnknownRegex] may not be applied to the type "@Regex(1) String"
        String s = MyClass.toString('a');
                                   ^
1 error
```

**Comment by Bohdankm22** [comment]
I will work on it.

**Comment by smillst** [comment]
The workaround is no longer work and is causes failures such as https://travis-ci.org/typetests/daikon-typecheck/jobs/301695884#L1402.
