### ISSUE TITLE
Stub parser error reporting

### ISSUE THREAD

**Issue by kelloggm** [typetools/checker-framework#1371]
The stub parser does not report errors in a way friendly to users. Consider the following two examples:

- invalid syntax in a stub (such as a semicolon at the very end, right after the class close-bracket) can cause a `NullPointerException` in the stub parser ([here](https://github.com/typetools/checker-framework/blob/8f0a2f38464a7a06a1ffc27ffb0f99f104668e64/framework/src/org/checkerframework/framework/stub/StubParser.java#L381)) instead of reporting an error to the user.
- even in debug mode, misspelling an annotation (e.g. `PolyAll` as `PolyAl` or similar) fails silently without warning the user that the annotation they wrote doesn't exist

These sort of problems make using the stub parser difficult, especially for novices.

**Comment by wmdietl** [comment]
I agree with the general sentiment and a GSoC student is working on general improvements to the stubparser.
Regarding the second bullet: what do you mean with "in debug mode"? Did passing `stubWarnIfNotFound` not give a warning for this?

**Comment by mernst** [comment]
Fixed by 8997a34.
