### ISSUE TITLE
NPE when invoking CFGBuilder.CFGTranslationPhaseOne.process()

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#1372]
I don't have a small test case for this, but hopefully it's simple enough to just explain.  The `CFGBuilder.CFGTranslationPhaseOne.process()` method has two overloads, [here](https://github.com/typetools/checker-framework/blob/0a439f90bc4d804de32dfffdf23aeed758682961/dataflow/src/org/checkerframework/dataflow/cfg/CFGBuilder.java#L1440) and [here](https://github.com/typetools/checker-framework/blob/0a439f90bc4d804de32dfffdf23aeed758682961/dataflow/src/org/checkerframework/dataflow/cfg/CFGBuilder.java#L1485).  The second overload initializes the `trees` field and then invokes the first.  But in cases where the first overload is invoked directly, `trees` remains uninitialized, leading to an NPE.  I saw this when trying to run dataflow analysis for some lambda expressions.

Maybe `trees` could just be initialized in the first `process()` method?  I don't fully understand this code so not sure if I'm missing something.  Let me know if more details are required.

**Comment by wmdietl** [comment]
Can you share the stacktrace for the NPE? That will help us track down which code called `process` incorrectly.

**Comment by msridhar** [comment]
Hrm, tried a few different things but couldn't reproduce.  Closing for now, will re-open if I see this again
