### ISSUE TITLE
@Covariant not implemented for Nullness Checker

### ISSUE THREAD

**Issue by wmdietlGC** [typetools/checker-framework#1382]
The Nullness Checker provides a `@Covariant` annotation.
I would expect the following to compile:

```java
import org.checkerframework.checker.nullness.qual.Covariant;
import org.checkerframework.checker.nullness.qual.Nullable;

@Covariant(0)
class Box<T> {}

class Demo {
    void foo(Box<@Nullable Object> p) {}
    void bar(Box<Object> p) {
        foo(p);
    }
}
```

However, I get:

```
Error: [argument.type.incompatible] incompatible types in argument.
  found : @Initialized @NonNull Box<@Initialized @NonNull Object>
  required: @Initialized @NonNull Box<@Initialized @Nullable Object>
```

I see some code to handle Covariant in `https://github.com/typetools/checker-framework/blob/master/checker/src/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java`, but nothing in the NullnessATF.
https://github.com/typetools/checker-framework/blob/master/checker/src/org/checkerframework/checker/nullness/qual/Covariant.java#L9 mentions to move into the framework, but I had expected it to work for all Nullness Checker annotations.
I can work on fixing this, but wanted a second pair of eyes whether I'm doing something wrong.

https://github.com/typetools/checker-framework/blob/master/checker/src/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java#L187 looks like it wouldn't work with the Covariant annotation being in a stub file, right?

**Comment by wmdietlGC** [comment]
@smillst for second pair of eyes.

**Comment by smillst** [comment]
I agree that `@Covariant` seems to only be implemented for KeyFor.  

> looks like it wouldn't work with the Covariant annotation being in a stub file, right?

Right, it should call `AnnotatedTypeFactory#getDeclAnnotation` instead.

As far as I can tell, moving the code in KeyForAnnotatedTypeFactory to `DefaultTypeHierarchy#isContainedBy` should be enough to allow all type systems to use `@Covariant`.  (Though this is something else the Java 8 type argument inference should account for.  I'll make a note on that issue.)
