### ISSUE TITLE
Error parsing a field with array of primitive types in a stub file

### ISSUE THREAD

**Issue by Bohdankm22** [typetools/checker-framework#1456]
Consider following stub file:
`class Myclass {
    @MyAnnotation int[] field;
}
`

It is being parsed by the stubparser project successfully. However, it leads to the ClassCastException in the framework subproject of the Checker Framework.
`[java] error: SourceChecker.typeProcessingStart: unexpected Throwable (ClassCastException); message: com.github.javaparser.ast.type.PrimitiveType cannot be cast to com.github.javaparser.ast.type.ReferenceType; The Checker Framework crashed.  Please report the crash.  To see the full stack trace invoke the compiler with -AprintErrorStack`

Errored Travis job:
https://travis-ci.org/Bohdankm22/sparta/builds/264818673

I think the problem is somewhere in the StubParser.java in the framework subproject. It tries to cast the object to the ReferenceType.
The exception is probably thrown in https://github.com/typetools/checker-framework/blob/8997a341784732c42444ba5a0123e6c514348c0e/framework/src/org/checkerframework/framework/stub/StubParser.java#L763

Checked the ArrayType.java in the stubparser project and it extends ReferenceType. Hence it should be possible to cast ArrayType to the ReferenceType.

Also, need to mention that the issue happens only for the arrays of primitive types.

A possible reason could that it tries to cast to the ReferenceType underlying in the ArrayType type instead of casting the ArrayType itself.

**Comment by mernst** [comment]
> Checked the ArrayType.java in the stubparser project and it extends ReferenceType. Hence it should be possible to cast ArrayType to the ReferenceType.
> ...
> A possible reason could that it tries to cast to the ReferenceType underlying in the ArrayType type instead of casting the ArrayType itself.

I think this part of your analysis is correct.  the annotation is not on the array, but on the element type.
`@MyAnnotation int[]` [means](https://checkerframework.org/manual/#faq-array-syntax-meaning) "array of @MyAnnotation int".
`@Positive int @NonEmpty []` [means](https://checkerframework.org/manual/#faq-array-syntax-meaning) "non-empty array of positive integers".
