### ISSUE TITLE
Checker Framework gradle setup

### ISSUE THREAD

**Issue by zhenqi** [typetools/checker-framework#1459]
Hi,

I face an issue when add checkerframework in gradle build, I follow the instructions: https://checkerframework.org/manual/#gradle, do all the steps to add these config settings into build.gradle(add all the items from instructions in certain part), and then do a build, here is the error log:

18:40:40 Download http://<company-url>:9999/proximity/repository/public/org/checkerframework/checker/2.1.14/checker-2.1.14.pom
18:40:41 Download http://<company-url>:9999/proximity/repository/public/org/springframework/boot/spring-boot-starter-parent/1.5.4.RELEASE/spring-boot-starter-parent-1.5.4.RELEASE.pom
18:40:44 Download http://<company-url>:9999/proximity/repository/public/org/checkerframework/checker/2.1.14/checker-2.1.14.jar
18:40:44 Download http://<company-url>:9999/proximity/repository/public/org/checkerframework/jdk8/2.1.14/jdk8-2.1.14.pom
18:40:45 Download http://<company-url>:9999/proximity/repository/public/org/checkerframework/jdk8/2.1.14/jdk8-2.1.14.jar
18:40:45 
18:40:45 FAILURE: Build failed with an exception.
18:40:45 
18:40:45 * Where:
18:40:45 Build file '/var/builds/workspace/111592-v3-PR-824/BUILD_CONTAINER/oracle-jdk8-current/label/DOCKER-LOW/app_root/build.gradle' line: 185
18:40:45 
18:40:45 * What went wrong:
18:40:45 A problem occurred evaluating root project '<project-namw>'.
18:40:45 > Cannot change strategy of configuration ':checkerFramework' after it has been resolved.
18:40:45 

I am not sure where this error comes from, does someone have ideas?

Thanks,

Ace

**Comment by wmdietl** [comment]
@zhenqi points out in #1474  a discussion on the gradle issue tracker: https://github.com/gradle/gradle/issues/2747
We should see what the gradle recommendations are and adapt our setup.

Also, with our recent switch to Java 8, there no longer is a reason to put javac on the bootclasspath.
@CharlesZ-Chen is going through all instructions and removes those bootclasspath setups.
So hopefully this issue will have a nice solution with the next release. Sorry for not updating this issue.

**Comment by zhenqi** [comment]
OK, thanks, so is that means the checker cannot be attached into gradle build and work well until the next release?

**Comment by wmdietl** [comment]
There are definitely people that use the current configuration with gradle successfully.
Do you have a minimal example to reproduce your issue?
Did you try depending on an older version to see whether it recently broke?

**Comment by zhenqi** [comment]
I tried to use checker version 2.0.0 and some others before latest version, the gradle version we use is 4.1(the latest one), and it returns me the same error. And our project is an enterprise project, I am not sure how to make a minimal example to reproduce my issue based on our project... so I guess the people that use the current configuration with gradle successfully might be also using an older version of gradle?

**Comment by mernst** [comment]
We have made many improvements since you reported this issue.  Could you please try again with the latest Checker Framework (either build it from source or use the 2.2.0 release).
If it still fails, could you please provide a complete, reproducible, minimal example?  We would like to help you, but we need that example in order to do so.
Thanks!

**Comment by zhenqi** [comment]
OK, I will do it, thanks for the updating.

**Comment by zhenqi** [comment]
Hi @mernst , I tried the newest version but the problem still exist, here is the min example that can also reproduce the problem: https://github.com/zhenqi/service-api-proxy, please help me review and try the gradle build, you can simply download and run gradle build locally, then you will see the problem I mentioned before:

**Comment by zhenqi** [comment]
It is the same error: 
A problem occurred evaluating root project ''.
Cannot change strategy of configuration ':checkerFramework' after it has been resolved.

**Comment by tmtron** [comment]
As noted in [gradle  #2747](https://github.com/gradle/gradle/issues/2747#issuecomment-323394339) , you must not resolves dependencies eagerly at configuration time, but instead do it later in the gradle execution phase. To make this work, you must use `doFirst()` like so:

```groovy
allprojects {
    tasks.withType(JavaCompile).all { compile ->
        compile.doFirst {
            compile.options.compilerArgs = [
```
BTW: why you use `options.fork`? I don't see a reason to do this.

**Comment by wmdietl** [comment]
@zhenqi can you try @tmtron 's suggestion? If it works we can update the instructions.

Regarding `options.fork`: we need that when `-Xbootclasspath` is provided, which is necessary to get annotations-in-comments for Java 7 support.
Is there a performance hit in using that option? We should probably rewrite that section and provide separate instructions for use with and without annotations-in-comments.

**Comment by zhenqi** [comment]
Thanks @tmtron I tried your suggestion and it works finally! @wmdietl It can work with @tmtron's suggestion.

**Comment by tmtron** [comment]
@wmdietl 

> Regarding options.fork: we need that when -Xbootclasspath is provided, which is necessary to get annotations-in-comments for Java 7 support.

I thought, that the `-Xbootclasspath` option is only useful when we also use the special javac compiler of the checker-framework: see your [comment in issue 1510](https://github.com/typetools/checker-framework/issues/1510#issuecomment-328598210)

So I think, that setting [fork](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.CompileOptions.html#org.gradle.api.tasks.compile.CompileOptions:fork) to `true`, without also setting the [executable property](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/compile/ForkOptions.html#getExecutable()) of the [forkOptions](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.CompileOptions.html#org.gradle.api.tasks.compile.CompileOptions:forkOptions) to the checker-framework java compiler is useless, right?

>Is there a performance hit in using that option? 

I don't think performance is an issue, but forking can often be tricky with different build tools, so I'd like to avoid it whenever possible.  
I am also quite a beginner with gradle, so I wonder if using fork in this case make sense for some reason, that I am not aware of.

>We should probably rewrite that section and provide separate instructions for use with and without annotations-in-comments.

I agree.

**Comment by smillst** [comment]
@tmtron  Thanks for your suggestions.  I made the changes in #1548.
