### ISSUE TITLE
Remove stubparser-core.jar and instead add dependency to the stubpaser project

### ISSUE THREAD

**Issue by Bohdankm22** [typetools/checker-framework#1466]
As suggested by @wmdietl https://github.com/typetools/checker-framework/commit/d216f67e1520df198b45e56d419b3f911374faf3#commitcomment-23775365 it is possible to transfer the dependency from the jar file to the stubparser project the same way as it works for annotation-tools and jsr308-langtools dependencies.

**Comment by wmdietl** [comment]
PR: #1476

**Comment by smillst** [comment]
Fixed via https://github.com/typetools/checker-framework/commit/f4444eee9f23d91dbfe7fb06be677b08fff5e3c6.
