### ISSUE TITLE
ThreadContext::get is @NonNull?

### ISSUE THREAD

**Issue by entonio** [typetools/checker-framework#1473]
I've had this code produce a known.nonnull with 2.1.14:

```java
import org.apache.logging.log4j.ThreadContext;

String s = ThreadContext.get("KEY");
if (s != null) ...
```

`ThreadContext::get` says the following:

```
@return The value associated with the key or null.
```

Is this normal?

**Comment by wmdietl** [comment]
We currently don't provide annotations for log4j's ThreadContext class and defaults are used.
These defaults are currently optimistic and assume non-null as return and parameter types.
Please see https://checkerframework.org/manual/#defaults-classfile for a discussion how to change this default.
