### ISSUE TITLE
memory leak from AnnotationUtils.annotationMirrorNames cache when using Checker in daemon build process

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#1482]
`AnnotationUtils` uses static fields for various caches, which is undesirable for a number of reasons (see #1108).  Though the state is global, caches like `annotationMirrorNames` have a bounded size of 500, so one might think that memory leaks have been prevented.  Unfortunately, this is not the case.  When running a daemon build process that re-uses the same JVM across multiple invocations of javac, `AnnotationUtils` can end up caching entries from javac invocations that have already completed.  These cache entries are useless, and worse, the `AnnotationMirror` type used as a key for `annotationMirrorNames` can transitively keep alive a huge amount of state.  We have observed this behavior leading to OOM errors in our builds.

The right solution is to get rid of the static state, but that is potentially a huge refactor (though, IMO, a worthwhile one to tackle moving forward).  As a temporary fix, I am wondering if it would be possible to have a different key type for this cache than `AnnotationMirror`, so even if there are stale entries from old javac invocations, they don't keep so much state alive?  I could take a crack at this if no one sees any significant roadblocks.  In the meantime, the only workaround I can see is to call `AnnotationUtils.clear()` periodically.  This will reduce the effectiveness of the cache, though, as we have multiple concurrent instances of javac running in the same JVM.

**Comment by msridhar** [comment]
I should also note that I single out `annotationMirrorNames` since that is the cache I have observed to leak in memory profiles, but the other static caches may have similar issues.

**Comment by wmdietl** [comment]
Thanks for raising this issue!
I see that in the case where the Checker Framework creates the AnnotationMirrors, we are capturing the entire enclosing AnnotationBuilder, which is bad.
In https://github.com/typetools/checker-framework/pull/1494 I'm changing the anonymous inner class into a static inner class, which should avoid this capturing.
Could you see whether this fixes this memory leak?
If this doesn't fix the issue, can you tell us what state the AnnotationMirrors still capture?

**Comment by msridhar** [comment]
Thanks! I will try to take a look at this soon, but its may be a few days.

**Comment by wmdietl** [comment]
@msridhar We refactored that code a bit. Please let us know if this solved the memory leak issue or reopen the issue if it didn't. Thanks.

**Comment by msridhar** [comment]
Unfortunately this did not fix the problem.  Here is a heap path we are seeing:

<img width="833" alt="screen shot 2017-09-11 at 9 34 55 pm" src="https://user-images.githubusercontent.com/193105/30308287-2eaa2868-9739-11e7-9edf-eb7e6cf69810.png">

We're looking at an entry in the `annotationMirrorNames` map.  The key is of type `com.sun.tools.javac.code.Attribute$Compound`, which is *not* constructed by the Checker Framework.  Following the pointers, you see that the whole `JavaCompiler` object is reachable from this object, at which point we are in trouble.  E.g., as shown in the image, all the state of all the annotation processors is kept alive.

The issue should be reopened (I seem to be unable to do it).

**Comment by smillst** [comment]
@msridhar Thanks for the additional information!  We removed the static cache completely.  Let us know if this fixes your issue.
