### ISSUE TITLE
Build instructions seem incomplete for latest master (missing com.github.javaparser dependency?)

### ISSUE THREAD

**Issue by lazaroclapp** [typetools/checker-framework#1492]
As far as I can tell, the instructions posted here https://checkerframework.org/manual/#build-source are no longer sufficient to build checker-framework from the latest master. Upon reaching the `ant` command for the checker itself, it complains that `error: package com.github.javaparser does not exist`.

Excerpt (for commit `f4444eee9f23d91dbfe7fb06be677b08fff5e3c6`):

```
BUILD FAILED
/Users/lazaro/github_forks/checker-framework/build.xml:23: The following error occurred while executing this line:
/Users/lazaro/github_forks/checker-framework/checker/build.xml:47: The following error occurred while executing this line:
/Users/lazaro/github_forks/checker-framework/checker/build.xml:68: The following error occurred while executing this line:
/Users/lazaro/github_forks/checker-framework/framework/build.xml:146: Java returned: 4

Total time: 7 seconds
build:
     [java] javac 1.8.0-jsr308-2.1.14
     [java] /Users/lazaro/github_forks/checker-framework/framework/src/org/checkerframework/framework/stub/StubParser.java:7: error: package com.github.javaparser does not exist
     [java] import com.github.javaparser.JavaParser;
     [java]                             ^
     [java] /Users/lazaro/github_forks/checker-framework/framework/src/org/checkerframework/framework/stub/StubParser.java:8: error: package com.github.javaparser does not exist
     [java] import com.github.javaparser.ParseProblemException;
     [java]                             ^
     [java] /Users/lazaro/github_forks/checker-framework/framework/src/org/checkerframework/framework/stub/StubParser.java:9: error: package com.github.javaparser.ast does not exist
     [java] import com.github.javaparser.ast.*;
     [java] ^
     [java] /Users/lazaro/github_forks/checker-framework/framework/src/org/checkerframework/framework/stub/StubParser.java:10: error: package com.github.javaparser.ast.body does not exist
     [java] import com.github.javaparser.ast.body.BodyDeclaration;
     [java]                                      ^
     [java] /Users/lazaro/github_forks/checker-framework/framework/src/org/checkerframework/framework/stub/StubParser.java:11: error: package com.github.javaparser.ast.body does not exist
     ...
```

Manually adding the path to the latest release of  com.github.javaparser (3.3.3) to the classpath inside framework/build.xml (line 145, "build" target) simply changes the errors being reported to warnings about improper method overrides. It is possible that that `javaparser` version required is a different one.

I am able to reproduce this on two different machines, both when rebasing my current working branch on top of that commit (Mac OS X, 10.12.6), as well as when performing a clean installation following the instructions above (Linux, Ubuntu, 16.04).

Was this dependency added recently?

**Comment by wmdietl** [comment]
The website and the build instructions there are only updated when the release happens.
Until then, please see the master version at https://github.com/typetools/checker-framework/blob/master/docs/manual/troubleshooting.tex#L747

The stubparser was split out into a separate repository to make updating easier: https://github.com/typetools/stubparser

Please let us know if you run into any issues with the updated instructions.

**Comment by lazaroclapp** [comment]
Acknowledged and confirmed. Apologies for the spam :)
