### ISSUE TITLE
Dataflow graph for code with try-finally failing on JDK 9 javac due to a moved field

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#1504]
We updated NullAway to use Checker Framework 2.2.0 (to pick up #1483), but in later testing ran into uber/NullAway#6, a crash on code with try-finally with this stack trace:

```
Caused by: java.lang.NoSuchFieldError: operator
  	at org.checkerframework.javacutil.trees.FullyTreeCopier.visitBinary(FullyTreeCopier.java:67)
  	at org.checkerframework.javacutil.trees.FullyTreeCopier.visitBinary(FullyTreeCopier.java:40)
  	at com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1993)
  	at com.sun.tools.javac.tree.TreeCopier.copy(TreeCopier.java:61)
  	at org.checkerframework.javacutil.trees.FullyTreeCopier.copy(FullyTreeCopier.java:48)
  	at org.checkerframework.javacutil.trees.FullyTreeCopier.copy(FullyTreeCopier.java:40)
  	at com.sun.tools.javac.tree.TreeCopier.visitParenthesized(TreeCopier.java:333)
  	at com.sun.tools.javac.tree.TreeCopier.visitParenthesized(TreeCopier.java:45)
  	at com.sun.tools.javac.tree.JCTree$JCParens.accept(JCTree.java:1849)
```

I think the issue is that in JDK 8 javac, the `JCBinary` class declares the `operator` field [directly](https://github.com/loverdos/javac-openjdk7/blob/master/src/main/java/openjdk7/com/sun/tools/javac/tree/JCTree.java#L1554), whereas [in JDK 9 javac](https://github.com/google/error-prone-javac/blob/upstream/src/jdk.compiler/share/classes/com/sun/tools/javac/tree/JCTree.java#L1970), the field has moved to [a new `JCOperatorExpression` class](https://github.com/google/error-prone-javac/blob/upstream/src/jdk.compiler/share/classes/com/sun/tools/javac/tree/JCTree.java#L1886).  We need to run on JDK 9 javac since NullAway is an Error Prone plugin check.

Not sure of the best way to fix this, but given that JDK 9 is coming out soon, it'd be great if this code could be written in a way that works on both JDK 8 and JDK 9 javac.

**Comment by wmdietl** [comment]
Thanks for the report. In 9, `JCBinary` inherits from `JCOperatorExpression`, so the public `operator` field should still be directly accessible, shouldn't it?

Supporting both people that want to use the Java 8 compiler and people that already want to use the Java 9 compiler won't be possible in general. I have a branch with Java 9 support, but it has the drawback that it doesn't allow people to use the standard Java 8 compiler.

**Comment by msridhar** [comment]
I think that there are weird rules where if you override an instance field in a subclass, it's actually a different field.  So `JCBinary.operator` and `JCOperatorExpression.operator` are different fields at the bytecode level, and if you have bytecode accessing `JCBinary.operator`, it won't transparently work if that field has been moved to a superclass (even if it is still public).

One possible solution here would be to cut a separate `javacutil` Maven artifact that is compiled against the JDK 9 javac (maybe same version number but with a `-jdk9` suffix).  That would require no source-level changes and should fix this problem.  If you're open to this solution, we can try it out and see if we run into other issues.

**Comment by bitterfox** [comment]
Thank you for reporting.

Maybe packaging `FullyTreeCopier` class file which is compiled in JDK9 into CheckerFramework's jar file using [Multi Release JAR](http://openjdk.java.net/jeps/238) can solve this issue without any side-effect to JDK8 users.

**Comment by msridhar** [comment]
@bitterfox Multi Release JAR looks interesting!  But I don't think it's a medium-term solution for us, still we will need to support the use case of using JDK 9 javac while executing on a JDK 8 JVM for quite a while.

**Comment by wmdietl** [comment]
Ah, it's a source-compatible change, but not a bytecode-compatible change. Sorry for the confusion.
I'll look into the jdk9 branch again and will come back ASAP.

**Comment by msridhar** [comment]
FYI, this bug doesn't seem to occur with CF 2.3.1.  But, I think it's because the `FullyTreeCopier` class isn't running in this release.  Leaving this open as it hasn't actually been fixed.
