### ISSUE TITLE
Crash: Unexpected F2A + Combination 

### ISSUE THREAD

**Issue by smillst** [typetools/checker-framework#1512]
(Submitted by @kelloggm in #979)
I encountered a problem that I believe is related to the type inference algorithm. This example, adapted from real code, throws a very unhelpful error that doesn't even point to the offending code (we found it via delta debugging in a much larger codebase):
```java
public class LambdasAndGenericStaticMethods {
    private static TwoTypeArguments throwsTheError() {
        return lambdaArg -> lambdaArg
                .compose(genericStaticMethod());
    }

    private static <T> TwoTypeArguments<T, T> genericStaticMethod() {
        return null;
    }

    private interface TwoTypeArguments<T, R> {
        OneTypeArgument<R> apply(AbstractClassWithOneTypeArgument<T> arg);
    }

    private interface OneTypeArgument<T> {
        void method(T t);
    }

    private abstract class AbstractClassWithOneTypeArgument<T> implements OneTypeArgument<T> {
        public final <R> AbstractClassWithOneTypeArgument<R> compose(TwoTypeArguments<? super T, ? extends R> composer) {
            return null;
        }
    }
}
```
As far as we can tell, all of these elements need to be present for the crash to occur. The resulting error looks like this:
```
error: Unexpected F2A + Combination:
  subtype=? extends Object
  supertype= null
  constraints=[

  ]; invoke the compiler with -AprintErrorStack to see the stack trace.
error: Unexpected F2A + Combination:
  subtype=? extends @Initialized @NonNull Object
  supertype=null
  constraints=[

  ]; invoke the compiler with -AprintErrorStack to see the stack trace.
```
Note that there is no way, from this error, to trace it back to the offending line. A workaround is to add explicit type arguments throughout the function `throwsTheError`. Then the type inference algorithm is able to proceed normally. I found this while running the nullness checker, but it's not nullness checker exclusive.

**Comment by smillst** [comment]
I can't reproduce this crash.  Can you reproduce it with master?

**Comment by kelloggm** [comment]
No. It looks like the version I was using wasn't 2.2.0 when I saw this. Closing.
