### ISSUE TITLE
Generic type handling and this

### ISSUE THREAD

**Issue by maggu2810** [typetools/checker-framework#1528]
I have created a very small example to reproduce the error.
You can find it here: [repository]

The problem occurs if a method consumes a reference that is using a `@NonNull` generic type itself and `this` (implementing such a reference) is provided as parameter.
I assume the [example] below demonstrate much better what I mean (I added `@NonNull` on ever place regardless if this is the default).

```Java
import org.checkerframework.checker.nullness.qual.NonNull;

public class Test {

    public interface Consumer {

        <@NonNull T> void foo(final Container<@NonNull T> c);
    }

    public static class Container<@NonNull T> {

        private @NonNull
        T t;

        public Container(final @NonNull T t) {
            this.t = t;
        }

        public void set(final @NonNull T t) {
            this.t = t;
        }

        public @NonNull
        T get() {
            return t;
        }

        public void call(final @NonNull Consumer c) {
            c.foo(this);
        }
    }

}
```

Compilation is done by using the following [command]:

```text
#!/bin/sh

CF_VER=2.2.0

javac \
    -version \
    -verbose \
    -AprintErrorStack -AprintAllQualifiers \
    -d out \
    -classpath ../checkerframework/checker-"${CF_VER}".jar \
    src/Test.java \
    -processor org.checkerframework.checker.nullness.NullnessChecker \
    -g \
    -target 1.8 -source 1.8 \
    -encoding UTF-8 \
    -Astubs=stubs -AstubWarnIfNotFound -AstubWarnIfOverwritesBytecode -AstubDebug -AshowSuppressWarningKeys \
    -Xbootclasspath/p:../checkerframework/jdk8-"${CF_VER}".jar
```

This is the error:

```text
src/Test.java:30: error: [[all, rawness, nullness, fbc, initialization]:argument.type.incompatible] incompatible types in argument.
            c.foo(this);
                  ^
  found   : /*DECL*/ @Initialized @NonNull Container<T extends @Initialized @Nullable Object>
  required: @Initialized @NonNull Container<T extends @Initialized @NonNull Object>
[total 1978ms]
1 error
```

How can I ensure that `this` is interpret correcty. Shouldn't the class declaration `Container<@NonNull T>` state that `T` is non-null for every container?

[repository]: https://github.com/maggu2810/checker-framework-demo/tree/master/generic-nonnull-type
[example]: https://github.com/maggu2810/checker-framework-demo/blob/master/generic-nonnull-type/src/Test.java
[command]: https://github.com/maggu2810/checker-framework-demo/blob/master/generic-nonnull-type/compile

**Comment by maggu2810** [comment]
Tested with:
* 2.1.10
* 2.1.14
* 2.2.0

**Comment by maggu2810** [comment]
And please allow me to add a further question as it seems (IMHO) be related to generic type parameter handling (I will create another issue if there is a bug).

If I extend the above `Container` with this method:

```Java
        protected boolean valueEquals(final T val1, final T val2) {
            return val1.equals(val2);
        }
```

so, the class already states that T is `@NonNull` explicit (and isn't it the default already implicit), why do I get an error that `val1` could be `null`?

```text
src/Test.java:34: error: [[all, rawness, nullness, fbc, initialization]:dereference.of.nullable] dereference of possibly-null reference val1
            return val1.equals(val2);
                   ^
```

**Comment by wmdietl** [comment]
There is a difference between type parameter declarations and type parameter uses.
What you want to write is:

```java
public static class Container<T extends @NonNull Object> {
```

which you can simplify to:

```java
public static class Container<T extends Object> {
```

With this your original example and the additional `valueEquals` method compile successfully.

In a declaration `class C<@A T>` the annotation `@A` always applies to the lower bound of the type parameter, for which `@NonNull` already is the default.
What you want to achieve is change the upper bound, which you do with `class C<T extends @B C2>`.
For a type parameter use, as in `@A T f;` there is only one annotation you can provide and it applies to both bounds.

This behavior is described in https://checkerframework.org/manual/#generics . Please do let us know if this explanation can be improved somewhere.

**Comment by smillst** [comment]
>Shouldn't the class declaration `Container<@NonNull T>` state that `T` is non-null for every container?

No, annotating the declaration of a type variable is different than annotating its use. `class Container<@NonNull T>{...}`  says that T can have any value from `@NonNull Void` to `@Nullable Object`.  To restrict the values of `T` to only `@NonNull` types, you have to annotate the upper bound of `T`:

```
public static class Container<T extends @NonNull Object> { ...}
```
If you make that change to your example, it type checks.  This also solves the second error in `valueEquals`

See the full explanation of annotating generics in [the manual](https://checkerframework.org/manual/#generics-instantiation).   The reason why upper bounds are not defaulted to `@NonNull` is also explained in [the manual](https://checkerframework.org/manual/#climb-to-top).  Please let us know if we can clarify these sections or otherwise make improvements.

**Comment by maggu2810** [comment]
Thank you very much and sorry that I didn't notice this topic in the manual myself.
I will read it and if I think that something could be improved I will report.
