### ISSUE TITLE
Wrong information about @IgnoreInWholeProgramInference in the manual?

### ISSUE THREAD

**Issue by negora** [typetools/checker-framework#1535]
Hello:

In the [manual](https://checkerframework.org/manual/) there this piece of information:

> As noted below, whole-program inference requires invocations of your code, or assignments to your methods, to generalize from. If a field is set via reflection (such as via injection), then whole-program inference would produce an inaccurate result. There are two ways to make whole-program inference ignore such a field. (1) You probably have an annotation such as @Inject or @Option that indicates such fields. Meta-annotate the declaration of the Inject or Option annotation with @IgnoreInWholeProgramInference. (2) **Annotate the field to be ignored with @IgnoreInWholeProgramInference.**

I've checked the declaration of the `@IgnoreInWholeProgramInference` annotation, and it seems to be applicable only to other annotations, not fields, just as the point 1 says:

```java
@Documented
@Retention (value = RetentionPolicy.RUNTIME)
@Target (value = {ElementType.ANNOTATION_TYPE})
public @interface IgnoreInWholeProgramInference {
}
```

I've tried to put the annotation just above a field declaration and, obviously, the compiler has thrown an error. Is it a mistake in the manual or am I understanding it wrongly?

Thank you.

**Comment by smillst** [comment]
Thanks for reporting this.  It looks like the second option wasn't implemented.  We'll fix that.  (In the mean time, you could create your own annotation meta-annotated with `@IgnoreInWholeProgramInference` that can be applied to fields.)

**Comment by negora** [comment]
Thank you! 👍
