### ISSUE TITLE
Javadoc link broken

### ISSUE THREAD

**Issue by Pr0methean** [typetools/checker-framework#1553]
When I run `mvn javadoc:javadoc` against https://github.com/Pr0methean/BetterRandom/blob/56f418984b4d03e2fdceb768760dbbd3002c5d22/betterrandom/pom.xml, I get the following warning 3 times:

[WARNING] Error fetching link: https://checkerframework.org/apidocs/package-list. Ignored it.

The correct link is https://checkerframework.org/api/package-list

**Comment by smillst** [comment]
This error isn't related to the Checker Framework.  It's because you are using [detectLinks](https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#detectLinks):
>The detection is based on the default Maven conventions, i.e.: ${project.url}/apidocs.
