### ISSUE TITLE
Move javadoc annotations into a dedicated annotated tools.jar

### ISSUE THREAD

**Issue by kelloggm** [typetools/checker-framework#1602]
When we construct an annotated JDK (e.g. by running `ant jdk.jar`), the resulting jar file does not contain class files for every class with an annotation in the JDK source. This appears to only affect JDKs that are built from source (index, nullness, lock). In particular, the generated jar is missing classes under the `com/sun/javadoc` directory, which the nullness JDK contains annotated source for, and I'd like to include in the index JDK. At least some of these classes do have annotations: consider `com/sun/javadoc/RootDoc.java`.

Steps to reproduce:
1. Build or download an annotated JDK.
2. unzip it: `unzip jdk8.jar`
3. Observe that no `com` directory is generated
4. Compare to the structure of the nullness JDK, in `checker/jdk/nullness/src`, which contains a `com` directory, with some annotated classes

**Comment by kelloggm** [comment]
I looked into this. As far as I can tell, `com.sun.javadoc` is a JDK internal API. Since the annotated JDK uses `ct.sym` (the external API for the JDK) to decide which classes to include in the generated jar, these classes are skipped as they aren't supposed to be externally visible.

I think the correct solution is to remove these classes from the annotated JDK. For projects that need them (plume-lib), they should be distributed as a separate annotated library.

**Comment by wmdietl** [comment]
I agree with your conclusion. Javadoc is not in ct.sym, so those source annotations are ignored.
One would have to build an annotated version of `tools.jar` from the JDK to annotate javadoc.
We had previously run into the same issue when an annotated version of guava was in the annotated JDK directory, but didn't result in any useful output.
It would be nice if the annotated build process warned about such source files (but is lenient e.g. with source annotations that might come from a future Java version).

**Comment by mernst** [comment]
An easier step that distributing a separate annotated library would be to include the annotations in stub files in the Checker Framework distribution.

**Comment by kelloggm** [comment]
I agree with Mike. Transferring those annotations to stub files won't take long - I've already done it for the Index Checker, and I'm happy to do it for the Nullness Checker as well.

**Comment by mernst** [comment]
@kelloggm Thanks for doing this for the stub file (is this in master yet, or is there a pull request)?  Doing this for the Nullness Checker too would be great.

**Comment by kelloggm** [comment]
Not yet. I'll move the nullness annotations, too, and then create a PR.

**Comment by kelloggm** [comment]
#1613 fixes this.
