### ISSUE TITLE
possible issue with missing default annotations on supertypes

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#1605]
Unfortunately, I don't have a small test case to reproduce this issue, and I'm not even sure I can explain it properly.  We are seeing weird crashes like those seen in #1415 (MultiGraphQualifierHierarchy found an unqualified type), and it seems to be due to missing default annotations on supertypes.  I see some possibly-suspicious code in [this method](https://github.com/typetools/checker-framework/blob/master/framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java?utf8=%E2%9C%93#L935) of `AnnotatedTypeFactory`.  That code gets an `AnnotatedTypeMirror` for an `Element` and then calls `addComputedTypeAnnotations` which adds default annotations for some type systems (like for the GUI effect checker).  But if the type has supertypes, it seems that it is possible the computed type annotations are not added for the supertypes here?  With the GUI effect checker we are seeing, e.g., `class B extends A` where the type for `B` is `@AlwaysSafe B` but the supertype is just `A`, rather than `@AlwaysSafe A`.

Sorry for the somewhat vague report and lack of a proper test input.  I'm hoping the above code pointers will be enough for someone to see if something is problematic here.  I can try to produce a reduced input for our problem, but it may take a while.

**Comment by msridhar** [comment]
We could try adding some well-formedness assertions somewhere, but I'm not exactly sure how they should look.  I think that if a type system like the GUI effect checker has some kind of default annotation, and we see that default annotation on a type, then it's weird if there is no explicit annotation on the supertypes.  Is that a good intuition or is it way off?

**Comment by csgordon** [comment]
That's my intuition, though I haven't stared at that part for a while.  Is this happening with a particular one of the checkers in the framework, or with one of your own?

**Comment by msridhar** [comment]
It's happening with the GUI effect checker I'm pretty sure (@lazaroclapp
can confirm)

**Comment by smillst** [comment]
> if the type has supertypes
Are you talking about calling `directSuperTypes()` on an `AnnotatedDeclaredType` and the returned `AnnotatedTypeMirror` is missing annotations?  

If so, then those supertypes are annotated by `org.checkerframework.framework.type.SupertypeFinder#directSuperTypes(AnnotatedDeclaredType)`.

**Comment by msridhar** [comment]
Still fuzzy on what is going on the code, but that `SupertypeFinder` method is only called if the unannotated types are not already cached, if I recall correctly.  I'm definitely seeing cases where the types stored in the `supertypes` field are missing annotations.  Couldn't quite track down how that was possible though; the code I linked in my original report was my best guess.  We will try to put together a reduced test case to help debug here.

**Comment by lazaroclapp** [comment]
Hi everyone. Apologies on the delay, but here is a minimized repro case for the issue we are observing: https://github.com/lazaroclapp/cf_issue1605_repro 

If you checkout that repo, then change `buildit.sh` to point to the correct `checker-framework` directory and run it, you should get the following error:

```
error: MultiGraphQualifierHierarchy found an unqualified type.  Please ensure that your implicit rules cover all cases and/or use a @DefaultQualifierInHierarchy annotation.
  Compilation unit: src/com/example/a/A.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:727)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:25)
  org.checkerframework.framework.util.MultiGraphQualifierHierarchy.checkAnnoInGraph(MultiGraphQualifierHierarchy.java:508)
  org.checkerframework.framework.util.MultiGraphQualifierHierarchy.isSubtype(MultiGraphQualifierHierarchy.java:472)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isAnnoSubtype(DefaultTypeHierarchy.java:292)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isPrimarySubtype(DefaultTypeHierarchy.java:274)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isPrimarySubtype(DefaultTypeHierarchy.java:258)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:497)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:55)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:308)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:247)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:182)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:160)
  org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:1920)
  org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:1887)
  org.checkerframework.common.basetype.BaseTypeVisitor.checkArguments(BaseTypeVisitor.java:2345)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethodInvocation(BaseTypeVisitor.java:959)
  org.checkerframework.checker.guieffect.GuiEffectVisitor.visitMethodInvocation(GuiEffectVisitor.java:182)
  org.checkerframework.checker.guieffect.GuiEffectVisitor.visitMethodInvocation(GuiEffectVisitor.java:31)
   ...
```

What the example includes is two Java packages, compiled separately, and stub annotations (`models.astub`) for one of them.

The following code inside package `com.example.b` is compiled without checking:

```
public interface C {
  public void baz();
}
```

```
public class B implements C {
  @Override
  public void baz() {
  }
}
```

This is built into a jar (`b.jar`) and given the stubs:

```
package com.example.b;

@UIType
class B implements C { }
```

Finally, we compile the following code, using the `GuiEffectChecker`, including `b.jar` in the classpath, and passing the stubs above:

```
@UIType
public class A extends B {

  public A() {}

  public static void bar(final C c) {
  }

  protected void foo() {
    bar(this);
  }
}
```

The error goes away if `final C` in the type of the formal argument to `bar` is replaced by either `A` or `B`, or if the stubs are removed. Adding a stub for `@UIType interface C { }` does not help.

**Comment by msridhar** [comment]
If anyone has time to take a look at this one soon we'd really appreciate it.  We have a tool rollout that we can't resume until we find a fix or workaround here.

**Comment by mernst** [comment]
I can reproduce the problem.  It occurs with the GUI Effect Checker but not with the Nullness Checker.

@csgordon , Are you the right person to look into this?  That is, is it a problem with the GUI Effect Checker, or is it revealing a problem with the underlying Checker Framework?

**Comment by smillst** [comment]
I've looked into this crash a bit.  It only occurs in the GUI Effect Checker because its AnnotatedTypeFactory calls `AnnotatedDeclaredType#directSuperTypes` when other checkers do not.  (Though those calls are should not cause problems.)  

Using the `-AatfDoNotCache` options prevents the crash.  (Using this options causes checkers to be much slower, so it is not really a work around, though you could try it.)  

So this implies some sort of caching problem.  (I tried turning off the caches just before the Gui Effect Checker's extra calls to `AnnotatedDeclaredType#directSuperTypes`, but the crash still occurred.  There must be some problem with caching the directSuperTypes.

Also, given that to reproduce this bug, the source of `B` must not be on the source path, there might be a differences between `SupertypeFinder.SupertypeFindingVisitor#supertypesFromTree` and `SupertypeFinder.SupertypeFindingVisitor#supertypesFromElement` that is causing the bug.

I'll keep working on this.

**Comment by msridhar** [comment]
Thanks so much for looking @smillst!  Unfortunately a workaround that makes checkers much slower will not work for us, but thanks for that tip.

**Comment by lazaroclapp** [comment]
Thanks for taking a look @smillst . I can confirm that using the `-AatfDoNotCache` option solves the original crash in our codebase, but it seems to be causing false positives in other targets (not clear yet if this is a bug that only happens with that flag, or if this issue was masking another issue). At any rate, the performance hit is likely going to prevent us from using that workaround either way. Just wanted to confirm this does seem to be our issue, though! :)

**Comment by lazaroclapp** [comment]
Thanks so much for the fix!

We just wanted to report that we have tested it and it works to fix our original problem. Over a fairly large codebase, this gave us a 2-3% performance regression at most (which is within the noise of our measurements). cc: @msridhar

**Comment by smillst** [comment]
@lazaroclapp Great!  Thanks for the performance regression information!
