### ISSUE TITLE
Replace the flow expression parser with a real parser

### ISSUE THREAD

**Issue by smillst** [typetools/checker-framework#1614]
The current implementation attempts to parse Java expressions by applying a set of regular expressions.  The regex approach could perhaps be made to work on our test cases, but cannot be made to work in general.  Use of regexes was perhaps defensible when flow expressions were only allowed to be field accesses, but not beyond that.

Furthermore, those regular expressions are buggy (every time I fix one problem, I find another), such an approach is inefficient, and the implementation is ill-documented.

The current flow expression parser needs to be replaced by a real parser, such as [JavaParser](https://javaparser.org/), which is already used by the Checker Framework.  To parse an expression, wrap it in a dummy class and extract it.  (There is code to do that somewhere; I'm not sure if it is in the Checker Framework.)

A complication is that [the flow expression syntax](https://checkerframework.org/manual/#java-expressions-as-arguments) permits non-standard Java expressions such as `"#1"`.  (`"<self>"` is pre-processed and wouldn't need to be handled.)  Maybe pre-process to replace occurrences of `#n` by the correct identifier (which is already known:  it is passed to the flow expression parser already, maybe in the context).

(The above was written by @mernst in #1609, but was moved to here as it is a separate issue.)

**Comment by KankshaZ** [comment]
Hi, I have attempted to tackle the above problem of replacing the Flow Expression Parser with calls to the JavaParser (it is a very crude and limited implementation - just wanted to make sure that my approach is correct). Please follow this link: [https://github.com/KankshaZ/ReplaceFlowExpressionParser]( https://github.com/KankshaZ/ReplaceFlowExpressionParser)
