### ISSUE TITLE
com.google.common.base.Strings#isNullOrEmpty should clear @Nullable if not met

### ISSUE THREAD

**Issue by justmin** [typetools/checker-framework#1641]
This fragment of code should not have any nullness issues but it has.
```
if(!Strings.isNullOrEmpty(str)){
  return str.length();
}
```
After checking condition !Strings.isNullOrEmpty(str) str could not be null, but CF produces error at `str.length()`

**Comment by wmdietl** [comment]
The annotated guava at:
https://github.com/typetools/guava/blob/master/guava/src/com/google/common/base/Strings.java#L66
does currently not provide a post-condition specification for that method.
Adding `@EnsuresNonNullIf(result = false, expression = "#1")` should fix this issue.
We would appreciate pull requests that help all of us to more completely specify guava.

Are you using the annotated guava jar provided with the Checker Framework?
It would be helpful if you would send a self-contained example with the command line invocation that is causing you issues.

**Comment by justmin** [comment]
Hello,
We are not using annotated guava in prod. But we use -Xbootclasspath/p:<home>\.m2\repository\org\checkerframework\jdk8\2.2.1\jdk8-2.2.1.jar as javac arg. I suppose it includes annotated guava.

**Comment by mernst** [comment]
The `jdk.jar` file contains the JDK.  It does not contain other libraries such as Guava.

**Comment by wmdietl** [comment]
Judging from the path in @justmin 's comment, it looks like he's using Maven.
I just looked through our Maven artefacts and it looks like we are not re-distributing the libraries in `checker/lib` with any of the Maven artefacts.
@smillst am I missing where these jars are? If not, I would suggest we open another issue to improve that about the Maven artefacts and use this issue to improve the Guava specifications.
