### ISSUE TITLE
@org.springframework.lang.Nullable is not understood by Nullness Checker

### ISSUE THREAD

**Issue by astiob** [typetools/checker-framework#1664]
Spring Framework 5 has introduced nullness annotations; see [SPR-15540](https://jira.spring.io/browse/SPR-15540).

They are based on JSR-305 meta-annotations, which Checker Framework does not support (I’ve opened a separate issue for that: #1665), so Checker Framework cannot interpret them fully correctly. However, in practice Spring libraries are annotated with [`@NonNullApi`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/lang/NonNullApi.html), which matches Checker Framework’s default, and [`@NonNullFields`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/lang/NonNullFields.html) should hopefully not be critical for users of Spring as most or all public APIs use accessor methods rather than fields.

The only annotation that remains, and the most important of them all, is [`@org.springframework.lang.Nullable`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/lang/Nullable.html). Checker Framework should treat it as an alias for its own `@Nullable`, but currently it ignores it.

By the way, is there any way to add this alias manually as a temporary measure until Checker Framework supports it out of the box? I have been unable to find one, but it’s very hard to search for this, especially because there’s an Aliasing Checker that’s a completely different thing. I even considered writing an aspect and weaving it into Nullness Checker via AspectJ, but I couldn’t find any information on the Web on the possibility of weaving aspects into annotation processors that are run during compilation. :-(

**Comment by mernst** [comment]
Thanks for letting us know about the Spring annotations.
I have added support for them to the Nullness Checker.
You can look at commit ea4826d to see how to add a new aliased type annotation.

**Comment by astiob** [comment]
Thanks!

> You can look at commit ea4826d to see how to add a new aliased type annotation.

Am I right in assuming that there is no way to add a new aliased type annotation without rebuilding Checker Framework?

**Comment by mernst** [comment]
Yes, you are correct.

It would be possible to implement such a feature, but that hasn't been a priority.  After all, it isn't so often that a new framework comes along that has defined its own `@NonNull` annotation.  But, if that happens frequently, we would accept a pull request that enabled users to add their own aliased type annotations.
