### ISSUE TITLE
JSR-305 meta-annotations should be supported

### ISSUE THREAD

**Issue by astiob** [typetools/checker-framework#1665]
Checker Framework currently has no knowledge of JSR-305/FindBugs [meta-annotations](http://static.javadoc.io/com.google.code.findbugs/jsr305/3.0.2/javax/annotation/meta/package-summary.html). They can be used
* to declare entirely new type qualifiers (possibly of interest to Checker Framework, but I’m not sure as I don’t know exactly how this is supposed to work),
* to declare new annotations that are aliases to previously existing qualifiers or sets thereof (this should be supported, e. g. Spring Framework 5 uses this to define its own `@Nullable`, see #1664)
* and to declare new annotations that behave like scoping constructs and override the default qualifier for all code within their scope (this should also be supported, but I imagine that this might be harder—I’m just guessing though; this is also used by Spring Framework 5 and by Reactor).

For reference, these are used by Spring Framework and Reactor and understood (for nullability qualifiers) by the Kotlin compiler (to the best of my knowledge). Perhaps less importantly, it appears that `jsr305` itself also uses these to implement many of its annotations (which doesn’t really matter as long as Checker Framework understands them) and provide a few scoping annotations that Nullness Checker doesn’t understand at the moment (but I have no idea if anyone uses them).

**Comment by mernst** [comment]
JSR 305 was abandoned in 2009.
I don't see a significant benefit to supporting niche annotations that would be used rarely (if in fact they are ever used).  The Checker Framework has other mechanisms for declaring type qualifiers, adding aliases for type qualifiers, and declaring defaults, and those seem to work well enough.

If you really need support the abandoned JSR 305 meta-annotations, feel free to open a pull request.  But, I'm closing this issue for now.

**Comment by astiob** [comment]
Fair enough. Just one thing I’d like to point out:

> that would be used rarely (if in fact they are ever used)

I did provide real-world examples. Spring is hardly a niche product. But hopefully they’ll stick to defaulting to nonnull and anyone else who might use their annotations will do likewise.

**Comment by mernst** [comment]
I found no uses of

```java
TypeQualifierValidator
@Exclusive
@Exhaustive
@TypeQualifier
```

in https://github.com/spring-projects/spring-framework and only two uses each of

```java
@TypeQualifierNickname
@TypeQualifierDefault
```

So I don't see any essential uses of the annotations, but I accept your point that some of them do at least appear.

**Comment by astiob** [comment]
You’re right. `@TypeQualifier` and the others may well be irrelevant to Checker Framework and/or unused in the wild. It sounds like they’re analogous to Checker Framework’s qualifier hierarchies, but I’m just guessing. At any rate, not making Checker Framework support whole custom qualifier hierarchies made for other tools sounds reasonable.

`@TypeQualifierDefault` and `@TypeQualifierNickname` are relevant to a hierarchy (nullness) that Checker Framework already supports though, so it seems to me that without support for them, Checker Framework can incorrectly interpret nullness qualifiers in external libraries that use the JSR-305/FindBugs annotations. Unfortunately, even though JSR-305 was abandoned many years ago as you say, and even though these annotations infringe on the reserved `javax` namespace, they still seem popular as a common denominator that is “supported by everything”.

I will maybe try my hand at implementing this if I feel bored sometime. There is certainly no rush to get this done, as the only example I know (Spring) should hopefully work as is due to the matching defaults. Then again, I haven’t looked for other examples.
