### ISSUE TITLE
Unrelated type error when method type arguments are missing

### ISSUE THREAD

**Issue by lazaroclapp** [typetools/checker-framework#1705]
Consider the following stub models:

```
class Single<T> implements SingleSource<T> {
  @PolyTainted Single<T> observeOn(Single<T> this, @PolyTainted Scheduler arg0);
  <R> @PolyTainted R to(@PolyTainted Single<T> this, Function<? super Single<T>,R> arg0);
}

class Maybe<T> implements MaybeSource<T> {
  @PolyTainted Maybe<T> doOnComplete(@PolyTainted Maybe<T> this, Action arg0);
  void subscribe(MaybeObserver<? super @Untainted T> arg0);
}
...
class Schedulers {
    static @Untainted Scheduler single();
}
```

Here the instantiation of `@PolyTainted` in the return to method `to(...)` should depend only on the type of the receiver, and not the type of `arg0`. Similarly for `doOnComplete`.

However, if we have the following code:

```
  protected void errorExample() {
    requireUntainted(getSingleTuple()
        .observeOn(Schedulers.single())
        .to(Example.singleTupleToTwoParamMaybe())
        .doOnComplete(
            new Action() {
              @Override
              public void run() throws Exception {
              }
            }));
  }

  private void requireUntainted(/*@Untainted*/ Maybe var) { }
```

Where `singleTupleToTwoParamMaybe()` is a method taking type arguments, with the following signature:

```
public static <T, U>
  Function<Single<Tuple<T, U>>, TwoParamTupleMaybe<T, U>> singleTupleToTwoParamMaybe()
```

This produces an error like:

```
Example.java:75: error: [argument.type.incompatible] incompatible types in argument.
        .doOnComplete(
                     ^
  found   : @Tainted Maybe<@Tainted Tuple<@Tainted Object, @Tainted Object>>
  required: @Untainted Maybe<? extends @Tainted Object>
1 error
```

However, if we explicitly give the type arguments for singleTupleToTwoParamMaybe, this produces no error:

```
protected void noErrorExample() {
    requireUntainted(getSingleTuple()
        .observeOn(Schedulers.single())
        .to(Example.<Object,Object>singleTupleToTwoParamMaybe())
        .doOnComplete(
            new Action() {
              @Override
              public void run() throws Exception {
              }
            }));
  }
```

The full code for this repro example is available at https://github.com/lazaroclapp/cf_223_type_args_issue_repro . 

It is as simplified as we could get it, and thus very artificial, but it is based on an error we are seeing frequently with our own custom checker. We used `TaintingChecker` since it is a simple checker that shows the issue, but note this also means that the Rx annotations in the stubs don't necessarily make sense for a real program. Any help understanding what is going on here, and/or a fix that makes the code without `<Object,Object>` behave like the one with, would be greatly appreciated.

cc: @msridhar

**Comment by msridhar** [comment]
@smillst would there be a quick fix for this one short of fixing #979?  Or is there a workaround?  This problem is a tough one for us, since asking devs to add the explicit type parameters contradicts the advice that IntelliJ is giving them (it warns that the parameters are unnecessary).

**Comment by smillst** [comment]
#1706 fixes this particular false positive.

**Comment by lazaroclapp** [comment]
We backported the patch from PR #1706 and it is working for us. Thank you very much @smillst !
