### ISSUE TITLE
ArrayDeque.offer(T) cannot accept null

### ISSUE THREAD

**Issue by chengniansun** [typetools/checker-framework#1714]
I find that ArrayDeque.offer(T) is modeled to be able to take a nullable argument. However, according to its javadoc, it will throw an NPE is the parameter is null.

(https://github.com/typetools/checker-framework/blob/master/checker/jdk/nullness/src/java/util/ArrayDeque.java#L26)

public boolean offer(E e)
Inserts the specified element at the end of this deque.
This method is equivalent to offerLast(E).

Specified by:
offer in interface Deque<E>
Specified by:
offer in interface Queue<E>
Parameters:
e - the element to add
Returns:
true (as specified by Queue.offer(E))
Throws:
NullPointerException - if the specified element is null

**Comment by wmdietl** [comment]
Looking at https://docs.oracle.com/javase/8/docs/api/index.html?java/util/ArrayDeque.html it seems like all methods that add an element, e.g. `push` and `addFirst` throw and NPE for a null element.

So should we simply change the class to:

`public class ArrayDeque<E extends @NonNull Object> ...`

to forbid instantiations that claim to allow null?

**Comment by mernst** [comment]
Yes, that is the correct fix.  I will make it.
