### ISSUE TITLE
Progress output

### ISSUE THREAD

**Issue by mernst** [typetools/checker-framework#1754]
This is a feature request for a command-line argument that would cause the Checker Framework to periodically output a progress message (say, indicating what checker is running and how many classes it has processed so far).

The Checker Framework can run for a long time when it is run on a big program.
This can cause a user not to know if it is still making progress or is in an infinite loop.
It can also cause Travis jobs to time out with a message
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

**Comment by smillst** [comment]
As a work around until this feature is implemented, you can use the `filenames` option.  It prints the name of the file of the class before the checker checks it and also the name of the checker.

**Comment by mernst** [comment]
Using `-Afilenames` is a bit verbose, but is an adequate workaround.  I'll close this issue.
