### ISSUE TITLE
I18n-formatter unit tests in wrong location and not executed

### ISSUE THREAD

**Issue by wmdietl** [typetools/checker-framework#1796]
Directory `checker/src/org/checkerframework/checker/i18nformatter/unittests/` contains two unit test classes. Neither test is executed at the moment.

These files should be moved to a appropriate `checker/tests/` directory and integrated with the i18n-formatter tests.

**Comment by mernst** [comment]
The only other JUnit tests currently reside in `framework/tests/src/tests/`.
That suggests that these should go in `framework/tests/src/tests/` (perhaps in a single file to prevent clutter).
