### ISSUE TITLE
can't find basic block for if statement in CFG

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#1801]
Consider code like the following:
```java
try {
  if (cond) {
    s1;
  } else {
    s2;
  }
} catch (...) { ... }
```
After running a dataflow analysis, I'd like to know which facts hold in the store corresponding to the program point immediately after the `if`-`else` statement.  However, in the CFGs, I don't seem to be able to take the `IfTree` and find a corresponding CFG node; there is no `IfTree` in the `ControlFlowGraph.treeLookup` map.  Is there a way to figure this out that I am missing?  Or is there a bug somewhere?  If there were a statement `s3` following the `if` I could hack things by looking at the facts holding before `s3`.  But that doesn't work for the case above.

Relatedly, it'd be very convenient if I could somehow query the dataflow store corresponding to the program point immediately after a `BlockTree`.

**Comment by wmdietl** [comment]
The documentation for `ControlFlowGraph.treeLookup` states: `Maps from AST {@link Tree}s to {@link Node}s. Every Tree that produces a value will have at least one corresponding Node.`
The `IfTree` doesn't produce a value, so it makes sense that it doesn't get mapped in `treeLookup`.
You should be able to go from the condition of the if-tree to a Node in the CFG and then on to `then` and `else` blocks.
(The tree for a ternary expression should be mapped by `treeLookup`, as it produces a value.)

I agree that a convenience method that returns the store after a block could be useful. At the moment one has to find the final node and use `AnalysisResult.getStoreAfter(Node)`.
Do you think you could contribute such an extension?

**Comment by msridhar** [comment]
As an update we're working on the suggested extension; we'll see how it goes 😄 When we have something working we'll post a PR for feedback.

**Comment by msridhar** [comment]
Also, FWIW, if #293 were fixed (with relatively low overall performance cost for CFG construction), we probably wouldn't need this functionality; we're building it as a workaround.

**Comment by wmdietl** [comment]
Now that #293 is nearly fixed (#1826), are you still working on a work-around or the API improvement?

**Comment by msridhar** [comment]
We are not actively working on this issue, as it was motivated by finding a workaround for #293.  I still think this would be useful in general, but we probably won't need it in the short term.

**Comment by wmdietl** [comment]
Ok, let's close this issue for now and see whether we want the enhancement in the future.
