### ISSUE TITLE
stubparser: use a different package to avoid version conflicts

### ISSUE THREAD

**Issue by cushon** [typetools/checker-framework#1819]
Consider using a different package for stubparser (e.g. by using jarjar), to avoid version conflicts with other copies of javaparser that may share a classpath with the checker framework.

**Comment by mernst** [comment]
I agree we should do this.  Thanks for pointing it out.

**Comment by mernst** [comment]
We plan to complete this before the April 1 release.

**Comment by smillst** [comment]
This has been fixed, but only for the released versions of the jars.  Use `./gradlew release` to build locally.

Fixed via 5303dc4609a8184eca64364bbf488a4dd0cc144f
