### ISSUE TITLE
Method T newInstance(Object... initargs) is wrongly annotated for Constructor class.

### ISSUE THREAD

**Issue by ashishrana160796** [typetools/checker-framework#1850]
From javadoc specifications : https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Constructor.html#newInstance-java.lang.Object...-
and the following statement in that specification :
`If the number of formal parameters required by the underlying constructor is 0, the supplied initargs array may be of length 0 or null. `

But the annotated code line is given in `Constructor.java` as :
`
public @NonNull T newInstance(Object ... initargs) throws InstantiationException,IllegalAccessException,IllegalArgumentException,InvocationTargetException { throw new RuntimeException("skeleton method"); }`

This clearly show the wrongly annotated code which will be causing problems in situations like :
`
Constructor ctor = clazz.getDeclaredConstructor((Class[]) null);`

Considering this problem an improvement in annotation is required and a `pr` can be made.

**Comment by wmdietl** [comment]
See previous discussion in issue #1365 and pull request #1388.
These are the correct conservative annotations.

**Comment by ashishrana160796** [comment]
Thanks!
