### ISSUE TITLE
Annotation addition needed for class java.security.BasicPermission  

### ISSUE THREAD

**Issue by ashishrana160796** [typetools/checker-framework#1852]
Considering `BasicPermission` class is extended by classes like AWTPermission and others like it. With this class unannotated, its default type qualifier behavior is not according to specification defined. 
Considering a particular example of `AWTPermission` extends `BasicPermission` :
```
...
     * @param actions should be <code>null</code>
     *
     * @throws NullPointerException if <code>name</code> is <code>null</code>.
     * @throws IllegalArgumentException if <code>name</code> is empty.
     */
    public AWTPermission(String name, @Nullable String actions)
    {
        super(name, actions);
    } 
...
```
This produces error even if the specification says `the name is the symbolic name of the BasicPermission, and the actions String is currently unused`. Hence, annotated constructor `BasicPermission(String name, String actions)` is required. Suggested solution is addition of annotated `BasicPermission.java` and `Permission.java`.

**Comment by mernst** [comment]
I agree this is needed.  I'm going to close this because if we opened an issue for every missing annotation in the JDK, we would have an unbounded number of open issues.
Feel free to submit a pull request.

**Comment by ashishrana160796** [comment]
Thanks for closing it. Will get to it soon.
