### ISSUE TITLE
Report source position for crashes

### ISSUE THREAD

**Issue by cushon** [typetools/checker-framework#1866]
This is a feature request to detect which AST node was being visited when fatal exceptions occur and include a source position when reporting crashes like #1865. This would be helpful when minimizing repros for crashes. Knowing the file that caused the error is a good start, but it still takes some time to bisect to the part of the file. Since a crash can often be reproduced with a single expression or statement, having a source position would cut out some steps.

We do something similar in Error Prone: the main AST visitor handles fatal exceptions when visiting each node: https://github.com/google/error-prone/blob/66c0e96b90a8fb28a2d3febde5bef3b339b9f6cc/check_api/src/main/java/com/google/errorprone/scanner/ErrorProneScanner.java#L1149. There's nothing particularly great about that implementation, but I've found it helpful when triaging bugs.

**Comment by wmdietl** [comment]
Thanks for the suggestion.
#1868 outputs the currently visited tree when a crash occurs.
Please let us know whether this is helpful.
