### ISSUE TITLE
Manual update required for Section 30.7.1 example definitions

### ISSUE THREAD

**Issue by ashishrana160796** [typetools/checker-framework#1876]
Definition of `@NonNull` annotation class stated in this section doesn't match with current one and needs a update in manual.
Earlier manual section pointed:
```
For example, consider the definitions of the @Nullable and `@NonNull` type qualifiers:
...
@SubtypeOf( { Nullable.class } )
...
      literals = { LiteralKind.BOOLEAN, LiteralKind.CHAR, LiteralKind.DOUBLE,
                   LiteralKind.FLOAT, LiteralKind.INT, LiteralKind.LONG,
                   LiteralKind.STRING })
..
```
Updated manual section suggested and also addition of `@MonotonicNonNull` definition : 
```
For example, consider the definitions of the @Nullable and `@NonNull` type qualifiers:
...
@SubtypeOf(MonotonicNonNull.class)
...
literals = {LiteralKind.STRING}
...
```
But if this example is for illustration purpose than close this issue, still I'll suggest not reference `@NonNull` and `@Nullable` from actual link of JavaDoc which is quite misleading.

**Comment by mernst** [comment]
Closed by  7390552
