### ISSUE TITLE
Interaction of stub files and -AuseDefaultsForUncheckedCode

### ISSUE THREAD

**Issue by mernst** [typetools/checker-framework#1881]
According to Nick Wong:

The existence of a Stub file for a class overrides the `-AuseDefaultsForUncheckedCode=bytecode` compiler argument. This means it will go back to default behavior which is also sort of surprising as a user who was expecting all non annotated methods in the stub to continue to behave pessimistically.

**Comment by wmdietl** [comment]
Related to #1873 .

**Comment by mernst** [comment]
I think this was resolved by ffcf120310616ff345f01716b737f876f284ab2e.  Please re-open if a problem or confusion remains.
