### ISSUE TITLE
Index Checker: minor change to @MinLen() required prompt suggestion.

### ISSUE THREAD

**Issue by NhatDinh** [typetools/checker-framework#1898]
Hi,
While using the index checker, I had this warning prompt:
Error: 
 found:....
 required: **@MinLen("2")** -- an array guaranteed to have at least 2 elements
I suggested changing it to @MinLen(2) in the required prompt because in the manual, @MinLen(int) takes an int as argument. I think this would be less confusing for users.
If this is a valid concern, I would like to work on fixing it.
Side note: This is my first issue report, feel free to add suggestions so I can make a better report next time.

**Comment by mernst** [comment]
Per https://checkerframework.org/api/org/checkerframework/common/value/qual/MinLen.html, the argument to `@MinLen` is already an integer.

Is this issue report a request to fix a misleading error message that contains quotation marks?

**Comment by tanejasomi** [comment]
Hi Nhat, 
You can also use following link to create minimal example (as in simple test) of issue for checker you are using. It would get easy to understand and fix. 
http://eisop.uwaterloo.ca/live/#mode=edit

P.S Its just a suggestion, I thought it would be handy so shared, if not please ignore it.
-Somya

**Comment by NhatDinh** [comment]
Hi Somya,
I actually never thought about it, thanks for the suggestion.
I headed over to the link and I did not find the index checker in the drop down menu.

**Comment by mernst** [comment]
That would indeed be more useful, and it is the best choice in general.
In this particular case, I was able to reproduce the problem and I have a fix in testing:  https://github.com/typetools/checker-framework/pull/1899

**Comment by NhatDinh** [comment]
That's great.
