### ISSUE TITLE
Confusing error message.

### ISSUE THREAD

**Issue by tanejasomi** [typetools/checker-framework#1903]
This request is in reference to #1879 , as a user I find following error messages misleading . In general we use "found" for something already part of written code and "required" to be something that should be there instead. Its kind of opposite for checker framework in this case. For example in following simple program:

import org.checkerframework.checker.nullness.qual.*;
import org.checkerframework.checker.initialization.qual.*;
class Test {
    String type;
    Test(){
        this.getType();
        }
        
    @EnsuresNonNull({"type"})    
    void getType(@UnknownInitialization(Test.class) Test this){
        this.type = "abc";
            }
}

I would expect error something like:
found: @UnknownInitialization(Test.class)
required: @UnderInitialization(..) 

Actual error:
Error: [method.invocation.invalid] call to getType() not allowed on the given receiver.
 found   : @UnderInitialization(java.lang.Object.class) @NonNull Test
 required: @UnknownInitialization(Test.class) @NonNull Test

From #1879 I do understand logic behind error. So am not arguing about logical aspect but just plastic change of words in error message "found" and "required". If there is some other logic behind it and am not understanding it, please guide.

**Comment by wmdietl** [comment]
I do not understand your suggestion. The `found` and `required` types are correct and follow the pattern that you describe.

- The error is raised for the line `this.getType();`.
- The message states `[method.invocation.invalid] call to getType() not allowed on the given receiver.`
- The `found` type is given as `@UnderInitialization(java.lang.Object.class) @NonNull Test`. That is the type of `this` in the constructor of `Test`.
- The `required` type is given as `@UnknownInitialization(Test.class) Test`. That is the declared receiver type of method `getType`.
- The invoked method expects a receiver that is initialized up-to Test.class, but is invoked on a receiver that is initialized up-to only Object.class. So this invocation is incorrect.

So found/expected follow the usual logic: the type checker found an unexpected type and the program needs to be changed to provide a (subtype of) the expected type.

What is your concrete suggestion for a change to this error message?

**Comment by tanejasomi** [comment]
Thank you for explaining. I was looking at error from receiver method annotation, therefore was getting confused as in error raised for given piece of code said: "required" @UnknownInitialization(Test.class) Test and yet function getType() already has same annotation. Now I understand we are looking at error from constructor function call "this.getType()".  
Thank you for taking time to clarify.

**Comment by wmdietl** [comment]
No problem. Do let us know if you see a way to improve instructions somewhere. And please do continue to raise any issues you're running into.
