### ISSUE TITLE
Index checker doesn't match types correctly.

### ISSUE THREAD

**Issue by gsaga** [typetools/checker-framework#1911]
Here's the code which demonstrates this error:

    import org.checkerframework.checker.index.qual.*;
    import org.checkerframework.checker.nullness.qual.NonNull;
    import org.checkerframework.common.value.qual.MinLen;
    
    public class t {
        public static void main (String[] args) throws Exception {
        }
    } 
    
    class TestingBug {
        private char @MinLen(1) [] fileContent; 
        private @LengthOf("fileContent") int fileSize;
        private @NonNegative @LTEqLengthOf("fileContent") int index;
    
        public TestingBug(String s) throws Exception {
            if (s.length() < 1) {
                throw new Exception();
            }
            this.fileContent = s.toCharArray();
            this.fileSize = s.length();
            this.index = 0;
        }
    
        public void goToNextChar() {
            index = index + 1;
        }
    
        public char currentChar() throws Exception {
            if (index < fileSize) {
                return fileContent[index];
            }
            throw new Exception();
        }
    }

Compiling it with `javac -processor index t.java` gives the following error:

    t.java:35: error: [assignment.type.incompatible] incompatible types in assignment.
            index = index + 1;
                          ^
      found   : @LTLengthOf(value="this.fileContent", offset="-2") int
      required: @LTEqLengthOf("this.fileContent") int
    1 error

It says that the value it found(index + 1) minus 2, i.e. index -1 is less than length of this.fileContent. Which is equivalent to saying that index is less or than equal to length of this.fileContent. The error goes away if the @LTEqLengthOf annotation is removed.

**Comment by kelloggm** [comment]
This is a true positive from the Index Checker: your code is unsafe. If a user calls `goToNextChar()` more times than the length of `this.fileContent`, then `index` will in fact be too large, violating the contract in the annotation.

The meaning of the error you see is that `index - 2` is less than the length of `this.fileContent`, but the annotation requires that `index - 1` is less than the length of `this.fileContent` (or, equivalently, that `index` is less than or equal to the length).
