### ISSUE TITLE
Index Checker: IntelliJ's warnings flow is different from command line.

### ISSUE THREAD

**Issue by NhatDinh** [typetools/checker-framework#1912]
As raised in [Issue #1901](https://github.com/typetools/checker-framework/issues/1901), because IntelliJ warnings flow is different from command line's flow, this leads to potential code cluster and extra build steps for IntelliJ users.
Consider:
```java
public class SimpleMethod1{
    int[] fields_arr = new int[10];
    void simpleMethod( int i, int[] para_arr) {
        int[] local_arr = new int[10];
        this.fields_arr[i] = i;
        local_arr[i] = i;
    }
    public static void main(String args[]) {
    }
}
```
Warnings issued by IntelliJ: only index lower bound value is checked, 2 warnings are issued.
```java
Error:(9, 25) java: [array.access.unsafe.low] Potentially unsafe array access: the index could be negative.
  found   : @LowerBoundUnknown int
  required: an integer >= 0 (@NonNegative or @Positive)
Error:(10, 19) java: [array.access.unsafe.low] Potentially unsafe array access: the index could be negative.
  found   : @LowerBoundUnknown int
  required: an integer >= 0 (@NonNegative or @Positive)
```
After adding @NonNegative as required and build again, IntelliJ will then issue warnings to check upper bound value whereas command line will issue all warnings at once.
```java
Error:(9, 25) java: [array.access.unsafe.high] Potentially unsafe array access: the index could be larger than the array's bound
  found   : @UpperBoundUnknown int
  required: @IndexFor("this.fields_arr") or @LTLengthOf("this.fields_arr") -- an integer less than this.fields_arr's length
Error:(10, 19) java: [array.access.unsafe.high] Potentially unsafe array access: the index could be larger than the array's bound
  found   : @UpperBoundUnknown int
  required: @IndexFor("local_arr") or @LTLengthOf("local_arr") -- an integer less than local_arr's length
```
This leads to 2 extra steps and unnecessary annotations like: @NonNegative @IndexFor("this.fields_arr") or @NonNegative @LTLengthOf("this.fields.arr") for IntelliJ users.

Proposed solution:
I suggest to adjust IntelliJ warnings flow to be the same as command line.

**Comment by kelloggm** [comment]
This seems like an issue with IntelliJ, and not with the Index Checker (or the Checker Framework at all). As far as I can tell, IntelliJ is running the parts of the Index Checker separately, and stopping once one fails. This behavior seems to be part of IntelliJ, and a few minutes of Googling didn't lead me to any workarounds other than fixing the errors and recompiling.

That said, you can always replace `@NonNegative` with `@IndexFor` if it's necessary (and you really ought to be reading the documentation and writing annotations based on that, not just running the compiler and blindly writing annotations if the documentation doesn't call for them).

Another workaround for IntelliJ's issue is to just run the compiler from the command line.

**Comment by NhatDinh** [comment]
@kelloggm Thank you for the explanation. The more I use Index Checker, the more I realize that running the compiler from the command line is just better than using IntelliJ.
That said, I will try to find a workaround.
