### ISSUE TITLE
Error: annotation processor xx not found

### ISSUE THREAD

**Issue by zzghost** [typetools/checker-framework#1914]
I installed the checker framework on Intellij IDEA community.
And my language level is:
<img width="593" alt="2018-03-26 4 10 48" src="https://user-images.githubusercontent.com/19383978/37894301-62583cb0-3110-11e8-94ab-3f37b665b5ed.png">
I followed the instruction bellow,
<img width="1057" alt="2018-03-26 4 16 23" src="https://user-images.githubusercontent.com/19383978/37894522-13207256-3111-11e8-93c7-86527ccbbc4d.png">
Here is my **compiler.xml**:
<img width="1403" alt="2018-03-26 4 12 15" src="https://user-images.githubusercontent.com/19383978/37894402-bb741fd0-3110-11e8-8e36-8b4f61be569d.png">

Then I type "javac -processor org.checkerframework.checker.nullness.NullnessChecker Main.java
" in the command line.
However, I always got a problem:
_error:annotation processor 'org.checkerframework.checker.nullness.NullnessChecker'
 not found_
I think I have entered the correct path and I don't know what's wrong with it??

**Comment by faushine** [comment]
> I installed the checker framework on Intellij IDEA community.
> And my language level is:
> <img alt="2018-03-26 4 10 48" width="593" src="https://user-images.githubusercontent.com/19383978/37894301-62583cb0-3110-11e8-94ab-3f37b665b5ed.png">
> I followed the instruction bellow,
> <img alt="2018-03-26 4 16 23" width="1057" src="https://user-images.githubusercontent.com/19383978/37894522-13207256-3111-11e8-93c7-86527ccbbc4d.png">
> Here is my **compiler.xml**:
> <img alt="2018-03-26 4 12 15" width="1403" src="https://user-images.githubusercontent.com/19383978/37894402-bb741fd0-3110-11e8-8e36-8b4f61be569d.png">
> 
> Then I type "javac -processor org.checkerframework.checker.nullness.NullnessChecker Main.java
> " in the command line.
> However, I always got a problem:
> _error:annotation processor 'org.checkerframework.checker.nullness.NullnessChecker' not found_
> I think I have entered the correct path and I don't know what's wrong with it??

Have you solved it?
