### ISSUE TITLE
Class Files not found (Android Studio 3.1)

### ISSUE THREAD

**Issue by tmtron** [typetools/checker-framework#1916]
After upgrading to Android Studio 3.1 I get following errors:

```
class file for java.lang.Class$AnnotationData not found
class file for java.lang.Class$ReflectionData not found
```
here is the [full stack trace](https://gist.github.com/tmtron/fb50d06baae9f5970b1877d9d01ea153)

I guess this could be related to the [New DEX compiler, D8](https://developer.android.com/studio/releases/gradle-plugin.html#D8):

> ...note that it now compiles against libraries included in the SDK build tools—not the JDK. So, if you are accessing APIs that exist in the JDK but not in the SDK build tools libraries, you get a compile error.

I can see the issue with checker-framework 2.2.1 and also with the newest version 2.4.0.

Any ideas how to work-around this?

**Comment by tmtron** [comment]
I've created a minimal test project to verify the issue: https://github.com/tmtron/As31CheckerFw

It consists of 3 gradle modules:
- _app_: the Android application (apk)
- _androidlib_: an Android library (aar)
- _javalib_: a "normal" Java module (jar) - no Android dependency

# javalib
First I've tried to activate the checker-framework for the _javalib_ only. I followed chapter [31.4 Gradle](https://checkerframework.org/manual/#gradle) in the docs and found some problems

## GStringImpl vs. String
When the [checkerframework.gradle](https://raw.githubusercontent.com/typetools/checker-framework/master/docs/manual/checkerframework.gradle) file is used as it is now, it fails with this error:
`org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String`

- Git Tag to verify the problem: [GStringImpl_vs_String](https://github.com/tmtron/As31CheckerFw/tree/GStringImpl_vs_String)
- Full build output: [Travis-Ci build #16](https://travis-ci.org/tmtron/As31CheckerFw/builds/358904269#L1454)

To fix the issue 
- I had to use `.toString()` explicitly, like this:  
` '-processorpath', "${configurations.checkerFrameworkCheckerJar.asPath}".toString(),`
- full commit to fix the issue: [8cca4d3](https://github.com/tmtron/As31CheckerFw/commit/8cca4d31d1641328f3f7e7efc6596da54a29886c)
- I suggest that you update [checkerframework.gradle](https://raw.githubusercontent.com/typetools/checker-framework/master/docs/manual/checkerframework.gradle)

## Android Lint Error
The next issue is that the _androidlib_ module compilation will fail with this error:
```
Execution failed for task ':app:lint'.
> Lint found errors in the project; aborting build.
...checker-qual-2.4.0.jar: Error: Invalid package reference in library; 
not included in Android: java.awt.image. 
Referenced from org.checkerframework.checker.signedness.SignednessUtil. 
[InvalidPackage]
```
The problem is that the [checkerframework.gradle](https://raw.githubusercontent.com/typetools/checker-framework/master/docs/manual/checkerframework.gradle) (which is used in the _javalib_ module) uses _compile_ instead of _implementation_ for the `checker-qual` dependency:
```
dependencies {
  ...  
  compile "org.checkerframework:checker-qual:${checkerFrameworkVersion}"
}
```
and thus, `checker-qual` will also be on the compile classpath of the _androidlib_ module, which causes the exception:

- Git Tag to verify the problem: [LintError_InvalidPackage](https://github.com/tmtron/As31CheckerFw/tree/LintError_InvalidPackage)
- Full build output: [Travis-Ci build #18](https://travis-ci.org/tmtron/As31CheckerFw/builds/358907955#L1495)
- I suggest that you update the docs so that _implementation_ is always used instead of _compile_

# androidlib
Now that the java-module works, I have tried to activate the checker-framework for the Android lib module: _androidlib_
I followed the docs in chapter [31.5  Android Studio 3.0 and the Android Gradle Plugin 3.0](https://checkerframework.org/manual/#android-gradle)

One problem with the docs is that a wrong gradle command is specified
`gradlew checkTypes`
This cannot work, because there is no gradle task named `checkTypes`. We have only specified a configuration with that name. An existing task is e.g. `assembleCheckTypes`.  
So in the root directory, we may call:
`./gradlew :androidlib:assembleCheckTypes`

And this fails with the original error, described by this issue:
```
> Task :androidlib:compileCheckTypesJavaWithJavac FAILED
error: InvocationTargetException when invoking constructor for class org.checkerframework.checker.nullness.KeyForAnnotatedTypeFactory; 
Underlying cause: com.sun.tools.javac.code.Symbol$CompletionFailure:
class file for java.lang.Class$AnnotationData not found;
```
- Git Tag to verify the problem: [Class_AnnotationData_not_found](https://github.com/tmtron/As31CheckerFw/tree/Class_AnnotationData_not_found)
- Full build output: [Travis-Ci build #21](https://travis-ci.org/tmtron/As31CheckerFw/builds/358914246#L1395)

**Comment by mernst** [comment]
Thanks very much for the bug report.  I have fixed the two javalib issues.
The androidlib issue remains to be fixed.

**Comment by tmtron** [comment]
Thanks: with version 2.5.2 all issues are gone: I've created a new branch [CheckerFw_2_5_2](https://github.com/tmtron/As31CheckerFw/tree/CheckerFw_2_5_2) and the build works.

**Comment by smillst** [comment]
Great!  Thanks for letting us know!
