### ISSUE TITLE
NullPointerException when using KeyFor and a generic method

### ISSUE THREAD

**Issue by twistedsquare** [typetools/checker-framework#1922]
I'm not 100% sure if this count as a bug in the framework or just an invalid usage, but I have a NullPointerException being thrown without using any SuppressWarnings annotations, which seems like it may count as a bug.  Below is a minimal working example of where I encountered the issue (compiled with version 2.4.0 and the nullness checker on).  I am managing to "launder" a non-key null value via the findKey method and have it return as if it was a key.  In the code as-is, no error is issued (but I do get a NullPointerException if I run it).  However, assigning null directly to myKey (the commented out line) correctly gives an error:

```
import org.checkerframework.checker.nullness.qual.KeyFor;
import org.checkerframework.checker.nullness.qual.NonNull;
import org.checkerframework.checker.nullness.qual.Nullable;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

public class TestKeyFor
{
    // A method to find a K in the collection and return it, or return null.
    public static <K> @Nullable K findKey(Collection<@NonNull K> keys, Object target)
    {
        for (K key : keys)
        {
            if (target.equals(key))
                return key;
        }
        return null;
    }
    
    // Find a key in a map and return String version of its value.
    public static String findKeyAndFetchString(Map<String, Object> someMap)
    {
        @Nullable @KeyFor("someMap") String myKey = TestKeyFor.<@KeyFor("someMap") String>findKey(someMap.keySet(), "Foo");
        // If I change above line to this line, I do get an error:
        //@Nullable @KeyFor("someMap") String myKey = null;
        
        Object value = someMap.get(myKey);
        // value will be null here, but checker gives no error: 
        return value.toString();
    }
    
    public static void main(String[] args)
    {
        findKeyAndFetchString(new HashMap<>());
    }
}
```

It's a slightly weird example now it's been cut down, but it's at least short.  I think the issue is the way that I can attach NonNull/Nullable extras to the K type of findKey, but that interacts with the KeyFor annotation in a way that the checker is not realising breaks the type safety.

**Comment by smillst** [comment]
This is a bug.  The problem is that the type of `null` is `@KeyForBottom`, but it really should be `@UnknownKeyFor`.
