### ISSUE TITLE
regression with declaration annotations and varargs in 2.5.0

### ISSUE THREAD

**Issue by cushon** [typetools/checker-framework#1934]
The handling of varargs methods with declaration parameter annotations changed between 2.4.0 and 2.5.0. Was this deliberate?

```java
import javax.annotation.Nullable;

public class T {
  void f(@Nullable Object... xs) {}

  void test() {
    f(null, null);
  }
}
```

```
./checker-framework-2.4.0/checker/bin/javac -processor Nullness -cp jsr305.jar T.java
... OK
./checker-framework-2.5.0/checker/bin/javac -processor Nullness -cp jsr305.jar T.java
T.java:7: error: [argument.type.incompatible] incompatible types in argument.
    f(null, null);
      ^
  found   : null
  required: @Initialized @NonNull Object
T.java:7: error: [argument.type.incompatible] incompatible types in argument.
    f(null, null);
            ^
  found   : null
  required: @Initialized @NonNull Object
2 errors
```

**Comment by mernst** [comment]
Yes, the change in behavior was intentional.  The changelog says:

> Declaration annotations that are aliases for type annotations are now treated as if they apply to the top-level type.  See "Declaration annotations" section in the "Warnings" chapter in the manual for more details.

The goal is to make it easier for people with pre-existing annotated code (that is annotated for, say, FindBugs) to switch to using the Checker Framework without changing the semantics of their declaration annotations.  Is this a significant problem for your codebase?  (Maybe because you are using declaration annotations, but they are placed at type annotation locations?)

**Comment by smillst** [comment]
Note, that we did not change the semantics of `@NullableDecl` and the other annotations in checker-compat-qual.jar.

**Comment by cushon** [comment]
So far it appears to be a significant breaking change, although the number of root causes may be somewhat lower than the number of breakages. The most common problem is with the jsr305 `@Nullable` on varargs parameters (similar to the test above). In all of the examples I've seen, the author's intent was `@NullableType T...` rather than `T @NullableType...`.

Is there a discussion of this change I can read to get more context about why it was made?

**Comment by wmdietl** [comment]
The discussion was in #1667

**Comment by cushon** [comment]
Thanks for the pointer.

Most of the code I've seen expects type annotations semantics when using the jsr305 `@Nullable`, especially in the case of varargs.

Some of the jsr305 annotations I'm seeing were added after the checker framework was adopted, so the expectations of those programmers may not be representative of all uses of jsr305. But in other cases this is third party code that doesn't directly use the checker, and where I don't necessarily have the ability to change the annotations and migrate from jsr305 to the checker's annotations.

So in practice, this change is going to make it harder for us to use the checker framework with code that depends on libraries that are still using jsr305.

@mernst I generally agree with your comments in the other bug that there are advantages to having the checker treat `@Nullable` and `@NonNull` consistently as a type annotation, regardless which annotation is imported.

**Comment by smillst** [comment]
>The most common problem is with the jsr305 `@Nullable` on varargs parameters (similar to the test above). In all of the examples I've seen, the author's intent was `@NullableType T...` rather than `T @NullableType....`

Is this true in the third party code that also uses jsr305 annotations?

We could add a command line flag to switch back to the old behavior.  But I'm wondering what level of granularity is needed.  For example, the annotations in `android.support.annotation` apply to the declaration not the type, so maybe we need configure this behavior per annotation.  Also, some libraries might have different semantics, so should it be configurable per package?

**Comment by cushon** [comment]
> Is this true in the third party code that also uses jsr305 annotations?

It is definitely true for some third party code that uses jsr305 annotations and does not directly use the checker framework. I don't have an estimate of what fraction of code in that category intended to get type annotation semantics. I'm probably seeing a biased sample--I'm only encountering cases where this change caused new errors to be reported.

I've made some progress on cleaning this up in my codebase by migrating affected code to use type annotations. If that succeeds then I probably wouldn't use the flag, since I'd rather stay close to the recommended defaults.

Having a flag and staggering breaking changes like this across two releases might have made the cleanup easier, though. i.e. starting with a warning for affected code and a flag to opt in to the new behaviour, and then enabling the new behaviour by default in a future release.

**Comment by mernst** [comment]
Sorry this caused you extra work!  The jsr305 annotations are a thorn in everyone's side, and I wish none of us had to deal with them.

Your point about the flag is a good one.  Thanks for pointing that out.

Let us know how well you can localize the issues in your code and in libraries.  We were hopeful that users could mostly switch to using type annotations, thereby rendering moot the Checker Framework's behavior for declaration annotations.

**Comment by cushon** [comment]
No problem, and I agree re: jsr305 :) We've started migrating off jsr305 because of issues with JDK 9 ([related guava bug](https://github.com/google/guava/issues/2960#issuecomment-350721044)), so this is yet another reason to continue that migration.

The cleanup ended up affecting a few hundred files, and I was able to fix most of them by mechanically switching to the checker framework annotations. All of the examples I've seen wanted type annotation semantics, so I'm still a bit skeptical that this change is an improvement for most users. But: I'm happy with migrating to different annotations a work-around, and as I said earlier the code I encountered during the cleanup probably isn't a representative sample.

I don't think it's worth adding a flag to configure this behaviour unless you get other requests for it.

**Comment by mernst** [comment]
Thanks for following up.  I will close this, unless someone else complains (but they should probably migrate, as you have done).
I'm glad this didn't cause extra work for you, but I do regret that it forced you to do that work right away rather than letting you schedule it as you wished.  Sorry about that.
The data about programmer intent when using JSR305 annotations is interesting too.
Thanks again for the bug report; we appreciate it.
