### ISSUE TITLE
checker-compat-qual uses v52 bytecode in 2.5.0

### ISSUE THREAD

**Issue by cushon** [typetools/checker-framework#1946]
Version 2.4.0 of checker-compat-qual.jar uses v50 bytecode, and 2.5.0 uses v52:

```
wget http://repo1.maven.org/maven2/org/checkerframework/checker-compat-qual/2.4.0/checker-compat-qual-2.4.0.jar
javap -v -p -cp checker-compat-qual-2.4.0.jar org/checkerframework/checker/nullness/compatqual/MonotonicNonNullDecl | grep major
  major version: 50
wget http://repo1.maven.org/maven2/org/checkerframework/checker-compat-qual/2.4.0/checker-compat-qual-2.5.0.jar
javap -v -p -cp checker-compat-qual-2.5.0.jar org/checkerframework/checker/nullness/compatqual/MonotonicNonNullDecl | grep major
  major version: 52
```

Do these annotations depend on Java 8 features now? We had been using them in code which needs to remain Java 7-compatible. If they don't rely on Java 8 features, would it be possible to continue to target an older platform version for this artifact?

**Comment by cushon** [comment]
Thanks! Fixing for the next release would be great. It doesn't look like anything else changed in compat-qual in 2.5.0, so I think I can just keep using version 2.4.0 of compat-qual for now.

**Comment by mernst** [comment]
That is correct.
