### ISSUE TITLE
checker-qual is not Android lint compatible

### ISSUE THREAD

**Issue by tonihei** [typetools/checker-framework#1978]
When using the checker-qual library in Andorid libraries, the Android lint tool issues this error even though we just use the annotations:
```
Error: Invalid package reference in library; not included in Android: java.awt. Referenced from org.checkerframework.checker.signedness.SignednessUtil. [InvalidPackage]
```

This causes problems when shipping our library, as we either need to require every user to add a lint suppression for this, or we need to remove the dependency before shipping the code. See for example, [here](https://github.com/google/ExoPlayer/issues/4234) for the issue reported for our library.

I was wondering if
 - The checker-qual library can be made Android compatible by only using Java classes also available on Android (that is: not java.awt).
 - Or by providing an annotations only version without the helper classes as already requested in #1510. 

Thanks!

**Comment by smillst** [comment]
Thanks for reporting!  We are going to do this:
 >The checker-qual library can be made Android compatible by only using Java classes also available on Android (that is: not java.awt).

**Comment by tonihei** [comment]
Sounds good :) Thanks for looking into this.
