### ISSUE TITLE
util package should generate a jar when running gradle assemble or shadowJar

### ISSUE THREAD

**Issue by jyluo** [typetools/checker-framework#2018]
This makes it easier for dependent projects, such as checker-framework-inference to import, define, and execute tests as subclasses of CheckerFrameworkPer***Test without having to have source level dependency on those classes (eg [checker-framework-inference/blob/master/build.gradle#L74](https://github.com/typetools/checker-framework-inference/blob/master/build.gradle#L74))

**Comment by wmdietl** [comment]
I think that jar file is what is also used by the testlib pom:
https://github.com/typetools/checker-framework/blob/master/maven-artifacts/poms/testlibPom.xml

**Comment by smillst** [comment]
`assemble` creates a jar in `util/build/libs`.  Is that not sufficient?

**Comment by smillst** [comment]
Now, the only sub-project with a `dist` folder is `checker` which is used in the release.  We now use the Gradle convention of sub-project/build/libs for jars.  We don't want to add back the `dist` folders.

**Comment by jyluo** [comment]
In `framework` if I run `shadowJar` then `framework.jar` is produced in `framework/dist`. However, running `shadowJar` in `util` does not produce a jar in `util/dist`.

I don't mind where the jar is, but could we change it so that the jar file names don't have a version number? or maybe generate symlinks when we build the jars?

**Comment by smillst** [comment]
You can use `testCompile fileTree(dir: "${checkerFrameworkPath}/util/build/libs", include: 'testlib-*.jar' )` in CFI.

`framework/dist/framework.jar` is a fat jar.  Do you want a testlib jar that's fat?

**Comment by jyluo** [comment]
the fileTree works perfectly! A fat jar isn't needed.

I've filed https://github.com/typetools/checker-framework-inference/pull/82 with this change for CFI.

Closing this issue as theres no futher action needed.
