### ISSUE TITLE
Add an Automatic-Module-Name

### ISSUE THREAD

**Issue by lukaseder** [typetools/checker-framework#2023]
In order to maintain a dependency on the checker-framework, it would be great if you folks exported an `Automatic-Module-Name` for forwards compatibility, in case you ever do decide to modularise the checker framework. See:
http://branchandbound.net/blog/java/2017/12/automatic-module-name

This can be done without much effort or backwards compatibility concerns, even in a patch release.

**Comment by mernst** [comment]
We have modularized the Checker Framework distribution into jar files, according to what we believe that clients may need.

The module names should reflect this modularization.  That is, every jar file should get its own module name, to permit importing at that level of granularity.

We will use the same names as Maven artifacts.  However, module names cannot use hyphens, so checker-qual will become checker.jar.  Here are the module names to use:
```
org.checkerframework.checker
org.checkerframework.checker.qual
org.checkerframework.dataflow
org.checkerframework.framework
org.checkerframework.javacutil
org.checkerframework.testlib
```

We will make these changes, but note that the Checker Framework does not yet support Java 9, so the utility of these will be limited until #1224 is fixed.  We are actively working on #1224, but don't know when that work will be complete.

**Comment by lukaseder** [comment]
Ok, cool, thank you very much, Mike! Note, just in case you decide to be able to publish these new maven modules prior to supporting Java 9, the `Automatic-Module-Name` would definitely help creating a dependency on the relevant modules already ahead of time...
