### ISSUE TITLE
Remove jdk.compiler packages from checker module.

### ISSUE THREAD

**Issue by lukaseder** [typetools/checker-framework#2024]
When working with the JPMS and declaring a module as follows:

```java
module org.jooq.checker {
    requires org.jooq;

    requires checker;
    requires jdk.compiler;
}
```

Then I'm getting errors as the following ones:

```
[ERROR] error: module checker reads package javax.tools from both java.compiler and checker
[ERROR] error: module checker reads package javax.lang.model.util from both java.compiler and checker
[ERROR] error: module checker reads package javax.lang.model.type from both java.compiler and checker
[ERROR] error: module checker reads package javax.lang.model.element from both java.compiler and checker
[ERROR] error: module checker reads package javax.lang.model from both java.compiler and checker
[ERROR] error: module checker reads package javax.annotation.processing from both java.compiler and checker
[ERROR] error: module checker reads package com.sun.tools.javac from both jdk.compiler and checker
[ERROR] error: module checker reads package com.sun.source.util from both jdk.compiler and checker
[ERROR] error: module checker reads package com.sun.source.tree from both jdk.compiler and checker
[ERROR] error: module checker reads package com.sun.source.doctree from both jdk.compiler and checker
```

This makes sense of course. The `checker` API embeds quite a bit of the JDK's classes, which it is no longer allowed to do from JDK 9 onwards - at least not on the module path. Ideally, you should do any of the below:

- Remove those JDK classes entirely
- Ship them in a separate artefact

Do note also the related issue about having an automatic module name: #2023

**Comment by wmdietl** [comment]
#1224 is working on full Java 9 support and our goal is to finish this work this summer.
In that process, we are separating out the java compiler into a separate dependency and will also have a separate `framework` artefact.

**Comment by lukaseder** [comment]
OK, very cool, thanks for the feedback!

**Comment by smillst** [comment]
The 3.0.0 release of the Checker Framework removed all the JDK classes from checker.jar.  So this issue is fixed.  Note that the name of the module is not checker, it's org.checkerframework.checker.
