### ISSUE TITLE
Index: Upper Bound Checker should infer @LessThan("size") as same as @LTLenghtOf("array")

### ISSUE THREAD

**Issue by NhatDinh** [typetools/checker-framework#2029]
Consider this:
```java
public class InferType {
    void simpleMethod(@NonNegative @LessThan("#2") int index,@NonNegative int size, char val){
        char[] arr = new char[size];
        arr[index] = val;
    }
}
```
Error message:
```java
Error:(14, 13) java: [array.access.unsafe.high] Potentially unsafe array access: the index could be larger than the array's bound
  found   : @UpperBoundUnknown int
  required: @IndexFor("arr") or @LTLengthOf("arr") -- an integer less than arr's length
```
Upper bound checker should infer annotation  `@LessThan("#2")` as `@LTLengthOf("arr")`.

**Comment by kelloggm** [comment]
Steps to solve this:
1. At array creation, record the expression in the initializer. Call that expression _e_. Also record the name of the new array _a_.
2. Look up every integer in the store that's in scope. For each integer _i_, check the LessThan type of that integer. If the LessThan type's argument is exactly _e_, then add a new upper bound type to _i_: `@LTLengthOf("a")`. Add this to the store.

**Comment by kelloggm** [comment]
This would be done in `UpperBoundTransfer#visitAssignment`, I think. Possibly `UpperBoundTransfer#visitArrayCreation`.

**Comment by NhatDinh** [comment]
Closed this issue since unit and integration tests in [PR #2103](https://github.com/typetools/checker-framework/pull/2103)
