### ISSUE TITLE
NPE while using CFGBuilder

### ISSUE THREAD

**Issue by peey** [typetools/checker-framework#2046]
I'm trying to use checker-framework's [dataflow capabilities](https://checkerframework.org/manual/checker-framework-dataflow-manual.pdf).

What I want to do is to obtain the CFG for a given Java file. I found the method: 
> CFGBuilder.build(CompilationUnitTree, MethodTree, ClassTree, ProcessingEnvironment)

And here's a minimal example of how I'm trying to use it, which produces an error

**Source**
```
import com.sun.source.tree.ClassTree;
import com.sun.source.tree.CompilationUnitTree;
import com.sun.source.tree.MethodTree;
import com.sun.source.util.JavacTask;
import com.sun.tools.javac.processing.JavacProcessingEnvironment;
import com.sun.tools.javac.util.Context;
import org.checkerframework.dataflow.cfg.CFGBuilder;
import org.checkerframework.dataflow.cfg.ControlFlowGraph;

import javax.annotation.processing.ProcessingEnvironment;
import javax.tools.JavaCompiler;
import javax.tools.JavaFileObject;
import javax.tools.SimpleJavaFileObject;
import javax.tools.ToolProvider;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;

public class CFGGen {


  public static void main(String[] args) throws IOException {
    ControlFlowGraph cfg = getCFG();
    //do stuff with cfg
  }

  public static CompilationUnitTree getCUnitTree() throws IOException {
    JavaFileObject sfo = new SimpleJavaFileObject(URI.create("myfo:/Test.java"), JavaFileObject.Kind.SOURCE) {
      public CharSequence getCharContent(boolean ignoreEncodingErrors) {
        return "class Hello { public static void main(String[] args) { boolean condition = false; if (condition) { System.out.println(\"Hello World\"); } else { System.out.println(\"Goodbye, world\");} } }";
      }
    };

    java.util.List<JavaFileObject> files = Arrays.asList(sfo);
    JavaCompiler tool = ToolProvider.getSystemJavaCompiler();
    JavacTask ct = (JavacTask)tool.getTask(null, null, null, null, null, files);
    Iterable<? extends CompilationUnitTree> compUnits = ct.parse();
    CompilationUnitTree cu = compUnits.iterator().next();
    return cu;
  }

  public static ControlFlowGraph getCFG() throws IOException {
    CompilationUnitTree cu = getCUnitTree();

    ClassTree clazz = (ClassTree) cu.getTypeDecls().get(0);

    MethodTree mt = (MethodTree) clazz.getMembers().get(0);

    Context context = new Context();

    ProcessingEnvironment env = JavacProcessingEnvironment.instance(context);

    return CFGBuilder.build(cu, mt, clazz,env);
  }
}
```

**Complete Contents of Output Pane**:

```
/app/jdk-8/bin/java -javaagent:/app/idea-IU-181.4203.550/lib/idea_rt.jar=35493:/app/idea-IU-181.4203.550/bin -Dfile.encoding=UTF-8 -classpath /app/jdk-8/jre/lib/charsets.jar:/app/jdk-8/jre/lib/ext/cldrdata.jar:/app/jdk-8/jre/lib/ext/dnsns.jar:/app/jdk-8/jre/lib/ext/jaccess.jar:/app/jdk-8/jre/lib/ext/localedata.jar:/app/jdk-8/jre/lib/ext/nashorn.jar:/app/jdk-8/jre/lib/ext/sunec.jar:/app/jdk-8/jre/lib/ext/sunjce_provider.jar:/app/jdk-8/jre/lib/ext/sunpkcs11.jar:/app/jdk-8/jre/lib/ext/zipfs.jar:/app/jdk-8/jre/lib/jce.jar:/app/jdk-8/jre/lib/jsse.jar:/app/jdk-8/jre/lib/management-agent.jar:/app/jdk-8/jre/lib/resources.jar:/app/jdk-8/jre/lib/rt.jar:/mnt/software/experiments/2018-06-19-checker-framework/out/production/2018-06-19-checker-framework:/mnt/software/experiments/2018-06-19-checker-framework/lib/checker-2.5.2.jar CFGGen
Exception in thread "main" java.lang.NullPointerException
	at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitVariable(CFGBuilder.java:4743)
	at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitVariable(CFGBuilder.java:1414)
	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:864)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
	at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:3256)
	at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:1414)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:918)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
	at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.process(CFGBuilder.java:1569)
	at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.process(CFGBuilder.java:1613)
	at org.checkerframework.dataflow.cfg.CFGBuilder.build(CFGBuilder.java:228)
	at org.checkerframework.dataflow.cfg.CFGBuilder.build(CFGBuilder.java:272)
	at CFGGen.getCFG(CFGGen.java:53)
	at CFGGen.main(CFGGen.java:23)

Process finished with exit code 1
```

I've run the debugger to inspect that I'm at least generating the `CompilationUnitTree`, `MethodTree` and `ClassTree` correctly, and I am

![image](https://user-images.githubusercontent.com/4688870/41705393-75f269fa-7556-11e8-930a-39ddfa05e3ab.png)

What might I be doing wrong? I couldn't find examples of how I should be using `CFGBuilder.build` so it's possible that I'm missing some configuration

**Comment by wmdietl** [comment]
It looks like you're getting the exception here:

```java
  TypeElement classElem = TreeUtils.elementFromDeclaration(enclosingClass);
  Node receiver = new ImplicitThisLiteralNode(classElem.asType());
```

So `classElem` is `null` and you get an NPE.

I think what is missing is the Attribution of the AST that you generated, and therefore Elements and Types might not be set.
For the Checker Framework we run the annotation processors after attribution, using:
https://github.com/typetools/checker-framework/blob/master/javacutil/src/main/java/org/checkerframework/javacutil/AbstractTypeProcessor.java

I'm also not sure about your use of `new Context()` to start a fresh context.

I'm not sure what the `JavaCompiler`/`JavacTask` way is to advance to Attribution.
Please do let us know if you find a solution, so that we can improve the Dataflow instructions.

**Comment by peey** [comment]
So if I understand correctly, the problem here is that usually things which are building on top of checker-framework are run as annotation processors on files invoked by doing something like

``` javac -processor XYZ sourcefile.java```

And when that's done, the `ProcessingEnvironment` and `Context` is managed by Javac and provided to the annotation processors as arguments.

Now what I want to do is to simply not bother with annotation processing business and use CFG Builder on an input Java file, programaticallly.

The current way to do this would be to call javac programatically, instead of calling it via command line.

So while doing so, I'll have to figure out what the right values for `ProcessingEnvironment` and `Context` are.

So far I've found how I could specify something as a annotation processor using a `ProcessingEnvironment`, that's done via `env.setProcessors`.

So by doing this, I might be able to run (something concrete which extends) `AbstractTypeProcessor` on my input files, and when I get their compilation units they would have necessary `TypeElement`s to resolve this NPE.

Then I could possibly pass that `ProcessingEnvironment` object and respective compilation unit tress, method unit trees, class unit trees to `CFGBuilder.build` as I was trying to do, and it would hopefully work.

In case this is all correct, then there's only one piece of the puzzle which I'm having a problem on. In making my `ProcessingEnvironment` object artificially, I'm not able to figure out how to specify files / compilation units which are to be processed. Does it have to be done in the `Context`? If yes, then how? Or is there a method on the `env` object itself? (I couldn't find one).

**Comment by wmdietl** [comment]
I don't understand your question.
If you already run your new annotation processor on the input files, what input files do you want to put into the Context/ProcessingEnvironment?
To get the right Context, couldn't your new annotation processor simply store that somewhere accessible?
Maybe com.sun.tools.javac.api.BasicJavacTask.getContext() is the method you want to call on your JavacTask?

**Comment by peey** [comment]
I didn't write my own code as an annotation processor. I was trying to run some existing annotation processor like say `SignaturePrinter` which inherits from `AbstractTypeProcessor`.

I hoped that doing this would avoid `classElm` from being null. 

In any case, what I was trying to do didn't work out because I think I'll have to use checker's `javacutil` instead of javac, because that's what checker framework requires to even run annotation processors according to [31.6](https://checkerframework.org/manual/#javac-installation)

I'm not familiar with `javacutil`. Is there a way I could use it to get a `CompilationUnit` and `ProcessingEnvrionment` which I could pass to `CFGBuilder.build` instead of using `JavaComipler` / `JavacTask` as I was?

**Comment by wmdietl** [comment]
I don't see any mention of `javacutil` in 31.6.
`javacutil` is just utility methods on top of javac; it augments and doesn't replace javac.
Basic functionality like getting a compilation unit would still be performed by the normal javac API.

**Comment by peey** [comment]
I'm not sure if checker-framework intends for use of CFGBuilder outside of checker-framework / annotation processing

But I think it'd be pretty useful. I actually read this in the data flow manual:

![image](https://user-images.githubusercontent.com/4688870/41850175-3eaad16e-78a1-11e8-825c-fdfec2824941.png)

And thought it was indeed meant to for all of these to be usable independently.

If checker-framework intends on doing this then it'd be good to internalize the AST Attribution and have an API which doesn't require providing a ProcessingEnvironment

**Comment by wmdietl** [comment]
Great to hear you got it working.

The sub-projects build on each other, so there is no expectation that you could use e.g. `framework` without `dataflow`. But we want `dataflow` to be usable independently of `framework` or higher levels.

However, it is not a goal to make `dataflow` independent of annotation processing or the OpenJDK javac.

You definitely shouldn't need the `jdk8.jar` dependency, as you don't seem to be interested in the annotated JDK annotations it provides.

The `checker.jar` dependency also shouldn't be needed and you can instead depend on the individual jar files for javac, javacutils, and dataflow.

Instead of having the dummy annotation processor I would probably put your additional logic directly into the processor to there iterate over the compilation units, classes, and methods.
