### ISSUE TITLE
java.util.List should be covariant

### ISSUE THREAD

**Issue by justmin** [typetools/checker-framework#2047]
```
        List<String> stringList = new ArrayList<>();
        List<@Nullable String> nullableStringList = stringList;

```
```
Error:(11, 53) java: [assignment.type.incompatible] incompatible types in assignment.
  found   : @Initialized @NonNull List<@Initialized @NonNull String>
  required: @UnknownInitialization @Nullable List<@Initialized @Nullable String>

```
It looks reasonable to make List be annotated with `@Covariant(0)`

**Comment by mernst** [comment]
As [explained in the manual](https://checkerframework.org/manual/#invariant-arrays), this would be unsound.  If you translate the [example for arrays](https://checkerframework.org/manual/#invariant-arrays) to lists, you will see the problem.
