### ISSUE TITLE
Bad OSGI info for Guava in latest jar

### ISSUE THREAD

**Issue by elharo** [typetools/checker-framework#2073]
In the latest jar of org.checkerframework.annotatedlib:guava on Maven central, the OSGI info is mismatched. In particular, notice the difference between what's exported - 24.1.0 - and the Bundle-Version - 25.1.0.jre 

Bundle-Version: 25.1.0.jre
Created-By: Apache Maven Bundle Plugin
Export-Package: com.google.common.annotations;version="24.1.0",com.googl
 e.common.base;version="24.1.0",com.google.common.cache;version="24.1.0"
 ;uses:="com.google.common.base,com.google.common.collect,com.google.com
 mon.util.concurrent",com.google.common.collect;version="24.1.0";uses:="
 com.google.common.base,javax.annotation",com.google.common.escape;versi
 on="24.1.0";uses:="com.google.common.base",com.google.common.eventbus;v
 ersion="24.1.0",com.google.common.graph;version="24.1.0";uses:="com.goo
 gle.common.collect",com.google.common.hash;version="24.1.0";uses:="com.
 google.common.base",com.google.common.html;version="24.1.0";uses:="com.
 google.common.escape",com.google.common.io;version="24.1.0";uses:="com.
 google.common.base,com.google.common.collect,com.google.common.graph,co
 m.google.common.hash",com.google.common.math;version="24.1.0",com.googl
 e.common.net;version="24.1.0";uses:="com.google.common.base,com.google.
 common.collect,com.google.common.escape",com.google.common.primitives;v
 ersion="24.1.0";uses:="com.google.common.base",com.google.common.reflec
 t;version="24.1.0";uses:="com.google.common.collect,com.google.common.i
 o",com.google.common.util.concurrent;version="24.1.0";uses:="com.google
 .common.base,com.google.common.collect",com.google.common.xml;version="
 24.1.0";uses:="com.google.common.escape"
Import-Package: javax.annotation;resolution:=optional;version="[3.0,4)",
 javax.crypto;resolution:=optional,javax.crypto.spec;resolution:=optiona
 l,sun.misc;resolution:=optional

The official guava release has instead:

Bundle-Version: 25.1.0.jre
Created-By: Apache Maven Bundle Plugin
Export-Package: com.google.common.annotations;version="24.1.0",com.googl
 e.common.base;version="24.1.0",com.google.common.cache;version="24.1.0"
 ;uses:="com.google.common.base,com.google.common.collect,com.google.com
 mon.util.concurrent",com.google.common.collect;version="24.1.0";uses:="
 com.google.common.base,javax.annotation",com.google.common.escape;versi
 on="24.1.0";uses:="com.google.common.base",com.google.common.eventbus;v
 ersion="24.1.0",com.google.common.graph;version="24.1.0";uses:="com.goo
 gle.common.collect",com.google.common.hash;version="24.1.0";uses:="com.
 google.common.base",com.google.common.html;version="24.1.0";uses:="com.
 google.common.escape",com.google.common.io;version="24.1.0";uses:="com.
 google.common.base,com.google.common.collect,com.google.common.graph,co
 m.google.common.hash",com.google.common.math;version="24.1.0",com.googl
 e.common.net;version="24.1.0";uses:="com.google.common.base,com.google.
 common.collect,com.google.common.escape",com.google.common.primitives;v
 ersion="24.1.0";uses:="com.google.common.base",com.google.common.reflec
 t;version="24.1.0";uses:="com.google.common.collect,com.google.common.i
 o",com.google.common.util.concurrent;version="24.1.0";uses:="com.google
 .common.base,com.google.common.collect",com.google.common.xml;version="
 24.1.0";uses:="com.google.common.escape"

**Comment by mernst** [comment]
Sorry for the bug (and for the long delay in responding -- I have been traveling).

I have corrected the problem by uploading a new artifact, 25.1.0.1, to Maven Central.  I believe it corrects the problem.

Thanks for the bug report!
