### ISSUE TITLE
Checker Framework web site links to outdated Javadoc

### ISSUE THREAD

**Issue by ahubold** [typetools/checker-framework#2099]
2.5.4 is the latest released version but https://checkerframework.org/api/ still shows API documentation for version 2.5.3

https://checkerframework.org/releases/2.5.4/api/ is empty.

**Comment by mernst** [comment]
Thanks for pointing this out.  We'll look into it.

**Comment by smillst** [comment]
I manually fixed the Javadoc in  https://checkerframework.org/api/ and https://checkerframework.org/releases/2.5.4/api/.  PR #2096 fixes the cause of this problem, so this won't happen next time we release. Thanks for reporting!
