### ISSUE TITLE
"Every Java file is a valid stub file" is not *technically* true

### ISSUE THREAD

**Issue by kelloggm** [typetools/checker-framework#2102]
Repeatedly when discussing stub files, the manual say "Every Java file is a valid stub file" (29.5.2 and 29.5.3, first paragraphs). This isn't *technically* true, though, which can cause confusion. In particular, the Checker Framework will never read a file ending in `.java` as if it were a stub file - the user needs to change the extension on the file to `.astub` to make it a valid stub file. Otherwise, it will be ignored by `org.checkerframework.framework.stub.StubUtil#allStubFiles`, because that method validates stub files by checking whether they end with `.astub`.

This documentation is confusing for users. I propose either:
* removing the claim that all Java files are valid stubs from the manual, and replacing it with something weaker (like "all Java files are valid stubs once they have been renamed"), along with an explicit statement in the manual that "only files that end in `.astub` are stub files"
* or changing `StubUtil` so that it will accept `.java` files in addition to `.astub` files. This seems to be what the manual, as currently written, says should happen, so I would favor this option.

**Comment by mernst** [comment]
Thanks for pointing out this confusing text!
My feeling is that `.java` will be confusing for tools and people, so I am inclined to stick with `.astub` for now, unless there is a strong case to be made.
I will update the documentation.
