### ISSUE TITLE
Annotations on enum constants in stub files are silently ignored

### ISSUE THREAD

**Issue by kelloggm** [typetools/checker-framework#2147]
All typecheckers silently ignore annotations written on stub files containing enums. For example, consider the following enum, defined in `SampleEnum.java`:

```java
public enum SampleEnum {
	FIRST,
        SECOND;
} 
```

Suppose that this code was available only as bytecode, but must be annotated. So, we write a stub file `SampleEnum.astub`:

```java
import org.checkerframework.checker.tainting.qual.*;

enum SampleEnum {
	@Untainted FIRST,
	@Tainted SECOND;
}
```

When this stub file is supplied to the compiler via `-Astubs=SampleEnum.astub`, I expect to see only one warning in the following client code (`EnumStubTest.java`):

```java
import org.checkerframework.checker.tainting.qual.*;

class EnumStubTest {
    void test() {
	requireEnum(SampleEnum.FIRST);
	// :: error: assignment.type.incompatible
	requireEnum(SampleEnum.SECOND);
    }

    void requireEnum(@Untainted SampleEnum sEnum) { }
}
```

Instead, errors are issued at both calls to `requireEnum`:
```bash
▶ checker/bin/javac -processor tainting EnumStubTest.java -Astubs=SampleEnum.astub
EnumStubTest.java:5: error: [argument.type.incompatible] incompatible types in argument.
	requireEnum(SampleEnum.FIRST);
	                      ^
  found   : @Tainted SampleEnum
  required: @Untainted SampleEnum
EnumStubTest.java:7: error: [argument.type.incompatible] incompatible types in argument.
	requireEnum(SampleEnum.SECOND);
	                      ^
  found   : @Tainted SampleEnum
  required: @Untainted SampleEnum
2 errors
```
If I move the annotations on `SampleEnum` into the `.java` file, the error goes away, so I suspect this is something in the stubparser. [Javaparser#1806](https://github.com/javaparser/javaparser/issues/1806) might be related.

I was able to reproduce the issue using the Value Checker, also, using `@StringVal` annotations instead of tainted/untainted.

**Comment by mernst** [comment]
There is currently a pull request (https://github.com/javaparser/javaparser/pull/1812) open to fix https://github.com/javaparser/javaparser/issues/1806.  I propose that we wait for it to be merged, then pull upstream into stubparser.  If that doesn't resolve the issue, then we should investigate further.

**Comment by wmdietl** [comment]
We do not use the symbol resolution part from JavaParser, so that pull request won't help.

We need to look at what https://github.com/typetools/checker-framework/blob/master/framework/src/main/java/org/checkerframework/framework/stub/StubParser.java does with enum constant annotations and whether the type factories actually ask for the enum constant annotations from the stub parser.

**Comment by mernst** [comment]
There is a processEnum method.
