### ISSUE TITLE
Nullness-checker: Wrong required type for method of nested generic class in concrete specialisation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [typetools/checker-framework#216]
```
Compiling and nullness checking the attached source results an error "found: 
String required: T extends Object".

Expected that the checker would infer String as the type (javac infers the type 
correctly).

Commandline:
~/tmp/checker-framework/checkers/binary/javac -version -verbose 
-AprintErrorStack -processor checkers.nullness.NullnessChecker 
scratch2/Scratch3.java 2>&1 | tee ~/tmp/output.txt

Attached is the output it produced

Checker-framework version: 1.6.2 (in versions 1.4.0, 1.4.4 (from Maven 
dependency), and 1.6.0 (from Maven dependency) all produce same behaviour)

JDK version: 1.7.0 (as supplied with checker-framework)
```

Original issue reported on code.google.com by `kaspervd...@gmail.com` on 27 Apr 2013 at 7:02

Attachments:
- [Scratch3.java](https://storage.googleapis.com/google-code-attachments/checker-framework/issue-216/comment-0/Scratch3.java)
- [output.txt](https://storage.googleapis.com/google-code-attachments/checker-framework/issue-216/comment-0/output.txt)

**Comment by wmdietlGC** [comment]
I've been working on fixing a nested class with generics bug and I'm looking through existing ones.
I looked at the InferMethod test for this bug report, but it seems to work as expected - even with the commented-out parts enabled.
Closing this issue.
