### ISSUE TITLE
Document why AnnotationMirror#equals and AnnotationMirror#hashcode can't be used.

### ISSUE THREAD

**Issue by smillst** [typetools/checker-framework#2166]
AnnotationMirror is an interface that is implement both by javac and the Checker Framework.   Using `equals` with one object created by the Checker Framework and one by javac will always return false even if they are the same.  Therefore, never use any method that compares AnnotationMirrors using `equals`.   AnnotationUtils has various methods that should be used instead.  Also, `org.checkerframework.framework.util.AnnotationMirrorMap` and `org.checkerframework.framework.util.AnnotationMirrorSet` can be used. This should be in the CF manual, but isn't.

#492 is related to this.

**Comment by mernst** [comment]
Should we create a checker that issues a warning if AnnotationMirror.equals or AnnotationMirror.hashCode is called?

**Comment by smillst** [comment]
We decide to just copy the text in the first comment into the manual.
