### ISSUE TITLE
Wrong assumptions on unchecked code

### ISSUE THREAD

**Issue by justmin** [typetools/checker-framework#2178]
```
import org.apache.commons.lang.StringUtils;
public class Example {
    public String foo(String str){
        return StringUtils.trimToNull(str);
    }
}

```
This code is compiled using CF but unexpectedly could produce `@Nullable` result
Suggesion: treat all return values in unprocessed code as `@Nullable`

**Comment by wmdietl** [comment]
There is a discussion of this issue at https://checkerframework.org/manual/#defaults-classfile
Passing `-AuseDefaultsForUncheckedCode=bytecode` will give you conservative defaults.
This probably will reveal missing annotations for third-party libraries, for which you will need to write stub files.
Please let us know if you run into any unexpected behavior with this option.

**Comment by mernst** [comment]
I'm closing this issue because we haven't heard about any problems.  Please re-open if necessary.
