### ISSUE TITLE
Missing copyright info in license

### ISSUE THREAD

**Issue by hos-p** [typetools/checker-framework#2180]
[Licence](https://github.com/typetools/checker-framework/blob/master/LICENSE.txt) does not conform to MIT License. There is no copyright in it. Could you please fix it?

Copyright <YEAR> <COPYRIGHT HOLDER>

**Comment by wmdietl** [comment]
I'm not sure what you mean. The MIT License is at the bottom of the file:
https://github.com/typetools/checker-framework/blob/master/LICENSE.txt#L389

**Comment by mernst** [comment]
The point is that file LICENSE.txt does not state the name of the copyright holders nor the date of the copyright.
