### ISSUE TITLE
Remove <mernst@cs.wahsington.edu> and <smillst@cs.washington.edu> in the <id> field

### ISSUE THREAD

**Issue by vbossica** [typetools/checker-framework#2207]
In the generate `pom.xml` the `<id>` sections containing `<` characters are invalid XML fragment:

```
<developer>
    <id>Michael Ernst <mernst@cs.washington.edu></id>
</developer>
<developer>
    <id>Suzanne Millstein <smillst@cs.washington.edu></id>
</developer>
```

Could you remove the email parts so that the `pom.xml` can easily be parsed?

Thanks!

**Comment by mernst** [comment]
Thank you for letting us know about the problem, and sorry you had trouble.  We have now fixed the problem.
