### ISSUE TITLE
Should every type system be required to have a polymorphic type qualifier? 

### ISSUE THREAD

**Issue by t-rasmud** [typetools/checker-framework#2217]
Section 24.2.3 of the manual states "Each type system has its own polymorphic type qualifier". However, the Initialization, Lock and PropertyKey checkers don't have polymorphic qualifiers defined in their type systems. As a result, calling "getPolymorphicAnnotation()" on any of these checkers results in a BugInCF Exception.
I tried adding a polymorphic annotation to the Initialization checker [(See changes here)](https://github.com/t-rasmud/checker-framework/commit/231a84e405d4e488efb355dff05747344bf4f45b). This causes a few tests to fail. One example of a failing test is [this](https://github.com/t-rasmud/checker-framework/blob/master/checker/tests/nullness/InferNullType.java) where the expected errors at lines 22 and 30 are not found when the command `./gradlew nullnessfbctest` is executed.
Moreover, I see that the `@PolyGuardedBy` annotation in the lock checker has been commented out with a "TODO comment" that suggests that this feature will be supported in future.
Given this, I think we should either get rid of the requirement that every type system must have a polymorphic qualifier or modify these checkers to support polymorphism.

**Comment by t-rasmud** [comment]
In that case, should the method `getPolymorphicAnnotation()` return null (and not throw an exception) when a type system doesn't have a polymorphic qualifier?

**Comment by wmdietl** [comment]
This issue has been closed by https://github.com/typetools/checker-framework/commit/48677c1f4c056319ad089cb763772369f3963fbb
