### ISSUE TITLE
addComputedTypeAnnotations not called on local variables

### ISSUE THREAD

**Issue by jwaataja** [typetools/checker-framework#2223]
The method to add implicit annotations in `AnnotatedTypeFactory` is never called on local variables. I added this method to `PropertyKeyAnnotatedTypeFactory.java` in the Property Key Checker:

```java
public void addComputedTypeAnnotations(Element elt, AnnotatedTypeMirror type) {
    super.addComputedTypeAnnotations(elt, type);
    if (elt.getKind() == ElementKind.LOCAL_VARIABLE) {
        System.out.println("Local variable");
    }
}
```

Running the checker on this class produces no output:
```java
class C {
    void f() {
        int i;
    }
}
```

Because this method is never called, adding implicit annotations to local variables in code can't be done. A search of the framework shows that no checker has attempted this before.

**Comment by smillst** [comment]
You should use `  protected void addComputedTypeAnnotations(Tree tree, AnnotatedTypeMirror type, boolean iUseFlow) {` instead for local variables.
