### ISSUE TITLE
androidx.annotation.Nullable

### ISSUE THREAD

**Issue by oknirb** [typetools/checker-framework#2224]
The Checker Framework supports
  android.annotation.Nullable
  android.support.annotation.Nullable
and the corresponding .NonNull annotations in those packages.

But those packages are obsolete, and are being replaced by androidx.annotation.

Please add support for androidx.annotation.Nullable and .NonNull.

Ref: https://developer.android.com/reference/androidx/annotation/package-summary

**Comment by wmdietl** [comment]
Thanks for reporting this! #2225 should address this.
