### ISSUE TITLE
AsSuperVisitor: type is not an erased subtype of supertype

### ISSUE THREAD

**Issue by shashiranjan** [typetools/checker-framework#2234]
I am currently  using checker framework 2.5.8 version and facing weird BugInCF crash issue.

I have a complex class hierarchy something like below 

public class Test1 extends Test2 {
}

public abstract class Test2<T extends Test3 & Test4>
        extends Test5<T> {
}

Test3 and Test4 are interfaces  and Test5 is something like below,

public abstract class Test5<T extends Test3 & Test4>  {
}

javac compiles this program, but running any Checker Framework checker results in a crash.

This might be a duplicate of the several open issues relating to AsSuperVisitor: #2190, #2195, #2196, #2198. I wanted to report this because I've encountered it in the wild.

Here is the output of -AprintErrorStack:

[javac] error: AsSuperVisitor: type is not an erased subtype of supertype.
    [javac]   type: @Public Object
    [javac]   superType: @Public Test1
    [javac]   Compilation unit:
    [javac]   Last visited tree at line 11 column 1:
    [javac]   public class RenameTableFormulaUpdater extends BaseTableRenameFormulaUpdater {
    [javac]   Exception: java.lang.Throwable; Stack trace: org.checkerframework.javacutil.BugInCF.<init>(BugInCF.java:25)
    [javac]   org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:154)
    [javac]   org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:350)
    [javac]   org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:28)
    [javac]   org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:307)
    [javac]   org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:57)
    [javac]   org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:85)
    [javac]   org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:67)
    [javac]   org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:112)
    [javac]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism$PolyCollector.visit(AbstractQualifierPolymorphism.java:400)
    [javac]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism$PolyCollector.visitDeclared_Declared(AbstractQualifierPolymorphism.java:466)
    [javac]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism$PolyCollector.visitDeclared_Declared(AbstractQualifierPolymorphism.java:284)
    [javac]   org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:307)
    [javac]   org.checkerframework.framework.type.visitor.EquivalentAtmComboScanner.scan(EquivalentAtmComboScanner.java:56)
    [javac]   org.checkerframework.framework.type.visitor.EquivalentAtmComboScanner.visit(EquivalentAtmComboScanner.java:36)
    [javac]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism$PolyCollector.visit(AbstractQualifierPolymorphism.java:402)
    [javac]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism$PolyCollector.visit(AbstractQualifierPolymorphism.java:363)
    [javac]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism$PolyCollector.access$100(AbstractQualifierPolymorphism.java:284)
    [javac]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism.annotate(AbstractQualifierPolymorphism.java:130)
    [javac]   org.checkerframework.framework.type.GenericAnnotatedTypeFactory.methodFromUse(GenericAnnotatedTypeFactory.java:1540)
    [javac]   org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:170)
    [javac]   org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:44)
    [javac]   com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
    [javac]   com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
    [javac]   org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:36)
    [javac]   org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:1238)
    [javac]   org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1016)
    [javac]   org.checkerframework.framework.flow.CFAbstractTransfer.getValueFromFactory(CFAbstractTransfer.java:201)
    [javac]   org.checkerframework.framework.flow.CFAbstractTransfer.visitMethodInvocation(CFAbstractTransfer.java:925)
    [javac]   org.checkerframework.framework.flow.CFAbstractTransfer.visitMethodInvocation(CFAbstractTransfer.java:93)
    [javac]   org.checkerframework.dataflow.cfg.node.MethodInvocationNode.accept(MethodInvocationNode.java:76)
    [javac]   org.checkerframework.dataflow.analysis.Analysis.callTransferFunction(Analysis.java:408)
    [javac]   org.checkerframework.dataflow.analysis.Analysis.performAnalysisBlock(Analysis.java:234)
    [javac]   org.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:187)
    [javac]   org.checkerframework.framework.flow.CFAbstractAnalysis.performAnalysis(CFAbstractAnalysis.java:91)
    [javac]   org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1225)
    [javac]   org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1143)
    [javac]   org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1487)
    [javac]   org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:260)
    [javac]   org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:291)
    [javac]   org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:159)
    [javac]   com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
    [javac]   com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
    [javac]   org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:85)
    [javac]   org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:967)
    [javac]   org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:494)
    [javac]   org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:182)
    [javac]   com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
    [javac]   com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
    [javac]   com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
    [javac]   com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
    [javac]   com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
    [javac]   com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
    [javac]   com.sun.tools.javac.main.Main.compile(Main.java:523)
    [javac]   com.sun.tools.javac.main.Main.compile(Main.java:381)
    [javac]   com.sun.tools.javac.main.Main.compile(Main.java:370)
    [javac]   com.sun.tools.javac.main.Main.compile(Main.java:361)
    [javac]   com.sun.tools.javac.Main.compile(Main.java:56)
    [javac]   com.sun.tools.javac.Main.main(Main.java:42)

**Comment by wmdietl** [comment]
@shashiranjan Thanks for the report and sorry for the problem you're running into.
All the issues that you referenced are closed and their test cases pass.
Like in those tests, could you try to produce a small, reproducible test case? This is much easier for the person reporting the issue than for us trying to take your description and trying to produce it.
Once we have a test case it is usually pretty quick to fix the bug.
Thanks!

**Comment by shashiranjan** [comment]
Hi Werner,

Thank you for quick response. Here is a small and reproducible test case,

//Test.java
public class Test extends Test2 {
    public Test() {
        super(new HashMap<>());
    }
}

//Test2.java
import java.util.Map;
public abstract class Test2<T extends String>{
    private Map<Abc, String> abcMap;
    public Test2(final Map<Abc, String> abcMap) {
        this.abcMap = abcMap;
    }
}

//Abc.java
public class Abc {
}


//Output
Without Checker it compiles successfully and with checker it throws below error

[javac] error: AsSuperVisitor: type is not an erased subtype of supertype.
    [javac]   type: @Public Object
    [javac]   superType: @Public Abc
    [javac]   Compilation unit: Test.java
    [javac]   Last visited tree at line 5 column 1:
    [javac]   public class Test extends Test2 {
    [javac]   Exception: java.lang.Throwable; Stack trace: org.checkerframework.javacutil.BugInCF.<init>(BugInCF.java:25)
    [javac]   org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:154)
    [javac]   org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:350)
    [javac]   org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:28)
    [javac]   org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:307)
    [javac]   org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:57)
    [javac]   org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:85)
    [javac]   org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:67)
    [javac]   org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:112)
    [javac]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism$PolyCollector.visit(AbstractQualifierPolymorphism.java:400)
    [javac]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism$PolyCollector.visitDeclared_Declared(AbstractQualifierPolymorphism.java:466)
    [javac]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism$PolyCollector.visitDeclared_Declared(AbstractQualifierPolymorphism.java:284)
    [javac]   org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:307)
    [javac]   org.checkerframework.framework.type.visitor.EquivalentAtmComboScanner.scan(EquivalentAtmComboScanner.java:56)
    [javac]   org.checkerframework.framework.type.visitor.EquivalentAtmComboScanner.visit(EquivalentAtmComboScanner.java:36)
    [javac]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism$PolyCollector.visit(AbstractQualifierPolymorphism.java:402)
    [javac]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism$PolyCollector.visit(AbstractQualifierPolymorphism.java:363)
    [javac]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism$PolyCollector.access$100(AbstractQualifierPolymorphism.java:284)
    [javac]   org.checkerframework.framework.type.poly.AbstractQualifierPolymorphism.annotate(AbstractQualifierPolymorphism.java:130)
    [javac]   org.checkerframework.framework.type.GenericAnnotatedTypeFactory.methodFromUse(GenericAnnotatedTypeFactory.java:1540)
    [javac]   org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:170)
    [javac]   org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:44)
    [javac]   com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
    [javac]   com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
    [javac]   org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:36)
    [javac]   org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:1238)
    [javac]   org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1016)
    [javac]   org.checkerframework.framework.flow.CFAbstractTransfer.getValueFromFactory(CFAbstractTransfer.java:201)
    [javac]   org.checkerframework.framework.flow.CFAbstractTransfer.visitMethodInvocation(CFAbstractTransfer.java:925)
    [javac]   org.checkerframework.framework.flow.CFAbstractTransfer.visitMethodInvocation(CFAbstractTransfer.java:93)
    [javac]   org.checkerframework.dataflow.cfg.node.MethodInvocationNode.accept(MethodInvocationNode.java:76)
    [javac]   org.checkerframework.dataflow.analysis.Analysis.callTransferFunction(Analysis.java:408)
    [javac]   org.checkerframework.dataflow.analysis.Analysis.performAnalysisBlock(Analysis.java:234)
    [javac]   org.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:187)
    [javac]   org.checkerframework.framework.flow.CFAbstractAnalysis.performAnalysis(CFAbstractAnalysis.java:91)
    [javac]   org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1225)
    [javac]   org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1143)
    [javac]   org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1487)
    [javac]   org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:260)
    [javac]   org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:291)
    [javac]   org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:159)
    [javac]   com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
    [javac]   com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
    [javac]   org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:85)
    [javac]   org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:967)
    [javac]   org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:494)
    [javac]   org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:182)
    [javac]   com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
    [javac]   com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
    [javac]   com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
    [javac]   com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
    [javac]   com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
    [javac]   com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
    [javac]   com.sun.tools.javac.main.Main.compile(Main.java:523)
    [javac]   com.sun.tools.javac.main.Main.compile(Main.java:381)
    [javac]   com.sun.tools.javac.main.Main.compile(Main.java:370)
    [javac]   com.sun.tools.javac.main.Main.compile(Main.java:361)
    [javac]   com.sun.tools.javac.Main.compile(Main.java:56)
    [javac]   sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [javac]   sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [javac]   sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]   java.lang.reflect.Method.invoke(Method.java:498)
    [javac]   org.apache.tools.ant.taskdefs.compilers.Javac13.execute(Javac13.java:57)
    [javac]   org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1395)
    [javac]   org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:1121)
    [javac]   org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    [javac]   sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [javac]   sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]   java.lang.reflect.Method.invoke(Method.java:498)
    [javac]   org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac]   org.apache.tools.ant.Task.perform(Task.java:348)
    [javac]   org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    [javac]   org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    [javac]   sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [javac]   sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]   java.lang.reflect.Method.invoke(Method.java:498)
    [javac]   org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac]   org.apache.tools.ant.Task.perform(Task.java:348)
    [javac]   org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:402)
    [javac]   org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    [javac]   sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [javac]   sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]   java.lang.reflect.Method.invoke(Method.java:498)
    [javac]   org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac]   org.apache.tools.ant.Task.perform(Task.java:348)
    [javac]   org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    [javac]   sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
    [javac]   sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]   java.lang.reflect.Method.invoke(Method.java:498)
    [javac]   org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac]   org.apache.tools.ant.Task.perform(Task.java:348)
    [javac]   net.sf.antcontrib.logic.TryCatchTask.execute(TryCatchTask.java:206)
    [javac]   org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    [javac]   sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [javac]   sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]   java.lang.reflect.Method.invoke(Method.java:498)
    [javac]   org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac]   org.apache.tools.ant.Task.perform(Task.java:348)
    [javac]   org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    [javac]   net.sf.antcontrib.logic.IfTask.execute(IfTask.java:217)
    [javac]   sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [javac]   sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [javac]   sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]   java.lang.reflect.Method.invoke(Method.java:498)
    [javac]   org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac]   org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
    [javac]   org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    [javac]   sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [javac]   sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]   java.lang.reflect.Method.invoke(Method.java:498)
    [javac]   org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac]   org.apache.tools.ant.Task.perform(Task.java:348)
    [javac]   org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    [javac]   net.sf.antcontrib.logic.IfTask.execute(IfTask.java:217)
    [javac]   sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [javac]   sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [javac]   sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]   java.lang.reflect.Method.invoke(Method.java:498)
    [javac]   org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac]   org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
    [javac]   org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    [javac]   sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [javac]   sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]   java.lang.reflect.Method.invoke(Method.java:498)
    [javac]   org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac]   org.apache.tools.ant.Task.perform(Task.java:348)
    [javac]   org.apache.tools.ant.Target.execute(Target.java:435)
    [javac]   org.apache.tools.ant.Target.performTasks(Target.java:456)
    [javac]   org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
    [javac]   org.apache.tools.ant.Project.executeTarget(Project.java:1376)
    [javac]   org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    [javac]   org.apache.tools.ant.Project.executeTargets(Project.java:1260)
    [javac]   org.apache.tools.ant.Main.runBuild(Main.java:857)
    [javac]   org.apache.tools.ant.Main.startAnt(Main.java:236)
    [javac]   org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
    [javac]   org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)

**Comment by wmdietl** [comment]
Sorry, I can't reproduce the issue.
In Test.java I added an import for java.util.HashMap.
I then tried multiple combinations of possible file orders and none crashed.
I tried the Nullness and Regex Checkers.

Can you give more complete instructions, including one of the distributed type systems?

**Comment by shashiranjan** [comment]
Hi Werner, 

I tried Checker Framework Live Demo page to test the code. Here is the link of live demo of code which fails.

[Checker framework live demo for asSuperType error](http://eisop.uwaterloo.ca/live/#mode=display&code=import+org.checkerframework.checker.nullness.qual.Nullable%3B%0Aimport+java.util.HashMap%3B%0Aimport+java.util.Map%3B%0A%0Aclass+Abc+%7B%0A++++public+Abc()+%7B%0A++++%7D%0A%7D%0A%0Aclass+Test+extends+Test2+%7B%0A%0A++++public+Test()+%7B%0A++++++++super(new+HashMap%3C%3E())%3B%0A++++%7D%0A%7D%0A%0Aabstract+class+Test2%3CT+extends+String%3E%7B%0A++++Map%3CAbc,+String%3E+abcMap%3B%0A%0A++++public+Test2(final+Map%3CAbc,+String%3E+abcMap)+%7B%0A++++++++this.abcMap+%3D+abcMap%3B%0A++++%7D%0A%7D&typeSystem=nullness)


Thanks,
Shashi

**Comment by wmdietl** [comment]
Perfect, thanks! I've minimized it further to

```java
import java.util.List;
import java.util.LinkedList;

class Super<T> {
    Super(List<Integer> p) {
    }
}

class Sub extends Super {
    Sub() {
        super(new LinkedList<>());
    }
}
```

Do note that the example `uses unchecked or unsafe operations`, in particular the raw type as supertype.
I'll see whether we can work around this.

**Comment by wmdietl** [comment]
Thanks again for the report! This issue should be fixed in master.
Please let me know if you're still running into this or file a new issue for other cases.
