### ISSUE TITLE
getExplicitAnnotations() method in the AnnotatedTypeMirror class doesn't return expected result.

### ISSUE THREAD

**Issue by t-rasmud** [typetools/checker-framework#2324]
Consider the following test case:

```
import org.checkerframework.checker.tainting.qual.*;

public class ExplicitAnnotationsIssue {
    void test() {
        Object x = new @Untainted Object();
    }
}
```
I want to get the explicit annotations on the `newClassTree` type which is `new @Untainted Object()` in the above example. I call the method `getExplicitAnnotations()` and print its size. See the diff [here](https://github.com/typetools/checker-framework/compare/master...t-rasmud:getExplicitAnnotationsIssue#diff-b997fe0effda8ef8635e7396f1861e64R2319).

I ran the tainting checker with the command: `javac -processor tainting ExplicitAnnotationsIssue.java`
I expected that the print statement would print `Explicit Annotations for new @Untainted() Object() : 1`. Instead, I get the following output:
```
Explicit Annotations for new @Untainted() Object() : 0
Explicit Annotations for new @Untainted() Object() : 0
Explicit Annotations for new @Untainted() Object() : 0
```

**Comment by mernst** [comment]
We could investigate whether the Java 9 compiler does a better job of retaining these annotations.
