### ISSUE TITLE
Updating Intellij Instruction to quickly apply Google Coding Style

### ISSUE THREAD

**Issue by the1derer** [typetools/checker-framework#2343]
While learning about Bazel tool I got to know a **super easy method to apply and adhere to Google Coding Style** and as Checker Framework also recommends using Google's Code Style I think it would help if we **include this in Checker Framework Manual**.
Guide Present at
**See only last step at**
[Steps to apply Google Java Code Style in IntelliJ](https://www.bazel.build/contributing.html#creating-an-intellij-project)

**Comment by mernst** [comment]
Thanks for the tip.  The authors of google-java-format give [instructions for configuring your IDE](https://github.com/google/google-java-format#using-the-formatter).  What is your reason for wanting to link to different instructions?

**Comment by the1derer** [comment]
Sorry, I didn't know that they provide formatter [instruction for configuring IDE](https://github.com/google/google-java-format#using-the-formatter) themselves as there is no mention for the same in [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html)
i am closing this issue.
Thanks for helping.

**Comment by the1derer** [comment]
[nstruction for config](url)

**Comment by mernst** [comment]
The style guide gives the rules, but doesn't dictate how to enforce them.
You are right that it might be nice for the style guide to give such a pointer somewhere, maybe at the very end.

**Comment by the1derer** [comment]
So, Should I make PR for doing this in Checker Framwork manual?

**Comment by the1derer** [comment]
> The style guide gives the rules, but doesn't dictate how to enforce them.
> You are right that it might be nice for the style guide to give such a pointer somewhere, maybe at the very end.

So, Should I make PR for doing this in the Checker Framework manual?

**Comment by mernst** [comment]
I already updated it.

**Comment by the1derer** [comment]
Thanks
