### ISSUE TITLE
Invalid conditional.type.incompatible error 

### ISSUE THREAD

**Issue by Kakarot-SSJ4** [typetools/checker-framework#2345]
Consider the following code:
`import java.io.IOException;
import java.io.Reader;

import org.checkerframework.checker.index.qual.*;

class conderr extends Reader{
public Reader abc;
public conderr(Reader xyz){
	this.abc = xyz;
}
public void close() throws IOException {
	abc.close();
}
public int read( final char[] cbuf, final @NonNegative int off, final int len ) throws IOException { // offset value has to be non negative
        int c;
        for (@NonNegative int i = 0; i < len; i++ ) {
            c = super.read();
            if ( c == -1 ) {
                return i == 0 ? -1 : i;
            }
        }
        return len;
    }
}`
Type in the terminal: javac -processor org.checkerframework.checker.index.IndexChecker conderr.java
Output:
conderr.java:14: error: [override.return.invalid] Incompatible return type.
public int read( final char[] cbuf, final @NonNegative int off, final int len ) throws IOException { // offset value has to be non negative
       ^
  Method
    @LowerBoundUnknown int read(@LowerBoundUnknown conderr this, @LowerBoundUnknown char @LowerBoundUnknown [] p0, @NonNegative int p1, @LowerBoundUnknown int p2) throws @LowerBoundUnknown IOException in conderr
  cannot override
    @GTENegativeOne int read(@LowerBoundUnknown Reader this, @LowerBoundUnknown char @LowerBoundUnknown [] p0, @NonNegative int p1, @NonNegative int p2) throws @LowerBoundUnknown IOException in java.io.Reader
  found   : @LowerBoundUnknown int
  required: @GTENegativeOne int
conderr.java:14: error: [override.return.invalid] Incompatible return type.
public int read( final char[] cbuf, final @NonNegative int off, final int len ) throws IOException { // offset value has to be non negative
       ^
  Method
    @UpperBoundUnknown int read(@UpperBoundUnknown conderr this, @UpperBoundUnknown char @UpperBoundUnknown [] p0, @UpperBoundUnknown int p1, @UpperBoundUnknown int p2) throws @UpperBoundUnknown IOException in conderr
  cannot override
    @LTEqLengthOf("#1") int read(@UpperBoundUnknown Reader this, @UpperBoundUnknown char @UpperBoundUnknown [] p0, @LTEqLengthOf("#1") int p1, @LTEqLengthOf("#1") int p2) throws @UpperBoundUnknown IOException in java.io.Reader
  found   : @UpperBoundUnknown int
  required: @LTEqLengthOf("#1") int
**conderr.java:19: error: [conditional.type.incompatible] incompatible types in conditional expression.
                return i == 0 ? -1 : i;
                                     ^
  found   : @IntRangeFromNonNegative int
  required: @IntVal(-1) int**
3 errors

Notice the last error. There is no need for i to be annotated with @IntVal(-1), it can take any non negative integral value. I think it is a bug.
@kelloggm

**Comment by kelloggm** [comment]
Thanks for reporting. This bug report is very difficult to read. Here are a few comments on why:
- your code example is not minimized: it issues errors other than the one you're reporting. You should try to remove everything but the part that issues the error.
- the code isn't formatted properly. Try surrounding code blocks with "```" on GitHub to get proper formatting.
- when writing annotations, please surround them with "\`" so that users with those names are not notified (we had an issue once where we accidentally kept pinging a user named `@IntRange` for instance, and we'd like to avoid that going forward).

Here is a minimized test case:
```java
// test case for https://github.com/typetools/checker-framework/issues/2345
class IndexConditionalReport {

    int c;
    
    public int getI(int len) {
	for ( int i = 0; i < len; i++ ) {
            c = read();
            if ( c == -1 ) {
                return i == 0 ? -1 : i; // unexpected error issued here
            }
	}
	return -1;
    }
    
    private int read() { return 0; }
}
```

I can confirm that I can reproduce the bug, and I believe it to be a false positive caused by the Constant Value Checker.

@Kakarot-SSJ4, would you like to investigate it? If so, I'm happy to help you to do so. If not, I can take a look myself.

**Comment by Kakarot-SSJ4** [comment]
Yes, I'd like to try to investigate this bug as my first bug, can you tell me where to start or which files to target?

**Comment by kelloggm** [comment]
The unexpected error is being issued by the Constant Value Checker, so I would start by investigating it. My usual process for finding an unexpected error, though, is to trace it backwards: start with the code that actually issues the error (which you can find by searching the codebase for the error code, which in this case is "conditional.type.incompatible") and try to understand what it does and why. Once you have an idea of what the error means, look to the implementation of the Value Checker. If I had to guess, the most likely places for this error to be generated are `ValueAnnotatedTypeFactory` and `ValueTransfer`, which implement most of the Value Checker's logic.
