### ISSUE TITLE
class file for java.util.regex.Pattern$HorizWS not found

### ISSUE THREAD

**Issue by Ambeco** [typetools/checker-framework#2375]
When I compile my Android Studio project with gradle (gradlew build :androidui:compileDebugJavaWithJavac), one of my many modules consistently fails with the message:
error: SourceChecker.typeProcessingStart: unexpected Throwable (CompletionFailure); message: class file for java.util.regex.Pattern$HorizWS not found
  Exception: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.util.regex.Pattern$HorizWS not found; no stack trace available.

That module's gradle file is here: https://justpaste.it/6a4mv
The androidchecker.gradle file is here: https://justpaste.it/1rrtf

I've been running into this for a few days, but am stumped, I can't find similar error messages on the web, nor can I quite track down in your code where this is coming from, or figure out why the class can't load. How come the 'unexpected Throwable' codepath doesn't preserve the original callstack?

This continues to occur even though my module no longer has any Java files inside, only Android resources.

**Comment by aagarwal1012** [comment]
@Ambeco, can you tell which `Android Studio version` and `Gradle plugin version` you are using?
Recently, I had worked with Android Studio version `3.3` and Gradle plugin version `4.10.1` and added checker framework dependency for an android library according to instructions provided in the [manual](https://checkerframework.org/manual/#android-gradle) and my module's Gradle file is below:
```java
apply plugin: 'com.android.library'

android {
    compileSdkVersion 26



    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"



    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        checkTypes {
            javaCompileOptions.annotationProcessorOptions.
                    classNames.add("org.checkerframework.checker.nullness.NullnessChecker")
            // You can pass options like so:
            // javaCompileOptions.annotationProcessorOptions.arguments.put("warns", "")
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}

configurations {
    checkerFrameworkAnnotatedJDK {
        description = 'a copy of JDK classes with Checker Framework type qualifers inserted'
    }
}


configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-annotations:23.1.1'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    ext.checkerFrameworkVersion = '2.7.0'
    implementation "org.checkerframework:checker-qual:${checkerFrameworkVersion}"
    annotationProcessor "org.checkerframework:checker:${checkerFrameworkVersion}"
    checkerFrameworkAnnotatedJDK "org.checkerframework:jdk8:${checkerFrameworkVersion}"
}

gradle.projectsEvaluated {
    tasks.withType(JavaCompile).all { compile ->
        if (compile.name.contains("checkTypes")) {
            compile.options.compilerArgs += [
                    "-Xbootclasspath/p:${configurations.checkerFrameworkAnnotatedJDK.asPath}"
            ]
        }
    }
}
```
I had **only** modified the `module's Gradle file`. You can try this if you want.

**Comment by Ambeco** [comment]
Android Studio 3.3.2, gradle version 4.10.1.

With some testing, I discovered that if I comment out the -Xbootclasspath line, then the code compiles and the null checker appears to be catching errors, but produces a warning:

You do not seem to be using the distributed annotated JDK.  To fix the problem, supply javac an argument like:  -Xbootclasspath/p:.../checker/dist/ .  Currently using: jdk8.jar

So that's related.  I'll experiment with the sample gradle file that aagarwal1012 posted.

**Comment by mernst** [comment]
There is a [discussion in the manual](https://checkerframework.org/manual/#common-problems-running) that starts:

> A “class file for … not found” error, especially for an inner class in the JDK, is probably due to a JDK version mismatch.

Could you pleas try its suggestions and let us know the result?

Thanks.

**Comment by mernst** [comment]
I'm closing this because we didn't hear back with more details or with an attempt to follow the instructions.  From the class name which appears only in JDK 9, the original poster was probably using JDK9.

If someone has more information, we can re-open this.
