### ISSUE TITLE
Assigment to a nullable with monotonic non null

### ISSUE THREAD

**Issue by vikasdo** [typetools/checker-framework#2410]
Every possibly-nullable assignment to a @MonotonicNonNull field is prohibited.
However, such an assignment should be permitted, as the first assignment in a constructor.
For example, the Nullness Checker currently rejects the below code, but it should be permitted
so I have changed
public class InitializeMonotonicNonNull {
  @MonotonicNonNull Object f;
  InitializeMonotonicNonNull( @Nullable Object a) {
     
a=this.f;
     
  }
 
}
How the checker can pass it.
my link:http://eisop.uwaterloo.ca/live/#mode=display&code=import+org.checkerframework.checker.nullness.qual.Nullable%3B%0D%0Aimport+org.checkerframework.checker.nullness.qual.MonotonicNonNull%3B%0D%0Aimport+org.checkerframework.checker.nullness.qual.NonNull%3B%0D%0Aimport+java.io.*%3B%0D%0A%0D%0Apublic+class+InitializeMonotonicNonNull+%7B%0D%0A%0D%0A++%40MonotonicNonNull+Object+f%3B%0D%0A%0D%0A++InitializeMonotonicNonNull(+%40Nullable+Object+a)+%7B%0D%0A+++++%0D%0Aa%3Dthis.f%3B%0D%0A%0D%0A+++++%0D%0A++%7D%0D%0A+%0D%0A%7D&typeSystem=nullness

**Comment by aagarwal1012** [comment]
@vikasdo, I think you should really need to refer to the discussion [https://groups.google.com/forum/#!topic/checker-framework-gsoc/XgDkBUkNhhQ](https://groups.google.com/forum/#!topic/checker-framework-gsoc/XgDkBUkNhhQ).

**Comment by smillst** [comment]
This is a verbatim duplicate of https://github.com/typetools/checker-framework/issues/2215.
