### ISSUE TITLE
local String constant considered @Untained by default, but one from different class is @Tainted by default ?

### ISSUE THREAD

**Issue by shuehner** [typetools/checker-framework#2421]
Using TaintingChecker (i.e. latest 2.8.0) by default it considers local String constant as @Untainted but referencing a String constant from different class as @Tainted.

See those 2 gists for compilable testcase:
https://gist.github.com/shuehner/7ea61522e39e55ebaa22acf4bf80ad57
https://gist.github.com/shuehner/6ce2e26705fbcf35ea25c1e0affe537c

Output:
[jsr308.javac]   found   : @Tainted Object
[jsr308.javac]   required: @Tainted SHUTest1
[jsr308.javac] /home/huehner/ob/branches/pi_checker_pg/src/SHUTest2.java:9: error: [argument.type.incompatible] incompatible types in argument.
[jsr308.javac]          test(SHUTest3.remoteConstant);
[jsr308.javac]                       ^
[jsr308.javac]   found   : @Tainted String
[jsr308.javac]   required: @Untainted String
[jsr308.javac] /home/huehner/ob/branches/pi_checker_pg/src/SHUTest2.java:10: error: [argument.type.incompatible] incompatible types in argument.
[jsr308.javac]          test(localConstant + SHUTest3.remoteConstant);
[jsr308.javac]                             ^
[jsr308.javac]   found   : @Tainted String
[jsr308.javac]   required: @Untainted String

Expected behavior is that 'public static final String name = "someConstantValue" is treated by default as @Untainted similar to a locally defined String.

That makes it quite harder to use as it forces to annotate auto-generated code having lots of constant values we use in our project meaning to modify code-generator + pull in checker dependency into our sources.

**Comment by wmdietl** [comment]
Please see the discussion at https://checkerframework.org/manual/#faq-infer-fields
The Checker Framework cannot determine whether a field in a different compilation unit was initialized with a constant.

**Comment by mernst** [comment]
I'm going to close this since I think the manual section answers the question.
If you have other questions or suggestions, please let us know.
