### ISSUE TITLE
Unexpected exception: "class file for sun.util.logging.PlatformLogger not found"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [typetools/checker-framework#244]
```
Running the nullness checker on the attached file will produce this error. The 
exact command I used was:

~/jsr308/checker-framework-dff/checkers/binary/javac -processor 
checkers.nullness.NullnessChecker CPanel.java 

Do I need to put something else on the classpath? This is not the only 
occurrence of this error I have right now.
```

Original issue reported on code.google.com by `alexloh@google.com` on 19 Aug 2013 at 6:14

Attachments:
- [CPanel.java](https://storage.googleapis.com/google-code-attachments/checker-framework/issue-244/comment-0/CPanel.java)

**Comment by jpschewe** [comment]
This appears to be showing up again, see typetools/jdk#86 for the test failures.
