### ISSUE TITLE
IndexChecker is unsound in methods that mutate one parameter

### ISSUE THREAD

**Issue by Maxi17** [typetools/checker-framework#2447]
Consider the following code:

```
import org.checkerframework.checker.index.qual.NonNegative;
import org.checkerframework.common.value.qual.ArrayLen;
import org.checkerframework.common.value.qual.IntRange;

public class Testing {
    public static void callingMethod() {
        @IntRange(from = 0, to = 3) int[] numbers = new int[10];
        testingArraysFill(numbers, 4); // No error here !
        for (int i = 0, len = numbers.length; i < len; i++)
            numbers[i] = 4; // Error here

        @NonNegative int number = 0;
        testingNonNegative(number); // No error here !
        number = -1; // Error here

        int @ArrayLen(10) [] array = new int[10];
        testExpandingArray(array); // No error here !
        array = new int[11]; // Error here
    }

    public static void testingArraysFill(int[] a, int val) {
        for (int i = 0, len = a.length; i < len; i++)
            a[i] = val;
    }

    public static void testingNonNegative(int value) {
        value = -1;
    }

    public static void testExpandingArray(int[] array) {
        array = new int[11];
    }
}
```
Run javac -processor index Testing.java.
The checker will issue 3 errors:

```
Error:(10, 26) java: [assignment.type.incompatible] incompatible types in assignment.
  found   : @IntVal(4) int
  required: @IntRange(from=0, to=3) int
```

```
Error:(14, 18) java: [assignment.type.incompatible] incompatible types in assignment.
  found   : @GTENegativeOne int
  required: @NonNegative int
```

```
Error:(18, 17) java: [assignment.type.incompatible] incompatible types in assignment.
  found   : @UnknownVal int @ArrayLen(11) []
  required: @UnknownVal int @ArrayLen(10) []
```

It looks like the checker is unsound when a method that mutates an annotated parameter is called.

**Comment by wmdietl** [comment]
Could this be related to covariant arrays, which the Checker Framework unsoundly allows by default?
https://checkerframework.org/manual/#invariant-arrays

What happens when you invoke the compiler with `-AinvariantArrays`?
I would assume that you would then also get an error about the `testingNonNegative(number)` invocation.

Method `testExpandingArray` is just re-assigning a parameter. That has no impact on the array in the caller's context. This is no issue.

**Comment by Maxi17** [comment]
Yes, invoking the compiler with `-AinvariantArrays` issues the expected error on this call: `testingArraysFill(numbers, 4);`

The error on `testingNonNegative(number)` is not issued with `-AinvariantArrays`.

**Comment by wmdietl** [comment]
Why do you expect an error for `testingNonNegative(number)`?
Primitives are copied by value. The implementation only sets the value visible within that method to -1, which is within the declared parameter range.
So similarly to `testExpandingArray` I don't see a problem here, as these calls have no effect on the callers.

**Comment by Maxi17** [comment]
I think I was a bit confused. The method call `testingNonNegative(number)` is not expected to issue any error. The third and fourth methods in my test case were flawed. But you pointed out:

> What happens when you invoke the compiler with -AinvariantArrays?
> I would assume that you would then also get an error about the testingNonNegative(number) invocation.

This made me unsure. Now it is clear. Thank you for the explanation.

**Comment by wmdietl** [comment]
Ah, sorry, I mixed up the different test cases.
I think all issues are clarified now. Please re-open if I missed an action item.
Thanks for reporting these.
