### ISSUE TITLE
Index Checker does not infer length properties attained by Array.getLength() 

### ISSUE THREAD

**Issue by Kakarot-SSJ4** [typetools/checker-framework#2452]
Consider the following code:
```
import java.lang.reflect.Array;
class checkerr {
    public Object xyz(Object[] a) {
        if (Array.getLength(a) > 0)
            return Array.get(a, 0);
        else
            return "abc";
    }
}
```
Run it by typing in the terminal:
javac -processor org.checkerframework.checker.index.IndexChecker checkerr.java

Output:
```
checkerr.java:5: error: [argument.type.incompatible] incompatible types in argument.
            return Array.get(a, 0);
                                ^
  found   : @UpperBoundUnknown int
  required: @LTLengthOf(value="a", offset={}) int
1 error
```

Now if we replace `if (Array.getLength(a) > 0)` by `if (a.length > 0)`, the code runs just fine.
The checker should infer the same properties as `a.length` by `Array.getLength()` as well.

**Comment by PalAditya** [comment]
Hi, this issue looks interesting. Can I have a go at it, please?

**Comment by kelloggm** [comment]
Pull requests are always welcome :)

We're happy to answer specific questions if you run into trouble.
