### ISSUE TITLE
Some source code missing from the 2.8.0 source jar

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#2462]
The source jar on Maven Central for release 2.8.0 (https://repo1.maven.org/maven2/org/checkerframework/checker/2.8.0/checker-2.8.0-sources.jar) is missing source for some classes.  E.g., there is no code for `org.checkerframework.common.basetype.BaseAnnotatedTypeFactory`.  This complicates debugging of dependent projects, source browsing, etc.  It seems that only the code under `org.checkerframework.checker.*` is being included.

**Comment by smillst** [comment]
Thanks for the report!  I'll fix this for the May release.
