### ISSUE TITLE
CFTreeBuilder doesn't handle TypeKind.INTERSECTION

### ISSUE THREAD

**Issue by kenzierocks** [typetools/checker-framework#2480]
CFTreeBuilder throws (with assertions enabled) an error trying to process an intersection type: https://gist.github.com/kenzierocks/8fc44d45c17e7b453567315a96072a6f

Reproducible test code: https://gist.github.com/kenzierocks/c56f1cb50f3d84194e9b6f78f1c06c00

**Comment by wmdietl** [comment]
Thanks for the bug report!
For easier reference, a slightly minimized version is:

```java
import java.util.List;

abstract class Error {
    void testCase() {
        for (Class<?> wrapperType : of(
            Character.class, Boolean.class
        )) {}
    }

    abstract <E> List<E> of(E... e1);
}
```

**Comment by wmdietl** [comment]
Fixed by https://github.com/typetools/checker-framework/commit/fc7b9a82590f5da8a2eb6c5442509b647b37fe25
