### ISSUE TITLE
@Present annotion on java.util.Optional orElseThrow receiver

### ISSUE THREAD

**Issue by rkraneis** [typetools/checker-framework#2537]
While introducing OptionalChecker into our code base I stumbled upon an exception I couldn't make too much sense of:
```java
[optional:method.invocation.invalid] call to <X>orElseThrow(java.util.function.Supplier<? extends X>) not allowed on the given receiver.
  found   : @MaybePresent Optional
  required: @Present Optional
```
This indicates, that I may only call `orElseThrow` on a non-empty `Optional` -- which does not make too much sense to me.

Digging into this I started to compare `orElseThrow` with the two similiar methods `orElse` and `orElseGet`, both of which do not require the `Optional` to be present:
```java
Optional.empty().orElse(new Object()); // fine
Optional.empty().orElseGet(() -> new Object()); // also fine
Optional.empty().orElseThrow(() -> new Exception()); // not fine
```

The signatures are:
https://github.com/typetools/checker-framework/blob/2466e7f4ca303d01c11b155fffdfb7c6dc1876ba/checker/jdk/optional/src/java/util/Optional.java#L256
https://github.com/typetools/checker-framework/blob/2466e7f4ca303d01c11b155fffdfb7c6dc1876ba/checker/jdk/optional/src/java/util/Optional.java#L270
https://github.com/typetools/checker-framework/blob/2466e7f4ca303d01c11b155fffdfb7c6dc1876ba/checker/jdk/optional/src/java/util/Optional.java#L290

The initial report on #1959 seems to be related.

**Comment by wmdietl** [comment]
The motivation for this is that `orElseThrow` on an empty `Optional` would throw an exception.
We want to prevent any exceptions from mis-uses of `Optional` - both the `NoSuchElementException` from `get` and the user-defined exception from `orElseThrow`.
On the other hand, both `orElse` and `orElseGet` are safe to use on any `Optional`, as they provide default objects.

If you are fine with an exception from a particular `orElseThrow` you can suppress the warning.
One future extension we could plan: if the `orElseThrow` occurs within a try-block for that exception, we allow the call. Would that solve your particular use?

**Comment by mernst** [comment]
This is explained in the manual in section [Annotations indicate non-exceptional behavior](https://checkerframework.org/manual/#annotate-normal-behavior).

**Comment by rkraneis** [comment]
Thanks for the explanation. Although I think that explicitly throwing user defined exceptions should be allowed (as `orElseThrow` is quite more verbose/indicative of consequences than e.g. `get`, which probably should have been called `getIfPresentOrThrowNoSuchElementException` ...). Especially in combination with Streams it is quite annoying to get the suppression in the smallest possible scope (actually our case here):
```
return ...
    .stream()
    ...
    .findFirst()
    .orElseThrow(() -> new InconsistentDatabaseException());
```
turns into something like
```
Optional<Foo> maybeFoo = ...
    .stream()
    ...
    .findFirst()
    @SuppressWarnings("optional:method.invocation.invalid")
Foo foo = maybeFoo.orElseThrow(() -> new InconsistentDatabaseException());
return foo;
```
Foregoing `Optional` in favor of `@Nullable` and `Opt` does not really make much sense in this case (Streams). I also wonder why `Opt.orElseThrow` actually does accept `@Nullable` ...
`Opt.orElseThrow(null, () -> new RuntimeException())` is completely legal, which I would not expect for symmetry reasons.

**Comment by rkraneis** [comment]
To also answer your question @wmdietl , we actually _do_ want to throw an exception in this special case. So allowing to throw an exception here to just catch it in an outer block would not solve our problem (and I'd actually regard it as a code smell). In cases where we care about the exception we actually tend to use `Either<Foo, Exception>` (from e.g. the vavr library).

**Comment by mernst** [comment]
René-

It sounds like you are in agreement with the semantics.  Can we close this issue?

You brought up several excellent points:

> `get`, which probably should have been called `getIfPresentOrThrowNoSuchElementException` ...). 

Agreed.  :-)  The designers of Optional told me that they regret not giving `get` a more forbidding name.

> Especially in combination with Streams it is quite annoying to get the suppression in the smallest possible scope (actually our case here):

I agree.  This is a general problem with "fluent" APIs.  I don't have a good solution for this.  In some cases static verification, such as with the Nullness Checker, may be able to eliminate the need for the error checking.  This is not always the case, however.

> Foregoing `Optional` in favor of `@Nullable` and `Opt` does not really make much sense in this case (Streams).

I agree, because `Optional` is already built into those APIs.  `Opt` is an alternative when designing an API rather than integrating with existing code that uses `Optional`.

> I also wonder why `Opt.orElseThrow` actually does accept `@Nullable` ...
> `Opt.orElseThrow(null, () -> new RuntimeException())` is completely legal, which I would not expect for symmetry reasons.

Good point.  It's a bug that we overlooked this.  I have changed it, which will appear in the next release.  Thanks for pointing that out.

**Comment by rkraneis** [comment]
Yes, I'd personally see the explicit nature of the method name as sufficient, but that's just a point of view :-). It might be a good idea to mention this explicitly in the documentation for Option Checker though, as it only mentions to avoid `get` and `isPresent`.
Thank's for your time and this excellent tool!
