### ISSUE TITLE
Cast from char to int loses IntRange information

### ISSUE THREAD

**Issue by mernst** [typetools/checker-framework#2540]
When a char is cast to an int (including via arithmetic promotion, which applies to the arguments of operators such as <<), the Index Checker should keep track of the value's bounds.  That is not currently the case.  (Or is this a problem with the Constant Value Checker?)

Here is a test case, which is commetted to the repository as `checker/tests/index/CharToIntCast.java`.

```
import org.checkerframework.common.value.qual.IntRange;

public class CharToIntCast {

    public static void charRange(char c) {
        @IntRange(from = 0, to = Character.MAX_VALUE) int i = c;
    }

    public static void charShift(char c) {
        char c2 = (char) (c >> 4);
    }

    public static void rangeShiftOk(@IntRange(from = 0, to = Character.MAX_VALUE) int i) {
        char c2 = (char) (i >> 4);
    }
}
```

The code should typecheck, but currently the first two methods do not type-check (the last one does).

This comes up in Guava.

**Comment by kelloggm** [comment]
This is likely related to https://github.com/kelloggm/checker-framework/issues/192, which caused quite a bit of trouble when we tried to implement it before.
