### ISSUE TITLE
Missing document about message keys.

### ISSUE THREAD

**Issue by xingweitian** [typetools/checker-framework#2585]
In the last paragraph of [31.5  The checker class: Compiler interface](https://checkerframework.org/manual/#creating-compiler-interface) in the manual:

> A checker can customize the default error messages through a Properties-loadable text file named messages.properties that appears in the same directory as the checker class. The property file keys are the strings passed to report (like type.incompatible) and the values are the strings to be printed ("cannot assign ..."). The messages.properties file only need to mention the new messages that the checker defines. It is also allowed to override messages defined in superclasses, but this is rarely needed. For more details about message keys, see Section 27.1.3.

It is said that we can find more details about message keys in section 27.1.3. But, 27.1.3 actually is [Good practices when suppressing warnings](https://checkerframework.org/manual/#suppresswarnings-best-practices).

**Comment by mernst** [comment]
Thank you for pointing that out.  I have tweaked the message (in commit a7e11e1).  Please let me know if that improves the text, or if you have a further suggestion.

**Comment by xingweitian** [comment]
Thanks for your reply, I think it definitely improves the text, it is clearer now.
