### ISSUE TITLE
Type inference is too eager to use Constant Value Checker types

### ISSUE THREAD

**Issue by mernst** [typetools/checker-framework#2686]
Consider the following code.

```
import org.checkerframework.common.value.qual.UnknownVal;

public class MyTree<Value> {

    public static <V> MyTree<V> newTree(V value) {
        throw new Error("body doesn't matter");
    }

    public MyTree<Value> put(String newKey, Value newValue) {
        throw new Error("body doesn't matter");
    }

    public void client1() {
        // type-checking error
        MyTree<String> root2 = MyTree.newTree("constructorarg").put("key1", "value1");
    }

    public void client2() {
        // OK
        MyTree<String> root2 = MyTree.newTree((@UnknownVal String) "constructorarg").put("key1", "value1");
    }

    public void client3() {
        // OK
        MyTree<String> root2 = MyTree.<String>newTree((@UnknownVal String) "constructorarg").put("key1", "value1");
    }

}
```

You can typecheck it for the Constant Value checker by running

	${CHECKERFRAMEWORK}/checker/bin/javac -processor org.checkerframework.common.value.ValueChecker MyTree.java

Type-checking of client1 fails with the messages:

```
MyTree.java:15: error: [assignment.type.incompatible] incompatible types in assignment.
        MyTree<String> root2 = MyTree.newTree("constructorarg").put("key1", "value1");
                                                                   ^
  found   : @UnknownVal MyTree<@StringVal("constructorarg") String>
  required: @UnknownVal MyTree<@UnknownVal String>
MyTree.java:15: error: [argument.type.incompatible] incompatible types in argument.
        MyTree<String> root2 = MyTree.newTree("constructorarg").put("key1", "value1");
                                                                            ^
  found   : @StringVal("value1") String
  required: @StringVal("constructorarg") String
```

The problem is that in the call `MyTree.newTree("constructorarg")`, the Checker Framework infers a constant-value type for "constructorarg", and then instantiates the constructor with that constant-value type.

Methods `client2` and `client3` show how to solve the problem, but both of them require code changes to the user code.  Is there a way to solve the problem without code changes to the user code?  It would be acceptable to not use constant-value types anywhere that type inference occurs.

**Comment by mernst** [comment]
cc @smillst @wmdietl

**Comment by smillst** [comment]
I'll work on this when I get a chance.  In the meantime, some one else could write test cases for the  expected behavior.

**Comment by mernst** [comment]
I would like `client1` to pass type-checking.
I *think* the behavior could be that type refinement for the Value Checker is ignored, when doing generic type inference.  You might have a better take on that.
