### ISSUE TITLE
If variable is annotated with @SignedPositive then different operations showing different results

### ISSUE THREAD

**Issue by gokaco** [typetools/checker-framework#2703]
Consider the following code-

Input-
```
import org.checkerframework.checker.signedness.qual.*;
public class issue {
    void m1(int c) {
        @SignedPositive int a=2;
        a = a % c;
    	a = a << c;
        a = a >> c;
        a = a >>> c;
        a = a / c;
        a = a + c;
        a = a - c;
        a = a * c;
    	a = c;
    }
}
```
Command-
```
javac -processor signedness issue.java
```
Output-
```
issue.java:10: error: [assignment.type.incompatible] incompatible types in assignment.
    	a = a / c;
    	      ^
  found   : @Signed int
  required: @SignednessGlb int
issue.java:11: error: [assignment.type.incompatible] incompatible types in assignment.
    	a = a + c;
    	      ^
  found   : @Signed int
  required: @SignednessGlb int
issue.java:12: error: [assignment.type.incompatible] incompatible types in assignment.
    	a = a - c;
    	      ^
  found   : @Signed int
  required: @SignednessGlb int
issue.java:13: error: [assignment.type.incompatible] incompatible types in assignment.
    	a = a * c;
    	      ^
  found   : @Signed int
  required: @SignednessGlb int
issue.java:14: error: [assignment.type.incompatible] incompatible types in assignment.
    	a = c;
    	    ^
  found   : @Signed int
  required: @SignednessGlb int
5 errors
```
We should never write `@SignedPositive` in a program. But here It is showing us different results with different operations. It should produce an error for `%`,`<<`,`>>`,`>>>` too as in these operations too the LHS and RHS have conflicting annotations.

**Comment by mernst** [comment]
>         @SignedPositive int a=2;

Please make issues as simple as possible.
Is the constant `2` essential to the test case?  If not, then eliminate it.
If you do so, you will see that although the Signedness Checker does issue an error regarding `%` with the value `2`, it does issue an error regarding `%` with an arbitrary `@SignedPositive`:

```
  void m1(@SignedPositive int sp, int s) {
    sp = sp % s;
  }
```

> We should never write `@SignedPositive` in a program.

Why?

> It should produce an error for `%`,`<<`,`>>`,`>>>` too as in these operations too the LHS and RHS have conflicting annotations.

The types of the LHS and RHS are different, but please explain why this operation should be forbidden.
Give a concrete operation (on specific values) where it produces an incorrect result (that is, a bit pattern that is incorrectly interpreted due to its signedness type).
How do the [Prohibited operations](https://checkerframework.org/manual/#signedness-checker-prohibited-operations) and [Rationale](https://checkerframework.org/manual/#signedness-checker-rationale) sections need to change? 


For reference, here is a modified version of your test case that avoids gratuitous and confusing operations, and that isolates the operations into different methods:

```
import org.checkerframework.checker.signedness.qual.*;

public class issue {
    void m1(@SignedPositive int sp, int s) {
        sp = sp % s;
    }

    void m2(@SignedPositive int sp, int s) {
        sp = sp << s;
    }

    void m3(@SignedPositive int sp, int s) {
        sp = sp >> s;
    }

    void m4(@SignedPositive int sp, int s) {
        sp = sp >>> s;
    }

    void m5(@SignedPositive int sp, int s) {
        sp = sp / s;
    }

    void m6(@SignedPositive int sp, int s) {
        sp = sp + s;
    }

    void m7(@SignedPositive int sp, int s) {
        sp = sp - s;
    }

    void m8(@SignedPositive int sp, int s) {
        sp = sp * s;
    }

    void m9(@SignedPositive int sp, int s) {
        sp = s;
    }
}
```

Here is the output of running `javac -processor signedness issue.java`:

```
issue.java:5: error: [assignment.type.incompatible] incompatible types in assignment.
    sp = sp % s;
            ^
  found   : @Signed int
  required: @SignednessGlb int
issue.java:21: error: [assignment.type.incompatible] incompatible types in assignment.
    sp = sp / s;
            ^
  found   : @Signed int
  required: @SignednessGlb int
issue.java:25: error: [assignment.type.incompatible] incompatible types in assignment.
    sp = sp + s;
            ^
  found   : @Signed int
  required: @SignednessGlb int
issue.java:29: error: [assignment.type.incompatible] incompatible types in assignment.
    sp = sp - s;
            ^
  found   : @Signed int
  required: @SignednessGlb int
issue.java:33: error: [assignment.type.incompatible] incompatible types in assignment.
    sp = sp * s;
            ^
  found   : @Signed int
  required: @SignednessGlb int
issue.java:37: error: [assignment.type.incompatible] incompatible types in assignment.
    sp = s;
         ^
  found   : @Signed int
  required: @SignednessGlb int
6 errors
```

**Comment by gokaco** [comment]
> Is the constant `2` essential to the test case? If not, then eliminate it.
> Give a concrete operation (on specific values) where it produces an incorrect result (that is, a bit pattern that is incorrectly interpreted due to its signedness type).

I meant that if a `@SignedPositive` variable is initialised with a **positive value** it produces different
result for different operations.
> ```
>   void m1(@SignedPositive int sp, int s) {
>     sp = sp % s;
>   }
> ```

In your given test case, `sp` is not initialized with any positive value(at compile time we do not know the value of `sp`), therefore it is giving an error for `%`. It should behave the same when it gets initialized with a positive value.

>Why?

I meant that we should write it rarely. Instead, the programmer should use `@Signed` or `@Unsigned` to indicate how the programmer intends the value to be interpreted.

>The types of the LHS and RHS are different, but please explain why this operation should be forbidden.

These operations should be forbidden because in-
`a = a % b` If the dividend is interpreted as `@SignedPositive` and the divisor is interpreted as `@Signed` then the remainder we get should be interpreted as `@Signed`. So error should occur, which do occurs but not when we initialize it with a **positive value**.

`a = a >>> b` The result should be `@Unsigned` as it is unsigned right shift and cannot be interpreted as signed. So error should occur as LHS will be `@SignedPositive` and RHS will be `@Unsigned`.

`a = a >> b` The result should be `@Signed` as it is signed right shift and cannot be interpreted as unsigned. So error should occur as LHS will be `@SignedPositive` and RHS will be `@Signed`.

` a = a << b` If `a` is in signed positive range than it is not necessary that `a<<b` will also be in signed positive range.

**Comment by mernst** [comment]
I asked:

> Give a concrete operation (on specific values) where it produces an incorrect result (that is, a bit pattern that is incorrectly interpreted due to its signedness type).

but you did not do so.  Your text gives a circular justification:  "it cannot be interpreted as signed".

**Comment by gokaco** [comment]
> > Give a concrete operation (on specific values) where it produces an incorrect result (that is, a bit pattern that is incorrectly interpreted due to its signedness type).

For `>>>`, `>>` and `%` I tried to get specific values but I am not able to, but the `@IntRange` is behaving as if there must be a value. For `<<` I have specified a value where the error should occur.

Input-
```
import org.checkerframework.checker.signedness.qual.*;
import org.checkerframework.common.value.qual.*;

public class issue {
   static void m1(@SignedPositive int sp, @IntRange(from=0, to=Integer.MAX_VALUE) int sp2, int s) {
        sp = sp % s; //Error
        sp2 = sp2 % s; // No Error
    }

   static void m2(@SignedPositive int sp, int s) {
        sp = sp << s;
        sp = 1;
        s = 31;
        sp = sp << s; // sp = -2147483648 (Error should occur)
    }

    static void m3(@SignedPositive int sp, @IntRange(from=0, to=Integer.MAX_VALUE) int sp2, int s) {
        sp = sp >> s;// No Error
        sp2 =sp2 >> s; // Error
    }

   static void m4(@SignedPositive int sp, @IntRange(from=0, to=Integer.MAX_VALUE) int sp2, int s){
        sp = sp >>> s; // No error
        sp2 = sp2 >>> s; // Error
    }
}
```
Command-
```
javac -processor signedness issue.java
```
Output-
```
issue.java:6: error: [assignment.type.incompatible] incompatible types in assignment.
        sp = sp % s; //Error
                ^
  found   : @Signed int
  required: @SignednessGlb int
issue.java:19: error: [assignment.type.incompatible] incompatible types in assignment.
        sp2 =sp2 >> s; // Error
                 ^
  found   : @IntRange(from=-2147483648, to=2147483647) int
  required: @IntRange(from=0, to=2147483647) int
issue.java:24: error: [assignment.type.incompatible] incompatible types in assignment.
        sp2 = sp2 >>> s; // Error
                  ^
  found   : @IntRange(from=-2147483648, to=2147483647) int
  required: @IntRange(from=0, to=2147483647) int
3 errors
```

**Comment by mernst** [comment]
You gave code and output, but didn't say what you expected the code to do, where the Checker Framework is misbehaving, and your justification for that claim.  Can you please do so?
