### ISSUE TITLE
Disable dereference.of.nullable for Map

### ISSUE THREAD

**Issue by micheal-swiggs** [typetools/checker-framework#2718]
When I compile the following I am getting a `dereference.of.nullable`. We have this kind of code already I am wondering how I can disable these errors? I still want to get errors for other fields/methods that are `@Nullable`.

```
    public Map<String, Map<String, String>> populateMap() {
        Map<String, Map<String, String>> labels = new HashMap<>();
        HashMap<String, String> v = new HashMap<>();
        v.put("firstLabel", "something");
        labels.put("name", v);
        return labels;
    }
    
    public void runThis(){
        Map<String, Map<String, String>> labels = populateMap();
        Map<String, String> nameLabels = labels.get("name");
        String firstLabel = nameLabels.get("firstLabel"); // [dereference.of.nullable] dereference of possibly-null reference nameLabels
    }

```

**Comment by mernst** [comment]
There is a [chapter about Suppressing Warnings](https://checkerframework.org/manual/#suppressing-warnings) in the [Checker Framework Manual](https://checkerframework.org/manual/).  Have you tried any of those approaches?  Did they not work for you?

**Comment by micheal-swiggs** [comment]
I was able to suppress all `dereference.of.nullable` warnings but that is not what I want. This issue is about suppressing only the `dereference.of.nullable` warnings originating from `Map.get`. I also used `-AskipUses="java\.lang\.|java\.util\.|java\.util\.Map"` but that doesn't seem to work...

**Comment by mernst** [comment]
I think you are saying that you want to treat the return type of `Map.get` as `@NonNull`.
If so, you could do so in a [stub file](https://checkerframework.org/manual/#stub).

(Your code can also be made to type-check by writing [`@KeyFor`](https://checkerframework.org/manual/#map-key-qualifiers) qualifiers, but I presume you want to avoid those annotations.)

**Comment by micheal-swiggs** [comment]
Yes exactly - I want `Map.get` to be treated as `@NonNull`. 

I'll look at creating a stub file.
