### ISSUE TITLE
Pass-through method loses nullability information

### ISSUE THREAD

**Issue by cpovirk** [typetools/checker-framework#2719]
This permits a runtime `NullPointerException`. For example:

```java
import static java.util.Arrays.asList;

import java.util.List;
import org.checkerframework.checker.nullness.qual.Nullable;

class Foo {
  public static void main(String[] args) {
    List<Integer> iList = asList(0);
    List<@Nullable Integer> jList = asList((Integer) null);
    List<List<Integer>> both = passThrough(asList(iList, jList));
    System.out.println(both.get(1).get(0).intValue());
  }

  static <T> T passThrough(T object) {
    return object;
  }
}
```

```
$ checker/bin/javac -processor org.checkerframework.checker.nullness.NullnessChecker Foo.java && java Foo
Exception in thread "main" java.lang.NullPointerException
  at Foo.main(Foo.java:11)
```

Without the `passThrough` call, the Checker Framework detects the problem. I wildly speculate that the lost information has something to do with "regular javac" choosing to infer the argument type to be `List<List<Integer>>` when the correct nullness-aware inferred type would be `List<List<? extends [@Nullable] Integer>>`, which isn't merely "the same type with some nullness annotations" but a different type, thanks to the extra `? extends`. _Without_ the `passThrough` call (I continue to wildly speculate), the Checker Framework immediately tries to attach nullness annotations to `List<List<Integer>>` and fails because no configuration makes sense. _With_ the `passThrough` call, I assume that this gets masked somehow.

[Source file](https://github.com/typetools/checker-framework/files/3505963/Foo.java.txt) and [`-version -verbose -AprintAllQualifiers` output](https://github.com/typetools/checker-framework/files/3505935/err.txt) attached.

**Comment by mernst** [comment]
Thanks for the report!

Here is a slightly rewritten version of your example that I found easier to understand.
In this version, the problem is isolated to the method `createListOfLists`, which should not type-check.

```
import static java.util.Arrays.asList;

import java.util.List;
import org.checkerframework.checker.nullness.qual.Nullable;

class Issue2719 {
  public static void main(String[] args) {
    List<Integer> iList = asList(0);
    List<@Nullable Integer> jList = asList((Integer) null);
    List<List<Integer>> both = createListOfLists(iList, jList);
    System.out.println(both.get(1).get(0).intValue());
  }

  static List<List<Integer>> createListOfLists(
      List<Integer> listOfNonNull, List<@Nullable Integer> listOfNullable) {
    return passThrough(asList(listOfNonNull, listOfNullable));
  }

  static <T> T passThrough(T object) {
    return object;
  }
}
```

**Comment by wmdietl** [comment]
This is caused by #979 and the work-arounds we have to reduce false-positives.
If you pass `-AconservativeUninferredTypeArguments` the second example produces a total of 11 errors.
These false-negatives are unfortunately a side-effect of the #979 work-arounds.

**Comment by cpovirk** [comment]
A simpler code snippet showing presumably the same bug:

```java
import static java.util.Arrays.asList;

class Foo {
  public static void main(String[] args) {
    passThrough(asList((String) null)).get(0).length();
  }

  static <T> T passThrough(T object) {
    return object;
  }
}
```

**Comment by smillst** [comment]
I added this test case to `checker-framework/checker/tests/nullness/java8inference` so that we make sure it passes once #979 is fixed.
