### ISSUE TITLE
PurityChecker is run even though -AcheckPurityAnnotations is absent

### ISSUE THREAD

**Issue by Maxi17** [typetools/checker-framework#2744]
Running `checker/tests/all-systems/java8/memberref/Purity.java` using  the `IndexChecker` and without providing the `-AcheckPurityAnnotations` argument (something like this: `(cd CHECKER_FRAMEWORK && ./gradlew assemble) && CHECKER_FRAMEWORK/checker/bin/javac -processor org.checkerframework.checker.index.IndexChecker -implicit:class Purity.java`), the `PurityChecker` runs anyways and issues one error (the expected one, but seven times).

One way around this would be providing the `-AcheckPurityAnnotations` for some specific tests when running them in the build. (this justifies the errors, doesn't fix the problem)

@mernst

**Comment by mernst** [comment]
Closed in favor of #2582.  I will also tweak the documentation at https://checkerframework.org/manual/#purity-trusted to be more explicit about what is tested (that is, the meaning of `-AcheckPurityAnnotations`.
