### ISSUE TITLE
Further documentation updates for use of Error Prone javac with Checker Framework 2.11.0

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#2749]
After updating a custom checker to depend on Checker Framework 2.11.0, we get the following error at initialization when running tests:

```
java.lang.NoSuchFieldError: ANNOTATION_PROCESSOR_MODULE_PATH
	at com.sun.tools.javac.file.Locations.initHandlers(Locations.java:1976)
	at com.sun.tools.javac.file.Locations.<init>(Locations.java:145)
	at com.sun.tools.javac.file.BaseFileManager.createLocations(BaseFileManager.java:115)
	at com.sun.tools.javac.file.BaseFileManager.<init>(BaseFileManager.java:76)
	at com.sun.tools.javac.file.JavacFileManager.<init>(JavacFileManager.java:147)
	at com.sun.tools.javac.file.JavacFileManager.lambda$preRegister$0(JavacFileManager.java:139)
	at com.sun.tools.javac.util.Context.get(Context.java:150)
	at com.sun.tools.javac.util.Context.get(Context.java:187)
	at com.sun.tools.javac.main.Main.compile(Main.java:246)
	at com.sun.tools.javac.main.Main.compile(Main.java:162)
	at com.sun.tools.javac.Main.compile(Main.java:75)
	at com.sun.tools.javac.api.JavacTool.run(JavacTool.java:208)
	at org.checkerframework.framework.test.TestUtilities.<clinit>(TestUtilities.java:34)
	at org.checkerframework.framework.test.PerDirectorySuite.getParametersList(PerDirectorySuite.java:74)
	at org.checkerframework.framework.test.PerDirectorySuite.<init>(PerDirectorySuite.java:57)
```

Based on experience I think this means we need to stick the Error Prone javac in the bootclasspath when running tests.  I just wanted to check if this is documented anywhere.  If not, it probably should be, as this will confuse users.

**Comment by msridhar** [comment]
FYI @wmdietl

**Comment by wmdietl** [comment]
If you're running on a Java 8 JVM, you need to provide `-source 8 -target 8`.
As 2.11.0 now uses a Java 9 javac, it defaults to Java 9, which tries to initialize modules, which don't exist on a Java 8 JVM.

If you're using `CheckerMain` (like the provided scripts do), this happens automatically: https://github.com/typetools/checker-framework/blob/master/framework/src/main/java/org/checkerframework/framework/util/CheckerMain.java#L431

The instructions in https://checkerframework.org/manual/#external-tools should also indicate this. Please let me know which instructions need updating.

**Comment by msridhar** [comment]
Hi @wmdietl,

So I think the key change here is that whenever running Checker Framework 2.11 on a Java 8 JVM, Error Prone javac needs to be in the bootclasspath.  I can think of a few related issues with upgrading:

* For any custom checker living in a different repository, when updating to CF 2.11, the configuration for unit tests will need to be updated to put Error Prone javac in the bootclasspath.  E.g., see these changes for our checker: https://github.com/kelloggm/object-construction-checker/pull/104/files#diff-a53c2cc55fb35aa32d1ca85a6ec5da60 @kelloggm perhaps https://github.com/kelloggm/empty-checker needs to be updated?  I'm not sure if that repo is linked from the main CF documentation.
* Instructions that just pulled in Checker Framework or a custom checker via annotation processor dependencies will no longer work, like these: https://github.com/kelloggm/object-construction-checker#using-the-checker In our case we need to instruct users to always use the Checker Framework Gradle plugin to ensure Error Prone javac gets used.  Other build system instructions need to be updated accordingly.  I don't think these Buck instructions will work anymore: https://checkerframework.org/manual/#buck At a quick glance the other external tool documentation looks ok.
* In certain rare cases, `CheckerMain` is not a perfect substitute for `javac`; see e.g. https://github.com/typetools/checker-framework/issues/2715.  So there should probably be some instructions for people who were previously running CF by using JDK 8 `javac` and putting it in the processor path.

**Comment by wmdietl** [comment]
Thanks for the pointers! I'll go through these and the manual to see what updates are missing.
I think the "empty-checker" was superseded by https://github.com/typetools/templatefora-checker.

**Comment by msridhar** [comment]
Ah right, https://github.com/typetools/templatefora-checker needs to be updated.  I knew I was missing the right link 😄
