### ISSUE TITLE
Post-condition for Object.equals

### ISSUE THREAD

**Issue by wmdietl** [typetools/checker-framework#2793]
The following test:

```java
import org.checkerframework.checker.nullness.qual.*;
class YourClassNameHere {
  void foo(Object nn, @Nullable Object nbl) {
    if (nn.equals(nbl)) {
        nbl.toString();
    }
  }
}
```

produces a Nullness Checker error on `nbl.toString()`.

`java.lang.Object.equals` should have the postcondition `@EnsuresNonNullIf(result = true, expression = "#1")`.
This corresponds to the `For any non-null reference value x, x.equals(null) should return false.` in the specification https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#equals(java.lang.Object)

As the post-condition is inherited, this doesn't add additional burden on all the overrides of `equals`.

(Filing as an issue, b/c the annotated JDK is in transition...)

**Comment by mernst** [comment]
During the transition, you can make a fix in this repository at checker/jdk/nullness, and also in https://github.com/typetools/jdk.

Does this need to be written on every override of `Object.equals`?

**Comment by smillst** [comment]
> Does this need to be written on every override of `Object.equals`?

No, `@EnsuresNonNullIf` is an inherited annotation, meaning that overrides will be treated as if they were annotated with `@EnsuresNonNullIf`.

**Comment by wmdietl** [comment]
This apparently was already changed as part of https://github.com/typetools/checker-framework/commit/5be5d3b0d71b4a9049c64e1678ae2cf6d0f836e6 (even though that changeset added lots of redundant annotations on overrides.)

However, those changes are not reflected in typetools/jdk: https://github.com/typetools/jdk/blob/master/src/java.base/share/classes/java/lang/Object.java#L175 does not contain the post-condition.
@mernst Do you have the follow-up typetools/jdk PR mentioned in https://github.com/typetools/checker-framework/pull/2983#pullrequestreview-332910945
