### ISSUE TITLE
Please bundle license text and license clarifications to the release jar files

### ISSUE THREAD

**Issue by vlsi** [typetools/checker-framework#2798]
1) Please add `Bundle-License: MIT` manifest entry (where `MIT` is SPDX identifier, see https://osgi.org/specification/osgi.core/7.0.0/framework.module.html#framework.module-bundle-license ).

Well, current `pom.xml` do reference licenses, however, that reference is not exact.

For instance:

1.1)  `<artifactId>checker</artifactId>` references `<name>GNU General Public License, version 2 (GPL2), with the classpath exception</name>`.
Does that mean `GPL-2.0-only` or `GPL-2.0-or-later`?

1.2) `<artifactId>checker-qual</artifactId>` references `<url>http://opensource.org/licenses/MIT</url>`. It does provide a "feeling" on the nature of the license, but it is not enough for the consumers, as that link misses "copyright owner"

Adding explicit `Bundle-License` manifest entry would simplify automatic analysis.

2) Please add LICENSE and NOTICE files to the produced jar files (and probably to the source repository).
The thing is the license requires re-distributions to reproduce the copyright notice, however, it is really hard to do that in an automatic way, taking into account `checker-qual.jar` is often taken from Maven Central. The jar file misses `NOTICE` file, so it is really hard to reproduce the copyright notice and track it for all `checker-qual` upgrades.

The suggested file location is `META-INF/LICENSE.

PS The missing license has been discovered by https://github.com/vlsi/vlsi-release-plugins#license-gather-plugin when managing license dependencies for Apache JMeter.

**Comment by vlsi** [comment]
1) It is a bit strange that build script uses both `archiveFileName != "checker-source.jar"` and `archiveFileName.get().startsWith("checker-qual")`

Should the first be `archiveFileName.get() != ...` ?

2) I've tried building ce7cebbcac96bbd9125578daf8ab45be20e40f60 locally, and checker-qual/build/libs/checker-qual-2.11.1.jar (and other jars) seems to miss a license file. I guess the file is missing since you use `from('.')`, and you want something like `from("$rootDir/LICENSE.txt")`

3) The license file itself is complicated. Do you think you can create a license file dedicated to checker-qual.jar? The jar is used quite often (it contains annotations), and it is really sad there's no simple and understandable license for it.

4) Please include the license under META-INF folder rather than to the root of the jar. Including licenses to the root causes issues with shading/producing uberjars. The tools more-or-less know how to process "duplicate" license files under META-INF, and typically they fail when they see license.txt in different jars in the root.

5) license.txt contains strange bits.

For instance:

>JUnit is licensed under the Common Public License v1.0

Is JUnit bundled into one of Checker release artifacts?
If so, which artifacts re-distribute JUnit?
If so, which JUnit version is re-distributed?

AFAIK, JUnit has Eclipse Public License 1.0, and so the mention in Checker license.txt is wrong.

6) Do you really mean `GPL-2.0-only WITH Classpath-exception-2.0`?
As you use `GPL-2.0-only` it makes checker-framework to be incompatible with GPL 3 projects.
It is not an issue for me for now, however, it is typically recommended to use `-or-later` variations of GPL (see https://www.gnu.org/licenses/identify-licenses-clearly.html )

**Comment by mernst** [comment]
Thanks for the feedback!  I appreciate it.

> 1. It is a bit strange that build script uses both `archiveFileName != "checker-source.jar"` and `archiveFileName.get().startsWith("checker-qual")`
> 
>     Should the first be `archiveFileName.get() != ...` ?

I agree it's odd.  I was trying to avoid changing existing code, but since this contained multiple errors, I have fixed it in 3f56e78.

> 2. I've tried building [ce7cebb](https://github.com/typetools/checker-framework/commit/ce7cebbcac96bbd9125578daf8ab45be20e40f60) locally, and checker-qual/build/libs/checker-qual-2.11.1.jar (and other jars) seems to miss a license file. I guess the file is missing since you use `from('.')`, and you want something like `from("$rootDir/LICENSE.txt")`

I would like to resolve point 4 below before addressing this one.

> 3. The license file itself is complicated. Do you think you can create a license file dedicated to checker-qual.jar? The jar is used quite often (it contains annotations), and it is really sad there's no simple and understandable license for it.

I have done this, in commit e0538bfe1.

> 4. Please include the license under META-INF folder rather than to the root of the jar. Including licenses to the root causes issues with shading/producing uberjars. The tools more-or-less know how to process "duplicate" license files under META-INF, and typically they fail when they see license.txt in different jars in the root.

I can't seem to make this work.  I tried a number of things (`include`, `metainf`, etc.), but in each case the `META-INF/LICENSE` file in the `.jar` file is the one from BCEL.   Can you make a suggestion for code for the build.gradle file?

> 5. license.txt contains strange bits.
> 
> For instance:
> 
> > JUnit is licensed under the Common Public License v1.0
> 
> Is JUnit bundled into one of Checker release artifacts?
> If so, which artifacts re-distribute JUnit?
> If so, which JUnit version is re-distributed?
> 
> AFAIK, JUnit has Eclipse Public License 1.0, and so the mention in Checker license.txt is wrong.

This text was correct, but is obsolete.
JUnit 3 was distributed with the CF, and is licensed under the Common Public License v1.0
I removed the text in commit cf041b9a2.

> 6. Do you really mean `GPL-2.0-only WITH Classpath-exception-2.0`?
>    As you use `GPL-2.0-only` it makes checker-framework to be incompatible with GPL 3 projects.
>    It is not an issue for me for now, however, it is typically recommended to use `-or-later` variations of GPL (see https://www.gnu.org/licenses/identify-licenses-clearly.html )

Yes.  It is possible that some code in the Checker Framework is derived from code that uses that license.  I am not sure, but it is better to be safe than sorry.
