### ISSUE TITLE
member variable that is used in a private method flagged as possible null, not sure it's the right thing to do.

### ISSUE THREAD

**Issue by purrrkin** [typetools/checker-framework#2818]
```
import org.checkerframework.checker.nullness.qual.Nullable;
class NullableFailureOnCheckedVariable {
    @Nullable Object obj;
    
    NullableFailureOnCheckedVariable(@Nullable Object obj) {
        this.obj = obj;
    }
    
    void foo() {
        if (obj == null) {
            return;   
        }
        bar();
    }
    
    private void bar() {
        obj.toString();   
    }
}
```
Reproduction:

http://eisop.uwaterloo.ca/live#mode=display&code=import+org.checkerframework.checker.nullness.qual.Nullable%3B%0Aclass+NullableFailureOnCheckedVariable+%7B%0A++++%40Nullable+Object+obj%3B%0A++++%0A++++NullableFailureOnCheckedVariable(%40Nullable+Object+obj)+%7B%0A++++++++this.obj+%3D+obj%3B%0A++++%7D%0A++++%0A++++void+foo()+%7B%0A++++++++if+(obj+%3D%3D+null)+%7B%0A++++++++++++return%3B+++%0A++++++++%7D%0A++++++++bar()%3B%0A++++%7D%0A++++%0A++++private+void+bar()+%7B%0A++++++++obj.toString()%3B+++%0A++++%7D%0A%7D&typeSystem=nullness

A transcript of all the output (as text, not a screenshot).
Error: [dereference.of.nullable] dereference of possibly-null reference obj

pected to happen instead.  It can be helpful to explain your reasoning or reference a section of the manual.

The private method is called only in code path that checked the existing member variable for not-null. I'd expect it to not be an error.

Files that are used by the commands you ran.

**Comment by purrrkin** [comment]
Repro link with added final to the class:
http://eisop.uwaterloo.ca/live#mode=display&code=import+org.checkerframework.checker.nullness.qual.Nullable%3B%0Afinal+class+NullableFailureOnCheckedVariable+%7B%0A++++%40Nullable+Object+obj%3B%0A++++%0A++++NullableFailureOnCheckedVariable(%40Nullable+Object+obj)+%7B%0A++++++++this.obj+%3D+obj%3B%0A++++%7D%0A++++%0A++++void+foo()+%7B%0A++++++++if+(obj+%3D%3D+null)+%7B%0A++++++++++++return%3B+++%0A++++++++%7D%0A++++++++bar()%3B%0A++++%7D%0A++++%0A++++private+void+bar()+%7B%0A++++++++obj.toString()%3B+++%0A++++%7D%0A%7D&typeSystem=nullness

**Comment by wmdietl** [comment]
We always perform a modular analysis and don't do special handling for final classes.
You can express the extra assumption using a precondition on `bar`:

```java
import org.checkerframework.checker.nullness.qual.Nullable;
import org.checkerframework.checker.nullness.qual.RequiresNonNull;
class NullableFailureOnCheckedVariable {
    @Nullable Object obj;
    
    NullableFailureOnCheckedVariable(@Nullable Object obj) {
        this.obj = obj;
    }
    
    void foo() {
        if (obj == null) {
            return;   
        }
        bar();
    }
    
    @RequiresNonNull("obj")
    private void bar() {
        obj.toString();   
    }
}
```

http://eisop.uwaterloo.ca/live#mode=display&code=import+org.checkerframework.checker.nullness.qual.Nullable%3B%0Aimport+org.checkerframework.checker.nullness.qual.RequiresNonNull%3B%0Aclass+NullableFailureOnCheckedVariable+%7B%0A++++%40Nullable+Object+obj%3B%0A++++%0A++++NullableFailureOnCheckedVariable(%40Nullable+Object+obj)+%7B%0A++++++++this.obj+%3D+obj%3B%0A++++%7D%0A++++%0A++++void+foo()+%7B%0A++++++++if+(obj+%3D%3D+null)+%7B%0A++++++++++++return%3B+++%0A++++++++%7D%0A++++++++bar()%3B%0A++++%7D%0A++++%0A++++%40RequiresNonNull(%22obj%22)%0A++++private+void+bar()+%7B%0A++++++++obj.toString()%3B+++%0A++++%7D%0A%7D&typeSystem=nullness
