### ISSUE TITLE
Out-of-date documentation about the initialization checker

### ISSUE THREAD

**Issue by kelloggm** [typetools/checker-framework#2840]
The introduction to the section about the initialization checker in the manual says:

> If you wish to disable the initialization checks, pass the command-line argument -AsuppressWarnings=uninitialized when running the Nullness Checker.

I don't think this is true, and I don't think it has been true for a very long time. From the changelog:

> Version 1.2.4, 15 Dec 2011
> Nullness Checker:
> - The -Alint=uninitialized command-line option now defaults to off, and
  applies only to initialization of primitive and `@Nullable` fields.  It is
  not possible to disable, from the command line, the check that all
  `@NonNull` fields are initialized.  Such warnings must be suppressed
  explicitly, for example by using `@SuppressWarnings`.

**Comment by smillst** [comment]
`-AsuppressWarnings=uninitialized` suppresses all warnings that contain `uninitialized` in their error keys. So it suppresses `initialization.fields.uninitialized` and `initialization.static.fields.uninitialized`.

**Comment by wmdietl** [comment]
Larger issue about suppressing only initialization issues: #1590
