### ISSUE TITLE
type.invalid.annotations.on.use diagnostics for non-type annotations

### ISSUE THREAD

**Issue by cushon** [typetools/checker-framework#2848]
`javax.annotation.Nullable` isn't a type annotation, and writing `byte @javax.annotation.Nullable []` would be illegal.

Is this diagnostic working as intended?

```java
import javax.annotation.Nullable;

class T {
  void f(@Nullable byte[] bx) {}
}
```

```
./checker-framework-2.11.1/checker/bin/javac -processor Nullness -cp jsr305-3.0.2.jar T.java
T.java:4: error: [type.invalid.annotations.on.use] invalid type: annotations [@Initialized, @Nullable] conflict with declaration of type byte
  void f(@Nullable byte[] bx) {}
                          ^
1 error
```

**Comment by mernst** [comment]
Liam-

Yes, this is working as intended.

[Section 3.7  Other tools for nullness checking](https://checkerframework.org/manual/#nullness-related-work) says, "[The Nullness Checker] treats annotations from other tools as if you had written the corresponding annotation from the Nullness Checker".

It would be illegal to write `org.checkerframework.checker.nullness.qual.@Nullable` on the `byte` type.

This can be viewed as the Checker Framework encouraging you to migrate off obsolete declaration annotations that have been replaced by type annotations, which are clearer and more expressive.

**Comment by cushon** [comment]
Thanks for the reminder, I guess this is more or less the same discussion as #1934.

For what it's worth we still have code using `javax.annotation.Nullable` on purpose. This diagnostic doesn't seem very actionable for code that can't or doesn't want to migrate to a different annotation, so we'll probably have to suppress it.

**Comment by mernst** [comment]
Yes, I agree you'll have to suppress the warning for such code.  Sorry about that.

The Checker Framework stopped supporting that use case because it is rare and because supporting it added significant complexity (to the code and to explanations in the manual).
