### ISSUE TITLE
Typo in updated manual for Maven 

### ISSUE THREAD

**Issue by maggu2810** [typetools/checker-framework#2873]
There is small typo / error in the updated manual (PR #2806).

https://github.com/typetools/checker-framework/pull/2806/files#diff-f237d7d35cf0b39268f02bfae4298b0cR735

```
  <annotatedJdk>$\{org.checkerframework:jdk8:jar\}</annotatedJdk>
  <errorProneJavac>${com.google.errorprone:javac:jar}</errorProneJavac>
```

The `{` and `}` needs to be escaped, otherwise they are missing in the generated documentation (see current published manual) and without the braces it will not work.

**Comment by wmdietl** [comment]
Thanks for letting us know!
