### ISSUE TITLE
Raw List returned by Class.cast converts without warning to List<@NonNull>

### ISSUE THREAD

**Issue by cpovirk** [typetools/checker-framework#2880]
```java
import java.util.ArrayList;
import java.util.List;
import org.checkerframework.checker.nullness.qual.NonNull;
import org.checkerframework.checker.nullness.qual.Nullable;

class ClassCastToNonNullWildcard {
  public static void main(String[] args) {
    List<@Nullable String> nullables = new ArrayList<@Nullable String>();
    nullables.add(null);

    List<@NonNull ?> notNulls = List.class.cast(nullables);
    notNulls.get(0).toString();
  }
}
```

```sh
/tmp/tmp.pIjExBbI7C/checker-framework-3.0.0/checker/bin/javac -Xlint:all -processor org.checkerframework.checker.nullness.NullnessChecker -AcheckCastElementType -AconservativeUninferredTypeArguments ClassCastToNonNullWildcard.java && java ClassCastToNonNullWildcard
Exception in thread "main" java.lang.NullPointerException
  at ClassCastToNonNullWildcard.main(ClassCastToNonNullWildcard.java:12)
```

[Source file](https://github.com/typetools/checker-framework/files/3833031/ClassCastToNonNullWildcard.java.txt) and [`-version -verbose -AprintAllQualifiers` output](https://github.com/typetools/checker-framework/files/3833034/err.txt) attached.

FWIW, I would have guessed that the conversion from `List` to `List<@NonNull ?>` would have been a _javac_ warning (instead of or in addition to a Checker Framework warning), much like the conversion from `List` to `List<? extends @NonNull Object>`. But I have not tried to look this up in the JLS.

**Comment by cpovirk** [comment]
I won't speak with confidence when interpreting the JLS, but it says:

[§5.1.9](https://docs.oracle.com/javase/specs/jls/se12/html/jls-5.html#jls-5.1.9):
> There is an unchecked conversion from the raw class or interface type ([§4.8](https://docs.oracle.com/javase/specs/jls/se12/html/jls-4.html#jls-4.8)) G to any parameterized type of the form G\<T<sub>1</sub>,...,T<sub>n</sub>\>.
> ...
> Use of an unchecked conversion causes a compile-time _unchecked warning_ unless all type arguments T<sub>i</sub> (1 ≤ _i_ ≤ _n_) are unbounded wildcards ([§4.5.1](https://docs.oracle.com/javase/specs/jls/se12/html/jls-4.html#jls-4.5.1))....

[§4.5.1](https://docs.oracle.com/javase/specs/jls/se12/html/jls-4.html#jls-4.5.1)
> The wildcard `? extends Object` is equivalent to the unbounded wildcard `?`.

The latter snippet seems to be the _definition_ of the unbounded wildcard. It's not clear to me whether it's meant to include `@NonNull ?` or not.

The latter snippet is also not very precise: If `? extends Object` is "equivalent to" `?`, then why is it legal to write...
```java
new ArrayList<?>[0]
```
...but illegal to write...
```java
new ArrayList<? extends Object>[0]
```

The spec says that array creation [requires a reifiable type](https://docs.oracle.com/javase/specs/jls/se12/html/jls-15.html#jls-15.10.1), which includes ["a parameterized type in which all type arguments are unbounded wildcards."](https://docs.oracle.com/javase/specs/jls/se12/html/jls-4.html#jls-4.7) But it seems that `? extends Object` is not "equivalent" in this respect.

This all means that my analogy to `List<? extends @NonNull Object>` is less well grounded than I'd hoped: The problem there is with `List<? extends Object>`, not with the type annotation. (This is unsurprising: Java itself doesn't check type annotations in general.)

**Comment by cpovirk** [comment]
Possibly the difference in handling of `? extends Object` is a bug:

> Consensus from some additional discussion is that we want a special rule that says '? extends Object' is \_the same as\_ '?' (that is, '? extends Object' is an unbound wildcard). This should have the effect of all of the following, without having to make a special exception for each case:
> ...
> Foo\<? extends Object\> is reifiable

https://bugs.openjdk.java.net/browse/JDK-6480391?focusedCommentId=13306223&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13306223

I'm going to bring this up with our javac experts internally.

(See also [another effect of the different treatment](https://stackoverflow.com/q/33791257/28465).)

**Comment by smillst** [comment]
By default, the Checker Framework ignores any warnings from raw types. If you add `-AignoreRawTypeArguments=false` to your example you get the following warning:
```
ClassCastToNonNullWildcard.java:11: error: [assignment.type.incompatible] incompatible types in assignment.
    List<@NonNull ?> notNulls = List.class.cast(nullables);
                                               ^
  found   : @Initialized @NonNull List</*INFERENCE FAILED for:*/ ? extends @Initialized @NonNull Object>
  required: @UnknownInitialization @Nullable List<? extends @Initialized @NonNull Object>
```
Note that ` -AconservativeUninferredTypeArguments ` is required as well and that the `/*INFERENCE FAILED for:*/`  text has been added since the last release.

I've noticed that the manual is incorrect about the behavior of `-AignoreRawTypeArguments`, I'll update it.

That's interesting that Java doesn't report a warning.  We had hoped if javac didn't report any that we could ignore raw types and rely on javac to report `unchecked` or `rawtypes` warnings instead.

**Comment by cpovirk** [comment]
Thanks! I had noticed the `-AignoreRawTypeArguments` option but, as you've noted, saw it described only as _decreasing_ soundness, so I'd ignored it.

Also: I'm realizing another problem with my earlier `List<? extends @NonNull Object>` example: Java consistently does _not_ consider type annotations when deciding if a type is reifiable. For example, I can write `new String @NonNull [1]` or `instanceof @NonNull String`, and javac doesn't mind. I suppose it's _possible_ that this is considered to be a bug -- it would be nice if the spec were more direct about it -- but it seems likely to be intentional. That suggests that the Checker Framework won't be able to rely on javac here if it wants to address this (admittedly fairly unlikely) edge case.

**Comment by cpovirk** [comment]
(Random: I just noticed a reference to javac's different treatment of `<?>` and `<? extends Object>` [in the Checker Framework manual](https://checkerframework.org/manual/#common-problems-running-javac).)

**Comment by smillst** [comment]
I update the manual in 275ed29b175661bd102ccd59c1ff6f4380b1954b.
