### ISSUE TITLE
List forbidnonnullarraycomponents under "More sound (strict) checking" and "-Alint command-line option"

### ISSUE THREAD

**Issue by cpovirk** [typetools/checker-framework#2886]
Currently, the manual doesn't list the `Foo @NonNull []` case as one of the unsound cases linked to from [2.3](https://checkerframework.org/manual/#checker-guarantees):

> The Checker Framework is, by default, unsound in a few places where a conservative analysis would issue too many false positive warnings. These are listed in Section [2.2.3](https://checkerframework.org/manual/#unsound-by-default).

Admittedly, 2.2.3 does mention `-Alint`, the option used to control array soundness. However:
- The mention of `-Alint` is only under "Type-checking modes: enable/disable functionality," not under "More sound (strict) checking: enable errors that are disabled by default."
- It links to [27.6](https://checkerframework.org/manual/#lint-options), which doesn't mention `-Alint=forbidnonnullarraycomponents` in its list of options.

That's not to say that `-Alint=forbidnonnullarraycomponents` is undocumented: It does get mentioned in a couple places, including [3.1.1](https://checkerframework.org/manual/#nullness-lint) and [3.3.4](https://checkerframework.org/manual/#nullness-arrays). It just feels like it could belong in the main list of unsound cases and in the `-Alint` docs

(I see that you may still be planning to [make sound array checking the default](https://github.com/typetools/checker-framework/issues/986). If so, it might not be worth your effort to update the documentation for the current state of things. In that case, feel free to close this.)

**Comment by mernst** [comment]
Thanks for pointing this out, Chris.  I appreciate it.

The reason that `-Alint=forbidnonnullarraycomponents` isn't mentioned in sections 2.2.3 and 27.6 is that it is specific to the Nullness Checker, whereas both of those sections list options that every checker is guaranteed to support.  I have added text in both sections noting that a checker may support more such command-line options, which are described in the checker's documentation.  (Section 2.3 already has text to that effect.)  If there is a way to make more prominent or easier to understand, please let us know.

**Comment by cpovirk** [comment]
Ah, thank you! I'd missed that distinction, but it makes a lot of sense, and I think the revised doc would have been enough to help me understand that in the first place.
