### ISSUE TITLE
When searching for qualifiers, fall back to classpath search if classLoader.getResource returns null

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#2893]
We believe we've found a case where in the process of reflectively loading qualifiers, the following call to `classLoader.getResource` returns `null`:

https://github.com/typetools/checker-framework/blob/11a2869526052061c13fba25ff6ac157cf91c41b/framework/src/main/java/org/checkerframework/framework/type/AnnotationClassLoader.java#L132

That is trying to get a resource for the qualifiers directory.  Further, we found that getting a resource for a specific qualifier class in that directory gives a non-null result.  Specifically in our case, `classLoader.getResource("org/checkerframework/checker/returnsrcvr/qual")` returns `null`, but `classLoader.getResource("org/checkerframework/checker/returnsrcvr/qual/MaybeThis.class")` gives a non-null result.  Unfortunately, I don't have a test case to reproduce at the moment.

Should the code in `AnnotationClassLoader` fall back on trying to get the qualifier directory via `getURLFromClasspaths` if the above call returns `null`?  Not sure if that makes sense or would be guaranteed to fail if the above call returns `null`.

/cc @lazaroclapp

**Comment by wmdietl** [comment]
This supposedly was fixed with #3106 back in February.
@msridhar Did you have a chance to test that change? Are you fine with closing this issue? (I'm not sure why it wasn't auto-closed from the PR...)

**Comment by msridhar** [comment]
I will close.  We can re-open if we run into this issue again.  I am unable to test it at this point
