### ISSUE TITLE
Possible data race in AnnotationBuilder?

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#2897]
Possibly related to #722 and #2256 

@lazaroclapp is seeing the following crash stack:

```
Underlying Exception: org.checkerframework.javacutil.BugInCF: No element with name 'value' in annotation @org.checkerframework.framework.qual.PolymorphicQualifier; useDefaults=true, valmap.keySet()=[]; Stack trace: org.checkerframework.javacutil.AnnotationUtils.getElementValue(AnnotationUtils.java:628)
```

The crash is non-deterministic and tends to happen more in concurrent builds.  I noticed that `AnnotationBuilder` has a static cache:

https://github.com/typetools/checker-framework/blob/11a2869526052061c13fba25ff6ac157cf91c41b/javacutil/src/main/java/org/checkerframework/javacutil/AnnotationBuilder.java#L64-L70

Also this seems to be the code creating the `AnnotationMirror`:

https://github.com/typetools/checker-framework/blob/11a2869526052061c13fba25ff6ac157cf91c41b/framework/src/main/java/org/checkerframework/framework/util/MultiGraphQualifierHierarchy.java#L93-L101

Not sure how it fits together, but it seems like maybe `MultiGraphQualifierHierarchy` should be using a different API, and possibly the buggy behavior only gets exposed in a concurrent build with multiple threads reading from that cache?

Unfortunately don't have a small repro example.  I'm hoping that a maintainer can spot the problem 🙂

**Comment by lazaroclapp** [comment]
For context, in our concurrent build environment (using `buck`) I am seeing that, when running code like the following:

```
AnnotationMirror am = 
  QualifierPolymorphism.getPolymorphicQualifier(
       [... some annotation with @PolymorphicQualifier ...]);
for (int i = 0; i < 20; ++i) {
    log += ((Symbol.TypeSymbol) am.getAnnotationType().asElement())
                    .members().getClass().getCanonicalName() 
                 + " ";
}
```
I sometimes get out `com.sun.tools.javac.code.Scope.ErrorScope` a number of times, then `om.sun.tools.javac.code.Scope.ScopeImpl` every time after that. 

If I call `AnnotationUtils.getElementValuesWithDefaults(am)` when getting the `ErrorScope`, `value` is missing from the resulting dictionary, but it's present if what I got last was a `ScopeImpl`.

**Comment by msridhar** [comment]
Fundamentally, I think having `annotationsFromNames` as a static field is dangerous.  It really doesn't seem to make sense to be sharing this cache between multiple instances of `javac` running in different threads in the same JVM.

**Comment by msridhar** [comment]
Follow-up here: running the checker in isolation for each build target fixes the problem, so that is strong evidence that the issue is some kind of interference due to the static field.

**Comment by smillst** [comment]
We've removed the cache in AnnotationBuilder (https://github.com/typetools/checker-framework/commit/5234790d43f0ba20baeae59da5edb3b226eb216e).  There is also a static cache in AnnotationUtils for use with areSameByClass.  That cache makes the checkers faster, so I need to refactor several checkers to use areSameByName instead before I can remove it.

**Comment by msridhar** [comment]
Thanks @smillst! Could you change the other cache to be an instance field and somehow keep the relevant `AnnotationUtils` object inside the base type checker, so you don’t need to refactor so many checkers?

**Comment by smillst** [comment]
I've removed the other static cache in #2997.

**Comment by msridhar** [comment]
Thanks @smillst! When we get to test the latest version, I’ll report back on whether the race conditions have disappeared

**Comment by msridhar** [comment]
I’ll close this issue for now and re-open if we still see a problem
