### ISSUE TITLE
Minor syntax changes for source code readability of multiple return function body

### ISSUE THREAD

**Issue by smonteiro** [typetools/checker-framework#2900]
Too many  return anno;

    private AnnotationMirror convertToUnknown(AnnotationMirror anno) {
        if (AnnotationUtils.areSameByClass(anno, ArrayLenRange.class)) {
            Range range = getRange(anno);
            if (range.from == 0 && range.to >= Integer.MAX_VALUE) {
                return UNKNOWNVAL;
            }
            return anno;
        } else if (AnnotationUtils.areSameByClass(anno, IntRange.class)) {
            Range range = getRange(anno);
            if (range.isLongEverything()) {
                return UNKNOWNVAL;
            }
            return anno;
        } else {
            return anno;
        }
    }

**Comment by smonteiro** [comment]
I am not finding a way to create a feature branch in this repository for this very simple change to push a change for someone to review as a pull request.

**Comment by mernst** [comment]
To make a pull request:
 * fork the repository
 * make a feature branch in your fork
 * make a pull request from that branch

Please give an explanation of your changes.  Thanks in advance!

**Comment by smonteiro** [comment]
This was a very tiny change to reduce the number of returns in the source file ValueAnnotatedTypeFactory.java

I am a senior level developer but it is my first time contributing on github.

**Comment by smillst** [comment]
Thanks for the contribution!  Also, in GitHub if you edit a file, GitHub will fork the repository and create a branch for you.  https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-another-users-repository.
