### ISSUE TITLE
Typo in GSoC documentation

### ISSUE THREAD

**Issue by anantjain6** [typetools/checker-framework#2919]
https://github.com/typetools/checker-framework/blob/00f73398a6194324d9821da3a6f9bf49da002292/docs/developer/gsoc-ideas.html#L109

https://github.com/typetools/checker-framework/blob/00f73398a6194324d9821da3a6f9bf49da002292/docs/developer/gsoc-ideas.html#L110

It is written "It `it` attractive to programmers who care about their craft and the quality of their code"
But it should be "It `is` attractive to programmers who care about their craft and the quality of their code"

I know GSoC 2019 is over but this documentation is helpful for 2020 aspirants

**Comment by mernst** [comment]
Thanks for pointing this out, and for the fix.
