### ISSUE TITLE
Implementation and javadoc do not match for org.checkerframework.common.value.util.Range.{byte,char,short,int}Range()

### ISSUE THREAD

**Issue by smonteiro** [typetools/checker-framework#2930]
Methods {byte,char,short,int}Range() are not what their javadocs say.
Example 

```
    /**
     * Converts this range to a char range.
...
     * <p>If {@link #ignoreOverflow} is false and the bounds of this range are not representable as
     * 8-bit integers, convert the bounds to Character type in accordance with Java overflow rules
     * (twos-complement), e.g., Character.MAX_VALUE + 1 is converted to Character.MIN_VALUE.
     */
```

1.  It does not convert the range in place, all these methods create a new Range.
2.  Despite the internal casting that leads to underflow and overflow, those bounds are not expressed in the range returned: whatever casting overage happens makes the from and to values violate from<= to so the full domain is returned instead in every one of these methods.

In light of this de facto behavior, maybe we are better off re-reading these methods as something much simpler and implementing as such:  
`//`
    `private Range toRange(Range domain) {`
`        if (this.isNothing()) {`
`            return this;`
`        }`
`        if (domain.contains(this)) {`
`            return this;`
`        } `
`       if (ignoreOverflow) {`
`            return create(Math.max(from, domain.from), Math.min(to, domain.to));`
`        }`
`        return domain;`
`    }`

And here domain is any of the Ranger constants already defined and in use `Range.{Type}_EVERYTHING`.

The advantages are many:

1.  Only one scenario in that body results in an actual new instance being created; all others return existing instances.
2. This does away with all the `private static final long {Type}_WIDTH`

What do you think ?

**Comment by mernst** [comment]
> It does not convert the range in place, all these methods create a new Range.

I think that is implicit in the fact that `Range` is documented to be immutable and the methods return a value.  I could change the wording if this is too confusing.  (The methods whose Javadoc starts "refines" are even more confusing!)

> Despite the internal casting that leads to underflow and overflow, those bounds are not expressed in the range returned: whatever casting overage happens makes the from and to values violate from<= to so the full domain is returned instead in every one of these methods.

Sometimes the methods return the full domain, but not always.

Here is a test case that illustrates that behavior:

```
        Range r2 = Range.create(1024 + 17, 1024 + 22);

        Range.ignoreOverflow = true;

        assert r2.byteRange().equals(Range.create(Byte.MAX_VALUE, Byte.MAX_VALUE));

        Range.ignoreOverflow = false;

        assert r2.byteRange().equals(Range.create(17, 22));
```

With these arguments, the result of byteRange is not `Range.BYTE_EVERYTHING`, regardless of the value of `ignoreOverflow`.

> if (domain.contains(this)) {
> return this;
> }

The idea of checking `contains` in order to avoid creating a new `Range` is a good one, thanks.  I will make that change.

Thanks for bringing up these issues!
