### ISSUE TITLE
Enhancement request: new @EnumVal() that would behave like @StringVal()

### ISSUE THREAD

**Issue by smonteiro** [typetools/checker-framework#2953]
I could be wrong but I did not find documentation for a `@EnumVal`
The concept is not too far-fetched: one wants to enforce domain, co-domain, and range:

> Example of use case:
import javax.lang.model.type.TypeKind;
static @EnumVal({TypeKind.BYTE,
                    TypeKind.BOOLEAN,
                    TypeKind.CHAR,
                    TypeKind.DOUBLE,
                    TypeKind.FLOAT,
                    TypeKind.INT,
                    TypeKind.LONG}) TypeKind toPrimitiveTypeKind(...)
...
static  int fromPrimitiveTypeKind( @EnumVal({TypeKind.BYTE,
                    TypeKind.BOOLEAN,
                    TypeKind.CHAR,
                    TypeKind.DOUBLE,
                    TypeKind.FLOAT,
                    TypeKind.INT,
                    TypeKind.LONG}) TypeKind tk) {...)

**Comment by kelloggm** [comment]
This is probably related to #2156. I agree that it would be useful for the Value Checker to support an `@EnumVal` annotation; see e.g. 
[this comment](https://github.com/awslabs/aws-kms-compliance-checker/blob/master/src/main/java/com/amazon/checkerframework/compliance/kms/ComplianceChecker.java#L18) in a third-party checker, which describes a desire to write annotations in a stub file on enum constants. The linked CF issue (#2147) was closed in favor of the more general #2156.

**Comment by smonteiro** [comment]
While the topic of  #2156 is Enum, it is about something else.
My interest here is to clamp the domain  of arguments to functions and clamp their return values.

**Comment by mernst** [comment]
I agree that this is a valuable enhancement, and that it's unrelated to #2156.
I don't think this would be very challenging to do:  the logic should be very similar to the other `*Val` annotations.

**Comment by mernst** [comment]
Fixed in 483bd239c6d3755cdd62166f0bdd9e2e89d81acc
