### ISSUE TITLE
Minimize size of annotated JDK

### ISSUE THREAD

**Issue by zhangjiangqige** [typetools/checker-framework#3010]
At present the dependency of the annotated JDK 11 copied by the gradle task `copyJdk11Files` is ~24M, and it's possible to minimize those files with javaparser. After the minimization (of comments, body of methods, etc), the size of `checker.jar` can be decreased from ~14M to ~9M.

The minimizer can be found at [here](https://github.com/zhangjiangqige/try-javaparser/blob/master/src/main/java/org/zhangjiangqige/Minimizer.java), and the minimized JDK [here](https://github.com/zhangjiangqige/mini-jdk11).

Although it doesn't speed up the speed when using JDK 11, but it's still probably good. So I was wondering if there's a proper way to integrate the minimizer into this repo?

cc @wmdietl

**Comment by wmdietl** [comment]
This was fixed in #3257.
