### ISSUE TITLE
Maven instructions: suggest installing to local repo instead of using system dependence?

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#3050]
In the [instructions for using Maven](https://checkerframework.org/manual/#maven), the manual suggests to use a `system` dependence to make use of a local version of Checker Framework.  This approach is a bit problematic for a couple of reasons:
* The `system` dependence feature [is deprecated](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#System_Dependencies).
* When using third-party checkers by sticking them under `annotationProcessorPaths` in the `maven-compiler-plugin` config, the `system` dependence does not seem to override the dependence declared by the third-party checker.  E.g., when placing the Object Construction Checker in the `annotationProcessorPaths`, the compiler plugin still stuck v3.0.0 of the Checker Framework on the processor path, ignoring the declared `system` dependence.

An alternative approach that I found to work better was to install the relevant Checker Framework jars to the local Maven repository under a `SNAPSHOT` version number.  E.g., I did:
```
mvn install:install-file -DgroupId=org.checkerframework -DartifactId=checker -Dversion=3.1.1-SNAPSHOT -Dpackaging=jar -Dfile=path/to/checker-framework/checker/dist/checker.jar
```
Then, in my `annotationProcessorPaths` for `maven-compiler-plugin` I added:
```xml
            <path>
              <groupId>net.sridharan.objectconstruction</groupId>
              <artifactId>object-construction-checker</artifactId>
              <version>0.1.7-SNAPSHOT</version>
            </path>
            <path>
              <groupId>org.checkerframework</groupId>
              <artifactId>checker</artifactId>
              <version>3.1.1-SNAPSHOT</version>
            </path>
```
This had the desired effect of overriding our checker's declared dependence on Checker Framework 3.0.  I think the `mvn install` approach should work fine for `checker-qual`, `jdk8`, etc. as well, though I haven't tested that.

Is there a strong reason to retain the `system` approach?

**Comment by mernst** [comment]
Thanks for this suggestion.  Can you please review #3051?
