### ISSUE TITLE
Objects.requireNonNullElse is improperly annotated

### ISSUE THREAD

**Issue by octylFractal** [typetools/checker-framework#3056]
It seems that `Objects.requireNonNullElse` has improper nullability annotations. Here are a few test cases that fail in various ways, with associated compilation log:
https://gist.github.com/octylFractal/7680eefabc242ca21f510b1fdfc42807

I think that a more correct signature would be `<T> T requireNonNullElse(@Nullable T obj, @NonNull T defaultObj)` or `<T extends @NonNull Object> T requireNonNullElse(@Nullable T obj, T defaultObj)`, but neither of these fail the third case, which seems weird to me.

**Comment by wmdietl** [comment]
Thanks for the report!
https://github.com/typetools/checker-framework/blob/master/checker/jdk/nullness/src/java/util/Objects.java is for Java 8. `requireNonNullElse` and `requireNonNullElseGet` were added in Java 9.

The Java 11 annotations at https://github.com/typetools/jdk/blob/master/src/java.base/share/classes/java/util/Objects.java#L323
don't have appropriate annotations for those two new methods yet.

Do you want to open a PR?

Can you expand on what about the "third case" doesn't work?

**Comment by octylFractal** [comment]
The third case is `System.err.println((Object) requireNonNullElse(null, null));` (each line is one test case). I can't get checker to fail it for having `null` in the second argument slot.

**Comment by mernst** [comment]
This was in part fixed by changes to JDK annotations and in part will be fixed by https://github.com/typetools/checker-framework/pull/3173.
