### ISSUE TITLE
Don't clone typetools/jdk until necessary

### ISSUE THREAD

**Issue by wmdietl** [typetools/checker-framework#3069]
In an empty directory, clone a fresh copy of typetools/checker-framework:

```
git clone https://github.com/typetools/checker-framework.git
```

Then, I then run `./gradlew tasks` to see what tasks are available.
This takes nearly three minutes, because behind-the-scenes a clone of typetools/jdk is produced.
This is surprising and rather annoying, in particular on a JDK 8 system where this dependency isn't needed.

Would it be possible to delay cloning typetools/jdk until it is needed by the build?
Could there be some feedback to indicate that this is happening?
Can we avoid cloning this altogether if it isn't needed?
Should this be part of `cloneAndBuildDependencies`, if necessary?

**Comment by smillst** [comment]
Make it output some text saying that the JDK is cloning.
