### ISSUE TITLE
MavenExampleJDK11 missing from download

### ISSUE THREAD

**Issue by eamonnmcmanus** [typetools/checker-framework#3076]
The [documentation](https://checkerframework.org/manual/#maven) says this:

> See the directory `docs/examples/MavenExample/` for examples of the use of Maven build files that run a checker with JDK 8. See the directory `docs/examples/MavenExampleJDK11/` for examples of the use of Maven build files that run a checker with JDK 11.

I downloaded [`checker-framework-3.1.0.zip`](https://checkerframework.org/checker-framework-3.1.0.zip) and there is indeed a directory `docs/examples/MavenExample` but there is no `docs/examples/MavenExampleJDK11/`. The file `docs/examples/MavenExample/README` also refers to the phantom directory.

**Comment by smillst** [comment]
Thanks for pointing this out.  I've fixed this so it will be correct in the next release.  In the meantime, you can see the example in the repository: https://github.com/typetools/checker-framework/tree/master/docs/examples/MavenExampleJDK11.
