### ISSUE TITLE
IDEs cannot import any com.sun.* packages under Java 8

### ISSUE THREAD

**Issue by zcai1** [typetools/checker-framework#3083]
This issue only happens when trying to open the CF source code in an IDE with Java 8 as the project SDK. Although gradle does not have any issues with compiling, the IDE will not be able to process the files properly and consequently generate ubiquitous warnings. However, the issue is gone when switching the project SDK to Java 11.

Example:
![image](https://user-images.githubusercontent.com/12403206/74171509-b04e8880-4bfc-11ea-9ecb-1d9e84dcc924.png)

I was able to reproduce this issue on IDEA and Eclipse, with oracle JDK 1.8.0_241.

I had a discussion with @xingweitian, and we think the followings are the possible solutions:
1. Simply ask developers to use Java 11 in IDEs
2. Add `compileOnly "com.google.errorprone:javac:9+181-r4173-1"` to `build.gradle`, which contains those com.sun.* packages (Thanks to @xingweitian)

**Comment by smillst** [comment]
I can't reproduce this with IntelliJ.  Did you import via File -> New project from existing sources -> navigate to the Checker Framework directory -> select "import project from external model" and Gradle?

I can reproduce this with Eclipse.  You can fix this by adding checker/dist/javac.jar to as a dependency of the projects.

**Comment by xingweitian** [comment]
@smillst I can also reproduce it with my Idea. I just clean the project and re-import it with gradle. I did not add any external dependencies manually. (My Java version is 1.8.0_231).

**Comment by xingweitian** [comment]
@smillst I tried to import it following the way you just mentioned, I can still reproduce it.

**Comment by smillst** [comment]
What version of IntelliJ are you using?

**Comment by xingweitian** [comment]
IntelliJ IDEA 2019.3.2 (Ultimate Edition)
Build #IU-193.6015.39, built on January 20, 2020

**Comment by zcai1** [comment]
@smillst Yes, I can reproduce the issue by following the steps you posted. Please check File -> Project Structure -> "Project SDK" in the "Project" tab and make sure it is Java 8.

Although adding `checker/dist/javac.jar` seems to provide most of the packages, some of them are still missing. For example, my Eclipse failed to import `com.sun.source.tree.ClassTree` and `com.sun.source.tree.AssignmentTree` after adding the jar.

(I'm also using IntelliJ IDEA 2019.3.2)

**Comment by wmdietl** [comment]
@smillst I can reproduce the problem with IntelliJ IDEA 2019.3.3.
I removed the `checker-framework/.idea` directory.
I import the project as a gradle project.
I change File -> Project Structure -> "Project SDK" to use a Java 8 SDK.
IntelliJ then complains about the javac imports/uses in the project.

Can you let us know what "Project SDK" you are using?

Instead of adding the additional dependency in #3088, should we simply update the developer instructions to use Java 11 in their IDEs?

**Comment by smillst** [comment]
@wmdietl I did the following:

* Deleted JDK 11 from IntelliJ
* clone the Checker Framework
* There is no `checker-framework/.idea` to delete.
* In IntelliJ IDEA 2019 2019.3.3 Community Addition,   File -> New project from existing source -> select the checker-framework directory of the fresh clone -> Import project for external module and select Gradle, click finish. 
* I open `org.checkerframework.javacutil.AbstractTypeProcessor` and there are no compiler warnings/errors on the sun classes.
* If I check the module and project settings they are both JDK 8.  (Remember, I deleted JDK 11 from IntelliJ.)

Is that would you did?  

> Instead of adding the additional dependency in #3088, should we simply update the developer instructions to use Java 11 in their IDEs?

Yes, we can say something like, if your IDE has trouble finding the compiler classes, use JDK 11.  Can you confirm that using JDK 11 works for you?

**Comment by zcai1** [comment]
@smillst I found that you made a similar change to CF Inference in https://github.com/typetools/checker-framework-inference/pull/129

Could you explain why the change was needed?

**Comment by smillst** [comment]
Thanks for pointing that out.  That shouldn't be needed either.  I've made a pull request to fix it:
https://github.com/typetools/checker-framework-inference/pull/143

I made that change when I removed the javac jar from checker.jar:
https://github.com/typetools/checker-framework/pull/2850

**Comment by smillst** [comment]
@wmdietl @zcai1 @xingweitian What "Runtime version" of java is your version of Intellij using?  You can find out by looking at the information in the 
About Intellij screen.  Mine is showing Java 11 (see below) so maybe that's the difference?

```
IntelliJ IDEA 2019.3.3 (Community Edition)
Build #IC-193.6494.35, built on February 10, 2020
Runtime version: 11.0.5+10-b520.38 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: 
Non-Bundled Plugins: PythonCore, VisualVMLauncher, mobi.hsz.idea.latex, nl.rubensten.texifyidea
```

**Comment by xingweitian** [comment]
@smillst Mine is also showing Java 11. I can have another try with the community edition.

```
IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 10, 2020
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-40-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1908M
Cores: 8
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: BashSupport, Gradle View, GradleDependenciesHelper, Pythonid, com.alayouni.ansiHighlight, com.cybrosis.catdea, com.github.b3er.idea.plugins.arc.browser, com.jetbrains.lightThemePreview, com.thvardhan.gradianto, mobi.hsz.idea.gitignore, mobi.hsz.idea.latex, net.vektah.codeglance, nl.rubensten.texifyidea, org.plugin.dot.id
```

**Comment by xingweitian** [comment]
@smillst What's the JDK version of your Gradle JVM in the project? Is it also `8`? In `Build, Execution, Deployment > Build Tools > Gradle` you can find `Gradle JVM` on the right-hand side.

For me, if I select to use JDK 8 for the project's Gradle JVM, I can still reproduce it by the community edition.

**Comment by zcai1** [comment]
@smillst By default, Intellij comes with its own runtime (https://www.jetbrains.com/help/idea/switching-boot-jdk.html), so I don't think it is relevant to this issue.

**Comment by smillst** [comment]
As I've said before:
>If I check the module and project settings they are both JDK 8. (Remember, I deleted JDK 11 from IntelliJ.)

**Comment by smillst** [comment]
@xingweitian I just realized that you were asking about the Gradle JDK. It's also 8.  I have even deleted all JDK except 8 from my machine and I still cannot reproduce this.

**Comment by xingweitian** [comment]
> @xingweitian I just realized that you were asking about the Gradle JDK. It's also 8. I have even deleted all JDK except 8 from my machine and I still cannot reproduce this.

It's really weird...

**Comment by zcai1** [comment]
@smillst [test-src.zip](https://github.com/typetools/checker-framework/files/4291075/test-src.zip)
I'd like to provide you this Dockerfile I created, which contains both `checker-framework/checker/bin-devel/Dockerfile-ubuntu-jdk8` and the Intellij IDEA. Hopefully, it can help you in reproducing this issue.

Could you try:

1. unzip the files to a new folder
2. run `./build-image.sh`
3. run `./run.sh`

In case of any X11-related issues, you might want to check https://gist.github.com/cschiewek/246a244ba23da8b9f0e7b11a68bf3285 for how to set up the `DISPLAY` environment variable properly.

(I was able to reproduce it using the docker image)

**Comment by smillst** [comment]
@zcai1 . Finally, I was able to reproduce this.  It must be a Mac vs linux problem.  I'll try to see if there is a way to work around this without changing the build.gradle.
