### ISSUE TITLE
Crash: "Unexpected null first argument to areSameByName"

### ISSUE THREAD

**Issue by epmjohnston** [typetools/checker-framework#3120]
CF Version: 3.1.1
javac Version: 11.0.1

Attachments: [checker-framework-bug-report.zip](https://github.com/typetools/checker-framework/files/4269486/checker-framework-bug-report.zip)
* `NullFirstArgToAreSameByName.java` - Minimal java file to repro the crash when compiled by CF & javac 11.0.1
* `checker-framework-bug-output.txt` - Output from invoking the command below.

Command:
```
javac \
    -J--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED \
    -processorpath $CHECKERFRAMEWORK/checker/dist/checker.jar \
    -cp $CHECKERFRAMEWORK/checker/dist/checker-qual.jar \
    -processor org.checkerframework.checker.nullness.NullnessChecker \
    ./NullFirstArgToAreSameByName.java 
```

This command crashes with "`error: Unexpected null first argument to areSameByName`". Full stack trace is attached (see above).

Note, this does *not* repro with the javac wrapper included in the CF 3.1.1 distro. That is, running `$CHECKERFRAMEWORK/checker/bin/javac ./NullFirstArgToAreSameByName.java` compiles successfully.

**Comment by wmdietl** [comment]
Thanks a lot for the detailed bug report!
The following even simpler example also causes the same crash:

```java
    CharSequence foo() {
        return bar();
    }

    <T extends Enum<T>> CharSequence bar() {
        return null;
    }
```

and I do get the same behavior with the CF javac wrapper and plain javac.

I've filed #3121 to fix the issue.

**Comment by epmjohnston** [comment]
Great! Thanks for the quick fix! :)
