### ISSUE TITLE
Cannot extend PreparedStatement - setBytes has invalid annotation@Nullable on byte[]

### ISSUE THREAD

**Issue by MichalStehlikCz** [typetools/checker-framework#3129]
I have problems with annotated JDK - PreparedStatement interface. It seems to me last modification has been a bit too aggressive and left following declaration

    void setBytes(int parameterIndex, @Nullable byte x[]) throws SQLException;

When I try to implement this interface, compiler reports cannot override if @Nullable is not present and
Error:(127, 59) java: [type.invalid.annotations.on.use] invalid type: annotations [@Initialized, @Nullable] conflict with declaration of type byte
if I try to use @Nullable annotation on parameter x.

I believe annotation should be removed from this parameter

**Comment by mernst** [comment]
Thanks for pointing out this problem.  `@Nullable` was written in the wrong location; it should have been written on the array, not the (primitive) array annoattions.  I have committed a fix.
