### ISSUE TITLE
No outputs for -AsuggestPureMethods.

### ISSUE THREAD

**Issue by QRXqrx** [typetools/checker-framework#3285]
Hi there,
I'm new in program analysis, and I'm trying to make purity analysis through checker framework.  I follow the lead of Manual to get suggestion from PurityChecker in order to know which method is side-effect, and here is the cmd line I use:
`` javacheck -processor org.checkerframework.util.PurityChecker -AsuggestPureMethods -AcheckPurityAnnotations -AprintAllQulifiers -verbose -version  MyClass.java``

I create a alias of javac(javacheck) follows your tutorial, may you could switch javacheck to javac
 
And the output is like follows:
![image](https://user-images.githubusercontent.com/49576982/80896745-29550c00-8d24-11ea-9cf7-a99023a18b38.png)

The simple class I use is as follows
```
public class MyClass{

    private static class A {
        int a;
        int b;
    }

    // Pure
    // @SideEffectFree
    static void method1(A a) {
        System.out.println(a.a + " + " + a.b);
    }

    // Impure
    // @SideEffectFree
    static void  method2(A a) {
        a.a = 123;
        a.b = 321;
        System.out.println(a.a + " + " + a.b);
    }


    public static void main(String args[]) {
	A a = new A();
        a.a = 1;
        a.b = 1;
        method1(a);
        method2(a);
    }

}
```
> If you supply the command-line option -AsuggestPureMethods, then the Checker Framework will suggest methods that can be marked as @SideEffectFree, @Deterministic, or @Pure.

According to your mannual, I thought I could get some tips of using purity annotaions,  but the fact is that I didn't get any useful feedback. Did I do sth wrong? If I did, please tell me how to get what I want(i.e. distinguish pure and impure methods) properly at your convinience, thank u very much!

**Comment by xingweitian** [comment]
Hi, I think the processor should be `org.checkerframework.framework.util.PurityChecker`. Also, there is a typo: `-AprintAllQulifiers` should be `-AprintAllQualifiers`.

**Comment by QRXqrx** [comment]
> Hi, I think the processor should be `org.checkerframework.framework.util.PurityChecker`. Also, there is a typo: `-AprintAllQulifiers` should be `-AprintAllQualifiers`.

Hey, thanks for replying! I tried you suggestion and got output like this:
![image](https://user-images.githubusercontent.com/49576982/80897562-a8e6d900-8d2c-11ea-8924-fa881bd06a72.png)
cmd line:
``javacheck -processor org.checkerframework.framework.util.PurityChecker -AsuggestPureMethods -AcheckPurityAnnotations -AprintAllQualifiers MyClass.java``

You can see here is still no output. I have also tried ``-verbose``  and ``-version`` but I don't think I have found the information I want from that output.

By the way, according to your reply, I think there are mistakes within you manual. It is on page 125
![image](https://user-images.githubusercontent.com/49576982/80897538-48f03280-8d2c-11ea-92f5-e6a20642b7a5.png)

**Comment by wmdietl** [comment]
Thanks for noticing the problem in the manual! Do you want to file a PR that fixes it?

Regarding the empty suggestions: `System.out.println` isn't side-effect-free:
https://github.com/typetools/jdk/blob/master/src/java.base/share/classes/java/io/PrintStream.java#L893

So all of the methods could have side effects, so there is nothing to suggest.
If you simplify the code, e.g. method1 to just `return a.a + a.b;` you will get purity suggestions.

**Comment by QRXqrx** [comment]
@wmdietl 
Thanks for replying. What you suggest does work. I have gotten information I want from my simple example.
I'd like to file a PR, but I'm not sure what to do since I haven't file one before. It seems I need to open a project and push code for reviewing(but since this is a PR for manual so I don't think this is the a proper way). Or should I create a branch for this issue first? Let me know if there anything I can help :-) .

**Comment by wmdietl** [comment]
@QRXqrx These two posts by @mernst give a great overview of version control and how to make a PR:
https://homes.cs.washington.edu/~mernst/advice/version-control.html
https://homes.cs.washington.edu/~mernst/advice/github-pull-request.html

The process is the same for anything in a repository.
You want to edit https://github.com/typetools/checker-framework/blob/master/docs/manual/purity-checker.tex#L13
