### ISSUE TITLE
Can't write annotations in try-with-resources statement

### ISSUE THREAD

**Issue by jwaataja** [typetools/checker-framework#3305]
When I declare a variable with an annotation in a try statement, I get an error.
```java
import org.checkerframework.checker.nullness.qual.*;

public class C {
  public static void f() {
    try (@Nullable AutoCloseable obj = null) {
    } catch (Exception e) {
    }
  }
}
```
```
C.java:5: warning: [type.anno.before.modifier] write type annotation @Nullable() immediately before type, after modifiers [final]
    try (@Nullable AutoCloseable obj = null) {
                                 ^
```

This seems to be because there's an implicit "final" modifier after the annotation. This modifier doesn't actually exist, so it should be ignored.

**Comment by wmdietl** [comment]
Thanks for the report.
In your example the `@Nullable` isn't necessary, because it's the default for that location.
But in general I agree that that warning shouldn't be issued in such code.
