### ISSUE TITLE
TypeUseLocation.ALL_EXCEPT_LOCALS is mentioned in DefaultQualifier's javadoc but no longer exists

### ISSUE THREAD

**Issue by PawelLipski** [typetools/checker-framework#3316]
As of v3.4.0, `org.checkerframework.framework.qual.DefaultQualifier`'s javadoc has the following mention:

```javadoc
 * &nbsp; @DefaultQualifier(value = Interned.class, locations = ALL_EXCEPT_LOCALS)
```

but no such constant seems to be defined anywhere.

**Comment by mernst** [comment]
Thanks for pointing this out.
