### ISSUE TITLE
Integrate javadoc.astub with typetools/jdk

### ISSUE THREAD

**Issue by wmdietl** [typetools/checker-framework#3357]
https://github.com/typetools/checker-framework/blob/4ecaa4cbe17a14afd3dbcd009b2a442fc263fa65/checker/src/main/resources/javadoc.astub#L1 mentions that

```
// This file, javadoc.astub, models the JavaDoc classes in the JDK 8's
// com.sun.javadoc package, which were renamed/removed in JDK 11 and therefore
// cannot be part of an annotated JDK.
```

I looked at a few of these classes and they are still available:
https://github.com/typetools/jdk/blob/master/src/jdk.javadoc/share/classes/com/sun/javadoc/Doc.java
https://github.com/typetools/jdk/blob/master/src/jdk.javadoc/share/classes/com/sun/javadoc/RootDoc.java
etc.

Some of these classes already contain annotations.
Is there still a reason to keep `javadoc.astub` separate?

**Comment by mernst** [comment]
This is now possible, because the annotated JDK is now being read as stub files.
In Java 8, Javadoc classes were in tools.jar and thus did not appear in the annotated JDK jar file.
