### ISSUE TITLE
Add message parameter to castNonNull(@Nullable T ref) so the exceptions can be easier to read

### ISSUE THREAD

**Issue by vlsi** [typetools/checker-framework#3424]
The current method `org.checkerframework.checker.nullness.NullnessUtil#castNonNull(@Nullable T ref)` does not provde a way to describe the reference, so the assertion error would be hard to understand.

What do you think if an extra parameter was added?

Sample:

```java
public void addFunctions(ResultSet rs) throws SQLException {
  while (rs.next()) {
    func.put(castNonNull(rs.getString(1), "function_name"), rs.getInt(2));
  }
}
```

**Comment by mernst** [comment]
@vlsi Thanks for the suggestion.  You can use the extra arguments if you build from source, or you can wait for the next release at the beginning of August.

**Comment by vlsi** [comment]
For now I've added my own `castNonNull` method, and the key driver was that IntelliJ IDEA somehow fails to decompile checkerframework.jar (I've filed an issue), so it doesn't understand `castNonNull` ensures non-nullness.
