### ISSUE TITLE
Complete the implementation of FlowExpressions.BinaryOperation

### ISSUE THREAD

**Issue by smillst** [typetools/checker-framework#3474]
https://github.com/typetools/checker-framework/pull/3397/ missed the following tasks:

- [ ] Add BinaryOperation to ` JavaExpression#fromTree(AnnotationProvider, ExpressionTree, boolean)`
- [ ] Document the extension of the "Java" expression language in [the manual](https://checkerframework.org/manual/#java-expressions-as-arguments).

**Comment by wmdietl** [comment]
We should also add cross-references between the `internalReprOf` methods mentioning that they should be kept in sync and mention the manual section in the code.

**Comment by wmdietl** [comment]
@txiang61 Can you take a look at these?
