### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by bodorjzsolt** [typetools/checker-framework#3500]
Please shed some light on the following situation: in some files where file contains code derived from **, beside the GPL 2 with Classpath Exception reference, appears the following reference style for the original licensing:

"This file is available under and governed by the GNU General Public
License version 2 only, as published by the Free Software Foundation.
However, the following notice accompanied the original version of this
file:
 
_original license notice_"

Does this means the file is under GPL 2 with Classpath Exception AND GPL 2 only, as the second reference does not contain the exception?
Thank you in advance!

**Comment by mernst** [comment]
Can you please clarify your question?

> in some files where file contains code derived from **

1. What is "**"?
2. What exact files contain the text you are referring to?

Thanks.

**Comment by bodorjzsolt** [comment]
Yes of course, these are some examples
, 
checker-framework-checker-framework-2.5.2/checker/jdk/nullness/src/org/w3c/dom/ls/LSResourceResolver.java
or this 
checker-framework-checker-framework-2.5.2/checker/jdk/nullness/src/java/util/concurrent/BlockingDeque.java

**Comment by bodorjzsolt** [comment]
The question of course, it's not about any code derived from GPL-2.0 only code.
The files contain code under either W3C license or CC0.

**Comment by mernst** [comment]
Thanks for the clarification.  The current version of the Checker Framework is 3.5.0.  It does not contain these files.

Could you please use the most recent version of the Checker Framework?  If its licensing is not clear, please let us know and we will clarify it.

Regarding the files in the old 2.5.2 version of the Checker Framework:  Those files are verbatim from the JDK, so if you are able to use the JDK, you can use that version of the Checker Framework.  If you have questions about the JDK's license terms, please direct them to the JDK developers.
