### ISSUE TITLE
@Inherited annotations written in a stub file 

### ISSUE THREAD

**Issue by Nargeshdb** [typetools/checker-framework#3594]
If we have an @Inherited annotation written in a stub file, subclasses in source code will not inherit the annotation! 
e.g. Consider InheritedAnnotationType:
```
@Inherited
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface InheritedAnnotationType {
 ...   
}
```

Add @InheritedAnnotationType to Socket in a stub file:

```
@InheritedAnnotationType
class Socket implements Closeable {...}

```
Then, SubSocket doesn't inherit @InheritedAnnotationType!
`class SubSocket extends Socket {}`

**Comment by msridhar** [comment]
I think the question here is, is there any way to annotate a JDK library class declaration, via stub files, modifying the annotated JDK, or some other trick, such that the annotation will be inherited?  As @Nargeshdb notes above just using `@Inherited` does not seem to work.

**Comment by smillst** [comment]
>is there any way to annotate a JDK library class declaration, via stub files, modifying the annotated JDK, or some other trick, such that the annotation will be inherited?

Not currently, but I made a PR #3600 that reads inherited annotations from stub files and applies them to subclasses.

**Comment by msridhar** [comment]
Thanks, @smillst!  @Nargeshdb is working on testing out #3600
