### ISSUE TITLE
@StubFiles docs should indicate need to customize build config

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#3720]
In order for the `@StubFiles` annotation to work properly (as documented [in the manual](https://checkerframework.org/manual/#stub-creating), Section 31.5.5), `.astub` files from the source directories need to be copied into the jar file when the checker is built.  This is accomplished in the main Checker Framework via the following Gradle config:
```gradle
sourceSets {
    main {
        resources {
            // Stub files, message.properties, etc.
            srcDirs += ['src/main/java']
        }
    }
}
```
But the need for this configuration is not documented.  We should document this need, and possibly add the relevant build configuration to the [checker template](https://github.com/typetools/templatefora-checker).  In the documentation / template, maybe the example config should be more targeted and only include `.astub` files, so checker developers do not end up with unexpected files in their final jars.

**Comment by mernst** [comment]
I agree with this.  Thanks for pointing it out!
If you could make a pull request with the suggested documentation (and the build configuration for the template), we would be very grateful.

**Comment by msridhar** [comment]
Closing as relevant PRs have landed
