### ISSUE TITLE
How-to guide for getting started with nullness checker

### ISSUE THREAD

**Issue by vlsi** [typetools/checker-framework#3740]
Hi,

I've been working with checker-framework for a while, and my overall impression of the documentation is that the documentation is there, it does clarify corner cases, however, [getting started](https://checkerframework.org/manual/#nullness-getting-started) seems too short. I know I read most of the chapters on nullness/generics multiple times, however, most of the time is like "here are all the different nuts and bolts, now you can go and build your own car".

Do you think there's room for adding samples (including generics) there?

I think I'll complete adding nullable annotations to Apache Calcite soon, and I expect dev documentation would need to be updated to mention "how to place nullable annotations and what error messages even mean".

For instance, `<T>`, `<T extends Object>`, `<T extends @Nullable Object>`, `<@Nullable T>` are likely to be tricky for the ones who see them for the first (and second!) time :)
Should method parameters be `List<@Nullable String>` or should it be `List<? extends @Nullable String>`?
Should method return value be`List<@Nullable String>` or should it be `List<? extends @Nullable String>`?
Should I use `Objects.requireNonNull` or `Nullness.castNonNull` or `SuppressWarning` or `assert`?
and so on. 

I've added samples to [pgjdbc documentation](https://github.com/pgjdbc/pgjdbc/blob/01dbbac5b6c43e1079a463119e13c1bee74cbfdb/CONTRIBUTING.md#null-safety), however, the code there is not using generics much.

One of the "issues" with the current guide is it provides too much flexibility (~ "if you use CLIMB", "if you are not using CLIMB", ...), so it becomes harder to read.

What do you think of adding CLIMB-opinionated series of samples to "getting started"? (e.g. something like in pgjdbc, with more samples and generics)

**Comment by mernst** [comment]
I agree wholeheartedly with your comments.  Thank you for raising this point.

Improving this documentation has been a long-standing desire.  We have had trouble because it can be very difficult for an expert to know what a new user needs.  Therefore, your perspective is very valuable.

Your main suggestion is to add more samples to that section of the manual, and I agree with that.  Thanks for suggesting some specific examples.

> what error messages even mean

I would like to improve the Checker Framework's error messages to address this where possible.  But it would still be useful to better explain the underlying concepts that users need to understand in order to understand a type-checking error.

> One of the "issues" with the current guide is it provides too much flexibility (~ "if you use CLIMB", "if you are not using CLIMB", ...), so it becomes harder to read.

I agree that sounds like an issue, and the Checker Framework manual should be opinionated that users use CLIMB-to-top.
However, I didn't find that text in https://checkerframework.org/manual/ .  Could you please point it out to me?
To partially address your suggestion, I did make a [commit that de-emphasizes the CLIMB-to-top terminology](https://github.com/typetools/checker-framework/commit/ba0d45c05d1c1d0a3f297dbed7cd3d9f41e1d751).

**Comment by vlsi** [comment]
> I agree that sounds like an issue, and the Checker Framework manual should be opinionated that users use CLIMB-to-top.

It looks like I remembered the following paragraph from inference section:

> Inference of @Nullable: If your code uses the standard CLIMB-to-top default (Section 28.5.3) or the NonNull default, then use the AnnotateNullable tool of the Daikon invariant detector.

If the guide is already CLIMB-to-top biased, then there's no problem adding the same samples.

**Comment by vlsi** [comment]
> We have had trouble because it can be very difficult for an expert to know what a new user needs

Frankly speaking, my initial thought was to automatically infer annotations, and I even spent some time trying to execute Daikon (or something like that). However, it failed, and I went with annotating the thing manually.

Then it was non-obvious that `@Nullable` and `@NonNull` annotations are more like "local to declaration" (== local to method), and `@RequiresNonNull` / `@EnsuresNonNull` are inter-method declarations.

It turns out the current "getting started" has the following:

> To indicate a method precondition (a contract stating the conditions under which a client is allowed to call it), you can use annotations such as @RequiresNonNull (see Section 3.2.2).

That sentence is right in theory, however, it seems to be written from the perspective of "ok, all my code is already annotated, how do I add a new method that requires a precondition?"
On the other hand, when the user is adding the Checker Framework to already existing codebase, the question is more like "ok, suppose you have X and Y methods, how do you make the checker happy?"

> I would like to improve the Checker Framework's error messages to address this where possible. 

Well, there's a relevant section for initialization checker: https://checkerframework.org/manual/#initialization-warnings

I agree at best the error messages should be self-descriptive, however, making generic-related errors readable is challenging.

---

What do you think of suggesting to add error_prone verifications before annotating nullness by the way?
It looks like the checkers highlight somewhat related issues (at least they might intersect), and fixing error-prone issues is easier (because the number of violations is probably less).
