### ISSUE TITLE
Exception parameter lowerbounds should be the default type, not the top type

### ISSUE THREAD

**Issue by kelloggm** [typetools/checker-framework#3839]
The method `getExceptionParameterLowerBounds` in `BaseTypeVisitor` (https://github.com/typetools/checker-framework/blob/master/framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java#L2488) defaults to top. I think it should use the default qualifier in the hierarchy instead. As it is, any checker that uses a non-top default has to override this method.

I created a small project that demonstrates the problem using a modification of the `templatefora-checker` repository. https://github.com/kelloggm/bottom-default-problems. The difference is that I've switched the default annotation to be bottom rather than top. There are three branches:
* `without-defaultfor`, which shows what happens with a simple test case (`tests/templatefora/SimpleException.java`) for an exception. If you run `./gradlew build` and inspect the failing tests, you'll see a `method.invocation.invalid` error at line 12. (Note that the `inconsistent.constructor.type` warnings can be ignored, for the purposes of this issue.)
* `with-defaultfor`, which is similar to the above but adds a `@DefaultFor({TypeUseLocation.EXCEPTION_PARAMETER})` annotation to the definition of the bottom type, to remove the error from the previous step. Since bottom is the default, it makes sense for exception parameters to be the default, too. (Note that this is why the nullness checker doesn't have this problem - all exception parameters are non-null, so it doesn't do any checks for them at all - see e.g. https://github.com/typetools/checker-framework/blob/master/checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java#L661) Running `./gradlew build` again, you can note that the error mentioned in the previous bullet has been replaced by an `exception.parameter.invalid` error.
* `simple-fix`, which fixes the error by changing `getExceptionParameterLowerBounds` to return bottom rather than top.

In general, I think it would simplify the design and testing of new non-top-default checkers if this method returned whatever the checker's default annotation was, rather than always returning top. Effectively, that's what the above fixes I've described do for the checker I just described.

I don't see any reason this would be unsound, but I might be missing something. If not, I'd be happy to take a shot at implementing this.

**Comment by smillst** [comment]
The Checker Framework doesn't check that the exceptions caught by a catch clause are a subtype of the exception parameter.  So, it's not sound to use a non-top default for an arbitrary checker.  All thrown exceptions must be nonnull, so it's sound for the Nullness Checker to default exception parameters to `@NonNull`.

**Comment by mernst** [comment]
> The Checker Framework doesn't check that the exceptions caught by a catch clause are a subtype of the exception parameter.

The reason for this is that the Checker Framework doesn't create an exhaustive mapping from `throw` statements to `catch` clauses, indicating which ones are feasible.  (I think that doing so might require a non-modular analysis.)  If a `catch` clause had a non-top type, then the Checker Framework would need to issue a warning at every `throw` that might create an exception with a top type.

Maybe this should be documented somewhere.

**Comment by mernst** [comment]
Here is an alternative design:

If the Checker Framework defaults exception parameters to type *T*, then the Checker Framework must issue a warning at every `throw` statement whose argument might not be a subtype of *T*.  (When *T* is top, there are no such warnings.)

What do you think of that?  It would permit each checker to choose its own default for exception parameters -- or each checker could use its normal defaulting rules.

**Comment by mernst** [comment]
@kelloggm @smillst Ping.

**Comment by kelloggm** [comment]
> For deep type systems such as tainting, where the type of a field can determine the type of its containing instance, another loophole is those few exceptions that carry a user-supplied payload. (Example: a user passes a secret regex to the JDK, and the JDK throws a format exception that includes the regex. Or, the user passes a secret integer and the JDK throws a DivideByZeroException that reveals the value.) I think this loophole does not exist for non-deep type systems.

I think this concern is really important. For these sort of "deep" type systems, I agree that the framework's current behavior (treat all exception parameters as top) is the only sound thing to do, to guard against exactly the cases you've described. Thanks for reminding me of that; when I filed the issue, I hadn't considered these cases.

> I think that this issue is a feature request to have a boolean in the implementation of BaseTypeChecker with the implementation, so that each type system whose default is not the top doesn't need to override a few methods to re-implement the functionality.

That's partially correct. It was also an excuse for me to write up my concerns and present them to you all, because I couldn't figure out why the implementation was the way that it was. Your comment about JDK exceptions has cleared this up for me, I think, so I'm going to close this issue.
