### ISSUE TITLE
A wildcard with an implicit upper bound applies its own defaulting rules to its corresponding type parameter's bound

### ISSUE THREAD

**Issue by cpovirk** [typetools/checker-framework#3845]
```java
$ cat DefaultClash.java
import org.checkerframework.checker.nullness.qual.Nullable;
import org.checkerframework.framework.qual.DefaultQualifier;
import org.checkerframework.framework.qual.TypeUseLocation;

class Holder<T> {
  final T value;

  Holder(T value) {
    this.value = value;
  }
}

interface HolderSupplier<H extends Holder<Object>> {
  H get();
}

@DefaultQualifier(value = Nullable.class, locations = TypeUseLocation.ALL)
class DefaultClash {
  Object go(HolderSupplier<?> s) {
    if (s != null) {
      return s.get();
    }
    return "";
  }
}
```

```
checker-framework-3.7.0 $ checker/bin/javac -processor org.checkerframework.checker.nullness.NullnessChecker DefaultClash.java
DefaultClash.java:19: error: [type.argument.type.incompatible] incompatible type argument for type parameter H of HolderSupplier.
  Object go(HolderSupplier<?> s) {
                           ^
  found   : ? extends @Initialized @NonNull Holder<@Initialized @Nullable Object>
  required: @Initialized @NonNull Holder<@Initialized @NonNull Object>
1 error
```

At a high level, I would expect for `HolderSupplier<?>` to always be valid, with CF filling in an appropriate value for the implicit upper bound.

Drilling in a little more: If I'm reading the code right, the `@Nullable Object` argument to `Holder` comes from the default that's in effect at the _use_ site -- that is, where `HolderSupplier<?>` is written. I would instead expect for it to use the default of `@NonNull Object`, since that's the default in effect where `Holder<Object>` appears in the source code.

Among the code involved is here:
https://github.com/typetools/checker-framework/blob/88f1dd2b094df90ddbc202bc3f7d284f8aaf05a8/framework/src/main/java/org/checkerframework/framework/type/BoundsInitializer.java#L584-L591

That gives us a `TypeMirror`, which is then converted to an unannotated `AnnotatedTypeMirror` to be filled in later by the defaults in effect at the wildcard site:
https://github.com/typetools/checker-framework/blob/88f1dd2b094df90ddbc202bc3f7d284f8aaf05a8/framework/src/main/java/org/checkerframework/framework/type/BoundsInitializer.java#L599

It seems like what we'd want for the type-parameter bound is to create the `AnnotatedTypeMirror` based on the defaults in effect at the type-parameter declaration.

We do have access at this point to the `AnnotatedTypeFactory`, so perhaps we could call `getAnnotatedType` on `wildcard.getTypeVariable().asElement()` (and then extract `getUpperBound()`). (When `getTypeVariable()` is not available, we could probably get what we need from `wildcardToTypeParam((com.sun.tools.javac.code.Type.WildcardType) wildcard.getUnderlyingType())`.) That would (I think) apply appropriate defaults. But I worry that that would be approaching the problem at the wrong "level." In particular, `getAnnotatedType` could call back into `BoundsInitializer` (I think?), and I wonder if that could produce infinite loops with recursive generics like `Comparable<E extends Comparable<? super E>>` (or otherwise violate assumptions).

The good news is that the example above is just an unnecessary warning, rather than an unsoundness. But it seems likely that it could be turned into unsoundness. And I did actually hit this one in some actual code, unlike half of my reports so far :)

(One other bad idea I considered: Setting the bound not to the type parameter's bounds but rather to a usage of the corresponding type variable. For example, for `class Foo<N extends Number> {} Foo<?> foo;`, I could treat `Foo<?>` as `Foo<? extends N>`. But this is wrong because later logic would sometimes substitute in specific values for `N`, which would be incorrect.)

**Comment by Vyom-Yadav** [comment]
I know I shouldn't write this message here. But I really need help to get started.  ( Yes, I really need help )

So below is a small message about me and what skills I have

Hey everybody, I am new to coding, I have started learning Java as my first language, I wish to contribute to open source, I know the basics of java and  OOP and currently, I am learning collection framework in java. I have done a lot of practice on the topics I have learned on various websites like geeks for geeks, Hackerrank, HackerEarth. I have also learned the commands on git and GitHub. Am I skilled enough to contribute or shall I learn more to contribute? If I am skilled enough then please can anybody help me get started? 

Looking forward to your reply.

**Comment by mernst** [comment]
@Vyom-Yadav Please don't spam the issue tracker with messages that are not relevant to the issue, as this one is not.

**Comment by cpovirk** [comment]
Hmm, is this the kind of thing that `PropagationTypeAnnotator` is intended to patch up? And maybe it's just not working in this case for some reason?

(I _may_ have seen a similar problem with _usages of type variables_ and _their_ bounds. If so, I don't think that problem would be covered by `PropagationTypeAnnotator` in any case. But I would have to look into whether such a problem actually exists.)

**Comment by smillst** [comment]
Thanks for the report!  I'm currently working on implementing capture conversion correctly which will improve wildcards.  Once that's done, I'll see if this is fixed, if not, I'll fix it.
