### ISSUE TITLE
3.7.1: uninferredTypeArgumentScanner consumes significant amount of memory in AnnotatedTypeMirror

### ISSUE THREAD

**Issue by vlsi** [typetools/checker-framework#3851]
Apparently, verification of Calcite codebase requires to bump `-Xmx` to 2g or something like that, and it turns out noticeable memory is taken by `SimpleAnnotatedTypeScanner`:

https://github.com/typetools/checker-framework/blob/9dbf0c7c06210a9cb926242a8181eb0dd888ab04/framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeMirror.java#L813-L820

Could it be a static instance and/or `ThreadLocal`?

`NullnessAnnotatedTypeFactory` consumed ~50MiB

<img width="995" alt="Снимок экрана 2020-11-04 в 1 10 30" src="https://user-images.githubusercontent.com/213894/98046407-37065e00-1e3b-11eb-8935-80308eddca03.png">

~ 50% of that was consumed by empty `IdentityHashMap` in `SimpleAnnotatedTypeScanner`

<img width="688" alt="Снимок экрана 2020-11-04 в 1 11 01" src="https://user-images.githubusercontent.com/213894/98046417-3c63a880-1e3b-11eb-871c-3800a08ceabb.png">

There are 72226 `SimpleAnnotatedTypeScanner` instances which are referenced from `AnnotatedTypeMirror$...` classes

<img width="806" alt="Снимок экрана 2020-11-04 в 1 11 29" src="https://user-images.githubusercontent.com/213894/98046424-41c0f300-1e3b-11eb-8e72-5248018598e7.png">

**Comment by smillst** [comment]
Thanks for tracking this down! I opened #3852 which clears the IdentityHashMap as soon as possible.  That should help, but I haven't tested it.
