### ISSUE TITLE
SBT Support

### ISSUE THREAD

**Issue by sirinath** [typetools/checker-framework#3862]
Can [SBT](https://www.scala-sbt.org/) support be added.

**Comment by mernst** [comment]
Yes!  Would you be willing to contribute it?  I assume you are an SBT user, which none of the Checker Framework developers is.  Therefore, you can do this much more efficiently than we can, and you can test it in real-world scenarios which we cannot.

The [introduction to the "Integration with external tools" chapter](https://checkerframework.org/manual/#external-tools) (before the first section) gives some hints about how to get started.

**Comment by sirinath** [comment]
I am not that familiar with SBT internals.

**Comment by mernst** [comment]
To write a plugin might require use of SBT internals.  To write a manual section about how to change your own build files should be possible without knowledge of SBT internals.  Would you be willing to do that?  Thanks in advance.

**Comment by sirinath** [comment]
Is the Checker Framework configured through java options?

**Comment by sirinath** [comment]
Can you specify all checkers?

**Comment by mernst** [comment]
> Is the Checker Framework configured through java options?

Yes.  The [Introduction](https://checkerframework.org/manual/#introduction) says:

> These checkers are easy to use and are invoked as arguments to javac.

That is also explained in the ["Integration with external tools" chapter](https://checkerframework.org/manual/#external-tools), which says:

> If your build system or IDE is not listed above, you should customize how it runs the javac command on your behalf. See your build system or IDE documentation to learn how to customize it, adapting the instructions for javac in [Section 35.6](https://checkerframework.org/manual/#javac).

**Comment by sirinath** [comment]
I think you can do something like `javacOptions ++= Seq( ... )`

**Comment by sirinath** [comment]
Following would be a way to get it working:

- JDK 8

```
javacOptions ++= Seq(
    "-J-Xbootclasspath/p:$CHECKERFRAMEWORK/checker/dist/javac.jar",
    "-cp $CHECKERFRAMEWORK/checker/dist/checker-qual.jar",
    "-processorpath $CHECKERFRAMEWORK/checker/dist/checker.jar",
    "-processor org.checkerframework.checker.nullness.NullnessChecker",
    "-source 8", "-target 8"
  )
```

- JDK 11
  - For compiling non-modularized code:

```
javacOptions ++= Seq(
    "-J--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED",
    "-processorpath $CHECKERFRAMEWORK/checker/dist/checker.jar",
    "-cp $CHECKERFRAMEWORK/checker/dist/checker-qual.jar",
    "-processor org.checkerframework.checker.nullness.NullnessChecker"
  )
```

  - For compiling modularized code:

```
javacOptions ++= Seq(
    "-J--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED",
    "-processorpath $CHECKERFRAMEWORK/checker/dist/checker.jar",
    "--module-path $CHECKERFRAMEWORK/checker/dist/checker-qual.jar",
    "-processor org.checkerframework.checker.nullness.NullnessChecker"
  )
```

**Comment by mernst** [comment]
Thank you for these details.  I have created a pull request to put them in the manual.

**Comment by sirinath** [comment]
Can you mention an all available `processor` list on one place so this line can be directly copied for the `javac` options?

**Comment by mernst** [comment]
Do you mean the list that appears in https://checkerframework.org/manual/#introduction?

I don't think it's good style to run every possible checker.  The [manual](https://checkerframework.org/manual/#get-started-start-small) recommends starting with just one, so I don't want to violate this recommendation in the new section by showing a verbose `-processor` argument that includes every checker.

I have added a cross-reference to section 2.2, however.  Does that help?

**Comment by sirinath** [comment]
Yes. But you can add a table/list of processors which you can choose from.

**Comment by mernst** [comment]
Where in the manual would you like that table/list to appear?

**Comment by sirinath** [comment]
In the Intro?

**Comment by mernst** [comment]
You said "in the intro", but [the list is already in the introduction](https://checkerframework.org/manual/#introduction).  It's literally the 4th sentence in the manual.

**Comment by mernst** [comment]
OK, you edited your comment from "in the intro" to "Better under command line where the checkers are listed out."  I don't understand what you are referring to.  Can you be more specific, with a concrete reference to a manual section?

**Comment by sirinath** [comment]
All information is scattered around in the manual. So you can have:
- list of all relevant `javac` option in one place with a summary
- list of all annotation with a summary

It can be 2 appendices if it turns out to be too long.

**Comment by mernst** [comment]
I'm going to merge the pull request now, since it addresses the original issue.

A distinct issue is creating an appendix that mixes together all information about all checkers.  If you wish to do that, please open a pull request for it.

Thanks again for the SBT instructions; I appreciate it!
