### ISSUE TITLE
Annotated JDKs missing

### ISSUE THREAD

**Issue by Meijuh** [typetools/checker-framework#3871]
Annotated JDKs `>3.3.0` are missing in at least the following repositories:

* Maven Central: https://mvnrepository.com/artifact/org.checkerframework/jdk8,
* jcentral: https://repo.jfrog.org/artifactory/libs-release-bintray/org/checkerframework/jdk8/.

This is problematic because this causes for instance the [nebula linter](https://github.com/nebula-plugins/gradle-lint-plugin) to fail, because it tries to analyze dependencies for a jar that can not be found.

Should those jars be uploaded there? And, is there a workaround for this problem? Is there an alternative repository I can use that does have those annotated JDKs?

**Comment by mernst** [comment]
I'm sorry you are having trouble.  Thanks for getting in touch.

The [release notes](https://github.com/typetools/checker-framework/releases) for [version 3.4.0](https://github.com/typetools/checker-framework/releases/tag/checker-framework-3.4.0) say:

> The annotated `jdk8.jar` is no longer used. You should remove any occurrence of `-Xbootclasspath/p:.../jdk8.jar` from your build scripts. Annotations for JDK 8 are included in checker.jar.

So:
 * If you are using Checker Framework 3.3.0 or earlier, use the `jdk8.jar` artifact.  (But, if you are using an old version of the Checker Framework, we recommend that you upgrade.)
 * If you are using Checker Framework version 3.4.0 or later, don't use the `jdk8.jar` artifact.  Just remove any mention of it from your build files.

In your context, which version of the Checker Framework are you using?
Is there some way we could update the documentation to make this more clear?

**Comment by mernst** [comment]
@Meijuh Does this address your problem?

**Comment by mernst** [comment]
I'm closing this issue because I provided a fix and the original poster is not responding.  If anyone else has the problem, and the fix does not work, let us know.
