### ISSUE TITLE
Allow suppressing warnings toArray.nullable.elements.not.newarray and toArray.nullable.elements.mismatched.size

### ISSUE THREAD

**Issue by vlsi** [typetools/checker-framework#3908]
It looks like `toArray.nullable.elements....` can't be suppressed.

I tried `@SuppressWarnings("toArray.nullable.elements.not.newarray")` at both statement, method, and even `-AsuppressWarnings=toArray.nullable.elements.mismatched.size,toArray.nullable.elements.not.newarray` level, however it does not suppress the warnings.

Will post the reproducers later, however, for now I suppressed the warning with `"all"`, so suppression works, however, named suppression does not.

Is it caused by upper-case letter A in `toArray`?

**Comment by mernst** [comment]
Your analysis is correct.  Sorry for the bug!  I have opened a pull request to fix it.
