### ISSUE TITLE
How to model state machine with the nullness checker?

### ISSUE THREAD

**Issue by krocard** [typetools/checker-framework#3932]
We have many classes with a state and members that must be nonNull depending on that state.
How can that be expressed concisely with the nullness checker?

For example, the following class constraints

~~~ java
class StateMachine {
  int state;
  @Nullable Object a; // must be non null on state A
  @Nullable Object ab; // must be non null in state A and B
  @Nullable Object bc; // ... 
 // ...
}
~~~

can currently be expressed by writing a series of to get/set the state:

~~~ java
class StateMachine {
  @RequiresNonNull({"a", "ab"})
  void setStateA() { state = A; }
  @EnsuresNonNullIf({"a", "ab"}, result = true)
  @IgnoreWarning(...)
  int isStateA() { return state == A; }
 // ...
}
~~~

But that is a *lot* of boilerplate. Is there a way to avoid it?

Ideally something like
~~~ java
class StateMachine {
 @IsNonNullFor({"a", "ab"}, value = A)
 @IsNonNullFor({"ab", "bc"}, value = B)
 int state;
}
~~~
or even 
~~~ java
class StateMachine {
  int state;
  @NullableIf(expression = "state", value = {"A"})
  Object a; // must be set on state A
  @NullableIf(expression = "state", value = {"A", "B"})
  Object ab; // must be set in state A and B
  @NullableIf(expression = "state", value = {"B", "C"})
  Object bc; // ... 
 // ...
}
~~~

Note: This is for parsing classes in Android, so runtime overhead are to be avoided.

**Comment by mernst** [comment]
It sounds like you have a solution, but you are looking for a more concise solution.  To answer your question, the Nullness Checker doesn't currently have a more concise way to express such a state machine.

I'll close this issue now.  If this is a major annoyance, we would accept a pull request that adds more concise syntax.
