### ISSUE TITLE
[Feature] CheckThrows to see that the throws keyword in the method declaration is completely defined

### ISSUE THREAD

**Issue by xenoterracide** [typetools/checker-framework#4032]
So currently if you are using a checked exception, java requires you to add it to throws if you aren't handling it. What I'd like to see is that ALL exceptions checked or not are defined in the throws declaration. This will not make them checked, but will allow you to see them, even if something else is obscuring the code, or otherwise the method is undocumented.

good
```java
void myThrows() throws RuntmeException {
   throws new RuntimeException();
}
```

bad
```java
void myThrows()  {
   throws new RuntimeException();
}
```

**Comment by mernst** [comment]
As stated, this would require every method to declare `OutOfMemoryError`, `NoSuchFieldError`, and many others.  Is that what you want?  If not, could you clarify your feature request?

Maybe you want this feature only for exceptions thrown by the Java code but not by the JVM.  What about exceptions that might be thrown by the JDK?  This feature request seems to require annotating all JDK methods with longer throws clauses.

Anyway, if you could clarify to give a complete specification, that would help us to understand the feature request.  Thanks!

**Comment by xenoterracide** [comment]
> Anyway, if you could clarify to give a complete specification, that would help us to understand the feature request. Thanks!

I don't think I know java well enough to give you a complete specification. But to clarify based on what you've suggested, I'd say Java code, ideally including the ones in the jdk. I wouldn't do the ones by the JVM.

**Comment by mernst** [comment]
I'm closing this for now because it lacks a complete specification of the desired behavior.  We are happy to re-visit it once there is a specification to guide the design and implementation.
