### ISSUE TITLE
UnsupportedOperationCheck

### ISSUE THREAD

**Issue by xenoterracide** [typetools/checker-framework#4071]
for example

```
Collections.unmodifiableMap(...).put(...)
```

will throw an `UnsupportedOperationException`, it would be nice to have a check that would tell me this was going to happen. However, I would probably only enable this check if it could tell that the type behind the interface was, or actually could be an UnmodifiableMap, as I don't want to wrap every single `add` or `put` in a try catch, so the Check would have to look back to the implementation somehow, and not just the `Map` interface.

**Comment by mernst** [comment]
This is a good idea; thanks.  I will add a more detailed writeup with a possible design.  Then I'll close this issue to avoid cluttering the issue tracker.  Others can still find the closed issue (feel free to comment on it), and hopefully someone will take up the task of implementing it.

**Comment by xenoterracide** [comment]
why close it, unless it hasn't been implemented? just out of curiousity.

**Comment by mernst** [comment]
Per my comment, to avoid cluttering the issue tracker.  There are an infinite number of features someone could possibly implement in the future.  We would like to keep the issue tracker more focused.

There are other good ways to organize an issue tracker, but this one is ours. :-)
