### ISSUE TITLE
Error building checker-framework

### ISSUE THREAD

**Issue by jpschewe** [typetools/checker-framework#4114]
I build the checker framework as part of my application build so that I can pull in my version of the annotated JDK. Starting sometime yesterday I can no longer build from scratch without running my machine out of memory. It appears that something has changed in the checker build causing infinite forking of JVMs. Attached is a process tree partway through a build today before I killed it. [checker-build-tree.txt](https://github.com/typetools/checker-framework/files/5791703/checker-build-tree.txt)

Commands to reproduce:

```bash
mkdir checker
cd checker
git clone https://github.com/typetools/checker-framework.git checker-framework
cd checker-framework 
git checkout checker-framework-3.9.0
cd ..
git clone https://github.com/jpschewe/checker-typetools-jdk jdk
cd jdk
git checkout jps-dev
cd ../checker-framework
./gradlew assemble
```

**Comment by jpschewe** [comment]
Watching a build with text output I'm able to see a pattern. I see the string "Running:  (cd ../annotation-tools && ./.travis-build-without-test.sh)" show up over and over in the build.

**Comment by mernst** [comment]
I'm sorry you are having trouble.  I can reproduce your problem (thanks for the clear instructions!).

You are building using a non-HEAD version of `checker-framework`, but the HEAD version of other repositories such as `annotation-tools` and `stubparser`.  Unfortunately, that won't work.

Here are two options that ought to solve your problem:
 * Use the HEAD version of `checker-framework` -- that is, don't do `git checkout checker-framework-3.9.0`.  (This is my recommendation.  It is tested in CI.)
 * Use a non-HEAD version of `annotation-tools` and `stubparser` -- that is, clone them like you do `checker-framework` and `jdk`, and do `git checkout` to get the last release.  (This worked in CI as of the time of the release.)

**Comment by jpschewe** [comment]
I was previously using the HEAD version of checker-framework and found that was causing build errors. So I'm trying to stick to the released version. The errors I was getting are here:
```
/home/jenkins_fll-sw_linux/workspace/FLL-SW_master/checker/checker-framework/framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java:2253: error: cannot find symbol
        for (Map.Entry<VariableElement, AField> entry : m.getPreconditions().entrySet()) {
                                                         ^
  symbol:   method getPreconditions()
  location: variable m of type AMethod
/home/jenkins_fll-sw_linux/workspace/FLL-SW_master/checker/checker-framework/framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java:2271: error: cannot find symbol
        for (Map.Entry<VariableElement, AField> entry : m.getPostconditions().entrySet()) {
                                                         ^
  symbol:   method getPostconditions()
  location: variable m of type AMethod
/home/jenkins_fll-sw_linux/workspace/FLL-SW_master/checker/checker-framework/framework/src/main/java/org/checkerframework/common/wholeprograminference/scenelib/ASceneWrapper.java:171: error: cannot find symbol
                                aMethod.contracts = contractAnnotations;
                                       ^
  symbol:   variable contracts
  location: variable aMethod of type AMethod
/home/jenkins_fll-sw_linux/workspace/FLL-SW_master/checker/checker-framework/framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenes.java:276: error: cannot find symbol
                return amethod.vivifyAndAddTypeMirrorToPrecondition(fieldElement, typeMirror);
                              ^
  symbol:   method vivifyAndAddTypeMirrorToPrecondition(VariableElement,TypeMirror)
  location: variable amethod of type AMethod
/home/jenkins_fll-sw_linux/workspace/FLL-SW_master/checker/checker-framework/framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenes.java:278: error: cannot find symbol
                return amethod.vivifyAndAddTypeMirrorToPostcondition(fieldElement, typeMirror);
                              ^
  symbol:   method vivifyAndAddTypeMirrorToPostcondition(VariableElement,TypeMirror)
  location: variable amethod of type AMethod
```

In `annotation-tools` I see `3.9.16`
I don't see any recent tags in `stubparser`, so I'm not sure what commit is expected to be used for that dependency. The last tag in that repository is from 2017.

Is it the case that the latest tag in each of the repositories corresponds to the latest release tag of checker-framework? 

Looking at `checker/bin-devel/build.sh` I can see that it calls `./gradlew assemble` at the bottom of it. This is likely going to cause an infinite loop as this script was launched by `./gradlew assemble`.

**Comment by jpschewe** [comment]
I guessed that the commit in `stubparser` prior to the current one is the one that you're thinking of. This appears to work:
https://github.com/jpschewe/fll-sw/commit/2affb01a6953433bf7d0384d2255b85d78c32c4f

**Comment by mernst** [comment]
I'm glad that is working.

You are right that we don't add tags to `stubparser`; sorry for the confusion regarding that.

> Is it the case that the latest tag in each of the repositories corresponds to the latest release tag of checker-framework?

Yes (except for stubparser).

The tag numbers in checker-framework and annotation-tools will be the same soon.
Years ago, someone changed the version of annotation-tools incorrectly (then did it again!), and we have been waiting for the version number of checker-framework to catch up to the annotation-tools version number.
