### ISSUE TITLE
Support additional (derived) units in units checker

### ISSUE THREAD

**Issue by rkraneis** [typetools/checker-framework#4116]
The units checker is already quite helpful but could support more derived units.

### Currently Supported Units
|name and symbol|unit(s)           |
|---------------|------------------|
|acceleration¹ a|m/s²              |
|angle φ        |rad (m/m), deg (°)|
|area¹ A        |m², mm², km²      |
|current I      |A                 |
|length ℓ, s    |m, mm, km         |
|luminance Iᵥ   |cd                |
|mass m         |kg, g             |
|speed¹ v       |m/s               |
|substance n    |mol               |
|temperature T  |K, C (°C)         |
|time t         |s                 |

### Useful Additional Units
|name and symbol   |unit(s)                        |
|------------------|-------------------------------|
|area¹ A           |ha (10000m²), dm², cm²         |
|capacitance² C    |F (C/V)                        |
|charge¹ q         |C (A s)                        |
|energy² E, work² W |J (N m, W s), kWh              |
|force¹ F          |N (kg m/s²), kN (t m/s²)       |
|length¹ ℓ, s      |dm, cm                         |
|mass m            |t                              |
|(el.) potential² U|V (W/A)                        |
|power² P          |W (J/s)                        |
|pressure² p       |Pa (N/m²)                      |
|resistence² R     |Ω (V/A)                        |
|solid angle Ω     |sr (m²/m²)                     |
|volume¹ V         |m³, mm³, km³, ℓ (dm³), dm³, cm³|

**Key**
¹ 1st order
² 2nd order

### Motivation for some additional units
- Density: [ρ] = g/cm³ = kg/m³
- Work: kWh often used for electric power consumption
- Area: ha often used in land measurement

### Further discussion
- Unfortunately, the unit `C` is already used in the units checker for the derived SI unit _degrees Centigrade_, so something else needs to be thought of for electric charge Coulomb.
- “Unusal” units (e.g. ha, ℓ)? At least for conversion to SI?
  - `@m2 int fromHektarToSquareMeter(@ha int hektar) { return hektar * 10000; }`
  - `@m3 int fromLiterToCubicMeter(@l int liter) { return liter / 1000; } // better @dm3?`
  - Probably better to leave out ℓ, dm³ and cm³ as relations are rather trival?
- Imperial units? At least for conversion to SI?
- Which relations to include? E.g. only those given (by lines) in https://physics.nist.gov/cuu/Units/SIdiagram.html
  - A = ℓ³, F = m a, p = F/A
  - W = F s, P = W/s = U I
  - q = I t, C = q/U, U = P/A = R I
- Additional derived units to include?
  - radioactive: Gy, Sv, Bq, Hz
  - electromagnetic: Wb, H, T
  - (bio)chemistry: kat (use is encouraged but adoption slow)
  - photometric: lx, lm

I'd like to create a PR after discussing what to actually include. Should the discussion happen here or in the PR itself?
Note: I've already created https://github.com/rkraneis/checker-extensions so hopefully somewhat know my way around. I probably still need some pointers on how to update the documentation (found `untits-checker.tex`, is that enough?).

~Edit: draft PR to drive discussion https://github.com/rkraneis/checker-framework/pull/1~

**Comment by rkraneis** [comment]
An additional (but orthogonal) feature would be to support annotating methods (and parameters?) as being _additive_, _subtractive_, _multiplicative_ or _divisive_(?) to keep the amount of specialised conversion methods down (especially interesting for non-scalar/ vector types). Here I have no clue regarding feasibility.

**Comment by sunishaarora** [comment]
Can I get a PR to work on this issue?
