### ISSUE TITLE
override.return.invalid description incorrect in manual

### ISSUE THREAD

**Issue by hborders** [typetools/checker-framework#4346]
The manual says in [Section 34.7](https://checkerframework.org/manual/#creating-extending-visitor):
> invalid overriding parameter type (override.parameter.invalid) when a parameter in a method declaration is incompatible with that parameter in the overridden method’s declaration
> invalid overriding return type (override.return.invalid) when a parameter in a method declaration is incompatible with that parameter in the overridden method’s declaration

It should say something like:
> invalid overriding parameter type (override.parameter.invalid) when a parameter in a method declaration is incompatible with that parameter in the overridden method’s declaration
> invalid overriding return type (override.return.invalid) when a return type in a method declaration is incompatible with the return type in the overridden method’s declaration

**Comment by mernst** [comment]
You are right.  Thanks for noticing that cut-and-paste typo.
