### ISSUE TITLE
dataflow support for Java 15: bad element kind BINDING_VARIABLE

### ISSUE THREAD

**Issue by cushon** [typetools/checker-framework#4410]
This [switch in `CFGTranslationPhaseOne`](https://github.com/typetools/checker-framework/blob/f501266c6a78ddfe264586ec6ae6fece6133b8a6/dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java#L2769-L2774) doesn't handle [ElementKind.BINDING_VARIABLE](https://github.com/openjdk/jdk/blob/d2f9e31ae4b82e031401c3efcbb499c59efa37d7/src/java.compiler/share/classes/javax/lang/model/element/ElementKind.java#L123-L127), which was introduced in Java 15 as part of support for pattern matching, which leads to crashes like the following:

```
[ERROR]   Caused by: org.checkerframework.javacutil.BugInCF: bad element kind BINDING_VARIABLE
[ERROR]         at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitIdentifier(CFGBuilder.java:4038)
[ERROR]         at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitIdentifier(CFGBuilder.java:1526)
[ERROR]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2427)
```

(If there's an existing bug tracking Java 15 support please feel free to dupe this one to it instead of tracking it separately, I'm filing this mostly to record [this crash report](https://github.com/google/error-prone/issues/2230) for posterity.)

**Comment by mernst** [comment]
Thanks for the report.

The Checker Framework supports LTS versions (currently Java 8 and 11).  We would be happy to accept a patch to work around the crash, though.

**Comment by mernst** [comment]
(I asked you for the patch because you can test it in your use case, whereas we cannot.  Thanks in advance for your help!)

**Comment by cushon** [comment]
I don't actually have a repro for this one, it was an external crash report against Error Prone.

We've been trying to provide best-effort support for non-LTS releases in open source Error Prone, but internally we aren't actively trying to support non-LTS releases, so this isn't currently a high priority for us either.
