### ISSUE TITLE
3.8.0 -> 3.11.0  broke my suppressions, field name change

### ISSUE THREAD

**Issue by xenoterracide** [typetools/checker-framework#4417]
although I'm aware upgrading can break stuff... this doesn't seem like it should have, especially in lieu of checker still being version 3

```java
  @SuppressWarnings({ "NullAway.Init", "initialization.fields.uninitialized" })
  @CommandLine.Parameters(
    index = "2",
    description = "The name of the project you're generating code for."
  )
  private String project;
```

is now throwing

```
/home/xeno/IdeaProjects/brix/src/main/java/com/xenoterracide/brix/Application.java:67: error: [initialization.field.uninitialized] the default constructor does not initialize field project
  private String project;
                 ^
/home/xeno/IdeaProjects/brix/src/main/java/com/xenoterracide/brix/Application.java:85: error: [initialization.field.uninitialized] the default constructor does not initialize field configDir
  private Path configDir;
```
which I previously fixed by adding the annotation. 

looks like this is caused by `fields` becoming `field`. here's my fix the breakage diff

https://github.com/xenoterracide/brix/commit/54a89b27908fa83356b32a3ab7f6175baab84c28

**Comment by mernst** [comment]
Sorry for the inconvenience that the changes caused.  We are constantly making improvements.

The [manual](https://github.com/typetools/checker-framework/blob/master/docs/manual/introduction.tex#L226) explains the versioning scheme:

> The minor version (the middle number in the version number) is incremented if there are any incompatibilities with the previous version, including in user-visible behavior or in methods that a checker implementation might call.

The [changelog](https://github.com/typetools/checker-framework/blob/master/changelog.txt#L33) explains that this change is not merely to the message key; rather, the message is output in a different and more specific location:

>  * `initialization.static.fields.uninitialized` => `initialization.static.field.uninitialized`, and it is now issued on the field rather than on the class

We think that this location is more useful to users.  Feedback is always welcome.

**Comment by xenoterracide** [comment]
my feedback is you should follow semver. Obviously here I didn't follow my own document https://github.com/xenoterracide/falsehoods/blob/master/versions.md which states "versions are semantic", sadly I assumed that having x.x.x you were doing semver.

[Semver](https://semver.org/) states
> Given a version number MAJOR.MINOR.PATCH, increment the:
> MAJOR version when you make incompatible API changes,

Since the `@SuppressWarnings` is in my code, and documented as a published API in another major version, I would consider this an API change. I would have added the new logic, but preserved the old behavior and deprecated it. 

Just my 2 cents, not my code, not my monkeys. I'll make sure to set my dynamic version to `x.x.+` or the like instead, as I doubt I've changed your mind to use semver.

**Comment by mernst** [comment]
Thanks for sharing that suggestion.  I appreciate it.

The semver.org proposal is also a fine policy, just not the one we have chosen.  It has its own advantages and disadvantages.  I like that it is written down, though it is ill-defined since it does not define key terms like "backwards compatible bug fixes" (which is an oxymoron).  If we followed it strictly, every single release would be a major version bump and we would be around release 100.0.0; the version numbers would not convey any information to users about the relative magnitude of the changes.

**Comment by xenoterracide** [comment]
Why are you breaking your published api every single release? That seems, well unpleasant for users. If I added that to the 200k line project that I'm leaving, I can only imagine how painful upgrading would be. Fortunately brix is small, but it still took me a bit to notice a 1 character change.

**Comment by mernst** [comment]
Our API has over 10,000 methods in it -- every method in the Checker Framework implementation that a checker implementation might call -- plus all user-visible behavior of the program itself.  If other projects strictly followed semver.org, they would likely also rev their major version every release.

For noticing the differences, please read the changelog (linked above) which is short and descriptive.  That's usually a good idea when an upgrade doesn't go smoothly.

**Comment by xenoterracide** [comment]
10,000 public methods? so you're suggesting you're more complex that Hibernate, or Spring, or even Java itself. Got it.
