### ISSUE TITLE
@SideEffectFree doesn't work as expected with operators ++ and --

### ISSUE THREAD

**Issue by ChristosToxiadis** [typetools/checker-framework#4449]
I ran the Purity Checker in the following code and it passed the checks.

@SideEffectFree
public void test1(long[] x){
	++x[0];
	--x[0];
	x[0]++;
	x[0]--;
}

The same happens if x is byte[], short[], int[], float[], double[].

**Comment by mernst** [comment]
Thanks for reporting this bug.
