### ISSUE TITLE
Is it possible to analize only some packages/folders

### ISSUE THREAD

**Issue by pablogrisafi1975** [typetools/checker-framework#4563]
I'm trying to incorporate CheckerFramework in a big legacy project. I can't find a way to make CheckerFramework analize only some packages. Is there such a thing? In NullAway you can set specific packages with -XepOpt:NullAway:AnnotatedPackages so you can improve your existing project in a progresive way.  With CheckerFramework I got lots errors and I can't fix them without making a huge commit that is pretty much unmergeable unless code-freezing the entire project. Given that soundness probably implies the whole project has to be analized, maybe CheckerFramework can ignore errores outside the specific packages I marked?

Anyway, thanks for your incredible work!

**Comment by mernst** [comment]
Yes, this is possible.  You can use the [`-AskipUses`, `-AonlyUses`](https://checkerframework.org/manual/#askipuses), [`-AskipDefs`, and `-AonlyDefs`](https://checkerframework.org/manual/#askipdefs) command-line options.  The linked manual sections give examples for applying them to packages.

**Comment by pablogrisafi1975** [comment]
Thank you! I missed it, sorry.

Maybe we could have a reference to -AskipUses, -AonlyUses, -AskipDefs, and -AonlyDefs in  "Chapter 31  Handling legacy code" ? So idiots like myself can find it faster....

**Comment by mernst** [comment]
Thanks for telling me where in the manual you were looking.

I disagree that you are an idiot -- if anyone is, it's the author of that manual chapter, which I agree was rather confusing.

I have revised the manual to make it more clear:  https://github.com/typetools/checker-framework/commit/2566ccdb16e6d68acab76707ed11cbc26dae1598 .  (The diffs are big.)  That chapter is removed and its content is modified placed in other locations.  I also added mentions of the -A{skip,only}{uses,defs} command-line arguments in a few other places, and mentioned the NullAway command-line argument, all to make the discussion more discoverable.

Please let us know if you have any comments for improving the revised manual.

Thanks again for raising this issue -- I appreciate it.

**Comment by pablogrisafi1975** [comment]
Thanks for your kind words.

Regarding -A{skip,only}{uses,defs} I would add something like 

**Be very carefull about spaces when using maven, since 
`<arg>-AonlyDefs=^com\.mycompany\.mypackage\.</arg>`
will work, but 
`<arg>-AonlyDefs= ^com\.mycompany\.mypackage\.</arg>`
will not match any class and not detect any errors**

(I lost a couple of hours because of this)

I would also add something regarding maven & lombok.
You can use maven & lombok without delombok, adding lombok annotation processor
before any checker:

      <annotationProcessorPaths>
          <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>${lombok.version}</version>
          </path>
          <path>
              <groupId>org.checkerframework</groupId>
              <artifactId>checker</artifactId>
              <version>3.12.0</version>
          </path>
      </annotationProcessorPaths>
      <annotationProcessors >
          <annotationProcessor>lombok.launch.AnnotationProcessorHider$AnnotationProcessor</annotationProcessor>
          
          <annotationProcessor>org.checkerframework.checker.nullness.NullnessChecker</annotationProcessor>
      </annotationProcessors> 

This configuration is working right now in my project, I copied it from [here](https://gist.github.com/sarxos/9ef9aad8b52e282cfc89fe5da2fb7efc)
