### ISSUE TITLE
Variable considered possibly null after interacting with it

### ISSUE THREAD

**Issue by jpschewe** [typetools/checker-framework#4571]
Removing the call to `setText` causes the error on the next line to go away. This doesn't appear to make sense. I'm using checker 3.12.0 with openJDK 11.

```
java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

```
/home/jpschewe/projects/checker-bugs/src/main/java/net/mtu/eggplant/checker/AssignedNonNull.java:47: error: [dereference.of.nullable] dereference of possibly-null reference this.selectedGoal
          this.selectedGoal.addPropertyChangeListener();
              ^
```

```java
package net.mtu.eggplant.checker;

import org.checkerframework.checker.nullness.qual.Nullable;

import javax.swing.JButton;

public class AssignedNonNull {

  private static final class AbstractGoal {

    public void addPropertyChangeListener() {
      // do something
    }

    public void removePropertyChangeListener() {
      // do something
    }

    public String getTitle() {
      return "Foo";
    }
  }

  public static @Nullable AbstractGoal getSelectedValue() {
    return new AbstractGoal();
  }

  private @Nullable AbstractGoal selectedGoal;

  private final JButton goalEditor;
  
  public AssignedNonNull() {

    goalEditor = new JButton("test");

    goalEditor.addActionListener(l -> {
        final AbstractGoal selected = getSelectedValue();
        if (null != selected) {
          if (null != this.selectedGoal) {
            this.selectedGoal.removePropertyChangeListener();
          }
          
          this.selectedGoal = selected;
          // comment out the next line and the error goes away
          goalEditor.setText(selected.getTitle());

          this.selectedGoal.addPropertyChangeListener();
        }
      });

  }
}
```

**Comment by mernst** [comment]
I'm sorry you are having trouble.

The checker warning is correct.  It is possible that method `setText` has access to the `this` at the call site (say, via an alias) and sets its `selectedGoal` field to null.

This behavior is discussed in the following sections of the manual: 
[29.7.2  Type refinement behavior](https://checkerframework.org/manual/#type-refinement-behavior),
[29.7.5  Side effects, determinism, purity, and type refinement](https://checkerframework.org/manual/#type-refinement-purity), and
[37.4.9  Why does the Checker Framework accept code on one line but reject it on the next?](https://checkerframework.org/manual/#faq-same-code-different-behavior).

Here is a simplifed version of your code that shows this behavior; if you run it, the output is "null".

```java
import org.checkerframework.checker.nullness.qual.Nullable;

public class AssignedNonNull {

  private static final class AbstractGoal {

    AssignedNonNull x;

    public AbstractGoal(AssignedNonNull x) {
      this.x = x;
    }

    public String getTitle() {
      x.selectedGoal = null;
      return "Foo";
    }
  }

  public static AbstractGoal getSelectedValue(AssignedNonNull x) {
    return new AbstractGoal(x);
  }

  private @Nullable AbstractGoal selectedGoal;

  public static void main(String[] args) {
    AssignedNonNull y = new AssignedNonNull();

    y.selectedGoal = getSelectedValue(y);

    y.selectedGoal.getTitle();

    System.out.println(y.selectedGoal);
  }
}
```

When you are confused about a checker's behavior, a good way to	proceed is explained in these two sections of the manual:
[2.4.5  What to do if a checker issues a warning about your code](https://checkerframework.org/manual/#handling-warnings)
[38.1.4  Unexpected type-checking results](https://checkerframework.org/manual/#common-problems-typechecking)

In your bug report, you didn't say why you think the checker warning is incorrect.  I suspect that, had you done so, you would have answered your own question. :-)  In particular, your argument would have included something like "`getTitle()` doesn't modify the `selectedGoal` field".  This is true fact about your code, but you have not communicated it to the checker.  You can do so by writing an annotation such as [`@SideEffectFree`](https://checkerframework.org/api/org/checkerframework/dataflow/qual/SideEffectFree.html) or [`@Deterministic`](https://checkerframework.org/api/org/checkerframework/dataflow/qual/Deterministic.html).

I hope this helps.

**Comment by jpschewe** [comment]
Thank you for the explanation. I had not thought about the side effect. Swapping the two lines avoids the issue and removes the warning.
