### ISSUE TITLE
MonotonicNonNull and other frameworks

### ISSUE THREAD

**Issue by xenoterracide** [typetools/checker-framework#4600]
This is a cross framework issue, and I'm not certain of the right solution. I actually think that maybe (and maybe it already works and I just don't know it) is the ability to say `@Nullable @MonotonicNonNull` is the same as `@MonotonicNonNull`. this way other frameworks could rely on the `@Nullable` hint, while checker could do more with it. My thought that if it isn't done this way, it essentially breaks every other tool that can recognize annotations named `@Nullable`.

I started this conversation at Nullaway, but realized it would be best to have checkers opinion too

https://github.com/uber/NullAway/issues/465#issue-871189791

**Comment by mernst** [comment]
`@MonotonicNonNull` is a subtype of `@Nullable`.  It is not permitted to write two different type qualifiers on a type.  Just as `@Nullable @NonNull` is not permitted, `@MonotonicNonNull @Nullable` is also not permitted.

Probably the best solution is for NullAway to treat `@MonotonicNonNull` an an alias for `@Nullable`.
I see that is what @msridhar [suggested](https://github.com/uber/NullAway/issues/465#issuecomment-829386478) too.  Handling other frameworks' annotations is standard for all tools, so it is reasonable for NullAway to do.  The Checker framework handles dozens of them (eg, see the ["Other tools for nullness checking" section of the manual](https://checkerframework.org/manual/#nullness-related-work)).
