### ISSUE TITLE
Short processor names don't work on Windows

### ISSUE THREAD

**Issue by wmdietl** [typetools/checker-framework#474]
On a Unix setup, one can use

-processor nullness

and CheckerMain correctly uses the expanded "org.checkerframework.checker.nullness.NullnessChecker".
On Windows this expansion doesn't work and when using the short name one gets a processor not found error.

https://github.com/typetools/checker-framework/blob/master/framework/src/org/checkerframework/framework/util/CheckerMain.java#L564

uses "/" as directory separator.
I couldn't find documentation whether ZipEntry.getName uses platform-independent entry names or not.

Changing this to File.separator might fix this issue. If not, there must be some other platform dependency in CheckerMain.

**Comment by JonathanBurke** [comment]
So I changed the "/" to a File.separator, since it should be changed one way or another.  I don't have a windows machine to test this on.

**Comment by wmdietl** [comment]
Fixed by 3ff88afa132764a35832ce3775f9d3cbf429cf60
