### ISSUE TITLE
Can checker-framework be used to extract control-flow and basic data-flow graphs?

### ISSUE THREAD

**Issue by nashid** [typetools/checker-framework#4767]
Thanks for submitting an issue.
As explained in the instructions for submitting an issue at https://checkerframework.org/manual/#reporting-bugs, please include four pieces of information:
 * commands (that can be cut-and-pasted into a command shell),
 * inputs,
 * outputs, and
 * expectation.
 
I need to extract control-flow and basic data-flow graphs i.e. def-use for intraprocedural analysis.

I am new to Checker-framework and this library looks great. I am wondering whether Checker-framework is a good fit for this task?

**Comment by mernst** [comment]
Yes, this is possible.  See the [Dataflow Manual](https://checkerframework.org/manual/checker-framework-dataflow-manual.pdf) for how to create a control flow graph.  You can [visualize it](https://checkerframework.org/manual/#creating-debugging-dataflow-graph) from the Checker Framework.
