### ISSUE TITLE
Intersection types fail functional interface test

### ISSUE THREAD

**Issue by dbrosoft** [typetools/checker-framework#478]
See [gist](https://gist.github.com/dbrosoft/81a013dbcba44b5cd471) for source code and reported errors. `errors0.txt` shows the output of `javac -processor signature -AprintErrorStack IntersectionBug.java`, and `errors1.txt` shows the same after I added a case for intersection types to `org.checkerframework.framework.type.TypeFromTypeTreeVisitor` to get past the constructor invocation.  Oracle's `javac` (1.8.0_51) compiles the source without error, and so does the Checker Framework's compiler if not given a `-processor` argument, but at least `igj`, `javari`, `nullness`, and `signature` cause the compiler to crash.

**Comment by JonathanBurke** [comment]
So, pre-Java8 I believe the only location that an intersection could appear is in a type parameter declaration.  I am sure there are locations within the Checker Framework where we assume this is the case.

**Comment by dbrosoft** [comment]
Ah, that makes sense.  I will have a go at this one, as it is a blocking
issue for compiling the merged annotated JDK.

-- Dan.

**Comment by dbrosoft** [comment]
I've created an 'issue-478' branch with the aforementioned change to `TypeFromTypeTreeVisitor` for anyone who wants to pick this one up.

**Comment by mernst** [comment]
Dan, can you add the test case in the gist to the issue-478 branch, so that there is a test case available in an obvious place?

**Comment by dbrosoft** [comment]
Done.

-- Dan.
