### ISSUE TITLE
Make nodes for switch expressions appear on their own in the containing CFG block

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#4979]
I'm working on getting NullAway to not crash in the presence of switch expressions, now that Checker dataflow does not crash for them.  One small issue is that the marker node for a switch expression may not appear as a top-level node in the containing CFG block, so it never gets directly visited by the dataflow analysis.  If I have a statement `Object o = null;`, I get four nodes in the corresponding CFG basic block: a `VariableDeclarationNode`, a `NullLiteralNode`, an `AssignmentNode`, and a `LocalVariableNode`.  But, if I write `Object o = switch (i) { ... };`, I just get three nodes in the corresponding block:  a `VariableDeclarationNode`, an `AssignmentNode`, and a `LocalVariableNode`; the marker node for the switch expression is missing.

I imagine the representation of `switch` expressions in CFGs is very temporary, and as it gets handled it will get its own node in the containing block for cases like these.  And I can add a special case to work around this for now.  Just wanted to note the issue.

**Comment by msridhar** [comment]
Update: given that `switch` expressions aren't yet properly represented in the CFG anyway, this issue doesn't really matter to us.  If it's of no value it can just be closed.

**Comment by smillst** [comment]
I'm actively working on add support for analyzing switch expressions, so this should be fixed soon.
