### ISSUE TITLE
Proposal: during CFG construction, create a synthetic variable for the value of each ternary expression

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#4994]
As in the recent handling of `switch` expressions (see #4982), it would be useful if there were a synthetic variable created for the value of each ternary expression during CFG construction, with an assignment of the "then" and "else" sub-expressions to the variable in the relevant CFG blocks.  I can think of two advantages:

1. Transfer functions in dataflow analysis could be simplified.  If there is already a transfer function for assignments, then it is likely that the abstract value for a ternary expression will just be the abstract value for its synthetic variable.
2. For analyses that track results for each control-flow path separately, like `MustCallConsistencyAnalyzer`, reasoning about ternary expressions will become much simpler.  Right now, `MustCallConsistencyAnalyzer` has some tricky special-case logic for ternary expressions.  With a synthetic variable for the ternary expressions, correct handling would fall out of handling the corresponding assignments.

@smillst @mernst thoughts?

**Comment by smillst** [comment]
This makes sense to me.
