### ISSUE TITLE
Checker crash with pattern matching latest version

### ISSUE THREAD

**Issue by tmarback** [typetools/checker-framework#5047]
Updating to version 3.21.2 gives me a `AsSuperVisitor: type is not an erased subtype of supertype.` error and crashes the framework when using pattern matching on an `Object`-type value. The full exception trace is [here](https://pastebin.com/yyhbxx3C), and the code that caused the crash is the following:

```java
public boolean equals( final @Nullable Object o ) {

    if ( o instanceof NumberParameterBuilder<?, ?, ?> b ) {
        return super.equals( o ) && Objects.equals( this.minimum, b.minimum )
                && Objects.equals( this.maximum, b.maximum );
    } else {
        return false;
    }

}
```

Based on the exception output, it seems to be flipping which is the subtype and which is the supertype. Also I would expect this to be reported as a normal error, not crash the framework.

The previous version (3.21.1) did not have this issue and finished normally.

**Comment by mernst** [comment]
Thanks for reporting the problem, and I am sorry you encountered the crash.

I am not able to reproduce this problem using the master branch of the Checker Framework.  I did not try it with version 3.21.2, though it is possible that 4c9c5d936562ec3bb260d86b394bc63cf3cf81d5 fixed the problem.  Are you able to build the Checker Framework from its repository and test it?

For completeness, this is the file I used to try to reproduce the problem.

```java
// Test case for issue #5047: https://tinyurl.com/cfissue/5047

import java.util.Objects;
import org.checkerframework.checker.nullness.qual.Nullable;

public class Issue5047 {}

class NumberParameterBuilder<T, U, V> {

  @Nullable Object minimum;
  @Nullable Object maximum;

  public boolean equals(final @Nullable Object o) {

    if (o instanceof NumberParameterBuilder<?, ?, ?> b) {
      return super.equals(o)
          && Objects.equals(this.minimum, b.minimum)
          && Objects.equals(this.maximum, b.maximum);
    } else {
      return false;
    }
  }
}
```

**Comment by tmarback** [comment]
You're right, it seems that this issue has been resolved by one of the recent commits in master (seems to have been 7e16a9cfeb23320db21fedf5ab7e32634d08cae5 rather than 4c9c5d936562ec3bb260d86b394bc63cf3cf81d5 though), so that's good. I'll just stick with 3.21.1 until the next version is out 👍 

Thanks!

**Comment by mernst** [comment]
@tmarback Thanks for confirming.  We are sorry you encountered the problem, but I'm glad it is now fixed.
