### ISSUE TITLE
Maven builds using regex options are not portable

### ISSUE THREAD

**Issue by gdupontf** [typetools/checker-framework#5081]
On Windows systems arguments' backslashes get (erroneously) translated to forward slashes without discrimination.

Stepping through the (forked) jvm during compilation indeed reveals this :

<img width="719" alt="Capture 2022-03-15 000743" src="https://user-images.githubusercontent.com/9341318/158310114-24c744ba-2423-4d43-8e47-6fab0d7d9b5b.png">

Thus the simple direct question :

What is the recommended way to run a Maven build using these kinds of arguments on Windows systems?

Here is a bare minimum repository (that assumes JDK 8 in the current home environment variable).

###  Commands
 `git clone git@github.com:gabarise/checker-reprod.git`

`git checkout ed9f9379`

`.\mvnw clean compile`

Build should normally fail.

Passes on my Windows machine.

### Inputs
N/A
### Outputs
N/A
### Expectation
Builds using recommended Maven configuration should be portable.

**Comment by markro49** [comment]
I found that <arg>-AonlyDefs=foo.bar.Test</arg> worked fine on both Windows and Linux.  Please verify it works for you and I will close the issue.

**Comment by mernst** [comment]
@gdupontf Could you please verify whether this works for you?  If not, we will investigate further.

**Comment by gdupontf** [comment]
The issue is that there are path translation shenanigans going on. The backslashes being converted here prevent the use of escape sequences.

**Comment by markro49** [comment]
Closing issue; we can reopen if get more info.
