### ISSUE TITLE
@This does not work with @RequiresCalledMethods when chaining

### ISSUE THREAD

**Issue by tmarback** [typetools/checker-framework#5402]
I'm observing a behavior where it seems that `@This` (i.e. the Returns Receiver Checker) does not properly forward the `@CalledMethods` qualifier of the object when chaining the result to a method that uses `@RequiresCalledMethods` to define requirements for the receiver.

Chaining the method call works when the requirements are defined with `@CalledMethods` on the explicit receiver parameter:

```java
import org.checkerframework.checker.calledmethods.qual.CalledMethods;
import org.checkerframework.checker.calledmethods.qual.RequiresCalledMethods;
import org.checkerframework.common.returnsreceiver.qual.This;

public class Foo {

    public @This Foo bar() {
        return this;
    }

    public void baz(@CalledMethods("bar") Foo this) {}

    public static void test() {
        final Foo foo = new Foo();
        foo.bar().baz(); // No error
    }

}
```

Storing the intermediate result, then calling a `@RequiresCalledMethods`-annotated method also works:

```java
import org.checkerframework.checker.calledmethods.qual.RequiresCalledMethods;
import org.checkerframework.common.returnsreceiver.qual.This;

public class Foo {

    public @This Foo bar() {
        return this;
    }

    @RequiresCalledMethods( value = "this", methods = "bar" )
    public void baz() {}

    public static void test() {
        final Foo foo = new Foo();
        final Foo foo1 = foo.bar();
        foo1.baz(); // No error
    }

}
```

But if I chain the call to the `@RequiresCalledMethods`-annotated method:

```java
import org.checkerframework.checker.calledmethods.qual.RequiresCalledMethods;
import org.checkerframework.common.returnsreceiver.qual.This;

public class Foo {

    public @This Foo bar() {
        return this;
    }

    @RequiresCalledMethods( value = "this", methods = "bar" )
    public void baz() {}

    public static void test() {
        final Foo foo = new Foo();
        foo.bar().baz(); // Error
    }

}
```

I get the error

```
> .\bin\javac.bat -cp . -processor calledmethods Foo.java
Foo.java:42: error: [contracts.precondition] precondition of foo.bar().baz is not satisfied.
        foo.bar().baz();
                     ^
  found   : foo.bar() is @CalledMethods
  required: foo.bar() is @CalledMethods("bar")
1 error
```

Which indicates that the qualifier isn't getting forwarded.

While this can be worked around by explicitly defining the `this` parameter and using `@CalledMethods`, it can become quite verbose when the class name is long and/or there are type parameters involved (imagine having to add a `@CalledMethods({"foo", "bar", "baz"}) VeryLongClassName<E, T, I> this` parameter on multiple methods in a class), and (IMO) is much less clear at a glance than a `@RequiresCalledMethods` annotation.

All of the examples were ran using the command `.\bin\javac.bat -cp . -processor calledmethods Foo.java`, with the code being placed in the `Foo.java` file, and with the current directory being the root directory of the Checker 3.27.0 release artifact.

**Comment by kelloggm** [comment]
The issue is that the checker only keeps information about calls to methods that are known to be deterministic in the store. In particular, the following variant of this program also typechecks:

```
import org.checkerframework.checker.calledmethods.qual.RequiresCalledMethods;
import org.checkerframework.common.returnsreceiver.qual.This;
import org.checkerframework.dataflow.qual.Deterministic;

public class Foo {

    @Deterministic
    public @This Foo bar() {
        return this;
    }

    @RequiresCalledMethods( value = "this", methods = "bar" )
    public void baz() {}

    public static void test() {
        final Foo foo = new Foo();
        foo.bar().baz(); // Error
    }

}
```

I looked into whether it would be possible to relax that restriction in the Called Methods Checker for methods that return their receiver, but I don't think it's technically possible: that restriction is too deeply imbedded in the Checker Framework itself. Technically, the key difference between `@RequiresCalledMethods` and annotating the receiver is that when we do the former, the framework needs to "translate" (viewpoint-adapt) the `"this"` in `@RequiresCalledMethods( value = "this", methods = "bar" )` to the name of `this` at the call site (i.e., `foo`); the information that `bar()` has been called is lost in that translation process (which only stores information about deterministic method calls). When the receiver is annotated directly, that process is unnecessary, because the typechecker takes care of propagating the type of `foo` directly and no translation/viewpoint-adaption is needed.

**Comment by msridhar** [comment]
I agree that is a bit of an annoying limitation.  We should try to document the issue in the manual, if we can't figure out a fix.

@kelloggm as an (unsound) workaround, I think passing `-AassumeDeterministic` would also work here, is that correct?

**Comment by kelloggm** [comment]
@msridhar I would have thought so, too, but I just tried it out and it does not prevent the error from being issued. That might be a (separate) bug with that command-line option. In particular, I followed the instructions in the original issue report. I used the following `Foo.java`:
```
import org.checkerframework.common.returnsreceiver.qual.This;

public class Foo {

    public @This Foo bar() {
        return this;
    }

    @RequiresCalledMethods( value = "this", methods = "bar" )
    public void baz() {}

    public static void test() {
        final Foo foo = new Foo();
        foo.bar().baz(); // Error
    }

}
```

I ran this command:
```
./checker/bin/javac -cp . -processor calledmethods -AassumeDeterministic Foo.java
```

And got this error (i.e., the same one reported originally):
```
Foo.java:15: error: [contracts.precondition] precondition of foo.bar().baz is not satisfied.
        foo.bar().baz(); // Error
                     ^
  found   : foo.bar() is @CalledMethods
  required: foo.bar() is @CalledMethods("bar")
1 error
```

If I add an `@Deterministic` annotation (as in my previous comment) to `Foo.java`, I don't get an error from the typechecker as expected. @mernst, is this a bug with `-AassumeDeterministic`?

**Comment by tmarback** [comment]
Interesting, that's good to know. Using `@Deterministic` on the methods is not too bad (I was already doing that anyway), though it sure would be convenient if there was a way to automatically make a method `@Deterministic` if it has a `@This` return since it is always true by definition (but that's OK). I agree that it definitely should be documented somewhere though.

However, there's still a problem. If the method that needs to be called receives a parameter, and that parameter is an expression instead of a constant or variable, it still won't work, even with `@Deterministic`:

```java
import org.checkerframework.checker.calledmethods.qual.RequiresCalledMethods;
import org.checkerframework.common.returnsreceiver.qual.This;
import org.checkerframework.dataflow.qual.Deterministic;

public class Foo {

    @Deterministic
    public @This Foo bar(String s) {
        return this;
    }

    @RequiresCalledMethods( value = "this", methods = "bar" )
    public void baz() {}

    public static void test() {
        final Foo foo1 = new Foo();
        foo1.bar("").baz(); // This is fine
        var s = String.format("");
        final Foo foo2 = new Foo();
        foo2.bar(s).baz(); // This is also fine
        final Foo foo3 = new Foo();
        foo3.bar(String.format("")).baz(); // This is not
    }

}
```
```
.\bin\javac.bat -cp . -processor calledmethods Foo.java
Foo.java:55: error: [contracts.precondition] precondition of foo3.bar(String.format("")).baz is not satisfied.
        foo3.bar(String.format("")).baz(); // This is not
                                       ^
  found   : foo3.bar(java.lang.String.format("")) is @CalledMethods
  required: foo3.bar(java.lang.String.format("")) is @CalledMethods("bar")
1 error
```

Using an anonymous object for the original receiver also causes issues:

```java
import org.checkerframework.checker.calledmethods.qual.RequiresCalledMethods;
import org.checkerframework.common.returnsreceiver.qual.This;
import org.checkerframework.dataflow.qual.Deterministic;

public class Foo {

    @Deterministic
    public @This Foo bar() {
        return this;
    }

    @RequiresCalledMethods( value = "this", methods = "bar" )
    public void baz() {}

    public static void test() {
        final Foo foo = new Foo();
        foo.bar().baz(); // Fine
        new Foo().bar().baz(); // Not fine
    }

}
```
```
.\bin\javac.bat -cp . -processor calledmethods Foo.java
Foo.java:45: error: [contracts.precondition] precondition of new Foo().bar().baz is not satisfied.
        new Foo().bar().baz(); // Not fine
                           ^
  found   : new Foo().bar() is @CalledMethods
  required: new Foo().bar() is @CalledMethods("bar")
1 error
```

Given the context I would imagine it to be some sort of limitation of how `@Deterministic` is applied. Like before, if it's not fixable it should definitely be documented, though it really is unfortunate that it makes `@RequiresCalledMethods` a lot less useful.
