### ISSUE TITLE
Security certificate expired

### ISSUE THREAD

**Issue by Bobcat00** [typetools/checker-framework#5438]
I get the following visiting your web site. Your SSL certificate expired Dec 8.

> Your connection isn't private
Attackers might be trying to steal your information from checkerframework.org (for example, passwords, messages, or credit cards).
NET::ERR_CERT_DATE_INVALID
This server could not prove that it is checkerframework.org; its security certificate expired in the last day. This may be caused by a misconfiguration or an attacker intercepting your connection.

**Comment by mernst** [comment]
Thank you!  We just noticed a few minutes ago and are working to fix it.
(Something went wrong with the renewal.)

**Comment by mernst** [comment]
Sorry about this.  Last year, we were issued a 1-year certificate instead of a 2-year certificate.  We didn't notice this at the time, so we were blindsided by its expiration.  We are working to get a valid certificate re-issued.  Thanks for your patience!

**Comment by mernst** [comment]
We have been working on this, but are encountering trouble in our conversations with our certificate issuer.  We're about ready to drop them...

Sorry for the delay.  We have not forgotten this.

**Comment by Bobcat00** [comment]
Looks like it's working again?

**Comment by mernst** [comment]
Yes, it is.  At least until next December 21.  :-/
I'll close this now.  Thanks again for pointing out the problem, and for your patience.

**Comment by ben-manes** [comment]
> JAVA_VERSION=21 ./gradlew javadoc --no-build-cache
> ...
> Task :caffeine:javadoc
error: Error fetching URL: https://checkerframework.org/api/ (javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target)

The certificate looks fine, but for some reason the javadoc tool fails. I add to the gradle task `setFailOnError(true)` as a workaround.

**Comment by mernst** [comment]
Thanks for the bug report.

There was a new intermediate cert from Incommon that had to be installed (in addition to the main certificate).  It should be all set now.
