### ISSUE TITLE
Recognizing javax jsr305 annotations

### ISSUE THREAD

**Issue by jslaroch** [typetools/checker-framework#5447]
This is more a wish than a bug

It would be nice if the checker could recognize annotations from the jsr305 package since a lot of tools already support this and it would minimize the clutter in the code if we could just use the javax.annotation.Nonnull  present in the code instead of adding additional annotation. The checker NotNull annotation could be used where javax Nonnull is not supported.

**Comment by mernst** [comment]
This is already done.  See, for example, https://checkerframework.org/manual/#nullness-related-work .
