### ISSUE TITLE
Add `@NonNullByDefault` to Nullness Checker

### ISSUE THREAD

**Issue by Monniasza** [typetools/checker-framework#5450]
I'd like to have a `@NonNullByDefault` annotation, to replace an annotation from FindBugs.
I'm looking to replace FindBugs because it is dormant and their annotations don't work in GitHub Actions.

**Comment by mernst** [comment]
In the Nullness Checker, [`@NonNull` is the default](https://checkerframework.org/manual/#nullness-checker).  Therefore, there is no need for a `@NonNullByDefault` annotation, which would have no effect.  You can just remove `@NonNullByDefault` annotations when switching to a more modern set of annotations such as those of the Checker Framework.

**Comment by mernst** [comment]
Does this resolve your problem?
