### ISSUE TITLE
checker-framework 3.12.0 or 3.28.0 builds are failing as it could not resolve grgit-gradle 4.1.0 plugin

### ISSUE THREAD

**Issue by nandakishorkn** [typetools/checker-framework#5487]
Trying to build checker-framework 3.12.0 using Gradle 6.0.1 or checker-framework 3.28.0 using Gradle 7.6 are failing with the same build error message as follows :
Note: Tried building using JDK 8 and JDK 11 as well but hitting same build error.
++++++++++++++++++++++++++++++++++++
$ ./gradlew clean build
OR
$ ./gradlew assemble

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'checker-framework'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.eclipse.jgit:org.eclipse.jgit:latest.release.
     Required by:
         project : > org.ajoberstar.grgit:org.ajoberstar.grgit.gradle.plugin:4.1.0 > org.ajoberstar.grgit:grgit-gradle:4.1.0 > org.ajoberstar.grgit:grgit-core:4.1.0
      > Failed to list versions for org.eclipse.jgit:org.eclipse.jgit.
         > Unable to load Maven meta-data from https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit/maven-metadata.xml.
            > Could not HEAD 'https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit/maven-metadata.xml'.
               > Network is unreachable (connect failed)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
++++++++++++++++++++++++++++++++++

Trying to access the file https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit/maven-metadata.xml via browser says 403 FORBIDDEN but with wget command it downloads the file locally without any issues.

Similarly, accessing grgit-gradle 4.1.0 plugin jar file https://jcenter.bintray.com/org/ajoberstar/grgit/grgit-gradle/4.1.0/grgit-gradle-4.1.0.jar from the browser says 403 FORBIDDEN but with wget command it downloads the file locally without any issues.

Please suggest how to resolve this build issue.

**Comment by mernst** [comment]
This is a transient network issue.  They key problem is:

> Could not HEAD 'https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit/maven-metadata.xml'.
> Network is unreachable (connect failed)

Either there is a problem with https://plugins.gradle.org and you need to wait for its system administrators to fix it (you can submit a bug report to them if necessary), or there is a network problem between you and https://plugins.gradle.org, in which case you need to wait for it to resolve itself or talk to your Internet provider.
