### ISSUE TITLE
Ajava-based WPI mangles string literals with escapes

### ISSUE THREAD

**Issue by kelloggm** [typetools/checker-framework#5489]
There is a test case on this branch: https://github.com/kelloggm/checker-framework/tree/ajava-bad-pattern

The problem occurs for any input Java file that contains an escape character. The test case, for example, is the following:
```
public class ComplexPatternEscape {

  private static final String DOT_DELIMITED_IDS = "";

  // From https://github.com/randoop/randoop/blob/ffed1540721212adc55da179f1ae3b3df582d0d5/agent/replacecall/src/main/java/randoop/instrument/ReplacementFileReader.java#L58
  private static final String SIGNATURE_STRING =
      DOT_DELIMITED_IDS + "(?:\\.<init>)?" + "\\([^)]*\\)";
}
```

The generated ajava file for e.g., the Value Checker, is the following:
```
@org.checkerframework.framework.qual.AnnotatedFor("org.checkerframework.common.value.ValueChecker")
public class ComplexPatternEscape {

    private static final @org.checkerframework.common.value.qual.StringVal({ "" }) String DOT_DELIMITED_IDS = "";

    // From https://github.com/randoop/randoop/blob/ffed1540721212adc55da179f1ae3b3df582d0d5/agent/replacecall/src/main/java/randoop/instrument/ReplacementFileReader.java#L58
    private static final @org.checkerframework.common.value.qual.StringVal({ "(?:\\.<init>)?\\([^)]*\\)" }) String SIGNATURE_STRING = DOT_DELIMITED_IDS + "(?:\.<init>)?\([^)]*\)";
}
```

Note that the string literal itself in the generated .ajava file does not match the corresponding source file: it is missing one backslash. This causes the ajava file not to be parseable: that's an invalid string. Interestingly, the `@StringVal` annotation has the correct string, which is surprising. I'm not sure why that's happening.

It is not straightforward to work around this problem by modifying the generated ajava file, because escaping all string literals would also destroy the correct `@StringVal` annotation's argument.

I'm not sure if the problem is in JavaParser or in our internal representation of ajava files, and I'd appreciate some help in figuring it out. @smillst, any ideas what might be causing this?

**Comment by mernst** [comment]
This may also be responsible for the failure at https://github.com/mernst/checker-framework/tree/wpi-plumeutil-onlyone .
