### ISSUE TITLE
Class.isInstance(x) Ensures That x Is Not Null

### ISSUE THREAD

**Issue by eatnumber1** [typetools/checker-framework#563]
[Class.isInstance(Object)] is documented as follows:

> The method returns true if the specified Object argument is non-null and can be cast to the reference type represented by this Class object without raising a ClassCastException. It returns false otherwise.

A quick test shows that the checker framework doesn't understand that `Class.isInstance` returning `true` indicates that the argument is non-null.

```java
class Foo {{
  Object x = null;
  if (Object.class.isInstance(x)) {
    x.toString();
  }
}}
```

produces

```
Foo.java:6: error: [dereference.of.nullable] dereference of possibly-null reference x
    x.toString();
    ^
1 error
```

Therefore, we can conclude that the checker is missing annotations on this method. The correct stub would be

```java
package java.lang;
import org.checkerframework.checker.nullness.qual.EnsuresNonNullIf;
class Class {
  @EnsuresNonNullIf(expression="#1", result=true) boolean isInstance(Object obj) {}
}
```

I'd send a PR, but a cursory glance at the checker's source doesn't make it obvious where I'd need to make changes.

[Class.isInstance(Object)]: https://docs.oracle.com/javase/7/docs/api/java/lang/Class.html#isInstance(java.lang.Object)

**Comment by wmdietl** [comment]
Thanks for noticing this!
The file to add this annotation to is:

https://github.com/typetools/checker-framework/blob/master/checker/jdk/nullness/src/java/lang/Class.java

I'll add the annotation, but wanted to mention this for future PRs.

**Comment by wmdietl** [comment]
Also added a test case, to make sure it works as expected:
checker-framework/checker/tests/nullness/Issue563.java
