### ISSUE TITLE
JDK 21 - NoSuchMethodError for TreeMaker.Select

### ISSUE THREAD

**Issue by cushon** [typetools/checker-framework#5672]
The signature of `TreeMaker.Select` is changing in the next release of the JDK (https://github.com/openjdk/jdk/commit/a917fb3fcf0fe1a4c4de86c08ae4041462848b82#diff-116d757068eaf94ea4c877b290331659678769ec5e30145f6cb5738fd5c02adcL356-R357), and this line will need to be updated:

https://github.com/typetools/checker-framework/blob/b11dfe578c5e52b5a414c5dbb828bc3d325e2346/javacutil/src/main/java/org/checkerframework/javacutil/trees/TreeBuilder.java#L122

Currently that method fails on JDK 21 with errors like:

```
 Exception: java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.JCTree$JCExpression com.sun.tools.javac.tree.TreeMaker.Select(com.sun.tools.javac.tree.JCTree$JCExpression, com.sun.tools.javac.code.Symbol)'; java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.JCTree$JCExpression com.sun.tools.javac.tree.TreeMaker.Select(com.sun.tools.javac.tree.JCTree$JCExpression, com.sun.tools.javac.code.Symbol)'
        at org.checkerframework.javacutil.trees.TreeBuilder.buildValueOfMethodAccess(TreeBuilder.java:392)
        at org.checkerframework.dataflow.cfg.builder.CFGTranslationPhaseOne.box(CFGTranslationPhaseOne.java:819)
        at org.checkerframework.dataflow.cfg.builder.CFGTranslationPhaseOne.commonConvert(CFGTranslationPhaseOne.java:1136)
```

**Comment by mernst** [comment]
@cushon Thanks for the heads-up.  We test on released JDKs and so would have noticed this only in a few weeks.

**Comment by mernst** [comment]
@cushon The next release of the JDK will be JDK 20.  JDK 21 will be released in September.  Did you mean that the failure is on JDK 20?

**Comment by cushon** [comment]
I meant JDK 21

**Comment by mernst** [comment]
Thank you for the clarification.  I was confused by the mismatch:

> The signature of `TreeMaker.Select` is changing in the next release of the JDK 
> ...
> Currently that method fails on JDK 21 with errors like:

So the method is changing in JDK 20 and fails under JDK 21.
Do you know whether the method works under JDK 20?  (If not, we can check.)

**Comment by cushon** [comment]
I believe it's only changing in JDK 21, and that the release branch for JDK 20 has already been made and does not include that change
