### ISSUE TITLE
Update the version of JavaParser used by the stub parser

### ISSUE THREAD

**Issue by smillst** [typetools/checker-framework#571]
The stub parser uses version 1.0.7 of [JavaParser](http://javaparser.github.io/javaparser/).  It should be updated to use the latest version, which is currently [2.3.0](https://github.com/javaparser/javaparser/releases/tag/javaparser-parent-2.3.0).  This will fix (or at the very least help fix) the limitations of the stub parser that violate Java 8 syntax.

(This should also fix some issues that have been filed: #407, #375, #297, #220, #798.)

**Comment by mernst** [comment]
Fixed by 8997a34.
