### ISSUE TITLE
Lambdas: Functional interface not found for parenthesized lambda expressions

### ISSUE THREAD

**Issue by dbrosoft** [typetools/checker-framework#572]
The Checker Framework compiler has no problem with the sample file [ParenthesizedLambda.java](https://gist.github.com/dbrosoft/437c22645955e5d81241), but the nullness checker crashes due to a missing case in the switch statement beginning at line 2921 of [AnnotatedTypeFactory.java](https://github.com/typetools/checker-framework/blob/master/framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java#L2921).

**Comment by smillst** [comment]
I added a test case in checker/tests/java8/lambda/Issue572
