### ISSUE TITLE
DefaultRawnessComparer: Unexpected AnnotatedTypeMirror combination

### ISSUE THREAD

**Issue by dbrosoft** [typetools/checker-framework#579]
`javac -processor nullness -Awarns `[UnexpectedATMCombination.java](https://gist.github.com/dbrosoft/4313cdbca2eb9cb0990e) throws two runtime exceptions, issuing the following messages:

```
error: DefaultRawnessComparer: Unexpected AnnotatedTypeMirror combination.
  type1 = AnnotatedNullType(  null )
  type2 = AnnotatedTypeVariable( T extends Object )
  visitHistory = VisitHistory( ( T extends Object => capture#876 of ? super T extends Object super T extends Object ), ( Object => Object ) )
```
```
error: DefaultRawnessComparer: Unexpected AnnotatedTypeMirror combination.
  type1 = AnnotatedNullType( null )
  type2 = AnnotatedTypeVariable( T extends @Initialized @Nullable Object )
  visitHistory = VisitHistory( ( T extends @Initialized @Nullable Object => capture#876 of ? super T extends @Initialized @Nullable Object super T extends @Initialized @Nullable Object ), ( @Initialized @Nullable Object => @Initialized @Nullable Object ) )
```

**Comment by smillst** [comment]
I did not try to minimize @dbrosoft 's testcase further, but the following method is causing the error:
````  
@Override
  public Comparator<T> thenComparing(Comparator<? super T> other) {
    return new UnexpectedATMCombination<>(real == null ? other
        : real.thenComparing(other));
  }
````
#557 might be related.

**Comment by smillst** [comment]
Issue #557 is in fact not related.

**Comment by wmdietl** [comment]
But this might have been fixed by:
https://github.com/typetools/checker-framework/commit/0c58d8f726e8bfa85447be54a0b4a4262fd34f96
as we also had that combination in that fix.

**Comment by smillst** [comment]
The combination in 0c5d8f is null_declared.  This is typevar_null.  
But I add the correct combination after reviewing 0c5d8f. See PR #628.

**Comment by wmdietl** [comment]
Ok, I'll look at the PR. It's a bit strange that it's typevar_null, as in dbrosoft's error type 1 is null and type 2 is a typevar, so I would expect null_typevar.

**Comment by smillst** [comment]
Yes, I just noticed that.  I found a different related bug.  I'll add null_typevar.

**Comment by smillst** [comment]
This is now (really) fixed in PR #630.

**Comment by dbrosoft** [comment]
Running fenum checker, saw the same message.  Save [Issue579.zip](https://github.com/typetools/checker-framework/files/241383/Issue579.zip) and proceed as follows:
```sh
$ unzip Issue691.zip
$ cd Issue691
$ java -jar $CHECKERFRAMEWORK/checker/dist/checker.jar -processor fenum -AuseDefaultsForUncheckedCode=source -AprintErrorStack -Awarns java/util/EnumMap.java
```
Stack trace is provided in `error.txt`.

**Comment by smillst** [comment]
@dbrosoft  Thanks for reporting.  This is actually a different combination than the original issue, so I opened a new issue #692.
