### ISSUE TITLE
Incorrect nullness annotations for java.lang.Process get*Stream methods

### ISSUE THREAD

**Issue by atomicknight** [typetools/checker-framework#582]
The Javadoc for `java.lang.Process` indicates that `getInputStream` and `getErrorStream` may return "null input streams" and that `getOutputStream` may return a "null output stream." However, this text appears to have been misinterpreted as "possibly-null stream references." The link in the Javadoc points to definitions in `java.lang.ProcessBuilder`, which are as follows:

> In this case, Process.getInputStream() and/or Process.getErrorStream() will return a *null input stream*, for which:
> - the read methods always return -1
> - the available method always returns 0
> - the close method does nothing

--
> In this case, Process.getOutputStream() will return a *null output stream*, for which:
> - the write methods always throw IOException
> - the close method does nothing

This is seemingly corroborated by the source for `java.lang.ProcessImpl`, which always assigns a non-null object to the stream references.

**Comment by mernst** [comment]
I agree:  a "null stream" is a non-null Stream with particular behavior, not a `@Nullable` Stream reference.
Thank you for catching this error!
