### ISSUE TITLE
Control flow graph for try-catch blocks is too imprecise

### ISSUE THREAD

**Issue by Calvin-L** [typetools/checker-framework#5936]
I am writing a small checker that cares very deeply about certain exceptions. (I can provide more context if necessary, but I don't think it's relevant here.)

Having [reverse engineered](https://github.com/typetools/checker-framework/blob/3d154faca2e9f421b6e565b01f432191088c5411/checker/src/main/java/org/checkerframework/checker/calledmethods/CalledMethodsTransfer.java#L79) how one might refine type information due to a thrown exception, I am now stuck. My checker fails on some of the test cases I have written.

The problem _appears_ to be that the Checker Framework's control flow graph is not very precise. Given this program:
```java
import java.io.*;

public class Test {

    public boolean run() throws Exception {
        try {
            modifyFilesystem();
        } catch (FileNotFoundException e) {
            return false;
        }
        return true;
    }

    public void modifyFilesystem() throws IOException {
    }

}
```

The Checker Framework generates this CFG for `run()`:

![case1](https://github.com/typetools/checker-framework/assets/1393639/a122f0ce-3119-4e64-b79b-9c1f12120848)

The CFG includes a conservative but imprecise edge labeled `java.io.IOException` from the `modifyFilesystem()` call to the `return false` block. Unless I am mistaken, that edge is only possible for `FileNotFoundException` and its subclasses. My checker has no practical way to determine that `return false` is only possible when `FileNotFoundException` was thrown, and so it cannot fully refine its type information down that branch.

Notably, if you change the signature of `modifyFilesystem()` from
```java
public void modifyFilesystem() throws IOException
```
to
```java
public void modifyFilesystem() throws IOException, FileNotFoundException
```
then the CFG contains the edge I want but _still_ includes the overly-conservative `java.io.IOException` edge:

![case2](https://github.com/typetools/checker-framework/assets/1393639/2c97766a-e769-41cf-b58c-5f93745ab85d)

(Actually, it is very bizarre that such a change affects the CFG at all. Correct me if I'm wrong, but I believe that the exceptions listed in a `throws` clause cannot affect the run-time behavior of the program. That clause is only for documentation and compile-time error reporting.)

**Comment by msridhar** [comment]
Hi @Calvin-L is the ask here that for your original example, the label on the control-flow edge to the catch block be labeled `FileNotFoundException` rather than `IOException`?  I think the edge itself needs to be there, but the label could be more precise.

**Comment by Calvin-L** [comment]
Yes, that's exactly right.
