### ISSUE TITLE
Resource leak checker does not seem to honor try-with-resources in some cases

### ISSUE THREAD

**Issue by jacek-lewandowski** [typetools/checker-framework#6037]
I have the following method:

```java
    static List<File> list(@Owning DirectoryStream<Path> stream) throws IOException
    {
        try
        {
            return StreamSupport.stream(stream.spliterator(), false)
                                .map(File::new)
                                .filter((f) -> !f.isDirectory())
                                .collect(Collectors.toList());
        }
        finally
        {
            stream.close();
        }
    }
```

It passes the analysis, however if I refactor it into:

```java
    static List<File> list(@Owning DirectoryStream<Path> stream) throws IOException
    {
        try (stream)
        {
            return StreamSupport.stream(stream.spliterator(), false)
                                .map(File::new)
                                .filter((f) -> !f.isDirectory())
                                .collect(Collectors.toList());
        }
    }
```

the analysis fails with required.method.not.called - is it possible that it automatically detects the close method was called on the parameter?

**Comment by kelloggm** [comment]
I suspect that there is an issue with our code for handling try-with-resources: all of the examples in our test suite currently involve allocating a new local variable in the `try`, not using a formal.

**Comment by msridhar** [comment]
@kelloggm it seems we could solve this problem if we exposed the right info in the CFG, is that right?  I think it is appropriate information to expose.  Arguably the CFG is incomplete right now since it does not expose this information, nor does it contain an explicit `close()` call in a `finally` block or some similar modeling.

**Comment by msridhar** [comment]
A slightly analogous case might be synchronized blocks, which are handled [here](https://github.com/typetools/checker-framework/blob/b610a9f1f140f24216bf91f297cf834a94eb521c/dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java#L3438-L3451).  We could add a similar `TryWithResourcesNode` at the start of the corresponding block.  I'm not sure we need a special node at the end of the block.

**Comment by jacek-lewandowski** [comment]
hey, is there any chance that it will be fixed in the upcoming July release?

**Comment by msridhar** [comment]
@jacek-lewandowski I think a fix for the July release is unlikely at this point.  I think @mernst was planning on making the requisite changes to the dataflow library.  After that we will have to update the Resource Leak Checker based on the newly-exposed information.  The latter step shouldn't take long, but given the upcoming release date, my expectation is that it won't be done in time.  Once this is fixed, we can consider a patch release if it is causing a serious inconvenience for you.

**Comment by mernst** [comment]
Thanks for the bug report!  I will change the dataflow library to address this.  However, I will not be able to do so in time for the August 1 release.
