### ISSUE TITLE
Checker hangs indefinitely after 3.35.0

### ISSUE THREAD

**Issue by tmarback** [typetools/checker-framework#6098]
Starting with version 3.35.0, some of my projects that are configured to use the Checker framework now hang indefinitely when compiling (with Checker enabled). For example, with these two sequences of commands: (assuming git/maven/javac already installed and configured)

```bash
git clone https://github.com/tmarback/modular-commands.git
cd modular-commands/
git submodule update --init --recursive
timeout 10m mvn clean compile -Dchecker.version=3.34.0 -P lint
```

```bash
git clone https://github.com/tmarback/modular-commands.git
cd modular-commands/
git submodule update --init --recursive
timeout 10m mvn clean compile -Dchecker.version=3.35.0 -P lint
```

The only difference is whether the Checker version used is 3.34.0 or 3.35.0, but in the former the build will complete successfully within 2-3 minutes while on the latter it gets up to the point where compilation with Checker enabled starts, then no further output happens until it times out (I've tried it without timeout before and even after 30+ minutes nothing happens). Changing what specific checkers are enabled or other configuration parameters doesn't seem to affect anything. Have reproduced this in multiple environments (both Windows and Linux) as well.

Will note that I'm seeing this happen on projects with >100 source files but not on one with <25 files, despite their configurations being largely identical minus dependencies, but not sure if this is related or only a coincidence.

I'm not quite sure how to even start tracking down where the source of the problem is, let alone reduce to a minimal reproducer, so any guidance is greatly appreciated.

**Comment by mernst** [comment]
Thanks for the bug report, and I'm sorry you are seeing this problem.

I would start debugging by:
 * using 3.36.0, which was released this month and fixes some bugs
 * using the progress tracing command line options at
   https://checkerframework.org/manual/#creating-debugging-options-progress
   which can show what code is being processed when the infinite loop occurs
 * while the Checker Framework is in its infinite loop (no more progress is being made), get a traceback from from each Java thread, using any of the following techniques:
    * `jstack _pid_`  (`jcmd` gives a list of pids)
    * `jcmd _pid_ Thread.print`  (just `jcmd` gives a list of pids)
    * `kill -QUIT _pid_`
    * `ctrl-\` if Java is running in a shell.

Other people might have different strategies.
If you can help with this, that would be great; but we can also do it later this week.

**Comment by tmarback** [comment]
> using 3.36.0, which was released this month and fixes some bugs

Sorry for not being more clear, 3.36.0 is still affected.

Thanks for the suggestions, I never noticed the progress options :)

See logs from running with `-Afilenames` enabled for a few seconds: https://pastebin.com/tLdkS6tT

There seems to be an error getting recursively generated which is why it's getting stuck (in hindsight I should have considered the possibility that Maven was just eating the output but oh well). Now that I think about it, I *did* find it weird that javac was using so much memory.
