### ISSUE TITLE
Hard-coded test root directory in CheckerFrameworkPerDirectoryTest and CheckerFrameworkPerFileTest

### ISSUE THREAD

**Issue by nickbreen** [typetools/checker-framework#6125]
When writing and testing a new Checker, contained within another project, it's convenient to extend `CheckerFrameworkPerFileTest` or `CheckerFrameworkPerDirectoryTest`.

These super classes unfortunately hard-code the root `"tests"` path for `testDir`. Specifically:

https://github.com/typetools/checker-framework/blob/ed85eac26f3aea938a8d3bcaf22f350e3fff8e0d/framework-test/src/main/java/org/checkerframework/framework/test/CheckerFrameworkPerFileTest.java#L73-L82

and

https://github.com/typetools/checker-framework/blob/ed85eac26f3aea938a8d3bcaf22f350e3fff8e0d/framework-test/src/main/java/org/checkerframework/framework/test/CheckerFrameworkPerDirectoryTest.java#L126-L138

This forces checker framework's project structure on the other project.

A trivial constructor refactor would allow test authors to avoid the hard-coded path.

[testRoot.diff.txt](https://github.com/typetools/checker-framework/files/12287136/testRoot.diff.txt)

**Comment by mernst** [comment]
Thank you for this suggestion.  We would accept this as a pull request.  Do you want to open one, or should I do it based on the diff you provided?

**Comment by nickbreen** [comment]
I'll do a PR.

I just hacked that diff up so I'll do it properly.

**Comment by mernst** [comment]
Great!  Thank you.  I look forward to it.
(You'll have to add your name to the contributors list; if you forget to do that, CI will fail for the PR and it will give you instructions about how to do it.)

**Comment by nickbreen** [comment]
There's another hard-coded `"tests"` in `org.checkerframework.framework.test.TestUtilities#findNestedJavaTestFiles`

https://github.com/typetools/checker-framework/blob/600920f22049b5d55b8c1ade5fd23402dff016d0/framework-test/src/main/java/org/checkerframework/framework/test/TestUtilities.java#L67-L69

With an unused variant near-by:

https://github.com/typetools/checker-framework/blob/600920f22049b5d55b8c1ade5fd23402dff016d0/framework-test/src/main/java/org/checkerframework/framework/test/TestUtilities.java#L71-L73

**Comment by nickbreen** [comment]
And another in `org.checkerframework.framework.test.PerDirectorySuite#getParametersList`

https://github.com/typetools/checker-framework/blob/600920f22049b5d55b8c1ade5fd23402dff016d0/framework-test/src/main/java/org/checkerframework/framework/test/PerDirectorySuite.java#L69-L83

**Comment by nickbreen** [comment]
The root directory for test fixtures is required in **two** places:

1. in the test class so it can be configured with the correct source path by `org.checkerframework.framework.test.TestConfigurationBuilder` to compile the fixtures.
2. in the test runner so it can find the test fixtures can be injected as the parameterised test parameters.

**Comment by nickbreen** [comment]
https://github.com/nickbreen/checker-framework/tree/issue-6125

**Comment by mernst** [comment]
@nickbreen Thanks for fixing this!
