### ISSUE TITLE
WPI: Update manual with instructions to run WPI from a binary distribution of the Checker Framework?

### ISSUE THREAD

**Issue by jyoo980** [typetools/checker-framework#6155]
Recently, I executed the following workflow:

1. Download the latest binary distribution of the Checker framework from [here](https://checkerframework.org).
2. Attempt to run `wpi.sh` on a Java codebase to infer annotations for the Optional checker. That is, I ran `wpi.sh -- --checker optional` from the root of a Java project.

This (obvious to me now) does not work, since `wpi.sh` assumes that it is being executed from a locally-built version of the Checker Framework (it has a dependency on `bin-devel`, which is not part of the binary distribution).

The current documentation for WPI in the Checker Framework does not make this clear.

I guess there are two things to consider:

1. Is what I did even a "normal" usage pattern for a potential user?

I can imagine it being so, since a user might want an easy way to try out WPI without having to build the Checker Framework from source first.

If that's the case, should we either:

1. Update the documentation to let users know that they should build from source first?
2. Update `wpi.sh` to download the necessary dependencies.

I could also be totally wrong and this isn't a usage pattern we would even want to consider.

**Comment by kelloggm** [comment]
Thanks for trying out WPI.

> Is what I did even a "normal" usage pattern for a potential user?

Yes, it's definitely what we envisioned. But I don't think WPI has been used by someone who didn't already have a local copy of the CF for other reasons, so we probably just didn't notice!

> Update `wpi.sh` to download the necessary dependencies.

This is definitely the preferred solution. If you'd like to make an attempt at a PR to do that, I'd be happy to review it. Or, I can take a look - but my schedule is super busy over the next ~10 days, so I probably can't prioritize it until 9/18 or so.

**Comment by jyoo980** [comment]
I can try to take a look this weekend at updating `wpi.sh`.

Thanks @kelloggm!
