### ISSUE TITLE
TaintingChecker does not run under certain circumstances

### ISSUE THREAD

**Issue by rkraneis** [typetools/checker-framework#618]
~~The TaintingChecker seems to not run at all in a larger project.~~ (Edit: the larger project used classic.Untainted; switching to "normal" Untainted leaves only the ordering issue)
Trying to reproduce the issue in a toy project (https://github.com/rkraneis/checker-labs) I found that it does not run if it is listed/called after the RegexChecker (cf. [the linked toy projects pom.xml](https://github.com/rkraneis/checker-labs/blob/5919122b5b5c233c211c5fd663925f1769414d7c/pom.xml#L40L42) and [main class](https://github.com/rkraneis/checker-labs/blob/5919122b5b5c233c211c5fd663925f1769414d7c/src/main/java/io/github/rkraneis/checker/labs/NewMain1.java)). Tested with versions 1.9.11 and 1.9.12.

**Comment by rkraneis** [comment]
Tested again with 1.8.11 (TaintingChecker works regardless of order) and 1.9.0 (TaintingChecker does not run if RegexChecker is configured before it).

**Comment by mernst** [comment]
I have confirmed this issue and added a test case that does not depend on Maven.
It appears in `checker-framework/checker/tests/command-line-tests/issue618`.

**Comment by mernst** [comment]
As noted in the source code for the test case, disabling caching does not affect the outcome of the test.
