### ISSUE TITLE
Will `NodeVisitor.visitDeconstructorPattern` ever be invoked for transfer functions?

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#6215]
I was starting to test NullAway with Checker Framework 3.39.0 (https://github.com/uber/NullAway/pull/839).  I wanted to write a test that would exercise our new `visitDeconstructorPattern` method but was unable to do so.  I tried a deconstruction pattern inside `instanceof` and a switch `case`.  I'm just curious, will this method ever be invoked (as of right now anyway) for a `NodeVisitor` implementing the `ForwardTransferFunction` interface for use with dataflow analysis?  If so, is there a corresponding code example that would cause it to be called?  Thanks!

**Comment by smillst** [comment]
Thanks for asking!  There's a bug.  I fixed it in #6217.
