### ISSUE TITLE
Improve documentation of AnnotatedTypeMirror.getExplicitAnnotations()

### ISSUE THREAD

**Issue by jthaine** [typetools/checker-framework#625]
`AnnotatedTypeMirror.getExplicitAnnotations()` does not return explicit annotations on class declarations, such as `@Regex(2)` in `@Regex(2) class MyClass {}`.

The Javadoc of `getExplicitAnnotations()` should be fixed to indicate which kinds of trees it reliably returns explicit annotations for.

Once this is done, the Javadoc of methods that call `getExplicitAnnotations()` should be fixed accordingly, especially the Javadoc for `AnnotatedTypeMirror.hasExplicitAnnotation` (both overloads) and `AnnotatedTypeMirror.hasExplicitAnnotationRelaxed`.

**Comment by wmdietl** [comment]
An AnnotatedTypeMirror is created for type uses. A class declaration is not a type use. In some situations we use the annotations on a class declarations to influence defaulting.
Method getExplicitAnnotations should return explicit annotations in type use locations, not explicit annotations that had an impact of defaulting - there would be quite a few others, e.g. `DefaultFor` annotations that might be in scope.
