### ISSUE TITLE
javac cannot process aliases of annotation processors when they are specified in an argument file

### ISSUE THREAD

**Issue by miyakawataku** [typetools/checker-framework#631]
When `-processor <alias>` option is given in an argument file, which is specified like `@javac-args.txt`, checker javac cannot find corresponding annotation processors.

Example argument file:

    -processor
    nullness
    Foo.java

To reproduce the issue, execute checker javac using the argument file above.

    path/to/checker/bin/javac @javac-args.txt

Then javac outputs the following message:

    error: Annotation processor 'nullness' not found
    1 error

I confirmed the issue in the version 1.9.12.

**Comment by mernst** [comment]
This is documented here:
http://types.cs.washington.edu/checker-framework/current/checker-framework-manual.html#shorthand-for-checkers
