### ISSUE TITLE
Spurious resource leak report when returning before a variable's definition

### ISSUE THREAD

**Issue by Calvin-L** [typetools/checker-framework#6317]
Given this code:
```java
import java.io.*;
import org.checkerframework.checker.nullness.qual.*;
import org.checkerframework.checker.mustcall.qual.*;
import org.checkerframework.checker.calledmethods.qual.*;

abstract class TestCase {

  abstract @Nullable Closeable alloc();
  abstract boolean arbitraryChoice();

  void method() throws IOException {

    if (arbitraryChoice()) {
      return;
    }

    Closeable r1 = alloc();
    if (r1 == null) {
      return;
    }
    r1.close();

  }

}
```

The RLC reports
```
error: [required.method.not.called] @MustCall method close may not have been invoked on r1 or any of its aliases.
      Closeable r1 = alloc();
                ^
  The type of object is: java.io.Closeable.
  Reason for going out of scope: regular method exit
```

The error looks spurious. Indeed, removing the early return block
```java
      if (arbitraryChoice()) {
        return;
      }
```
silences the warning! It appears that the RLC wants us to close `r1` at the premature return site, before it has been defined.

**Comment by msridhar** [comment]
Did some quick investigation here.  Something seems to be going on where when we remove the first early return block, the resource leak store (i.e., the called methods store) holds the fact that close() is always called on r1 at the normal exit of the method.  My guess is the first early return block leads to a control-flow merge just before the normal exit, such that the `r1.close()` fact no longer remains in the store at the normal exit, hence the false positive warning.

Where I am lost is that I don't understand why we don't report a warning even without the first early return block.  For this version of the code:
```java
  void method() throws IOException {
    Closeable r1 = alloc();
    if (r1 == null) {
      return;
    }
    r1.close();
  }
```
Reasoning that this code is safe requires knowing that at the explicit `return` statement, `r1` is `null` and hence should have type `@CalledMethodsBottom` (or something like that).  I don't see any code in our checkers that performs this kind of reasoning, though.  @kelloggm @Nargeshdb am I missing something, and did we write code somewhere to reason about this kind of null check?

**Comment by Calvin-L** [comment]
@msridhar I also did a little investigating. I'm not sure if this will be useful, but here are some disorganized thoughts.

----

My original diagnosis might not have been right. The test case is very brittle. You can also, surprisingly, silence the error by removing the second if-check:
```java
    if (r1 == null) {
      return;
    }
```
So I might have been wrong when I wrote "the RLC wants us to close r1 at the premature return site, before it has been defined". Instead, I now believe that there's some other explanation, and that you figured it out:

> So now I think the issue is in how we handle the control-flow merge resulting from the first explicit return statement. 

But, I have a different idea about the fix.

Here's the relevant part of the CFG:

<img width="1037" alt="Screenshot 2023-12-02 at 2 37 32 PM" src="https://github.com/typetools/checker-framework/assets/1393639/5fcc12b5-cd53-4329-9c54-1110110eb997">

The conditional block at the top of the picture corresponds to the second if-check in the original code. The error is reported when `MustCallConsistencyAnalyzer.propagateObligationsToSuccessorBlock` visits the starred edge. 

There's a piece of true information that is not shown the CFG:

 - Along the starred edge, the information `r1 > @CalledMethodsBottom` flows to the `<exit>` block.

But that information is lost. As you noted, `r1` is not present in the `<exit>` block's before-store because it is not present in every incoming store. Instead, we only have access to the merged result of all those incoming stores. Some incoming stores have `r1` in scope and some don't.

Instead of making a sweeping change like

> the absence of r1 in that store to be interpreted as r1 having the type @CalledMethodsBottom

maybe a simpler fix is to write a method that can tell us what information flows along a certain edge. Such a method might obviate a lot of complex and subtle logic in `MustCallConsistencyAnalyzer`:

https://github.com/typetools/checker-framework/blob/43db4471ceca09946aea0947701e7e23454f4b4e/checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java#L2098-L2099
 
Ideally, I think all that complex logic could be replaced with something extremely simple:
```java
  var mcStore = mcAtf.getAnalysisResult().getStoreAlongEdge(currentBlock, successor);
  var cmStore = analysis.getResult().getStoreAlongEdge(currentBlock, successor);
```

**Comment by msridhar** [comment]
Very interesting @Calvin-L.  I'll have to digest more but your proposed solution sounds a lot simpler and cleaner than what I was thinking.

**Comment by msridhar** [comment]
> maybe a simpler fix is to write a method that can tell us what information flows along a certain edge. Such a method might obviate a lot of complex and subtle logic in MustCallConsistencyAnalyzer

Looking more I think this is the right idea here.  The problem in this case is that when doing a consistency check for the CFG edge from a conditional block to the exit block, we use `analysis.getInput(currentBlock).getRegularStore()` to do the consistency check.  We should instead choose either the then store or the else store, depending on which successor edge we are looking at.  I _think_ this is only an issue for conditional blocks.  For any other block with multiple CFG successors (just exceptional blocks?), the block should contain at least one node, and then we choose the store immediately after that node, which is indeed the information that would flow along any successor edge.

As to adding a `getStoreAlongEdge()` method, it's a nice abstraction that could make the code easier to read, but I think we'd have to implement it using logic similar to what we have now.  Unfortunately I don't think that information is cached anywhere in the `AnalysisResult`.  There is also some hacky logic around `@CreatesMustCallFor` here:

https://github.com/typetools/checker-framework/blob/43db4471ceca09946aea0947701e7e23454f4b4e/checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java#L2145-L2148

But I think that will go away as part of #6221.

**Comment by msridhar** [comment]
FYI I have a WIP branch investigating  a fix to this issue here:

https://github.com/msridhar/checker-framework/tree/issue-6317

Still too hacky and not everything is working as I expect, but I think (hope?) it's on the right track.
