### ISSUE TITLE
Conflict between typetools/stubparser and javaparser/javaparser

### ISSUE THREAD

**Issue by cushon** [typetools/checker-framework#6406]
https://github.com/typetools/stubparser is a fork of https://github.com/javaparser/javaparser, and declares code in the same `com.github.javaparser` package. This means that if a compilation includes both the checker framework, and another annotation processor that depends on javaparser/javaparser, the two versions of those `com.github.javaparser` classes will conflict.

Would it be technically feasible to rename the packages used by typetools/stubparser to avoid this clash?

**Comment by smillst** [comment]
They are renamed in checker.jar when doing a release.  But Iooking at the gradle build files that doesn't happen when building the Maven artifacts for a local or SNAPSHOT release.  Is that where you are getting the conflict?  I can change it so they are always renamed.

**Comment by cushon** [comment]
I wasn't seeing the renaming in `checker.jar` either, am I missing anything?

```
$ wget https://checkerframework.org/checker-framework-3.42.0.zip
$ unzip checker-framework-3.42.0.zip
$ jar tf ./checker-framework-3.42.0/checker/dist/checker.jar | grep javaparser
```

My motivation here was that I was investigating building the Checker Framework with Bazel. Doing the renaming consistently in `checker.jar` and maven sounds good to me, but mostly I wondered if doing the renaming made sense in general or if it was likely to create an issues.
