### ISSUE TITLE
Retention of @DefaultQualifier should be RUNTIME

### ISSUE THREAD

**Issue by mmorrisontx** [typetools/checker-framework#6420]
Unless I'm missing something, I believe the `@Retention` of `@DefaultQualifier` should be RUNTIME, not SOURCE. As is, `@DefaultQualifier(@Nonnull)` used within a published library is disregarded when the library is consumed because the annotation is missing from intellij's decompiled version of the class.

https://github.com/typetools/checker-framework/blob/master/checker-qual/src/main/java/org/checkerframework/framework/qual/DefaultQualifier.java

Strangely, the retention of DefaultQualifier.List is already RUNTIME, but unfortunately that one isn't respected by intellij, making it not a viable hack around this issue.

**Comment by mernst** [comment]
Thanks for the bug report, and sorry for my delay in responding; this fell through the cracks.
