### ISSUE TITLE
Unexpected interference of RegexChecker and TaintingChecker

### ISSUE THREAD

**Issue by AFulgens** [typetools/checker-framework#647]
I'm fairly new in using the Checker Framework, so this as well may be a PEBKAC.

Wanted to create a checked version of [ParamConverterProvider](https://docs.oracle.com/javaee/7/api/javax/ws/rs/ext/ParamConverterProvider.html) with nested classes of [ParamConverter<T>](https://docs.oracle.com/javaee/7/api/javax/ws/rs/ext/ParamConverter.html), which passes the Nullness, Tainting and IGJ checkers. I ended up with the following astub:
```
public interface ParamConverter<@Nullable @Mutable @Untainted T> {
    public @Nullable @Mutable @Untainted T fromString(@Nullable @Tainted String value);
    public @Nullable @Untainted String toString(@Nullable @Mutable @Untainted T value);
}

public interface ParamConverterProvider {
    public <@Nullable @Mutable @Untainted T> @Nullable @Untainted ParamConverter<@Nullable @Mutable @Untainted T> getConverter(@Untainted Class<@Nullable @Mutable @Untainted T> rawType, @Nullable @Untainted Type genericType, Annotation @Nullable @Untainted [] annotations);
}
```
(Wonder why you need `@Nullable`? Check out [this link](http://stackoverflow.com/questions/24256095/jax-rs-paramconverter-paramconverterprovider-method-return-type-mismatch).)

Everything works perfectly with the Maven build, when invoking all the above mentioned checkers. However, as soon as I try to run the Tainting and the Regex checkers in the same build process, I get a lot of the following kind of errors:
```
[ERROR] found   : ParamConverter<T extends Object>
[ERROR]
[ERROR] required: ParamConverter<T extends Object>
```
and
```
[ERROR] found   : Type
[ERROR]
[ERROR] required: Type
```
and so on.

If I run only a bunch of checkers along with the Tainting BUT the Regex, everything is fine.
If I run only a bunch of checkers along with the Regex BUT the Tainting, everything is fine.
Any ideas, suggestions?

**Comment by mernst** [comment]
Possibly related to #618
