### ISSUE TITLE
Broken link on manual entry for 29.24 ReIm immutability 

### ISSUE THREAD

**Issue by smonteiro** [typetools/checker-framework#6510]
See (https://checkerframework.org/manual)

29.24 ReIm immutability 
A checker and inference tool for ReIm ‍[[HMDE12](https://checkerframework.org/manual/#HuangMDE2012), [Hua14](https://checkerframework.org/manual/#Huang2014)], an immutability type system, is available at http://www.cs.rpi.edu/~huangw5/cf-inference/.

^That last link yields a 404 Not Found

**Comment by jyoo980** [comment]
Thanks for reporting this! You are correct that the link you provided (http://www.cs.rpi.edu/~huangw5/cf-inference/) is returning a 404.

I think the closest replacement I found is here: https://github.com/proganalysis/type-inference.

@mernst Do you think replacing the 404 link with the one I found is a workaround?

**Comment by mernst** [comment]
Yes, that is a good update.  Thanks!  I committed it in d0d775418.

**Comment by mernst** [comment]
@smonteiro Thanks for reporting the problem, and my apologies for the delay in responding.

**Comment by smonteiro** [comment]
no worries. I am glad that weare still actively developing and maintaining.


-------- Original message --------
From: Michael Ernst ***@***.***>
Date: 8/4/24 18:17 (GMT-05:00)
To: typetools/checker-framework ***@***.***>
Cc: Sidney Monteiro ***@***.***>, Mention ***@***.***>
Subject: Re: [typetools/checker-framework] Broken link on manual entry for 29.24 ReIm immutability (Issue #6510)


@smonteiro<https://github.com/smonteiro> Thanks for reporting the problem, and my apologies for the delay in responding.
