### ISSUE TITLE
Update to JavaParser 3.26.0

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#6648]
Release notes: https://github.com/javaparser/javaparser/releases/tag/javaparser-parent-3.26.0

This fixes https://github.com/javaparser/javaparser/issues/4041, which was impacting WPI on certain programs that use `sealed` as a variable name.

I think updating JavaParser is a bit involved / risky so I wanted to open an issue first

FYI @iamsanjaymalakar

**Comment by smillst** [comment]
FYI, we will not be updating to version 3.26.0 because switch statements aren't parseable in that release. (https://github.com/javaparser/javaparser/issues/4455) I'll update the Stubparser as soon as the fixed is released.
