### ISSUE TITLE
IGJ checker non-terminating?

### ISSUE THREAD

**Issue by dbrosoft** [typetools/checker-framework#668]
Download and unzip [lox.zip](https://github.com/typetools/checker-framework/files/224899/lox.zip) to get the directory hierarchy (top level is "java") and run the following command:
```sh
(java -jar $CHECKERFRAMEWORK/checker/dist/checker.jar -processor igj\
 -AuseDefaultsForUncheckedCode=source java/util/concurrent/locks/StampedLock.java)
```
The IGJ processor seems to get stuck on this source file.  I haven't observed this behavior on any other source.  Without the -A argument, the compilation does terminate (by failing).

**Comment by smillst** [comment]
Added a test case here: checker/tests/igj/Issue668.java

The for loop in org.checkerframework.dataflow.analysis.Analysis#performAnalysis loops over 100,000 times.

**Comment by smillst** [comment]
(Same results when caching is turned off.)

**Comment by mernst** [comment]
IGJ checker will be removed.
