### ISSUE TITLE
Exception after upgrade from 3.47.0 to 3.48.0

### ISSUE THREAD

**Issue by romani** [typetools/checker-framework#6842]
Sorry for not following template, I will update as required a bit later:

> As explained in the instructions for submitting an issue at https://checkerframework.org/manual/#reporting-bugs, please include four pieces of information:
 * commands (that can be cut-and-pasted into a command shell),
 * inputs,
 * outputs, and
 * expectation.

------

detected at https://github.com/checkstyle/checkstyle/pull/15731

commands:
```
git clone git@github.com:checkstyle/checkstyle.git
cd checkstyle
mvn -e --no-transfer-progress clean compile  -Pchecker-index,no-validations
```

with groovy:
```
./.ci/checker-framework.groovy checker-index
```
this groovy just wraps execution to handle suppressions after  `mvn` is finished.

exception:
```
Warning:  /home/runner/work/checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/
xpath/iterators/ReverseListIterator.java:[53,25] [type.argument.inference.crashed]
 Type argument inference crashed for ArrayList constructor
  error: An exception occurred: class org.checkerframework.framework.type
.AnnotatedTypeMirror$AnnotatedTypeVariable cannot be cast to class 
org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedWildcardType 
(org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedTypeVariable and 
org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedWildcardType are 
in unnamed module of loader java.net.URLClassLoader @15bb6bea)
```

Expected: no exceptions.

**Comment by smillst** [comment]
Thanks for reporting!  I think this is the same crash that I fixed in https://github.com/typetools/checker-framework/pull/6850/.  I'm going to do a bug fix release today including that fix.  So, if the crash is not fixed after that release, please let us know.
