### ISSUE TITLE
I18n Checker: must implement GLB

### ISSUE THREAD

**Issue by dbrosoft** [typetools/checker-framework#688]
Save [Issue685.zip](https://github.com/typetools/checker-framework/files/239674/Issue685.zip) and proceed as follows:
```sh
$ unzip Issue685.zip
$ cd Issue685
$ java -jar $CHECKERFRAMEWORK/checker/dist/checker.jar -processor i18n -AprintErrorStack java/lang/invoke/MemberName.java
```
Stack trace is provided in `error.txt`.  Source for classes in `sun` is in the [Annotated JDK](https://bitbucket.org/typetools/annotated-jdk8u-jdk).

**Comment by dbrosoft** [comment]
(Now why did the number skip ahead and make my choice of zipfile name look silly?)

**Comment by mernst** [comment]
Because issues and pulls share a single index.  There are pull requests 686 and 687.

**Comment by smillst** [comment]
Because the I18N Checker has annotations that take arguments, the default implementation of GLB is wrong.
