### ISSUE TITLE
NullPointerException in FormatterTreeUtil.formatAnnotationToCategories()

### ISSUE THREAD

**Issue by dbrosoft** [typetools/checker-framework#690]
Save [Issue690.zip](https://github.com/typetools/checker-framework/files/241066/Issue690.zip) and proceed as follows:
```sh
$ unzip Issue690.zip
$ cd Issue690
$ java -jar $CHECKERFRAMEWORK/checker/dist/checker.jar -processor formatter -AprintErrorStack java/lang/invoke/MemberName.java
```
Stack trace is provided in `error.txt`.  Source for classes in `sun` is in the [Annotated JDK](https://bitbucket.org/typetools/annotated-jdk8u-jdk).

**Comment by smillst** [comment]
This is a duplication of #691.
