### ISSUE TITLE
Format Checker: must implement GLB

### ISSUE THREAD

**Issue by dbrosoft** [typetools/checker-framework#691]
Save [Issue691.zip](https://github.com/typetools/checker-framework/files/241144/Issue691.zip) and proceed as follows:
```sh
$ unzip Issue691.zip
$ cd Issue691
$ java -jar $CHECKERFRAMEWORK/checker/dist/checker.jar -processor formatter -AprintErrorStack java/util/Collections.java
```
Stack trace is provided in `error.txt`.

**Comment by smillst** [comment]
Stack trace:
````
error: SourceChecker.typeProcess: unexpected Throwable (NullPointerException) while processing java/util/Collections.java
  Compilation unit: java/util/Collections.java
  Exception: java.lang.NullPointerException; Stack trace: org.checkerframework.checker.formatter.FormatterTreeUtil.formatAnnotationToCategories(FormatterTreeUtil.java:394)
  org.checkerframework.checker.formatter.FormatterAnnotatedTypeFactory$FormatterQualifierHierarchy.isSubtype(FormatterAnnotatedTypeFactory.java:120)
  org.checkerframework.framework.util.MultiGraphQualifierHierarchy.findGlb(MultiGraphQualifierHierarchy.java:782)
  org.checkerframework.framework.util.MultiGraphQualifierHierarchy.calculateGlbs(MultiGraphQualifierHierarchy.java:762)
  org.checkerframework.framework.util.MultiGraphQualifierHierarchy.greatestLowerBound(MultiGraphQualifierHierarchy.java:413)
  org.checkerframework.framework.type.QualifierHierarchy.greatestLowerBounds(QualifierHierarchy.java:210)
  org.checkerframework.framework.util.AnnotatedTypes.addAnnotationsImpl(AnnotatedTypes.java:848)
  ````

**Comment by smillst** [comment]
@dbrosoft  The title of this issue was "AnnotatedTypeFactory.fromNewClassContextHelper: unexpected context (formatter)" but that's not the error I got (nor the error in error.txt).   Do you have another test case with that error?

**Comment by smillst** [comment]
Because the Format Checker has annotations that take arguments, the default implementation of GLB is wrong.  (The test case for this issue should be added to all-systems, with `@SuppressWarnings("")` so that new checkers will crash if they do not implement GLB when that should.)

**Comment by dbrosoft** [comment]
@smillst: My recollection is that the "unexpected context" error turned out to be due to a misconfiguration on my end; in any case, I'm not seeing it anymore.  I probably left a tab open with the issue creation dialog and the title filled in, then pasted details of this issue there by mistake.
