### ISSUE TITLE
Annotated source files for Exception and RuntimException do not contain constructor with (String, Throwable, boolean, boolean)

### ISSUE THREAD

**Issue by miyakawataku** [typetools/checker-framework#702]
Exception and RuntimeException in the annotated version of JDK do not contain constructors with parameters (String, Throwable, boolean, boolean), whereas Throwable and Error have ones.

As a result, the second argument for those constructors are wrongly regarded as ``@NonNull``.

**Comment by mernst** [comment]
Thanks for pointing that out.  I will add the missing constructors, which were added in JDK 7.
