### ISSUE TITLE
Do not include `afu.` version of annotation classes in checker-qual.jar and checker-compat-qual.jar

### ISSUE THREAD

**Issue by wmdietl** [typetools/checker-framework#711]
File `checker-framework-2.0.0.zip` contains versions of checker-qual.jar and checker-compat-qual.jar that contain unnecessary `afu.` versions of all annotations, e.g. `afu/org/checkerframework/checker/nullness/NullnessUtils.class`

These classes fulfil no purpose and should be removed.

**Comment by mernst** [comment]
When issue #700 is resolved, this issue will also be resolved.
