### ISSUE TITLE
AnnotatedDeclaredType#getEnclosingType returns ATM with missing annotations

### ISSUE THREAD

**Issue by smillst** [typetools/checker-framework#724]

**Comment by smillst** [comment]
QualifiedDeclaredType needs to keep track of the enclosing type like AnnotatedDeclaredType.

**Comment by smillst** [comment]
See test case in framework/all-systems/Issue577.java

**Comment by smillst** [comment]
I think this is the root cause of issues #437 and #134.

**Comment by wmdietlGC** [comment]
From #1099: #437 and #134 are fixed. Some mentions of #724 also work now.
A comment in AnnotatedTypes.asOuterSuper mentions #724 and is about nested classes; that hack should also be fixed. This issue stays open to fix this.
