### ISSUE TITLE
ClassCastException: AnnotatedIntersectionType to AnnotatedArrayType

### ISSUE THREAD

**Issue by Kiena** [typetools/checker-framework#738]
This may be a consequence, thus duplicate, of one or more already reported type bound related bugs, though I couldn't find one which would seem to match this exact case.

Steps to reproduce:

[cfcrash.zip](https://github.com/typetools/checker-framework/files/275524/cfcrash.zip)

1. The attached file contains a simple Maven project, with a single source file to demonstrate the issue.
- (Maven) In the `cfcrash` directory execute the command `mvn install`  
Expected: Successful build.  
Actual:  
`Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project cfcrash: Compilation failure  
error: SourceChecker.typeProcess: unexpected Throwable (ClassCastException) while processing P:\java\workspaces\test\cfcrash\src\main\java\test\cfcrash\Test.java; message: org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedIntersectionType cannot be cast to org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedArrayType`
- (Command line only) In the `cfcrash` directory execute the command (artifacts are reused from the repository):  
`javac -version -verbose -d .\target\classes -classpath ".\target\classes;p:\.m2\repository\org\checkerframework\checker\2.0.0\checker-2.0.0.jar;p:\.m2\repository\org\checkerframework\checker-qual\2.0.0\checker-qual-2.0.0.jar;p:\.m2\repository\org\checkerframework\jdk8\2.0.0\jdk8-2.0.0.jar;" -sourcepath ".\src\main\java;.\target\generated-sources\annotations;" .\src\main\java\test\cfcrash\Test.java -s .\target\generated-sources\annotations -processor org.checkerframework.checker.nullness.NullnessChecker -g -nowarn -target 1.8 -source 1.8 -encoding UTF-8 -AcheckPurityAnnotations -Alint=all -AprintAllQualifiers -AprintErrorStack -AshowSuppressWarningKeys -Awarns -Xbootclasspath/p:p:\.m2\repository\org\checkerframework\jdk8\2.0.0\jdk8-2.0.0.jar`  
Expected: No compilation error. (As happens without the processor.)  
Actual: See `cfcrash/error.txt` within the attachment for the complete output.

**Comment by smillst** [comment]
Thanks for reporting this issue.  I've added the test case to framework/tests/all-systems/Issue738.java

**Comment by smillst** [comment]
The crash reported has been fixed (47470dc).  However, this test case now crashes differently (`error: Incomparable types...)`.  This new crashed is track vis #701.
