### ISSUE TITLE
Incorrect type hierarchy in Format String Checker

### ISSUE THREAD

**Issue by mernst** [typetools/checker-framework#740]
The Format String Checker does not pass the test case
`checker-framework/checker/tests/formatter/ManualExample.java`,
which is taken from the manual.  The checker issues an error for a legal assignment (where the manual specifies a warning should be issued).

The I18n Format String Checker does not pass the test case
`checker-framework/checker/tests/i18n-formatter/ManualExample.java`
which is taken from the manual.  The checker fails to issue warnings on two error-prone, but legal, assignments.  Furthermore, it issues an `assignment.type.incompatible` error instead of the more specific `i18nformat.excess.arguments` error specified in the manual.

The GLB implementations and tests need to be updated as well, because they mimic the incorrect behavior in the rest of the implementation.

**Comment by jthaine** [comment]
Fixed with commit 9fbea5cc589824367a172dde3c22b84cf942bace
