### ISSUE TITLE
Flow Expression parser: issue a meaningful error when a flow expression cannot be parsed due to build order

### ISSUE THREAD

**Issue by jthaine** [typetools/checker-framework#763]
With the fix for issue #657 in place, given the following two files:

`Class2.java`:

    public class Class2 {
        public static void method() {
            Class1.method();
        }
    }

`Class1.java`:

    import org.checkerframework.checker.nullness.qual.*;

    public class Class1 {
        public static @Nullable Object field = null;

        @EnsuresNonNull("Class1.field")
        public static void method() {
            field = new Object();
        }
    }

An error is issued if the files are compiled in this order:

`./javac -processor nullness Class2.java Class1.java`

    Class2.java:3: error: [flowexpr.parse.error] cannot parse the expression 'Class1'
            Class1.method();
                         ^

but not if they are compiled in this order:

`./javac -processor nullness Class1.java Class2.java`

A more meaningful error message should be issued to the user in order to indicate that the expression cannot be parsed due to the order in which source files are compiled.

**Comment by mernst** [comment]
Closed in favor of #767

**Comment by jthaine** [comment]
See https://github.com/typetools/checker-framework/issues/767#issuecomment-223423032 for details on how this error occurs.
