### ISSUE TITLE
Lock expressions should be viewpoint adapted and canonicalized

### ISSUE THREAD

**Issue by smillst** [typetools/checker-framework#770]
[Rough draft of proposal](https://docs.google.com/document/d/10tYe0D60hDHdyLT2q9mIPmWHIzZaCU2UHS2lP-grNiQ/edit)
PR #686 attempted to do this, but failed.

Issue #681 and PR #674 are blocking this issue.
Issue #152 should be fixed after this issue is resolved. 

Test cases:
checker/tests/lock/ViewpointAdaptation.java
checker/tests/lock/ViewpointAdaptation2.java
checker/tests/lock/ViewpointAdaptation3.java
checker/tests/lock/Issue152.java

**Comment by jthaine** [comment]
Additional test cases in branch lock-checker-viewpoint-adaptation-for-review:
checker/tests/lock/ViewpointAdaptation.java  (different contents from the same file in the master branch)
checker/tests/lock/ViewpointAdaptation2.java
