### ISSUE TITLE
Print verbose generic information in error messages

### ISSUE THREAD

**Issue by smillst** [typetools/checker-framework#788]
Print verbose generic information anytime the lower bounds differ. 
For example, if we have:
````
found: T [extends @A super @B]
required: T [extends @C super @D]
````
then it is not enough to print
````
found: T [extends @A]
required: T [extends @C]
````
even though those (partial) printed representations are not identical.

See #594 for more discussion.

**Comment by mernst** [comment]
The test case in #594 now prints the desired information, so I am closing this issue.
