### ISSUE TITLE
Fake Enum Checker needs to be updated

### ISSUE THREAD

**Issue by jthaine** [typetools/checker-framework#789]
The Fake Enum Checker needs the following fixes:
- [ ] LUB and GLB need to be implemented since `isSubtype` is overridden and the annotation takes an argument. When doing this, ensure that LUB and GLB work for user-written fenum annotations that are subtypes of `@FenumTop`.
- [ ] The `switch.type.incompatible` error message is used in `FenumVisitor` but is not declared in `messages.properties`
- [x] The following line in the manual chapter is rendered without curly braces
  `@Target(ElementType.TYPE_USE, ElementType.TYPE_PARAMETER)`

Please consider also:
- [ ] Both TODOs in `FenumVisitor` look obsolete. Consider removing them.
- [ ] Currently the type annotation on the result of a binary comparison operator between two non-boolean types is the LUB of the fenum annotations on the LHS and RHS. Consider whether the result should be `@FenumUnqualified boolean` instead.

**Comment by mernst** [comment]
Furthermore, investigate why the compiler message checker did not issue a warning on line 54 of FenumVisitor.java where `switch.type.incompatible` is used.  That seems like a bug that should be fixed or have its own issue created.

**Comment by mernst** [comment]
All tasks have been completed.
