### ISSUE TITLE
Refactor duplicated code in CFAbstractTransfer

### ISSUE THREAD

**Issue by jthaine** [typetools/checker-framework#794]
Both `CFAbstractTransfer.processPostconditions` and `CFAbstractTransfer.processConditionalPostconditions` contain code that specially handles the expression `"this"` before calling the flow expression parser. The duplicated code should be extracted into one or more helper methods. Additionally, consider whether this code belongs in the `FlowExpressionParseUtil` class instead.

**Comment by smillst** [comment]
Fixed via c41ad16c83fb15dd2d36f8313136d8d8d31b50a5.
