### ISSUE TITLE
StackOverflowError from TypeForExpressionVisitor loop?

### ISSUE THREAD

**Issue by dbrosoft** [typetools/checker-framework#810]
Save as C.java:
```java
class C {
    java.util.Map m = new java.util.HashMap();
    java.util.Set n = m.keySet();
}
```
See [gist](https://gist.github.com/dbrosoft/62d09371c5046134d32bdf5d9350e6ac) for full output, which begins with
```
error: SourceChecker.typeProcess: unexpected Throwable (StackOverflowError) while processing C.java
  Compilation unit: C.java
  Exception: java.lang.StackOverflowError; Stack trace: java.util.HashMap$ValueIterator.<init>(HashMap.java:1456)
```
Note that there is a 38-node cycle starting at line 33 and continuing to the end.

**Comment by smillst** [comment]
Added test case framework/tests/all-systems/Issue810.java
Only the KeyForSubchecker seems to crash:
`javacheck -processor org.checkerframework.checker.nullness.KeyForSubchecker Issue810.java`
