### ISSUE TITLE
Reduce duplication in test suites

### ISSUE THREAD

**Issue by wmdietl** [typetools/checker-framework#846]
Large parts of
'framework/src/org/checkerframework/framework/test/PerDirectorySuite.java' and 'framework/src/org/checkerframework/framework/test/PerFileSuite.java' are the same.
Duplication between the files should be moved to an abstract class.
Related to PR #841

**Comment by mernst** [comment]
This can be resolved by just adding a todo comment in the source code.  (And the next time that we touch those classes, we'll hopefully fix it, but we won't keep this issue live in the issue tracker.)
