### ISSUE TITLE
unexpected Throwable (IndexOutOfBoundsException)

### ISSUE THREAD

**Issue by C-D-E** [typetools/checker-framework#871]
... when the following program is compiled:
```
package bar;
import java.nio.file.*;
import java.util.function.Predicate;
interface Foo {
	default Iterable<Path> a() {
		return f(Files::isRegularFile);
	}

	Iterable<Path> f(Predicate<Path> condition) ;
}
```

Full error message: _unexpected Throwable (IndexOutOfBoundsException) while processing D:\workspace_neon\bar\src\main\java\bar\Foo.java; message: Index: 1, Size: 1; invoke the compiler
 with -AprintErrorStack to see the stack trace_.

**Comment by mernst** [comment]
I have confirmed this bug and committed a test case as checker/tests/nullness/java8/methodref/Issue871.java .

Thanks for the report!

**Comment by smillst** [comment]
`Files::isRegularFile` signature is `static boolean isRegularFile(Path path,                                 LinkOption... options)`.  The index out of bounds occurs when checking that `Files::isRegularFile` correctly overrides `Predicate#test(T t)`.  The override checking should except (and allow) this override.
