### ISSUE TITLE
Making checkers focus on certain types

### ISSUE THREAD

**Issue by mernst** [typetools/checker-framework#872]
Some type-checkers are mostly interested in one type or a few types.
 * Some only care about strings and related types such as CharSequences and StringBuilders:  the Regex, Format String, Internationalization Format String, Property File, Internationalization, and Signature String Checkers.
 * Some only care about ints:  Signedness, Lower Bound, and Upper Bound Checkers.  
 * Some care about strings and ints: Constant Value Checker.

A type-checker sets a default annotation for unannotated code.  This should sometimes be different for types that the type-system cares about and those it does not care about.  An example is unchecked code that will later be read as a library.  The Checker Framework defaults every return value to Top and every formal parameter to Bottom, to indicate where annotations are missing.  However, this should not be done for types that the type system doesn't care about.

As an example, consider the formatter type system, which currently produces the following error when type-checking code against the annotated JDK:

```
        f.format("%H", new Integer(4));
                                   ^
  found   : int
  required: @FormatBottom int
```

Integer is not annotated for the formatter type system (and it shouldn't need to be), so the formal parameter to the constructor is treated as Bottom.  However, the formatter type system defaults the literal 4 to `@UnknownFormat`, so the invocation of the constructor fails.

It doesn't really matter what the formatter uses for non-relevant types such as int, but it should be consistent in checked and unchecked code.  Top seems like a reasonable choice.  In this case, all non-String types should default to `@UnknownFormat`, in all contexts including unchecked code.

Rather than fixing this individually for each of the 10 type systems above, the Checker Framework should provide a declarative mechanism for a checker to indicate the relevant types.  All non-relevant types would be ignored by the type system.  This might improve efficiency, too.  (I'm not sure whether we would still want to change the defaulting of the non-relevant types in unchecked code.)  Then, the 10 type systems should be rewritten to use the new mechanism.

**Comment by smillst** [comment]
Checkers will specify which types they are interested in using a meta-annotation on the Checker class.  The meta-annotation will take a list of Classes.  `Object[].class` implies that the checker is interested in all array types.  A boxed type, such as `Integer.class`, implies that the checker is interested in both `Integer` and `int` types.  

AnnotatedTypeFactory use this meta-annotation to default a declared or primitive types not in the list o a subtype of a class in the list to the top qualifier.   

Possible names:
`@SupportedJavaTypes`
`@PertinentJavaTypes`
`@GermaneJavaTypes`
`@RelavantJavaTypes`
