### ISSUE TITLE
inconsistent polymorphism defaulting

### ISSUE THREAD

**Issue by CharlesZ-Chen** [typetools/checker-framework#883]
In `AnnotatedTypeFactory#createSupportQualifiers()`, defaulting is set to support @PolyAll, and will add @PolyAll to the `supportedQuals`.

https://github.com/typetools/checker-framework/blob/master/framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java#L807

However, in `AnnotatedTypeFactory#checkSupportedQuals()`, it will enforce a checker must have polymorphic qualifiers if @PolyAll is in the list of it's `supportedQuals`.

https://github.com/typetools/checker-framework/blob/master/framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java#L420

This will cause an unexpected exception for a very simple type system that doesn't even need a polymorphic qualifier:

```java
java.lang.RuntimeException: Checker added @PolyAll to list of supported qualifiers, but the checker does not have a polymorphic qualifier.  Either remove @PolyAll from the list of supported qualifiers or add a polymorphic qualifier.
```

This is because by defaulting `AnnotatedTypeFactory` will add @PolyAll to `supportedQuals`, but because the type system is very simple and doesn't have a polymorphic qualifier, it would failed the PolyAll check in `AnnotatedTypeFactory #checkSupportedQuals()`.

It seems we need a consistent polymorphism defaulting in `AnnotatedTypeFactory` to avoid this problem. Or even better if we could enable/disable the @PolyAll depends on whether the checker has polymorphic qualifiers in it's supported qualifiers.

**Comment by smillst** [comment]
According to the documentation of `@PolyAll` it should not be supported by default.  PR #884 fixes this.
