### ISSUE TITLE
Output correct number of executed tests

### ISSUE THREAD

**Issue by wmdietl** [typetools/checker-framework#893]
This changeset https://github.com/typetools/checker-framework/commit/addc94231cc1a580cd4a695ec3fb23278036ffb2 started compiling all test files from a directory with a single javac invocation.

This greatly sped up test execution. However, the number of executed tests should be output correctly.

Previously: https://travis-ci.org/typetools/checker-framework/jobs/145028068
e.g. search for NullnessFbcTest and see `Tests run: 498`.

After this change: https://travis-ci.org/typetools/checker-framework/jobs/145047856
again for NullnessFbcTest: `Tests run: 13`

For many tests it now looks like just a single test is executed. This is misleading and makes our tests suits look poorly.

**Comment by smillst** [comment]
This number is automatically generated and I don't think there is an easy way to changes this.
