### ISSUE TITLE
NullPointerException during compilation

### ISSUE THREAD

**Issue by mgrafl** [typetools/checker-framework#906]
When running the checker version 2.1.2 (with org.checkerframework.checker.nullness.NullnessChecker) on my project (using maven), it fails at one file with a NullPointerException: 
`Exception: java.lang.NullPointerException; Stack trace: org.checkerframework.javacutil.AnnotationUtils.annotationName(AnnotationUtils.java:179)
  org.checkerframework.javacutil.AnnotationUtils.areSameByName(AnnotationUtils.java:248)
  org.checkerframework.javacutil.AnnotationUtils.areSameByClass(AnnotationUtils.java:263)
  org.checkerframework.framework.type.AnnotatedTypeMirror.replaceAnnotation(AnnotatedTypeMirror.java:620)
  org.checkerframework.framework.flow.util.LubTypeVariableAnnotator.annotateLub(LubTypeVariableAnnotator.java:128)
  org.checkerframework.framework.flow.util.LubTypeVariableAnnotator.annotateTypeVarAsLub(LubTypeVariableAnnotator.java:75)
  org.checkerframework.framework.util.AnnotatedTypes.annotateAsLub(AnnotatedTypes.java:779)
  org.checkerframework.framework.util.AnnotatedTypes.leastUpperBound(AnnotatedTypes.java:636)
  org.checkerframework.framework.util.typeinference.solver.SupertypesSolver.leastUpperBound(SupertypesSolver.java:399)
  org.checkerframework.framework.util.typeinference.solver.SupertypesSolver.targetToTypeLubs(SupertypesSolver.java:258)
  org.checkerframework.framework.util.typeinference.solver.SupertypesSolver.solveFromSupertypes(SupertypesSolver.java:48)
  org.checkerframework.framework.util.typeinference.DefaultTypeArgumentInference.inferFromArguments(DefaultTypeArgumentInference.java:420)
  org.checkerframework.framework.util.typeinference.DefaultTypeArgumentInference.infer(DefaultTypeArgumentInference.java:251)
  org.checkerframework.framework.util.typeinference.DefaultTypeArgumentInference.inferTypeArgs(DefaultTypeArgumentInference.java:102)
  org.checkerframework.framework.util.AnnotatedTypes.findTypeArguments(AnnotatedTypes.java:603)
  org.checkerframework.framework.type.AnnotatedTypeFactory.methodFromUse(AnnotatedTypeFactory.java:1905)
  org.checkerframework.framework.type.AnnotatedTypeFactory.methodFromUse(AnnotatedTypeFactory.java:1889)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.methodFromUse(GenericAnnotatedTypeFactory.java:1205)
  org.checkerframework.checker.nullness.NullnessAnnotatedTypeFactory.methodFromUse(NullnessAnnotatedTypeFactory.java:308)
  org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:207)
  org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:50)
  com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
  com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
  org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:37)
  org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:1244)
  org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1015)
  org.checkerframework.framework.flow.CFAbstractTransfer.getValueFromFactory(CFAbstractTransfer.java:210)
  org.checkerframework.framework.flow.CFAbstractTransfer.visitMethodInvocation(CFAbstractTransfer.java:918)
  org.checkerframework.checker.initialization.InitializationTransfer.visitMethodInvocation(InitializationTransfer.java:198)
  org.checkerframework.checker.nullness.NullnessTransfer.visitMethodInvocation(NullnessTransfer.java:214)
  org.checkerframework.checker.nullness.NullnessTransfer.visitMethodInvocation(NullnessTransfer.java:56)
  org.checkerframework.dataflow.cfg.node.MethodInvocationNode.accept(MethodInvocationNode.java:80)
  org.checkerframework.dataflow.analysis.Analysis.callTransferFunction(Analysis.java:404)
  org.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:222)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:960)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:917)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:844)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1159)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:206)
  org.checkerframework.checker.initialization.InitializationVisitor.visitClass(InitializationVisitor.java:276)
  org.checkerframework.checker.initialization.InitializationVisitor.visitClass(InitializationVisitor.java:59)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:66)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:978)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:464)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:208)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.main.Main.compile(Main.java:381)
  com.sun.tools.javac.main.Main.compile(Main.java:370)
  com.sun.tools.javac.main.Main.compile(Main.java:361)
  com.sun.tools.javac.Main.compile(Main.java:56)`

It appears that `getInAnnotationHierarchy` returns `null` in https://github.com/typetools/checker-framework/blob/checker-framework-2.1.2/framework/src/org/checkerframework/framework/flow/util/LubTypeVariableAnnotator.java#L129.

**Comment by smillst** [comment]
I'm sorry your having problems.  Can you please give us instructions on how to reproduce this exception?  Please see follow the instructions in [this section](http://types.cs.washington.edu/checker-framework/current/checker-framework-manual.html#reporting-bugs) of the manual.

**Comment by mgrafl** [comment]
I was able to reduce the file that creates the error: attached [NullPointerTest.java.txt](https://github.com/typetools/checker-framework/files/458653/NullPointerTest.java.txt) (upload does not allow .java, so please remove the .txt). 

Command: `java -jar checker.jar -proc:only -processor org.checkerframework.checker.nullness.NullnessChecker -version -verbose -AprintErrorStack -AprintAllQualifiers NullPointerTest.java`

Output: [output.txt](https://github.com/typetools/checker-framework/files/458657/output.txt)

**Comment by smillst** [comment]
Thanks for the test case!  I'm able to reproduce the problem and added the test to checker/tests/nullness/Issue906.java.

(This is a problem with LUB and should be fixed by #643.  I've added this issue to the list of issues there.)
