### ISSUE TITLE
Warn about annotations improperly interspersed with other modifiers

### ISSUE THREAD

**Issue by mernst** [typetools/checker-framework#916]
The Checker Framework should issue a warning:
- if a declaration annotation follows a regular modifier (public, private, static, final, etc.)
- if a type annotation precedes a regular modifier (public, private, static, final, etc.)
- if a type annotation precedes a declaration annotation

**Comment by mernst** [comment]
This looks a bit tricky because [ModifiersTree](http://docs.oracle.com/javase/8/docs/jdk/api/javac/tree/com/sun/source/tree/ModifiersTree.html) maintains a set of Modifiers, meaning it doesn't maintain order and has no line/column information either.

**Comment by smillst** [comment]
This is worth doing, but not worth our time to do.
