### ISSUE TITLE
Don't require @ImplicitFor(typeNames = Void.class)

### ISSUE THREAD

**Issue by mernst** [typetools/checker-framework#939]
Many but not all of the bottom type qualifiers in the Checker Framework are meta-annotated with

```
  @ImplicitFor(typeNames = Void.class)
```

Presumably the missing ones are errors. 

I think it would be nicer for the Checker Framework to automatically determine the bottom tye annotation and to apply it to the Void class and the null literal, unless overridden (as it would be for the Nullness type system).

**Comment by smillst** [comment]
Fixed via 6bfa424c1e5d206d7620ac71e8f91a61f9319f4d.
