### ISSUE TITLE
CF's Google Java Format should support casting to qualified primitive types.

### ISSUE THREAD

**Issue by jyluo** [typetools/checker-framework#941]
Hi Mike,

When running the formatter for CF code, statements like `(@m int) 5`  results in errors such as "error: did not generate token int" whereas `(@m Integer) boxedIntRef` is handled by the formatter. It would be great to support the formatting of qualifier casting of primitives as some of the Units Checker test cases I'm working on requires this.

Thanks!

**Comment by cushon** [comment]
Do you have a complete example of a file that causes the crash? The fix for google/google-java-format#65 should have fixed this too.

**Comment by mernst** [comment]
We are using the 1.0 release of google-java-format.  I just noticed that 1.1 was released last week.

**Comment by jyluo** [comment]
Hi Liam,

Example file contents:
```
import org.checkerframework.checker.units.qual.*;
class FormattingTestCase {
    //:: warning: (cast.unsafe)
    int x = (@m int) 5;
      //:: warning: (cast.unsafe)
      Integer y = (@m Integer) 5;
}
```

With ant reformat command in CF, the output gives:
> [apply] java.lang.AssertionError: /home/.../checker-framework/checker/tests/units/FormatTestCase.java:4:22: error: did not generate token "int"

Directly running the 1.0 release jar gives:
> java.lang.AssertionError: FormatTest.java:4:22: error: did not generate token "int"

The error is not present and the file is correctly formatted if 1.1 release is used. :)

**Comment by cushon** [comment]
Great, thanks for confirming!

**Comment by mernst** [comment]
I have an issue open upstream with the google-java-format maintainers.
I will upgrade after I hear back from them.

**Comment by jyluo** [comment]
Sounds good. Thanks!

**Comment by mernst** [comment]
google-java-format 1.1 contains too many bugs.
Commit fb7cd15187a4345f0ec8bbc102004d0933571a75 makes the formatting use a snapshot release of google-java-format 1.2 -- although it has its own problems, at least it resolves this issue.
