### ISSUE TITLE
Raw types crash in lub 

### ISSUE THREAD

**Issue by justmin** [typetools/checker-framework#988]
Simple interface compilation produce exception with CF 2.1.6. Works good with CF 2.1.0

```
public interface TestClass {
    Class getRawClass();
    Class<?> getGenericClass();
    default Class<?> getWithArg(boolean generic){
        return generic ? getGenericClass() : getRawClass();
    }
}

```

**Comment by wmdietl** [comment]
Thanks for your report! I've added a test case that reproduces the problem at `framework/tests/all-systems/Issue988.java`.
